' Gambas module file

Public Function Source_Programs_Get() As Collection
  
  Return modDBConnect.exec_query_collection("Select * from import_export.lu_source_program order by program DESC")
  
End

Public Function Templates_Get() As Collection
   '---------------------------------------------------------------------
   'Get field templates for supplied and user defined demographic sources
   '---------------------------------------------------------------------
  Return modDBConnect.exec_query_collection("Select * from import_export.vwdemographictemplates")
End

Public Function Template_Save(old_data As Collection, template As Collection) As Integer
   '-----------------------------------------------------------------------------------------
   'Saves templates for demographic data import eg Pracsoft, Medical Director or user defined
   '-----------------------------------------------------------------------------------------
   If IsNull(template!fk_template) Then
      template!fk_template = modDBConnect.insert("import_export.lu_demographics_field_templates", template)
   Else
      modDBConnect.update("import_export.lu_demographics_field_templates", old_data[template!fk_template], template, "fk_template")
      
   Endif
   Return template!fk_template
  
End
Public Function Demographic_Program_Save(old_data As Collection, program As Collection) As Integer
  
  If IsNull(program!fk_source_program) Then
      program!fk_source_program = modDBConnect.insert("import_export.lu_source_program", program)
   Else
      modDBConnect.update("import_export.lu_source_program", old_data[program!fk_program], program, "fk_program")
      
   Endif
   Return program!fk_source_program

  
End
Public Function Sample_Postcode_HTML() As String
  
  Dim Sstring As String = ""
  "<TABLE WIDTH=100% BORDER=0 CELLPADDING=4 CELLSPACING=3 STYLE=\"page-break-before: always\">"
    "<COL WIDTH=33*>"
    "<COL WIDTH=223*>"
    "<TR VALIGN=TOP>"
    "<TD WIDTH=13%>"
    "<P><B>Postcode</B></P>"
    "</TD>"
    "<TD WIDTH=87%>%postcode</TD>"
    "</TR>"
    "<TR VALIGN=TOP>"
    "<TD WIDTH=13%>"
    "<P><B>Locality</B></P>"
    "</TD>"
    "<TD WIDTH=87%>%locality</TD>"
    "</TR>"
    "<TR VALIGN=TOP>"
    "<TD WIDTH=13%>"
    "<P><B>State</B></P>"
    "</TD>"
    "<TD WIDTH=87>%state</TD>"
    "</TR>"
    "</TABLE>"
   Return Sstring
End

Public Function Sample_Patient_HTML() As String
  Dim sString As String = ""

"<TABLE WIDTH=764 BORDER=0 CELLPADDING=0 CELLSPACING=1 STYLE=\"page-break-before: always\">"
  "<COL WIDTH=102>"
  "<COL WIDTH=206>"
  "<COL WIDTH=182>"
  "<COL WIDTH=225>"
  "<TR VALIGN=TOP>"
  "<TD WIDTH=102>"
  "<P><B>Surname</B></P>"
  "</TD>"
  "<TD WIDTH=206>"
  "<P>%surname</P>"
  "</TD>"
  "<TD WIDTH=182>"
  "<P><B>Title</B></P>"
  "</TD>"
  "<TD WIDTH=225>"
  "<P>%title</P>"
  "</TD>"
  "</TR>"
  "<TR VALIGN=TOP>"
  "<TD WIDTH=102>"
  "<P><B>Firstname</B></P>"
  "</TD>"
  "<TD WIDTH=206>"
  "<P>%firstname</P>"
  "</TD>"
  "<TD WIDTH=182>"
  "<P><B>Sex</B></P>"
  "</TD>"
  "<TD WIDTH=225>"
  "<P>%sex</P>"
  "</TD>"
  "</TR>"
  "<TR VALIGN=TOP>"
  "<TD WIDTH=102>"
  "<P><B>Salutation</B></P>"
  "</TD>"
  "<TD WIDTH=206>"
  "<P>%salutation</P>"
  "</TD>"
  "<TD WIDTH=182>"
  "<P><B>Marital</B></P>"
  "</TD>"
  "<TD WIDTH=225>"
  "<P>%marital</P>"
  "</TD>"
  "</TR>"
  "<TR VALIGN=TOP>"
  "<TD WIDTH=102>"
  "<P><B>Birthdate</B></P>"
  "</TD>"
  "<TD WIDTH=206>"
  "<P>%birthdate</P>"
  "</TD>"
  "<TD WIDTH=182>"
 "<P><B>Medicare Number</B></P>" 
  "</TD>"
  "<TD WIDTH=225>"
  "<P>%medicarenumber</P>"
   "</TD>"
  "</TR>"
  "<TR VALIGN=TOP>"
  "<TD WIDTH=102>"
  "<P><B>Occupation</B></P>"
  "</TD>"
  "<TD WIDTH=206>"
  "<P>%occupation</P>"
  "</TD>"
  "<TD WIDTH=182>"

  "</TD>"
  "<TD WIDTH=225>"
 
  "</TD>"
  "</TR>"
  "<TR VALIGN=TOP>"
  "<TD WIDTH=102>"
 
  "</TD>"
  "<TD WIDTH=206>"
  "<P></P>"
   "</TD>"
  "<TD WIDTH=182>"
  "<P></P>"
  "</TD>"
  "<TD WIDTH=225>"
  "<P></P>"
  "</TD>"
  "</TR>"
  "<TR VALIGN=TOP>"
  "<TD WIDTH=102>"
  "<P><B>Street1</B></P>"
  "</TD>"
  "<TD WIDTH=206>"
  "<P>%street1</P>"
  "</TD>"
  "<TD WIDTH=182>"
  "<P><B>Home Phone</B></P>"
  "</TD>"
  "<TD WIDTH=225>"
  "<P>%homephone</P>"
  "</TD>"
  "</TR>"
  "<TR VALIGN=TOP>"
  "<TD WIDTH=102>"
  "<P><B>Street2</B></P>"
  "</TD>"
  "<TD WIDTH=206>"
  "<P>%street2</P>"
  "</TD>"
  "<TD WIDTH=182>"
  "<P><B>Work Phone</B></P>"
  "</TD>"
  "<TD WIDTH=225>"
  "<P>%workphone</P>"
   "</TD>"
  "</TR>"
  "<TR VALIGN=TOP>"
  "<TD WIDTH=102>"
  "<P><B>Suburb</B>"
  "</TD>"
  "<TD WIDTH=206>"
  "<P>%suburb</P>"
  "</TD>"
  "<TD WIDTH=182>"
  "<P><B>Mobile Phone</B></P>"
  "</P>"
  "</TD>"
  "<TD WIDTH=225>"
  "<P>%mobilephone</P>"
  "</TD>"
  "</TR>"

 
  "</TABLE>"
  Return sString
End 
