' Gambas module file


' Copyright (C) 2008-2013 Dr. Richard Terry Dr. Ian Haywood

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------


Public Sub Submit_Dictation(cc As CConsult, fk_referral As Integer, fname As String) As String
   
   Dim new_fname As String
   Dim task As CTask
   Dim cmd As String
   Dim dict As New Crow
   ' make a nice pretty name for the recording file
   new_fname = modUtil.Filename_Protect(cc!patient!firstname)
   new_fname &= "." & modUtil.Filename_Protect(cc!patient!surname)
   new_fname &= ".ref" & fk_referral & "." & Format$(Now(), "ddmmyy") & ".mp3"
   ' and store in the document archive
   modFiles.Put("document_archiving_directory", new_fname, fname)
   task = New CTask
   cmd = modUtil.FindProgram("ftp", "ftp-ssl")
   task.Init([cmd, "-ie", "ftp.ozescribe.com.au"])
   task.Send("passive\nbinary\ncd voice\n")
   task.Send(Subst$("put &1 &2\n", fname, new_fname))
   task.Send("bye\n")
   task.Close()
   dict!filename = new_fname
   dict!fk_referral = fk_referral
   dict!fk_user = modDBConnect.currentUser!fk_staff
   dict.Save("clin_consult.dictations", "pk_dictation")
   Return new_fname
End

Public Sub Get_New_Dictations() As Collection
   
  Dim sql As String
  
  sql = "select * from clin_consult.vwdictations where fk_user = &1 and not processed and transcript is not null"
  Return modDBConnect.exec_query_row(Subst$(sql, modDBConnect.currentUser!fk_staff))
   
End

Public Sub Flag_Completed(dict As Crow)
   
  dict!processed = True
  dict.Save("clin_consult.dictations", "pk_dictation")
   
   
End
