' Gambas module file

' Gambas class file

' Gambas module file

' Copyright (C) 2008-2016 Dr. Richard Terry
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------

Public Function Hepatitis_A_Immunity(fk_patient As Variant) As String
   
   '---------------------------------------------------
   ' CREATE OR REPLACE VIEW documents.vwobservations AS 
   '  SELECT documents.fk_patient,
   '     observations.pk,
   '     observations.identifier,
   '     observations.observation_date,
   '     observations.value_numeric,
   '     observations.value_numeric_qualifier,
   '     observations.units,
   '     observations.reference_range,
   '     observations.abnormal,
   '     observations.loinc
   '----------------------------------------------------
   Dim sql As String
   Dim HepA As Collection
   Dim sString As String = "No record of Hepatitis A IgG (Loinc:" & const.Loinc_hepatitis_A_IGG & ")"
   
   sql = "select *  from documents.vwobservations where loinc =$$" & const.Loinc_hepatitis_A_IGG & "$$ and fk_patient =" & fk_patient
   sql &= "ORDER BY observation_date DESC limit 1"
   HepA = modDBConnect.exec_query_first(sql)
   If Not IsNull(HepA) Then
      If HepA.count Then   
         sString = Format(HepA!observation_date, "dd/mm/yyyy") & ": " & HepA!identifier & " " 
         If IsNull(HepA!value_numeric) Then
            sstring &= HepA!value
         Else
            sstring &= HepA!value_numeric_qualifier & " " & Str(HepA!value_numeric)  
         Endif
         If Not IsNull(HepA!reference_range) Then  
            sstring &= HepA!units & " (" & HepA!reference_range & ")"
         End If   
      End If  
   End If   
   Return sString
   
End

Public Function Hepatitis_B_Immunity(fk_patient As Variant) As String
   '---------------------------------------------------
   ' CREATE OR REPLACE VIEW documents.vwobservations AS 
   '  SELECT documents.fk_patient,
   '     observations.pk,
   '     observations.identifier,
   '     observations.observation_date,
   '     observations.value_numeric,
   '     observations.value_numeric_qualifier,
   '     observations.units,
   '     observations.reference_range,
   '     observations.abnormal,
   '     observations.loinc
   '----------------------------------------------------
   
   Dim sql As String
   Dim HepB As Collection
   Dim sString As String = "No record of Hepatitis B Surface Ab (Loinc:" & const.Loinc_Hepatitis_B_Surface_ab & ")"
   
   sql = "select *  from documents.vwobservations where loinc =$$" & const.Loinc_Hepatitis_B_Surface_ab & "$$ and fk_patient =" & fk_patient
   sql &= "ORDER BY observation_date DESC limit 1"
   HepB = modDBConnect.exec_query_first(sql)
   If Not IsNull(hepB) Then
      If HepB.count Then   
         sString = Format(HepB!observation_date, "dd/mm/yyyy") & ": " & HepB!identifier & " " 
         sstring &= HepB!value_numeric_qualifier & " " & Str(HepB!value_numeric)  
         sstring &= HepB!units & " (" & HepB!reference_range & ")"
      End If  
   End If   
   Return sString
   
End
