' Gambas module file

' Copyright (C) 2008-2012 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
' Module for doing stats stuff

Public Function Hba1c_Distribution() As Result

   Dim sql As String
   
   sql = ""
   "Select "
   "           '>8' As XAxes_text, count(value_numeric), 6 As display_order "
   "           From Documents.vwObservations  where loinc = '4548-4' and value_numeric > 8"
   "           UNION"
   "       select "
   "           '7.5-8.0' As XAxes_text, count(value_numeric), 5 as display_order "
   "           From Documents.vwObservations  where loinc = '4548-4' and value_numeric between  7.5  and 8.0"
   "           UNION "
   "       select  "
   "          '7.0-7.5' As XAxes_text, count(value_numeric), 4 as display_order "
   "           From Documents.vwObservations  where loinc = '4548-4' and value_numeric between 7 and 7.5 "
   "         UNION "
   "       select "
   "           '6.5-7.0' As XAxes_text, count(value_numeric), 3 as display_order "
   "           From Documents.vwObservations  where loinc = '4548-4' and value_numeric between  6.5 and 7.0"
   "            UNION "
   "       select "
   "           '6.0-6.5' As XAxes_text, count(value_numeric), 2 as display_order "
   "           From Documents.vwObservations  where loinc = '4548-4' and value_numeric between  6.0 and 6.5"
   "            UNION "
   "       select "
   "             '<6' As XAxes_text, count(value_numeric), 1 as display_order "
   "            From Documents.vwObservations  where loinc = '4548-4' and value_numeric < 6"
   "            order by display_order"
   
   Return modDBConnect.exec_query(sql)

End

Public Function Age_Distribution() As Result
   
   '--------------------------------
   'Get age ranges, currently fixed
   '--------------------------------
   Dim sql As String
   Dim r As Result
   
   sql = ""
   sql = "select count (extract (year from age(birthdate))) as age, " 
   "'<5' as XAxes_text, '1' as display_order From contacts.vwPatients where extract(Year From age(birthdate)) < 5 " 
   " UNION "
   "select count (extract (year from age(birthdate))) as age, " 
   "'5-18' as XAxes_text, '2' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 5 and 18"
   " UNION "
   "select count (extract (year from age(birthdate))) as age ,"
   "'18-50' as XAxes_text, '3' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 18 and 50"
   " UNION "
   "select count (extract (year from age(birthdate))) as age ,"
   " '50-75' as XAxes_text, '4' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 50 and 75" 
   " UNION " 
   "select count (extract (year from age(birthdate))) as age, " 
   "'75-90' as XAxes_text, '5' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 75 and 90"
   " UNION " 
   "select count (extract (year from age(birthdate))) as age , "
   "'>90' as XAxes_text, '6' as display_order   from contacts.vwPatients where extract (year from age(birthdate))> 90" 
   " ORDER BY display_order"
   Return modDBConnect.exec_query(sql)

End

Public Function Age_Distribution1() As Result
   
   '--------------------------------
   'Get age ranges, currently fixed
   '--------------------------------
   Dim sql As String
   
   ' sql = ""
   ' sql = "select count (extract (year from age(birthdate))) as age, " 
   ' "'<5' as XAxes_text  from contacts.vwPatients where extract (year from age(birthdate))< 5" 
   ' " UNION "
   ' "select count (extract (year from age(birthdate))) as age, " sql = "select count (extract (year from age(birthdate))) as age, " 
   ' "'<5' as XAxes_text, '1' as display_order From contacts.vwPatients where extract(Year From age(birthdate)) < 5 " 
   ' " UNION "
   ' "select count (extract (year from age(birthdate))) as age, " 
   ' "'5-18' as XAxes_text, '2' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 5 and 18"
   ' " UNION "
   ' "select count (extract (year from age(birthdate))) as age ,"
   ' "'18-50' as XAxes_text, '3' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 18 and 50"
   ' " UNION "
   ' "select count (extract (year from age(birthdate))) as age ," Select count(extract(Year From age(birthdate))) As Age,  
   ' '<5' as XAxes_text, '1' as display_order From contacts.vwPatients where extract(Year From age(birthdate)) < 5  
   '  UNION 
   ' Select count(extract(Year From age(birthdate))) As Age,  
   ' '5-18' as XAxes_text, '2' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 5 and 18
   '  UNION 
   ' Select count(extract(Year From age(birthdate))) As Age,
   ' '18-50' as XAxes_text, '3' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 18 and 50
   '  UNION 
   ' Select count(extract(Year From age(birthdate))) As Age,
   '  '50-75' as XAxes_text, '4' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 50 and 75 
   '  UNION  
   ' Select count(extract(Year From age(birthdate))) As Age,  
   ' '75-90' as XAxes_text, '5' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 75 and 90
   '  UNION  
   ' Select count(extract(Year From age(birthdate))) As Age, 
   ' '>90' as XAxes_text, '6' as display_order   from contacts.vwPatients where extract (year from age(birthdate))> 90 
   '  ORDER BY display_order
   ' " '50-75' as XAxes_text, '4' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 50 and 75" 
   ' " UNION " 
   ' "select count (extract (year from age(birthdate))) as age, " 
   ' "'75-90' as XAxes_text, '5' as display_order  from contacts.vwPatients where extract (year from age(birthdate)) between 75 and 90"
   ' " UNION " 
   ' "select count (extract (year from age(birthdate))) as age , "
   ' "'>90' as XAxes_text, '6' as display_order   from contacts.vwPatients where extract (year from age(birthdate))> 90" 
   ' " ORDER BY display_order"
   ' "'5-20' as XAxes_text from contacts.vwPatients where extract (year from age(birthdate)) between 5 and 20"
   ' " UNION "
   ' "select count (extract (year from age(birthdate))) as age ,"
   ' "'20-30' as XAxes_text from contacts.vwPatients where extract (year from age(birthdate)) between 20 and 30"
   ' " UNION "
   ' "select count (extract (year from age(birthdate))) as age ,"
   ' " '30-40' as XAxes_text from contacts.vwPatients where extract (year from age(birthdate)) between 30 and 40" 
   ' " UNION " 
   ' "select count (extract (year from age(birthdate))) as age, " 
   ' "'40-50' as XAxes_text  from contacts.vwPatients where extract (year from age(birthdate)) between 40 and 50"
   ' " UNION " 
   ' "select count (extract (year from age(birthdate))) as age, "
   ' "'50-60' as XAxes_text  from contacts.vwPatients where extract (year from age(birthdate)) between 50 and 60" ""
   ' " UNION "
   ' "select count (extract (year from age(birthdate))) as age, " 
   ' "'60-70' as XAxes_text  from contacts.vwPatients where extract (year from age(birthdate)) between 60 and 70" 
   ' " UNION " 
   ' "select count (extract (year from age(birthdate))) as age, " 
   ' "'70-80' as XAxes_text  from contacts.vwPatients where extract (year from age(birthdate)) between 70 and 80" 
   ' " UNION "
   ' "select count (extract (year from age(birthdate))) as age,"
   ' " '80-90' as XAxes_text  from contacts.vwPatients where extract (year from age(birthdate)) between 80 and 90"
   ' " UNION " 
   ' "select count (extract (year from age(birthdate))) as age , "
   ' "'>90' as XAxes_text from contacts.vwPatients where extract (year from age(birthdate))> 90" 
   ' Return modDBConnect.exec_query(sql)
   
End

Public Function Save_Query(name As String, gnuplot As String, sql As String, Optional pk As Integer = -1) As Integer
   
   Dim r As Result
   
   If pk = -1 Then
      Return modDBConnect.insert("research.queries", ["name": name, "gnuplot": gnuplot, "sql": sql])
   Else
      modDBConnect.update("research.queries", Null, ["pk": pk, "gnuplot": gnuplot, "sql": sql])
      Return pk 
   Endif
   
End

Public Function List_Queries() As Collection
   
   Return modDBConnect.exec_query_collection("select pk, \"name\" from research.queries")
   
End

Public Function Get_Query(pk As Integer) As Collection
   
   Return modDBConnect.exec_query_first("select * from research.queries where pk = " & pk)
   
End
