' Gambas module file
' Gambas class file

' Gambas class file
' Copyright (C) 2008-2011 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------
' PURPOSE Database accessing routines for Diabetes Annual Cycle of Care
'----------------------------------------------------------------------

Public Function Last_Eye_Review(fk_patient As Integer, Optional limit As Integer = 0, sort As String = "ASC") As Result
   '--------------------------------------------------------------------------
   'Atempts by reading the documents table and categories to see when the last
   'recorded review by an optomotrist or an opthalmologist (or get all)
   '--------------------------------------------------------------------------
   Dim sql As String 
   sql = "Select * from documents.vwDocuments where (person_category ILIKE '%ophthal%' or organisation_category ILIKE '%ophthal%'"
         "or person_category ILIKE '%optom%' or organisation_category ILIKE '%optom%') AND fk_patient = "
   sql &= fk_patient & " ORDER BY date_created " & sort
   If limit Then
      sql &= " LIMIT " & limit 
   Endif

   Return modDBConnect.exec_query(sql)
End

Public Function Save_DACC(old_data As Collection, fk_dacc As Integer, new_data As Collection) As Boolean
  
   If fk_dacc = 0 Then
      new_data!fk_dacc = modDBConnect.insert("chronic_disease_management.diabetes_annual_cycle_of_care", new_data)
   Else
      modDBConnect.update("chronic_disease_management.diabetes_annual_cycle_of_care", old_data[fk_dacc], new_data, "pk")
   Endif
   Return True 'fixme
   
  
End

Public Function DACCs_Get(fk_patient As Integer) As Collection
   '--------------------------------------------------
   'Get previous DACCs - diabetes annual cycle of care
   'may not be complete, limit to the last few
   '---------------------------------------------------
   Dim sql As String
   sql = "Select * from chronic_disease_management.vwDiabetesCycleOfCare WHERE fk_patient = " & fk_patient
   sql &= " AND deleted = false order by fk_consult DESC LIMIT 5"
   Return modDBConnect.exec_query_collection(sql)
  
  
End
