' Gambas module file
' Copyright (C) 2008,2009 Dr. Richard Terry Dr. Ian Haywood

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------
' PURPOSE      Provide some minimal decision support
'----------------------------------------------------------------------
Public Function BMI_DecSupp(Weight As Variant, height As Variant) As String
   Dim range As String 
   Dim sMsgOverweight As String = "Patient is in overweight range of BMI"
   Dim sMsgObese As String = "Patient is in obese range of BMI"
   Dim sMsgUnderweight As String = "Patient is in the underweight range of BMI"
   Dim sWeightMessage As String  
   Dim BMI As Float
   
   BMI = Format((weight / (height ^ 2)) * 10000, "##.#")
   
   If BMI > 20 And BMI < 25 Then range = "normal" 
   If BMI > 25 And BMI < 30 Then range = "overweight"
   If BMI > 30 Then range = "obese" 
   If BMI < 20 Then range = "underweight"
   Select Case range
   Case "underweight"
         sWeightMessage = sMsgUnderweight
   Case "overweight"
           sWeightMessage = sMsgOverweight
   Case "obese"
      sWeightMessage = sMsgOverweight
   End Select
   Return sWeightMessage
   
End
