' Gambas module file

Public Function IsMeasurement(te As Textedit, keyword As String, sMeasurement As String) As Boolean
   '-------------------------------------------------------------------------------
   'Attempts to validate a measurement is valid and insert html into the texteditor
   'currently minimal validation FIXME: make me smarter
   'at moment this routine is duplicated in FProgressNoteEditor needs to be 
   'removed from that.
   '-------------------------------------------------------------------------------
   
   Dim Delimiter As String
   Dim charpos As Integer
   Dim SS As String
   Dim html_aref_tag As String
   Dim html_text As String
   Dim sUnits As String

   Select Case keyword
      Case "bp="
         Delimiter = "/"
         html_text = "blood pressure"
         html_aref_tag = "blood pressure"
         sUnits = "mmhg"
      Case "h="
         Delimiter = "."
         html_text = "height"
         html_aref_tag = "height"
         sUnits = "cm"
      Case "w="
         Delimiter = "."
         html_text = "weight"
         html_aref_tag = "weight"
         sUnits = "kg"
      Case "bsl="
         Delimiter = "."
         html_text = "blood Sugar"
         html_aref_tag = "blood Sugar"
         sUnits = "mmole"
   End Select
   SS = Right(sMeasurement, Len(sMeasurement) - InStr(sMeasurement, "="))
   charpos = InStr(SS, delimiter)
   Try Val(Left(SS, charpos - 1))
   If Error Then Return False
   Try Right(SS, Len(SS) - charpos)
   If Error Then Return False
   te.RichText = Replace$(LCase(te.RichText), keyword & SS, "<A HREF='" & html_aref_tag & "'>" & html_text & "=" & SS & sUnits & "</A><BR>")
   te.pos = InStr(te.text, html_text & "=" & SS & sunits) + Len(html_text & " = " & SS & sUnits)
   ' If keyword = "h=" Then
   '    sHeight = SS 
   '    CalcBMI()
   ' End If
   ' If keyword = "w=" Then
   '    sWeight = SS
   '    CalcBMI()
   ' Endif
   Return True
   
End
