' Gambas module file

' a module for basic billing reports
' output to both HTML, and ODS (libreoffice Calc XML)
' Copyright (C) 2008-2016 Dr. Richard Terry Dr. Ian Haywood

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------

Private Const fods_prefix As String = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
"<office:document xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" " 
"xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" "
"xmlns:text=\"urn:oasis:names:tc:opendocument:xmlns:text:1.0\" "
"xmlns:table=\"urn:oasis:names:tc:opendocument:xmlns:table:1.0\" "  
"xmlns:meta=\"urn:oasis:names:tc:opendocument:xmlns:meta:1.0\" "
"xmlns:fo=\"urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0\" "
"xmlns:number=\"urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0\" " 
"xmlns:config=\"urn:oasis:names:tc:opendocument:xmlns:config:1.0\" "
"xmlns:loext=\"urn:org:documentfoundation:names:experimental:office:xmlns:loext:1.0\" "
"xmlns:calcext=\"urn:org:documentfoundation:names:experimental:calc:xmlns:calcext:1.0\" "
"office:version=\"1.2\" "
"office:mimetype=\"application/vnd.oasis.opendocument.spreadsheet\">"
"<office:meta>" 
"<meta:generator>EasyGP/1.0</meta:generator></office:meta>"
"<office:styles>"
"<number:currency-style style:name=\"N104P0\" style:volatile=\"true\">"
"<number:currency-symbol number:language=\"en\" number:country=\"AU\">$</number:currency-symbol>"
"<number:number number:decimal-places=\"2\" loext:min-decimal-places=\"2\" number:min-integer-digits=\"1\" number:grouping=\"true\"/>"
"</number:currency-style>"
"<style:style style:name=\"money\" style:family=\"table-cell\" style:data-style-name=\"N104P0\"/>"
"<style:style style:name=\"bold\" style:family=\"table-cell\">"
"<style:text-properties fo:font-weight=\"bold\" style:font-weight-complex=\"bold\"/>"
"</style:style>"
"</office:styles>"
"<office:body>"
"<office:spreadsheet>"
"&1"
"</office:spreadsheet>"
"</office:body>"
"</office:document>"

Private all_reports As Collection[]


' loas the reports into the collection: this is where we define them
Private Sub Load_Reports()
   Dim f As File
   Dim l As String
   Dim curr_report As Collection
   Dim curr_table As Collection
   
   If IsNull(all_reports) Then
      all_reports = New Collection[]
      f = Open "reports.txt" For Read
      While Not Eof(f)
         Line Input #f, l
         If Left$(l, 2) = "  " Then
            curr_table!sql &= Right$(l, -2)
         Else If Left$(l, 1) = " " Then
            curr_table = New Collection
            curr_table!title = Right$(l, -1)
            curr_table!sql = " "
            curr_report!tables.Add(curr_table)
         Else
            curr_report = New Collection
            curr_report!title = l
            curr_report!tables = New Collection[]
            all_reports.Add(curr_report)
         Endif
      Wend
   Endif
   
End



Public Function List_Reports() As String[]
   
   Dim ret As New String[]
   Dim i As Variant
   
   Load_Reports()
   For Each i In all_reports
      ret.Add(i!title)
   Next
   Return ret
   
End



' make a report
' report: the report ID, as from List_Reports
' date1: the 'start date' for a report period
' period: 1=week, 2 =month, 3=quarter
' html: True for HTML, false for LibreOffice Calc
Public Function Make_Report(report As Integer, date1 As Date, period As Integer, fk_doctor As Integer, Optional html As Boolean = True) As String
   
   
   
End

Public Sub UnitTest(form_main As Fmain)
   
  List_Reports()
   
   
End


