' Gambas module file

' Gambas class file
' Copyright (C) 2012-2014 Dr Richard Terry
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------

Public Function Medications_List_HTML(Optional bEverything As Boolean = False, Optional bGenericOnly As Boolean = True, bIncludeHeading As Boolean = False, bJustToday As Boolean = False) As String
   '----------------------------------------------------
   'Construct html of the medications
   'Either with heading, the whole list, or just today
   'fixme use me in FProgressNotesEditor
   '---------------------------------------------------- 
   Dim medication As Collection 
   Dim medications As Collection = FClinical.medication_list()
   Dim sMedlist As String
   If Not medications.count Then Return  
   
   If bIncludeHeading Then
      sMedlist = "<B>Medications</B><BR>"
   Endif
   For Each medication In medications
      If bJustToday Then
         If modUtil.IsSameDay(medication!med!last_date, Now()) Then
            smedlist &= medication!generic & " " & medication!strength & " " & medication!form & " " 
            If bEverything Then  
               smedlist &= medication!instruction & " for " & medication!prescribed_for
            End If   
            If bGenericOnly = False Then 
               smedlist &= " (" & medication!brand & ") " 
            End If   
            If bEverything Then  
               smedlist &= medication!prescribed!quantity & " R" & medication!prescribed!repeats
            End If   
            smedlist &= "<BR>"
         End If   
      Else
         smedlist &= medication!generic & " " & medication!strength & " " & medication!form & " " 
         If bEverything Then  
            smedlist &= medication!instruction & " for " & medication!prescribed_for
         End If   
         If bGenericOnly = False Then 
            smedlist &= " (" & medication!brand & ") " 
         End If   
         If bEverything Then  
            smedlist &= medication!prescribed!quantity & " R" & medication!prescribed!repeats
         End If   
         smedlist &= "<BR>"
      End If   
   Next
   Return sMedlist 
   
End  
