' Gambas module file

' Gambas class file

' Copyright (C) 2008-2015 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'------------------------------------------------------------------------
' PURPOSE  Generate some simple forms using latex templates in templates/
'------------------------------------------------------------------------

Public Function Aclasta_Infusion_Form(cons As CConsult) As String
   
   '-------------------------------------------------------------------------------
   'Prepares the LaTeX definition to be with be printed on the actual form
   'don't move these out of order or the templsubst_common with wreck previous subs
   '-------------------------------------------------------------------------------   
   Dim P As Collection = cons!patient  
   
   Dim templ As CTemplate
   Dim bits As String[]
   
   templ = New CTemplate("aclasta-infusion", "tex")
    If P!sex = "M" Then 
      templ.Subst("sex-male", "M")
      templ.Subst("sex-female", "\\relax")
   End If   
   If P!sex = "F" Then
       templ.Subst("sex-female", "F")
       templ.Subst("sex-male", "\\relax")
   End If   
   templ.Subst("pdf-path", modUtil.Find_File("templates" &/ "aclasta-infusion.pdf"))
  
   bits = Split(Format(P!birthdate, "dd/mm/yyyy"), "/")
   templ.Subst("birthdate-day", bits[0])
   templ.Subst("birthdate-month", bits[1])
   templ.Subst("birthdate-year", bits[2])
   bits = Split(Format(Now(), "dd/mm/yyyy"), "/")
    templ.Subst("date-signed-patient-day", bits[0])
   templ.Subst("date-signed-patient-month", bits[1])
   templ.Subst("date-signed-patient-year", bits[2])
    templ.Subst("date-signed-practitioner-day", bits[0])
   templ.Subst("date-signed-practitioner-month", bits[1])
   templ.Subst("date-signed-practitioner-year", bits[2])
    templ.subst_common(cons)
  
   Return Templ.GetData()
   
End
