' Gambas module file

' Copyright (C)2008-2016 Dr. Richard Terry
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'
' PURPOSE A module to retrieve and manipulate miscellaneous forms
'----------------------------------------------------------------------

Public Function Forms_Get(fk_patient As Variant) As Collection
   
   Dim sql As String
   
   sql = "Select * from documents.vwDocuments where fk_patient =" & fk_patient & " AND deleted = False "
   "AND fk_lu_display_as =" & const.Document_Display_as_Form & " ORDER BY date_created DESC"
   Return modDBConnect.exec_query_collection(sql)
   
End
