' Gambas module file
' Copyright (C) 2008,2009 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'-----------------------------------------------------------------------

Private $hConn As Connection
Private $Result As Result
Private sql As String

Public Sub TargetDisease_get(lv As Listview, txt As Textbox)
  '---------------------------------------------------
  'Gets a list of target diseases to vaccinate against
  '---------------------------------------------------
  Dim x As Integer
  If Not (txt) Then Return
  sql = "Select * from clin_vaccination.lu_target WHERE "  
  SQL &= "target ILIKE '%" & Lower(Trim(txt.text)) & "%' "
  $Result = modDBConnect.exec_query(sql)
  'Print $Result.Count
  lv.clear
  If $Result.count Then
     For Each $Result
          lv.Add(x, $Result!target)
          Inc x
      Next
      With lv
         .Raise
         .Visible = True
         .tag = txt
     End With
  Else
     lv.Visible = False
     
  End If
 End
Public Sub Vacccines_Guess(lv As Listview, sString As String)
 
   
End 

Public Sub SerialNumbers_GetList(lv As Listview)
  
  '---------------------------------------------------
  'Gets a list of serial numbers to vaccinate against
  '---------------------------------------------------

  
End
Public Sub Vaccination_Sites_Get(lv As Listview)
 '---------------------------------------------------
  'Gets a list of vaccination sites
  '---------------------------------------------------
  sql = "Select * from common.lu_route_administration order by route;"
  modDBConnect.exec_query(sql)
  lv.Clear()
  For Each $Result
     lv.Add($Result!pk, $Result!route)
  Next
  If lv.count Then
     lv.Visible = True
  Else
     lv.Visible = False
  End If
  
End


Public Sub Vaccines_In_Schedules_Get(fk_schedule As Integer) As Collection
  
  Return modDBConnect.exec_query_collection("select * from clin_vaccination.vwVaccinesInSchedule where fk_schedule = " & fk_schedule)
  
End

Public Function Schedules_Save(old_data As Collection, pk_view As Integer, new_data As Collection) As Integer
  
  'Save (create or change) a vaccination schedule
  If IsNull(new_data!pk) Then
      modDBConnect.insert("clin_vaccination.lu_schedules", new_data)
  Else
      
      modDBConnect.update("clin_vaccination.lu_schedules", old_data[pk_view], new_data)
  Endif
 'fixme no return should be success or failure
End

Public Sub Schedules_get(Optional schedule As String = "", Optional active As Integer = 1) As Collection 
  '--------------------------------
  'Gets a list of current Schedules
  'active = 1 = only display active
  'active = 2 = only display inactive
  'active = 3 = display all
  '--------------------------------
  Dim sql As String
  
  sql = "Select * from clin_vaccination.lu_schedules "
'  If Schedule <> "" Then
    sql &= " WHERE schedule ILIKE $$%" & schedule & "%$$ "
 ' Endif

  Select Case active
    Case 1
      sql &= " AND inactive = False  "
    Case 2
       sql &= " AND inactive = TRUE "
  End Select
 
   Return modDBConnect.exec_query_collection(sql & " ORDER BY schedule")
  
End
