-- Updates matchable pdf product information files

update drugs.brand set product_information_filename='vip3tcts.pdf' where
brand=$$3TC$$; -- 3TC
update drugs.brand set product_information_filename='bqpabili.pdf' where
brand=$$ABILIFY$$; -- Abilify
update drugs.brand set product_information_filename='pfpaccut.pdf' where
brand=$$ACCUPRIL$$; -- Accupril
update drugs.brand set product_information_filename='afpacete.pdf' where
brand=$$ACETEC$$; -- Acetec
update drugs.brand set product_information_filename='appacimx.pdf' where
brand=$$ACIMAX TABLETS$$; -- Acimax
update drugs.brand set product_information_filename='nvpaclin.pdf' where
brand=$$ACLASTA$$; -- Aclasta
update drugs.brand set product_information_filename='ropactem.pdf' where
brand=$$ACTEMRA$$; -- Actemra
update drugs.brand set product_information_filename='afpactil.pdf' where
brand=$$ACTILAX$$; -- Actilax
update drugs.brand set product_information_filename='bypactil.pdf' where
brand=$$ACTILYSE CATHFLO$$; -- Actilyse
update drugs.brand set product_information_filename='lypactos.pdf' where
brand=$$ACTOS$$; -- Actos
update drugs.brand set product_information_filename='agpacula.pdf' where
brand=$$ACULAR$$; -- Acular
update drugs.brand set product_information_filename='lypadcir.pdf' where
brand=$$ADCIRCA$$; -- Adcirca
update drugs.brand set product_information_filename='swpadeno.pdf' where
brand=$$ADENOCOR$$; -- Adenocor
update drugs.brand set product_information_filename='swpadens.pdf' where
brand=$$ADENOSCAN$$; -- Adenoscan
update drugs.brand set product_information_filename='afpadron.pdf' where
brand=$$ADRONAT$$; -- Adronat
update drugs.brand set product_information_filename='aspaggrt.pdf' where
brand=$$AGGRASTAT$$; -- Aggrastat
update drugs.brand set product_information_filename='iapairom.pdf' where
brand=$$AIROMIR$$; -- Airomir
update drugs.brand set product_information_filename='afpakami.pdf' where
brand=$$AKAMIN 50$$; -- Akamin
update drugs.brand set product_information_filename='pfpaldat.pdf' where
brand=$$ALDACTONE$$; -- Aldactone
update drugs.brand set product_information_filename='iapaldar.pdf' where
brand=$$ALDARA$$; -- Aldara
update drugs.brand set product_information_filename='aspaldom.pdf' where
brand=$$ALDOMET$$; -- Aldomet
update drugs.brand set product_information_filename='aspalleg.pdf' where
brand=$$ALLEGRON$$; -- Allegron
update drugs.brand set product_information_filename='afpaller.pdf' where
brand=$$ALLEREZE$$; -- Allereze
update drugs.brand set product_information_filename='afpalodo.pdf' where
brand=$$ALODORM$$; -- Alodorm
update drugs.brand set product_information_filename='afpalpri.pdf' where
brand=$$ALPRIM$$; -- Alprim
update drugs.brand set product_information_filename='pfpaltvc.pdf' where
brand=$$ALTVEN$$; -- Altven
update drugs.brand set product_information_filename='afpalzen.pdf' where
brand=$$ALZENE$$; -- Alzene
update drugs.brand set product_information_filename='swpamary.pdf' where
brand=$$AMARYL$$; -- Amaryl
update drugs.brand set product_information_filename='nvpanfor.pdf' where
brand=$$ANAFRANIL 25$$; -- Anafranil
update drugs.brand set product_information_filename='swpanand.pdf' where
brand=$$ANANDRON$$; -- Anandron
update drugs.brand set product_information_filename='ropanapr.pdf' where
brand=$$ANAPROX 550$$; -- Anaprox
update drugs.brand set product_information_filename='mkpandri.pdf' where
brand=$$ANDRIOL TESTOCAPS$$; -- Andriol
update drugs.brand set product_information_filename='mkpantro.pdf' where
brand=$$ANTROQUORIL$$; -- Antroquoril
update drugs.brand set product_information_filename='swpapidr.pdf' where
brand=$$APIDRA$$; -- Apidra
update drugs.brand set product_information_filename='txpapale.pdf' where
brand=$$APO-ALENDRONATE$$; -- Apo-Alendronate
update drugs.brand set product_information_filename='txpamisu.pdf' where
brand=$$APO-AMISULPRIDE$$; -- APO-Amisulpride
update drugs.brand set product_information_filename='txpapaml.pdf' where
brand=$$APO-AMLODIPINE$$; -- Apo-Amlodipine
update drugs.brand set product_information_filename='txpamoxc.pdf' where
brand=$$APO-AMOXYCILLIN$$; -- Apo-Amoxycillin
update drugs.brand set product_information_filename='txpamoxy.pdf' where
brand=$$APO-AMOXYCILLIN$$; -- Apo-Amoxycillin/Clavulanic
update drugs.brand set product_information_filename='txpanast.pdf' where
brand=$$APO-ANASTROZOLE$$; -- APO-Anastrozole
update drugs.brand set product_information_filename='txpateno.pdf' where
brand=$$APO-ATENOLOL$$; -- Apo-Atenolol
update drugs.brand set product_information_filename='txpapbic.pdf' where
brand=$$APO-BICALUTAMIDE$$; -- Apo-Bicalutamide
update drugs.brand set product_information_filename='txpbisop.pdf' where
brand=$$APO-BISOPROLOL$$; -- APO-Bisoprolol
update drugs.brand set product_information_filename='txpcarve.pdf' where
brand=$$APO-CARVEDILOL$$; -- Apo-Carvedilol
update drugs.brand set product_information_filename='txpcephs.pdf' where
brand=$$APO-CEPHALEXIN$$; -- Apo-Cephalexin
update drugs.brand set product_information_filename='txpcital.pdf' where
brand=$$APO-CITALOPRAM$$; -- Apo-Citalopram
update drugs.brand set product_information_filename='txpclara.pdf' where
brand=$$APO-CLARITHROMYCIN$$; -- Apo-Clarithromycin
update drugs.brand set product_information_filename='txpclopi.pdf' where
brand=$$APO-CLOPIDOGREL$$; -- Apo-Clopidogrel
update drugs.brand set product_information_filename='txpdiaze.pdf' where
brand=$$APO-DIAZEPAM$$; -- APO-Diazepam
update drugs.brand set product_information_filename='txpdiclo.pdf' where
brand=$$APO-DICLOFENAC$$; -- APO-Diclofenac
update drugs.brand set product_information_filename='txpescit.pdf' where
brand=$$APO-ESCITALOPRAM$$; -- APO-Escitalopram
update drugs.brand set product_information_filename='txpfamci.pdf' where
brand=$$APO-FAMCICLOVIR$$; -- APO-Famciclovir
update drugs.brand set product_information_filename='txpfluvo.pdf' where
brand=$$APO-FLUVOXAMINE$$; -- Apo-Fluvoxamine
update drugs.brand set product_information_filename='txpgabcc.pdf' where
brand=$$APO-GABAPENTIN$$; -- Apo-Gabapentin
update drugs.brand set product_information_filename='txpglica.pdf' where
brand=$$APO-GLICLAZIDE MR$$; -- Apo-Gliclazide
update drugs.brand set product_information_filename='txpglime.pdf' where
brand=$$APO-GLIMEPIRIDE$$; -- Apo-Glimepiride
update drugs.brand set product_information_filename='txpiprat.pdf' where
brand=$$APO-IPRATROPIUM$$; -- Apo-Ipratropium
update drugs.brand set product_information_filename='txpisotr.pdf' where
brand=$$APO-ISOTRETINOIN$$; -- APO-Isotretinoin
update drugs.brand set product_information_filename='txplamot.pdf' where
brand=$$APO-LAMOTRIGINE$$; -- APO-Lamotrigine
update drugs.brand set product_information_filename='txplanso.pdf' where
brand=$$APO-LANSOPRAZOLE$$; -- Apo-Lansoprazole
update drugs.brand set product_information_filename='txpleflu.pdf' where
brand=$$APO-LEFLUNOMIDE$$; -- APO-Leflunomide
update drugs.brand set product_information_filename='txplerca.pdf' where
brand=$$APO-LERCANIDIPINE$$; -- Apo-Lercanidipine
update drugs.brand set product_information_filename='txpletro.pdf' where
brand=$$APO-LETROZOLE$$; -- APO-Letrozole
update drugs.brand set product_information_filename='txplevet.pdf' where
brand=$$APO-LEVETIRACETAM$$; -- APO-Levetiracetam
update drugs.brand set product_information_filename='txplisin.pdf' where
brand=$$APO-LISINOPRIL$$; -- Apo-Lisinopril
update drugs.brand set product_information_filename='txpmeloc.pdf' where
brand=$$APO-MELOXICAM$$; -- APO-Meloxicam
update drugs.brand set product_information_filename='txpmeman.pdf' where
brand=$$APO-MEMANTINE$$; -- APO-Memantine
update drugs.brand set product_information_filename='txpmirta.pdf' where
brand=$$APO-MIRTAZAPINE$$; -- Apo-Mirtazapine
update drugs.brand set product_information_filename='txpnifed.pdf' where
brand=$$APO-NIFEDIPINE XR$$; -- APO-Nifedipine
update drugs.brand set product_information_filename='txpondan.pdf' where
brand=$$APO-ONDANSETRON$$; -- Apo-Ondansetron
update drugs.brand set product_information_filename='txpoxaze.pdf' where
brand=$$APO-OXAZEPAM$$; -- APO-Oxazepam
update drugs.brand set product_information_filename='txpparac.pdf' where
brand=$$APO-PARACETAMOL$$; -- Apo-Paracetamol
update drugs.brand set product_information_filename='txpperin.pdf' where
brand=$$APO-PERINDOPRIL$$; -- APO-Perindopril
update drugs.brand set product_information_filename='txpprava.pdf' where
brand=$$APO-PRAVASTATIN$$; -- Apo-Pravastatin
update drugs.brand set product_information_filename='txpprazo.pdf' where
brand=$$APO-PRAZOSIN$$; -- APO-Prazosin
update drugs.brand set product_information_filename='txprochp.pdf' where
brand=$$APO-PROCHLORPERAZINE$$; -- APO-Prochlorperazine
update drugs.brand set product_information_filename='txpqueti.pdf' where
brand=$$APO-QUETIAPINE$$; -- APO-Quetiapine
update drugs.brand set product_information_filename='txpapqui.pdf' where
brand=$$APO-QUINAPRIL$$; -- Apo-Quinapril
update drugs.brand set product_information_filename='txprised.pdf' where
brand=$$APO-RISEDRONATE$$; -- APO-Risedronate
update drugs.brand set product_information_filename='txprispe.pdf' where
brand=$$APO-RISPERIDONE$$; -- APO-Risperidone
update drugs.brand set product_information_filename='txproxit.pdf' where
brand=$$APO-ROXITHROMYCIN$$; -- APO-Roxithromycin
update drugs.brand set product_information_filename='txpsalbu.pdf' where
brand=$$APO-SALBUTAMOL INHALER$$; -- APO-Salbutamol
update drugs.brand set product_information_filename='txpsimva.pdf' where
brand=$$APO-SIMVASTATIN$$; -- Apo-Simvastatin
update drugs.brand set product_information_filename='txpsumat.pdf' where
brand=$$APO-SUMATRIPTAN$$; -- APO-Sumatriptan
update drugs.brand set product_information_filename='txptemas.pdf' where
brand=$$APO-TEMAZEPAM$$; -- Apo-Temazepam
update drugs.brand set product_information_filename='txptopir.pdf' where
brand=$$APO-TOPIRAMATE$$; -- Apo-Topiramate
update drugs.brand set product_information_filename='txptramo.pdf' where
brand=$$APO-TRAMADOL$$; -- APO-Tramadol
update drugs.brand set product_information_filename='txptrama.pdf' where
brand=$$APO-TRAMADOL$$; -- Apo-Tramadol
update drugs.brand set product_information_filename='txptrand.pdf' where
brand=$$APO-TRANDOLAPRIL$$; -- Apo-Trandolapril
update drugs.brand set product_information_filename='txpvalac.pdf' where
brand=$$APO-VALACICLOVIR$$; -- APO-Valaciclovir
update drugs.brand set product_information_filename='txpvenla.pdf' where
brand=$$APO-VENLAFAXINE XR$$; -- APO-Venlafaxine
update drugs.brand set product_information_filename='txpmorph.pdf' where
brand=$$APOTEX-MORPHINE MR$$; -- APOTEX-Morphine
update drugs.brand set product_information_filename='txppiogl.pdf' where
brand=$$APOTEX-PIOGLITAZONE$$; -- APOTEX-Pioglitazone
update drugs.brand set product_information_filename='bypaptiv.pdf' where
brand=$$APTIVUS$$; -- Aptivus
update drugs.brand set product_information_filename='pfpaquit.pdf' where
brand=$$AQUINAFIL$$; -- Aquinafil
update drugs.brand set product_information_filename='swparabl.pdf' where
brand=$$ARABLOC$$; -- Arabloc
update drugs.brand set product_information_filename='anparani.pdf' where
brand=$$ARANESP$$; -- Aranesp
update drugs.brand set product_information_filename='swparava.pdf' where
brand=$$ARAVA$$; -- Arava
update drugs.brand set product_information_filename='mkparcox.pdf' where
brand=$$ARCOXIA$$; -- Arcoxia
update drugs.brand set product_information_filename='afparian.pdf' where
brand=$$ARIANNA$$; -- Arianna
update drugs.brand set product_information_filename='pfparict.pdf' where
brand=$$ARICEPT$$; -- Aricept
update drugs.brand set product_information_filename='apparimi.pdf' where
brand=$$ARIMIDEX$$; -- Arimidex
update drugs.brand set product_information_filename='gwpaxitr.pdf' where
brand=$$ARIXTRA$$; -- Arixtra
update drugs.brand set product_information_filename='pfparomt.pdf' where
brand=$$AROMASIN$$; -- Aromasin
update drugs.brand set product_information_filename='gwparopa.pdf' where
brand=$$AROPAX$$; -- Aropax
update drugs.brand set product_information_filename='afparthr.pdf' where
brand=$$ARTHREXIN$$; -- Arthrexin
update drugs.brand set product_information_filename='pfpartht.pdf' where
brand=$$ARTHROTEC 50$$; -- Arthrotec
update drugs.brand set product_information_filename='bypasasa.pdf' where
brand=$$ASASANTIN SR$$; -- Asasantin
update drugs.brand set product_information_filename='aspaustr.pdf' where
brand=$$AUSTRAPEN$$; -- Austrapen
update drugs.brand set product_information_filename='gwpavand.pdf' where
brand=$$AVANDAMET$$; -- Avandamet
update drugs.brand set product_information_filename='gwpavadt.pdf' where
brand=$$AVANDIA$$; -- Avandia
update drugs.brand set product_information_filename='gwpavoda.pdf' where
brand=$$AVODART$$; -- Avodart
update drugs.brand set product_information_filename='aspazith.pdf' where
brand=$$AZITHROMYCIN SANDOZ$$; -- Azith
update drugs.brand set product_information_filename='ropbactr.pdf' where
brand=$$BACTRIM$$; -- Bactrim
update drugs.brand set product_information_filename='bqpbarac.pdf' where
brand=$$BARACLUDE$$; -- Baraclude
update drugs.brand set product_information_filename='appbetat.pdf' where
brand=$$BETALOC$$; -- Betaloc
update drugs.brand set product_information_filename='swpbetam.pdf' where
brand=$$BETAMIN$$; -- Betamin
update drugs.brand set product_information_filename='swpbiaxs.pdf' where
brand=$$BIAXSIG$$; -- Biaxsig
update drugs.brand set product_information_filename='pfpbacii.pdf' where
brand=$$BICILLIN L-A$$; -- Bicillin
update drugs.brand set product_information_filename='afpbicor.pdf' where
brand=$$BICOR$$; -- Bicor
update drugs.brand set product_information_filename='aspbisal.pdf' where
brand=$$BISALAX$$; -- Bisalax
update drugs.brand set product_information_filename='ropbonit.pdf' where
brand=$$BONDRONAT$$; -- Bondronat
update drugs.brand set product_information_filename='agpbotox.pdf' where
brand=$$BOTOX$$; -- Botox
update drugs.brand set product_information_filename='afpbrend.pdf' where
brand=$$BRENDA-35 ED$$; -- Brenda-35
update drugs.brand set product_information_filename='pfpbrest.pdf' where
brand=$$BREVINOR$$; -- Brevinor;
update drugs.brand set product_information_filename='gwpbrevo.pdf' where
brand=$$BREVOXYL$$; -- Brevoxyl
update drugs.brand set product_information_filename='appbrici.pdf' where
brand=$$BRICANYL$$; -- Bricanyl
update drugs.brand set product_information_filename='mkpbridi.pdf' where
brand=$$BRIDION$$; -- Bridion
update drugs.brand set product_information_filename='swpbrole.pdf' where
brand=$$BROLENE$$; -- Brolene
update drugs.brand set product_information_filename='appbud64.pdf' where
brand=$$BUDAMAX AQUEOUS$$; -- Budamax
update drugs.brand set product_information_filename='bypbusco.pdf' where
brand=$$BUSCOPAN$$; -- Buscopan
update drugs.brand set product_information_filename='pfpcabat.pdf' where
brand=$$CABASER$$; -- Cabaser
update drugs.brand set product_information_filename='swpcalre.pdf' where
brand=$$CALCIUM FOLINATE EBEWE$$; -- Calcium
update drugs.brand set product_information_filename='afpcampr.pdf' where
brand=$$CAMPRAL$$; -- Campral
update drugs.brand set product_information_filename='afpcardo.pdf' where
brand=$$CARDOL$$; -- Cardol
update drugs.brand set product_information_filename='pfpcaviv.pdf' where
brand=$$CAVERJECT IMPULSE$$; -- Caverject
update drugs.brand set product_information_filename='afpcelap.pdf' where
brand=$$CELAPRAM$$; -- Celapram
update drugs.brand set product_information_filename='pfpcelec.pdf' where
brand=$$CELEBREX$$; -- Celebrex
update drugs.brand set product_information_filename='ropccept.pdf' where
brand=$$CELLCEPT$$; -- CellCept
update drugs.brand set product_information_filename='agpcellf.pdf' where
brand=$$CELLUFRESH$$; -- Cellufresh
update drugs.brand set product_information_filename='agpcellv.pdf' where
brand=$$CELLUVISC$$; -- Celluvisc
update drugs.brand set product_information_filename='vipcelse.pdf' where
brand=$$CELSENTRI$$; -- Celsentri
update drugs.brand set product_information_filename='afpcephz.pdf' where
brand=$$CEPHAZOLIN ALPHAPHARM$$; -- Cephazolin
update drugs.brand set product_information_filename='afpcepto.pdf' where
brand=$$CEPTOLATE$$; -- Ceptolate
update drugs.brand set product_information_filename='nvpceror.pdf' where
brand=$$CERTICAN$$; -- Certican
update drugs.brand set product_information_filename='sgpcetro.pdf' where
brand=$$CETROTIDE$$; -- Cetrotide
update drugs.brand set product_information_filename='pfpchamt.pdf' where
brand=$$CHAMPIX$$; -- Champix
update drugs.brand set product_information_filename='aspchlor.pdf' where
brand=$$CHLORVESCENT$$; -- Chlorvescent
update drugs.brand set product_information_filename='lypciali.pdf' where
brand=$$CIALIS$$; -- Cialis
update drugs.brand set product_information_filename='lupcipra.pdf' where
brand=$$CIPRAMIL$$; -- Cipramil
update drugs.brand set product_information_filename='mkpclard.pdf' where
brand=$$CLARATYNE$$; -- Claratyne-D
update drugs.brand set product_information_filename='pfpcleoc.pdf' where
brand=$$CLEOCIN$$; -- Cleocin
update drugs.brand set product_information_filename='swpclexa.pdf' where
brand=$$CLEXANE$$; -- Clexane
update drugs.brand set product_information_filename='swpclomi.pdf' where
brand=$$CLOMID$$; -- Clomid
update drugs.brand set product_information_filename='afpclone.pdf' where
brand=$$CLONEA$$; -- Clonea
update drugs.brand set product_information_filename='lupclopi.pdf' where
brand=$$CLOPIXOL DEPOT$$; -- Clopixol
update drugs.brand set product_information_filename='pfpcobat.pdf' where
brand=$$COBASOL$$; -- Cobasol
update drugs.brand set product_information_filename='afpcoles.pdf' where
brand=$$COLESE$$; -- Colese
update drugs.brand set product_information_filename='pfpcolep.pdf' where
brand=$$COLESTID$$; -- Colestid
update drugs.brand set product_information_filename='aspcolgo.pdf' where
brand=$$COLGOUT$$; -- Colgout
update drugs.brand set product_information_filename='aspcolif.pdf' where
brand=$$COLIFOAM$$; -- Colifoam
update drugs.brand set product_information_filename='smpcolof.pdf' where
brand=$$COLOFAC$$; -- Colofac
update drugs.brand set product_information_filename='agpcombi.pdf' where
brand=$$COMBIGAN$$; -- Combigan
update drugs.brand set product_information_filename='vipcombi.pdf' where
brand=$$COMBIVIR$$; -- Combivir
update drugs.brand set product_information_filename='nvpcomor.pdf' where
brand=$$COMTAN$$; -- Comtan
update drugs.brand set product_information_filename='swpcopax.pdf' where
brand=$$COPAXONE$$; -- Copaxone
update drugs.brand set product_information_filename='swpcopla.pdf' where
brand=$$COPLAVIX$$; -- CoPlavix
update drugs.brand set product_information_filename='sepcoral.pdf' where
brand=$$CORALAN$$; -- Coralan
update drugs.brand set product_information_filename='afpcoras.pdf' where
brand=$$CORAS$$; -- Coras
update drugs.brand set product_information_filename='aspcorta.pdf' where
brand=$$CORTATE$$; -- Cortate
update drugs.brand set product_information_filename='afpcosam.pdf' where
brand=$$COSAMIDE$$; -- Cosamide
update drugs.brand set product_information_filename='mkpcosop.pdf' where
brand=$$COSOPT$$; -- Cosopt
update drugs.brand set product_information_filename='sepcovam.pdf' where
brand=$$COVERAM$$; -- Coveram
update drugs.brand set product_information_filename='mkpcozaa.pdf' where
brand=$$COZAAR$$; -- Cozaar
update drugs.brand set product_information_filename='afpcozav.pdf' where
brand=$$COZAVAN$$; -- Cozavan
update drugs.brand set product_information_filename='appcrest.pdf' where
brand=$$CRESTOR$$; -- Crestor
update drugs.brand set product_information_filename='sgpcrino.pdf' where
brand=$$CRINONE 8%$$; -- Crinone
update drugs.brand set product_information_filename='mkpcrixi.pdf' where
brand=$$CRIXIVAN 400 MG$$; -- Crixivan
update drugs.brand set product_information_filename='ropcrysa.pdf' where
brand=$$CRYSANAL$$; -- Crysanal
update drugs.brand set product_information_filename='nvpcubin.pdf' where
brand=$$CUBICIN$$; -- Cubicin
update drugs.brand set product_information_filename='pfpcycla.pdf' where
brand=$$CYCLOBLASTIN$$; -- Cycloblastin
update drugs.brand set product_information_filename='pfpcyklt.pdf' where
brand=$$CYKLOKAPRON$$; -- Cyklokapron
update drugs.brand set product_information_filename='lypcymbt.pdf' where
brand=$$CYMBALTA$$; -- Cymbalta
update drugs.brand set product_information_filename='ropcymev.pdf' where
brand=$$CYMEVENE$$; -- Cymevene
update drugs.brand set product_information_filename='afpcypro.pdf' where
brand=$$CYPRONE$$; -- Cyprone
update drugs.brand set product_information_filename='pfpcytai.pdf' where
brand=$$CYTARABINE$$; -- Cytarabine
update drugs.brand set product_information_filename='pfpcytot.pdf' where
brand=$$CYTOTEC$$; -- Cytotec
update drugs.brand set product_information_filename='afpd-pen.pdf' where
brand=$$D-PENAMINE$$; -- D-Penamine
update drugs.brand set product_information_filename='pcpdakta.pdf' where
brand=$$DAKTARIN$$; -- Daktarin
update drugs.brand set product_information_filename='swpdaoni.pdf' where
brand=$$DAONIL$$; -- Daonil
update drugs.brand set product_information_filename='afpdapat.pdf' where
brand=$$DAPA-TABS$$; -- Dapa-Tabs
update drugs.brand set product_information_filename='gwpdarap.pdf' where
brand=$$DARAPRIM$$; -- Daraprim
update drugs.brand set product_information_filename='mkpdecad.pdf' where
brand=$$DECA-DURABOLIN$$; -- Deca-Durabolin
update drugs.brand set product_information_filename='afpdenpa.pdf' where
brand=$$DENPAX$$; -- Denpax
update drugs.brand set product_information_filename='pfpdepmi.pdf' where
brand=$$DEPO-MEDROL$$; -- Depo-Medrol
update drugs.brand set product_information_filename='pfpdepni.pdf' where
brand=$$DEPO-NISOLONE$$; -- Depo-Nisolone
update drugs.brand set product_information_filename='pfpdepoi.pdf' where
brand=$$DEPO-PROVERA$$; -- Depo-Provera
update drugs.brand set product_information_filename='pfpdepri.pdf' where
brand=$$DEPO-RALOVERA$$; -- Depo-Ralovera
update drugs.brand set product_information_filename='pfpdetrt.pdf' where
brand=$$DETRUSITOL$$; -- Detrusitol
update drugs.brand set product_information_filename='aspdexme.pdf' where
brand=$$DEXMETHSONE$$; -- Dexmethsone
update drugs.brand set product_information_filename='sepd60mr.pdf' where
brand=$$DIAMICRON 60MG MR$$; -- Diamicron
update drugs.brand set product_information_filename='afpdicar.pdf' where
brand=$$DICARZ$$; -- Dicarz
update drugs.brand set product_information_filename='pfpdidot.pdf' where
brand=$$DIDROCAL$$; -- Didrocal
update drugs.brand set product_information_filename='pfpdidrt.pdf' where
brand=$$DIDRONEL$$; -- Didronel
update drugs.brand set product_information_filename='pfpdiflb.pdf' where
brand=$$DIFLUCAN$$; -- Diflucan
update drugs.brand set product_information_filename='nvpdheal.pdf' where
brand=$$DIHYDERGOT$$; -- Dihydergot
update drugs.brand set product_information_filename='pfpdilaa.pdf' where
brand=$$DILANTIN$$; -- Dilantin
update drugs.brand set product_information_filename='mfpdilau.pdf' where
brand=$$DILAUDID$$; -- Dilaudid
update drugs.brand set product_information_filename='swpdhecd.pdf' where
brand=$$DILTAHEXAL CD$$; -- Diltahexal
update drugs.brand set product_information_filename='swpdimet.pdf' where
brand=$$DIMETRIOSE$$; -- Dimetriose
update drugs.brand set product_information_filename='swpdimir.pdf' where
brand=$$DIMIREL$$; -- Dimirel
update drugs.brand set product_information_filename='nvpdvnor.pdf' where
brand=$$DIOVAN$$; -- Diovan
update drugs.brand set product_information_filename='ispdiphi.pdf' where
brand=$$DIPHERELINE$$; -- Diphereline
update drugs.brand set product_information_filename='appdipri.pdf' where
brand=$$DIPRIVAN$$; -- Diprivan
update drugs.brand set product_information_filename='swpditro.pdf' where
brand=$$DITROPAN$$; -- Ditropan
update drugs.brand set product_information_filename='aspdobut.pdf' where
brand=$$DOBUTREX$$; -- Dobutrex
update drugs.brand set product_information_filename='swpdormi.pdf' where
brand=$$DORMIZOL$$; -- Dormizol
update drugs.brand set product_information_filename='pfpdosat.pdf' where
brand=$$DOSTAN$$; -- Dostan
update drugs.brand set product_information_filename='pfpdostt.pdf' where
brand=$$DOSTINEX$$; -- Dostinex
update drugs.brand set product_information_filename='bypduspd.pdf' where
brand=$$DULCOLAX$$; -- Dulcolax
update drugs.brand set product_information_filename='bqpduoco.pdf' where
brand=$$DUOCOVER$$; -- DuoCover
update drugs.brand set product_information_filename='gwpduoda.pdf' where
brand=$$DUODART 500UG/400UG$$; -- Duodart
update drugs.brand set product_information_filename='smpduoda.pdf' where
brand=$$DUODOPA$$; -- Duodopa
update drugs.brand set product_information_filename='smpduphc.pdf' where
brand=$$DUPHALAC$$; -- Duphalac
update drugs.brand set product_information_filename='fppdurai.pdf' where
brand=$$DURATOCIN$$; -- Duratocin
update drugs.brand set product_information_filename='afpdurid.pdf' where
brand=$$DURIDE$$; -- Duride
update drugs.brand set product_information_filename='nvpdukor.pdf' where
brand=$$DURO-K$$; -- Duro-K
update drugs.brand set product_information_filename='iapdurom.pdf' where
brand=$$DUROMINE$$; -- Duromine
update drugs.brand set product_information_filename='iaptramx.pdf' where
brand=$$DUROTRAM XR$$; -- Durotram
update drugs.brand set product_information_filename='pfpdynav.pdf' where
brand=$$DYNASTAT$$; -- Dynastat
update drugs.brand set product_information_filename='ispdyspi.pdf' where
brand=$$DYSPORT$$; -- Dysport
update drugs.brand set product_information_filename='afpemyci.pdf' where
brand=$$E-MYCIN$$; -- E-Mycin
update drugs.brand set product_information_filename='lupebixa.pdf' where
brand=$$EBIXA$$; -- Ebixa
update drugs.brand set product_information_filename='pfpedrot.pdf' where
brand=$$EDRONAX$$; -- Edronax
update drugs.brand set product_information_filename='pfpefexc.pdf' where
brand=$$EFEXOR-XR$$; -- Efexor-XR
update drugs.brand set product_information_filename='lypeffnt.pdf' where
brand=$$EFFIENT$$; -- Effient
update drugs.brand set product_information_filename='aspeldep.pdf' where
brand=$$ELDEPRYL$$; -- Eldepryl
update drugs.brand set product_information_filename='mkpeleup.pdf' where
brand=$$ELEUPHRAT$$; -- Eleuphrat
update drugs.brand set product_information_filename='nvpelicr.pdf' where
brand=$$ELIDEL$$; -- Elidel
update drugs.brand set product_information_filename='bqpeliqu.pdf' where
brand=$$ELIQUIS$$; -- Eliquis
update drugs.brand set product_information_filename='mkpeloco.pdf' where
brand=$$ELOCON$$; -- Elocon
update drugs.brand set product_information_filename='mkpelonv.pdf' where
brand=$$ELONVA$$; -- Elonva
update drugs.brand set product_information_filename='nvpenaor.pdf' where
brand=$$ENABLEX$$; -- Enablex
update drugs.brand set product_information_filename='pfpenbra.pdf' where
brand=$$ENBREL$$; -- Enbrel
update drugs.brand set product_information_filename='agpenidi.pdf' where
brand=$$ENIDIN$$; -- Enidin
update drugs.brand set product_information_filename='afpenlax.pdf' where
brand=$$ENLAFAX-XR$$; -- Enlafax
update drugs.brand set product_information_filename='pfperaxv.pdf' where
brand=$$ERAXIS$$; -- Eraxis
update drugs.brand set product_information_filename='cfpesipr.pdf' where
brand=$$ESIPRAM$$; -- Esipram
update drugs.brand set product_information_filename='gwpeskat.pdf' where
brand=$$ESKAZOLE$$; -- Eskazole
update drugs.brand set product_information_filename='mkpesmer.pdf' where
brand=$$ESMERON$$; -- Esmeron
update drugs.brand set product_information_filename='mkpethyo.pdf' where
brand=$$ETHYOL$$; -- Ethyol
update drugs.brand set product_information_filename='shpeulex.pdf' where
brand=$$EULEXIN$$; -- Eulexin
update drugs.brand set product_information_filename='lypevist.pdf' where
brand=$$EVISTA$$; -- Evista
update drugs.brand set product_information_filename='nvpexjor.pdf' where
brand=$$EXJADE$$; -- Exjade
update drugs.brand set product_information_filename='iapeyezp.pdf' where
brand=$$EYEZEP$$; -- Eyezep
update drugs.brand set product_information_filename='mkpezetr.pdf' where
brand=$$EZETROL$$; -- Ezetrol
update drugs.brand set product_information_filename='afpezovi.pdf' where
brand=$$EZOVIR$$; -- Ezovir
update drugs.brand set product_information_filename='nvpfamor.pdf' where
brand=$$FAMVIR$$; -- Famvir
update drugs.brand set product_information_filename='mkpfares.pdf' where
brand=$$FARESTON$$; -- Fareston
update drugs.brand set product_information_filename='pfpfasit.pdf' where
brand=$$FASIGYN$$; -- Fasigyn
update drugs.brand set product_information_filename='appfaslo.pdf' where
brand=$$FASLODEX$$; -- Faslodex
update drugs.brand set product_information_filename='swpfastu.pdf' where
brand=$$FASTURTEC$$; -- Fasturtec
update drugs.brand set product_information_filename='nvpfemor.pdf' where
brand=$$FEMARA 2.5 MG$$; -- Femara
update drugs.brand set product_information_filename='afpfemol.pdf' where
brand=$$FEMOLET$$; -- Femolet
update drugs.brand set product_information_filename='smpfemos.pdf' where
brand=$$FEMOSTON 2/10$$; -- Femoston
update drugs.brand set product_information_filename='afpfenac.pdf' where
brand=$$FENAC$$; -- Fenac
update drugs.brand set product_information_filename='appfenta.pdf' where
brand=$$FENTANYL SANDOZ$$; -- Fentanyl
update drugs.brand set product_information_filename='aspferru.pdf' where
brand=$$FERRUM H$$; -- Ferrum
update drugs.brand set product_information_filename='fppfirma.pdf' where
brand=$$FIRMAGON$$; -- Firmagon
update drugs.brand set product_information_filename='afpfleca.pdf' where
brand=$$FLECATAB$$; -- Flecatab
update drugs.brand set product_information_filename='gwpfloln.pdf' where
brand=$$FLOLAN KIT$$; -- Flolan
update drugs.brand set product_information_filename='aspflope.pdf' where
brand=$$FLOPEN$$; -- Flopen
update drugs.brand set product_information_filename='aspfluci.pdf' where
brand=$$FLUCIL$$; -- Flucil
update drugs.brand set product_information_filename='nvpfluin.pdf' where
brand=$$FLUORESCEIN NOVARTIS$$; -- Fluorescein
update drugs.brand set product_information_filename='afpfluta.pdf' where
brand=$$FLUTAMIN$$; -- Flutamin
update drugs.brand set product_information_filename='agpfmley.pdf' where
brand=$$FML LIQUIFILM$$; -- FML
update drugs.brand set product_information_filename='nvpforih.pdf' where
brand=$$FORADILE$$; -- Foradile
update drugs.brand set product_information_filename='lypforte.pdf' where
brand=$$FORTEO$$; -- Forteo
update drugs.brand set product_information_filename='appfosca.pdf' where
brand=$$FOSCAVIR$$; -- Foscavir
update drugs.brand set product_information_filename='pfpfragi.pdf' where
brand=$$FRAGMIN$$; -- Fragmin
update drugs.brand set product_information_filename='ropfuzeo.pdf' where
brand=$$FUZEON$$; -- Fuzeon
update drugs.brand set product_information_filename='afpgalan.pdf' where
brand=$$GALANTYL$$; -- Galantyl
update drugs.brand set product_information_filename='nvpgalor.pdf' where
brand=$$GALVUS$$; -- Galvus
update drugs.brand set product_information_filename='agpganfo.pdf' where
brand=$$GANFORT 0.3/5$$; -- Ganfort
update drugs.brand set product_information_filename='pfpganta.pdf' where
brand=$$GANTIN$$; -- Gantin
update drugs.brand set product_information_filename='mkpgarda.pdf' where
brand=$$GARDASIL$$; -- Gardasil
update drugs.brand set product_information_filename='agpgenop.pdf' where
brand=$$GENOPTIC$$; -- Genoptic
update drugs.brand set product_information_filename='pfpgenov.pdf' where
brand=$$GENOTROPIN$$; -- Genotropin
update drugs.brand set product_information_filename='nvpgilor.pdf' where
brand=$$GILENYA$$; -- Gilenya
update drugs.brand set product_information_filename='afpglime.pdf' where
brand=$$GLIMEL$$; -- Glimel
update drugs.brand set product_information_filename='nvpglior.pdf' where
brand=$$GLIVEC$$; -- Glivec
update drugs.brand set product_information_filename='afpglucp.pdf' where
brand=$$GLUCOPHAGE$$; -- Glucophage
update drugs.brand set product_information_filename='pupgluiv.pdf' where
brand=$$GLUCOSE 5% FREEFLEX$$; -- Glucose
update drugs.brand set product_information_filename='sgpgonal.pdf' where
brand=$$GONAL-F PEN$$; -- Gonal-f
update drugs.brand set product_information_filename='mkphbvii.pdf' where
brand=$$H-B-VAX II$$; -- H-B-VAX
update drugs.brand set product_information_filename='lyphulog.pdf' where
brand=$$HUMALOG$$; -- Humalog,
update drugs.brand set product_information_filename='lyphumat.pdf' where
brand=$$HUMATROPE$$; -- Humatrope
update drugs.brand set product_information_filename='afphydop.pdf' where
brand=$$HYDOPA$$; -- Hydopa
update drugs.brand set product_information_filename='bqphydre.pdf' where
brand=$$HYDREA$$; -- Hydrea
update drugs.brand set product_information_filename='afphydre.pdf' where
brand=$$HYDRENE 25/50$$; -- Hydrene
update drugs.brand set product_information_filename='asphydro.pdf' where
brand=$$HYDROXO-B12$$; -- Hydroxo-B12
update drugs.brand set product_information_filename='nvphygor.pdf' where
brand=$$HYGROTON 25$$; -- Hygroton
update drugs.brand set product_information_filename='afphypno.pdf' where
brand=$$HYPNODORM$$; -- Hypnodorm
update drugs.brand set product_information_filename='rophypno.pdf' where
brand=$$HYPNOVEL$$; -- Hypnovel
update drugs.brand set product_information_filename='aspialex.pdf' where
brand=$$IALEX$$; -- Ialex
update drugs.brand set product_information_filename='swpikore.pdf' where
brand=$$IKOREL$$; -- Ikorel
update drugs.brand set product_information_filename='nvpilain.pdf' where
brand=$$ILARIS$$; -- Ilaris
update drugs.brand set product_information_filename='gwpimigr.pdf' where
brand=$$IMIGRAN$$; -- Imigran
update drugs.brand set product_information_filename='swpimmuc.pdf' where
brand=$$IMMUCYST$$; -- Immucyst
update drugs.brand set product_information_filename='swpimova.pdf' where
brand=$$IMOVANE$$; -- Imovane
update drugs.brand set product_information_filename='afpimres.pdf' where
brand=$$IMREST$$; -- Imrest
update drugs.brand set product_information_filename='bypimuki.pdf' where
brand=$$IMUKIN$$; -- Imukin
update drugs.brand set product_information_filename='aspimura.pdf' where
brand=$$IMURAN$$; -- Imuran
update drugs.brand set product_information_filename='appinder.pdf' where
brand=$$INDERAL$$; -- Inderal
update drugs.brand set product_information_filename='aspindoc.pdf' where
brand=$$INDOCID$$; -- Indocid
update drugs.brand set product_information_filename='pfpinspt.pdf' where
brand=$$INSPRA$$; -- Inspra
update drugs.brand set product_information_filename='mkpinteg.pdf' where
brand=$$INTEGRILIN$$; -- Integrilin
update drugs.brand set product_information_filename='mkpinvan.pdf' where
brand=$$INVANZ$$; -- Invanz
update drugs.brand set product_information_filename='ropinvir.pdf' where
brand=$$INVIRASE$$; -- Invirase
update drugs.brand set product_information_filename='afpiprat.pdf' where
brand=$$IPRATRIN$$; -- Ipratrin
update drugs.brand set product_information_filename='agpircal.pdf' where
brand=$$IRCAL$$; -- Ircal
update drugs.brand set product_information_filename='appiress.pdf' where
brand=$$IRESSA$$; -- Iressa
update drugs.brand set product_information_filename='bqpiscov.pdf' where
brand=$$ISCOVER$$; -- Iscover
update drugs.brand set product_information_filename='mkpisent.pdf' where
brand=$$ISENTRESS$$; -- Isentress
update drugs.brand set product_information_filename='mkpjanum.pdf' where
brand=$$JANUMET$$; -- Janumet
update drugs.brand set product_information_filename='mkpjanuv.pdf' where
brand=$$JANUVIA$$; -- Januvia
update drugs.brand set product_information_filename='pfpjezit.pdf' where
brand=$$JEZIL$$; -- Jezil
update drugs.brand set product_information_filename='afpkalix.pdf' where
brand=$$KALIXOCIN$$; -- Kalixocin
update drugs.brand set product_information_filename='gwpkapan.pdf' where
brand=$$KAPANOL$$; -- Kapanol
update drugs.brand set product_information_filename='aspkarcd.pdf' where
brand=$$KARLOR CD$$; -- Karlor
update drugs.brand set product_information_filename='swpkarve.pdf' where
brand=$$KARVEA$$; -- Karvea
update drugs.brand set product_information_filename='aspkefle.pdf' where
brand=$$KEFLEX$$; -- Keflex
update drugs.brand set product_information_filename='aspkefli.pdf' where
brand=$$KEFLIN NEUTRAL$$; -- Keflin
update drugs.brand set product_information_filename='aspkefzo.pdf' where
brand=$$KEFZOL$$; -- Kefzol
update drugs.brand set product_information_filename='aspketor.pdf' where
brand=$$KETORAL INJECTION$$; -- Ketoral
update drugs.brand set product_information_filename='afpkevta.pdf' where
brand=$$KEVTAM$$; -- Kevtam
update drugs.brand set product_information_filename='afpkinso.pdf' where
brand=$$KINSON$$; -- Kinson
update drugs.brand set product_information_filename='vipkivex.pdf' where
brand=$$KIVEXA$$; -- Kivexa
update drugs.brand set product_information_filename='ropkytit.pdf' where
brand=$$KYTRIL$$; -- Kytril
update drugs.brand set product_information_filename='agplacri.pdf' where
brand=$$LACRI-LUBE$$; -- Lacri-Lube
update drugs.brand set product_information_filename='gwplamic.pdf' where
brand=$$LAMICTAL$$; -- Lamictal
update drugs.brand set product_information_filename='nvplamor.pdf' where
brand=$$LAMISIL$$; -- Lamisil
update drugs.brand set product_information_filename='afplamog.pdf' where
brand=$$LAMOGINE$$; -- Lamogine
update drugs.brand set product_information_filename='swplantu.pdf' where
brand=$$LANTUS$$; -- Lantus
update drugs.brand set product_information_filename='asplanvi.pdf' where
brand=$$LANVIS$$; -- Lanvis
update drugs.brand set product_information_filename='lyplanzk.pdf' where
brand=$$LANZEK$$; -- Lanzek;
update drugs.brand set product_information_filename='swplarga.pdf' where
brand=$$LARGACTIL$$; -- Largactil
update drugs.brand set product_information_filename='roplaria.pdf' where
brand=$$LARIAM$$; -- Lariam
update drugs.brand set product_information_filename='asplengo.pdf' where
brand=$$LENGOUT$$; -- Lengout
update drugs.brand set product_information_filename='smplercd.pdf' where
brand=$$LERCADIP$$; -- Lercadip
update drugs.brand set product_information_filename='smplerca.pdf' where
brand=$$LERCAN$$; -- Lercan
update drugs.brand set product_information_filename='smplercs.pdf' where
brand=$$LERCANIDIPINE SANDOZ$$; -- Lercanidipine
update drugs.brand set product_information_filename='nvplesor.pdf' where
brand=$$LESCOL$$; -- Lescol
update drugs.brand set product_information_filename='aspleuke.pdf' where
brand=$$LEUKERAN$$; -- Leukeran
update drugs.brand set product_information_filename='luplexap.pdf' where
brand=$$LEXAPRO$$; -- Lexapro
update drugs.brand set product_information_filename='roplexot.pdf' where
brand=$$LEXOTAN$$; -- Lexotan
update drugs.brand set product_information_filename='pfplinci.pdf' where
brand=$$LINCOCIN$$; -- Lincocin
update drugs.brand set product_information_filename='smplipid.pdf' where
brand=$$LIPIDIL$$; -- Lipidil
update drugs.brand set product_information_filename='afplipig.pdf' where
brand=$$LIPIGEM$$; -- Lipigem
update drugs.brand set product_information_filename='pfplipit.pdf' where
brand=$$LIPITOR$$; -- Lipitor
update drugs.brand set product_information_filename='applisod.pdf' where
brand=$$LISODUR$$; -- Lisodur
update drugs.brand set product_information_filename='asplithi.pdf' where
brand=$$LITHICARB$$; -- Lithicarb
update drugs.brand set product_information_filename='mkplivia.pdf' where
brand=$$LIVIAL$$; -- Livial
update drugs.brand set product_information_filename='pfplocit.pdf' where
brand=$$LOCILAN 28 DAY$$; -- Locilan
update drugs.brand set product_information_filename='pfplonit.pdf' where
brand=$$LONITEN$$; -- Loniten
update drugs.brand set product_information_filename='pfplopit.pdf' where
brand=$$LOPID$$; -- Lopid
update drugs.brand set product_information_filename='apploset.pdf' where
brand=$$LOSEC TABLETS$$; -- Losec
update drugs.brand set product_information_filename='afplovan.pdf' where
brand=$$LOVAN$$; -- Lovan
update drugs.brand set product_information_filename='afploxal.pdf' where
brand=$$LOXALATE$$; -- Loxalate
update drugs.brand set product_information_filename='nvplucin.pdf' where
brand=$$LUCENTIS$$; -- Lucentis
update drugs.brand set product_information_filename='agplumig.pdf' where
brand=$$LUMIGAN$$; -- Lumigan
update drugs.brand set product_information_filename='sgpluvpd.pdf' where
brand=$$LUVERIS$$; -- Luveris
update drugs.brand set product_information_filename='smpluvox.pdf' where
brand=$$LUVOX$$; -- Luvox
update drugs.brand set product_information_filename='pfplyric.pdf' where
brand=$$LYRICA$$; -- Lyrica
update drugs.brand set product_information_filename='ropmabth.pdf' where
brand=$$MABTHERA$$; -- Mabthera
update drugs.brand set product_information_filename='pfpmacrc.pdf' where
brand=$$MACRODANTIN$$; -- Macrodantin
update drugs.brand set product_information_filename='ropmadop.pdf' where
brand=$$MADOPAR$$; -- Madopar
update drugs.brand set product_information_filename='gwpmalar.pdf' where
brand=$$MALARONE$$; -- Malarone
update drugs.brand set product_information_filename='mkpmaxal.pdf' where
brand=$$MAXALT$$; -- Maxalt
update drugs.brand set product_information_filename='bqpmaxip.pdf' where
brand=$$MAXIPIME$$; -- Maxipime
update drugs.brand set product_information_filename='afpmeliz.pdf' where
brand=$$MELIZIDE$$; -- Melizide
update drugs.brand set product_information_filename='gwpmesal.pdf' where
brand=$$MESASAL$$; -- Mesasal
update drugs.brand set product_information_filename='bypmetal.pdf' where
brand=$$METALYSE$$; -- Metalyse
update drugs.brand set product_information_filename='iapmetmn.pdf' where
brand=$$METERMINE$$; -- Metermine
update drugs.brand set product_information_filename='pfpmetht.pdf' where
brand=$$METHOBLASTIN$$; -- Methoblastin
update drugs.brand set product_information_filename='aspmethy.pdf' where
brand=$$METHYLPRED$$; -- Methylpred
update drugs.brand set product_information_filename='pfpmindt.pdf' where
brand=$$MINIDIAB$$; -- Minidiab
update drugs.brand set product_information_filename='pfpminit.pdf' where
brand=$$MINIPRESS$$; -- Minipress
update drugs.brand set product_information_filename='nvpmioei.pdf' where
brand=$$MIOCHOL-E$$; -- Miochol-E
update drugs.brand set product_information_filename='ropmirce.pdf' where
brand=$$MIRCERA$$; -- Mircera
update drugs.brand set product_information_filename='mkpmirdp.pdf' where
brand=$$MIRTAZAPINE-DP$$; -- Mirtazapine-DP
update drugs.brand set product_information_filename='mkpmirta.pdf' where
brand=$$MIRTAZON$$; -- Mirtazon
update drugs.brand set product_information_filename='bqpmitom.pdf' where
brand=$$MITOMYCIN-C KYOWA$$; -- Mitomycin-C
update drugs.brand set product_information_filename='bypmobic.pdf' where
brand=$$MOBIC$$; -- Mobic
update drugs.brand set product_information_filename='bqpmodec.pdf' where
brand=$$MODECATE$$; -- Modecate
update drugs.brand set product_information_filename='aspmodur.pdf' where
brand=$$MODURETIC$$; -- Moduretic
update drugs.brand set product_information_filename='pfpmonot.pdf' where
brand=$$MONOFEME 28$$; -- Monofeme
update drugs.brand set product_information_filename='bqpmonor.pdf' where
brand=$$MONOPRIL$$; -- Monopril
update drugs.brand set product_information_filename='pfpmycoc.pdf' where
brand=$$MYCOBUTIN$$; -- Mycobutin
update drugs.brand set product_information_filename='nvpmyfor.pdf' where
brand=$$MYFORTIC$$; -- Myfortic
update drugs.brand set product_information_filename='aspmyler.pdf' where
brand=$$MYLERAN$$; -- Myleran
update drugs.brand set product_information_filename='swpmyocr.pdf' where
brand=$$MYOCRISIN$$; -- Myocrisin
update drugs.brand set product_information_filename='gwpnaram.pdf' where
brand=$$NARAMIG$$; -- Naramig
update drugs.brand set product_information_filename='nvpnaval.pdf' where
brand=$$NAVOBAN$$; -- Navoban
update drugs.brand set product_information_filename='nvpneoor.pdf' where
brand=$$NEORAL$$; -- Neoral
update drugs.brand set product_information_filename='ropneore.pdf' where
brand=$$NEORECORMON$$; -- NeoRecormon
update drugs.brand set product_information_filename='swpneula.pdf' where
brand=$$NEULACTIL$$; -- Neulactil
update drugs.brand set product_information_filename='anpneula.pdf' where
brand=$$NEULASTA$$; -- Neulasta
update drugs.brand set product_information_filename='anpneupi.pdf' where
brand=$$NEUPOGEN$$; -- Neupogen
update drugs.brand set product_information_filename='pfpneura.pdf' where
brand=$$NEURONTIN$$; -- Neurontin
update drugs.brand set product_information_filename='afpnicac.pdf' where
brand=$$NICOTINIC ACID$$; -- Nicotinic
update drugs.brand set product_information_filename='gwpnimbe.pdf' where
brand=$$NIMBEX$$; -- Nimbex
update drugs.brand set product_information_filename='swpnitro.pdf' where
brand=$$NITROLINGUAL PUMPSPRAY$$; -- Nitrolingual
update drugs.brand set product_information_filename='aspnizac.pdf' where
brand=$$NIZAC$$; -- Nizac
update drugs.brand set product_information_filename='appnolva.pdf' where
brand=$$NOLVADEX-D$$; -- Nolvadex
update drugs.brand set product_information_filename='mkpnorcu.pdf' where
brand=$$NORCURON$$; -- Norcuron
update drugs.brand set product_information_filename='pfpnordt.pdf' where
brand=$$NORDETTE 28$$; -- Nordette
update drugs.brand set product_information_filename='afpnordi.pdf' where
brand=$$NORDIP$$; -- Nordip
update drugs.brand set product_information_filename='pfpnorit.pdf' where
brand=$$NORIDAY 28 DAY$$; -- Noriday
update drugs.brand set product_information_filename='pfpnoryt.pdf' where
brand=$$NORINYL-1/28$$; -- Norinyl-1
update drugs.brand set product_information_filename='mkpnorox.pdf' where
brand=$$NOROXIN$$; -- Noroxin
update drugs.brand set product_information_filename='fppnorpt.pdf' where
brand=$$NORPROLAC$$; -- Norprolac
update drugs.brand set product_information_filename='mfpnorsp.pdf' where
brand=$$NORSPAN$$; -- Norspan
update drugs.brand set product_information_filename='pfpnornt.pdf' where
brand=$$NORVAPINE$$; -- Norvapine
update drugs.brand set product_information_filename='pfpnorvt.pdf' where
brand=$$NORVASC$$; -- Norvasc
update drugs.brand set product_information_filename='afpnoten.pdf' where
brand=$$NOTEN$$; -- Noten
update drugs.brand set product_information_filename='mkpnovas.pdf' where
brand=$$NOVASONE$$; -- Novasone
update drugs.brand set product_information_filename='nvpnovin.pdf' where
brand=$$NOVICRIT$$; -- Novicrit
update drugs.brand set product_information_filename='mkpnoxaf.pdf' where
brand=$$NOXAFIL$$; -- Noxafil
update drugs.brand set product_information_filename='anpnplap.pdf' where
brand=$$NPLATE$$; -- Nplate
update drugs.brand set product_information_filename='iapnuesp.pdf' where
brand=$$NUELIN$$; -- Nuelin
update drugs.brand set product_information_filename='afpnuflo.pdf' where
brand=$$NUFLOXIB$$; -- Nufloxib
update drugs.brand set product_information_filename='ispnut10.pdf' where
brand=$$NUTROPINAQ$$; -- NutropinAq
update drugs.brand set product_information_filename='nvpnyoop.pdf' where
brand=$$NYOGEL$$; -- Nyogel
update drugs.brand set product_information_filename='agpocufe.pdf' where
brand=$$OCUFEN$$; -- Ocufen
update drugs.brand set product_information_filename='agpocufl.pdf' where
brand=$$OCUFLOX$$; -- Ocuflox
update drugs.brand set product_information_filename='appomepr.pdf' where
brand=$$OMEPRAL$$; -- Omepral
update drugs.brand set product_information_filename='nvpobbih.pdf' where
brand=$$ONBREZ$$; -- Onbrez
update drugs.brand set product_information_filename='mkponcot.pdf' where
brand=$$ONCOTICE$$; -- Oncotice
update drugs.brand set product_information_filename='bqpongly.pdf' where
brand=$$ONGLYZA$$; -- Onglyza
update drugs.brand set product_information_filename='bqporenc.pdf' where
brand=$$ORENCIA$$; -- Orencia
update drugs.brand set product_information_filename='mkporgal.pdf' where
brand=$$ORGALUTRAN$$; -- Orgalutran
update drugs.brand set product_information_filename='mkporgar.pdf' where
brand=$$ORGARAN$$; -- Orgaran
update drugs.brand set product_information_filename='swporuva.pdf' where
brand=$$ORUVAIL SR$$; -- Oruvail
update drugs.brand set product_information_filename='swpotode.pdf' where
brand=$$OTODEX$$; -- Otodex
update drugs.brand set product_information_filename='appoxisa.pdf' where
brand=$$OXIS TURBUHALER$$; -- Oxis
update drugs.brand set product_information_filename='mfpoxyco.pdf' where
brand=$$OXYCONTIN$$; -- OxyContin
update drugs.brand set product_information_filename='asppanaf.pdf' where
brand=$$PANAFCORT$$; -- Panafcort
update drugs.brand set product_information_filename='aspparad.pdf' where
brand=$$PARADEX$$; -- Paradex
update drugs.brand set product_information_filename='nvpploor.pdf' where
brand=$$PARLODEL$$; -- Parlodel
update drugs.brand set product_information_filename='afppaxti.pdf' where
brand=$$PAXTINE$$; -- Paxtine
update drugs.brand set product_information_filename='mkppegat.pdf' where
brand=$$PEGATRON$$; -- Pegatron
update drugs.brand set product_information_filename='mkppepci.pdf' where
brand=$$PEPCIDINE$$; -- Pepcidine
update drugs.brand set product_information_filename='aspperia.pdf' where
brand=$$PERIACTIN$$; -- Periactin
update drugs.brand set product_information_filename='aspperma.pdf' where
brand=$$PERMAX$$; -- Permax
update drugs.brand set product_information_filename='apppethi.pdf' where
brand=$$Pethidine Injection BP$$; -- Pethidine
update drugs.brand set product_information_filename='smpphysi.pdf' where
brand=$$PHYSIOTENS$$; -- Physiotens
update drugs.brand set product_information_filename='afppiaxt.pdf' where
brand=$$PIAX$$; -- Piax
update drugs.brand set product_information_filename='afpplaci.pdf' where
brand=$$PLACIL$$; -- Placil
update drugs.brand set product_information_filename='swpplaqu.pdf' where
brand=$$PLAQUENIL$$; -- Plaquenil
update drugs.brand set product_information_filename='swpplavi.pdf' where
brand=$$PLAVIX$$; -- Plavix
update drugs.brand set product_information_filename='appplend.pdf' where
brand=$$PLENDIL ER$$; -- Plendil
update drugs.brand set product_information_filename='mkppneum.pdf' where
brand=$$PNEUMOVAX 23$$; -- Pneumovax
update drugs.brand set product_information_filename='gwppolyt.pdf' where
brand=$$POLYTAR$$; -- Polytar
update drugs.brand set product_information_filename='pfpponsc.pdf' where
brand=$$PONSTAN$$; -- Ponstan
update drugs.brand set product_information_filename='fpppor8i.pdf' where
brand=$$POR-8 FERRING$$; -- POR-8
update drugs.brand set product_information_filename='bypprada.pdf' where
brand=$$PRADAXA$$; -- Pradaxa
update drugs.brand set product_information_filename='afpprami.pdf' where
brand=$$PRAMIN$$; -- Pramin
update drugs.brand set product_information_filename='asppredm.pdf' where
brand=$$PREDMIX$$; -- Predmix
update drugs.brand set product_information_filename='agppredn.pdf' where
brand=$$PREDNEFRIN FORTE$$; -- Prednefrin
update drugs.brand set product_information_filename='asppredo.pdf' where
brand=$$PREDSONE$$; -- Predsone
update drugs.brand set product_information_filename='mkppregn.pdf' where
brand=$$PREGNYL$$; -- Pregnyl
update drugs.brand set product_information_filename='afpprexa.pdf' where
brand=$$PREXATON$$; -- Prexaton
update drugs.brand set product_information_filename='gwppriov.pdf' where
brand=$$PRIORIX$$; -- Priorix
update drugs.brand set product_information_filename='pfpprist.pdf' where
brand=$$PRISTIQ$$; -- Pristiq
update drugs.brand set product_information_filename='swpproct.pdf' where
brand=$$PROCTOSEDYL$$; -- Proctosedyl
update drugs.brand set product_information_filename='anpprolm.pdf' where
brand=$$PROLIA$$; -- Prolia
update drugs.brand set product_information_filename='mkpprope.pdf' where
brand=$$PROPECIA$$; -- Propecia
update drugs.brand set product_information_filename='mkpprosc.pdf' where
brand=$$PROSCAR$$; -- Proscar
update drugs.brand set product_information_filename='sepproto.pdf' where
brand=$$PROTOS 2 G$$; -- Protos
update drugs.brand set product_information_filename='pfpprovt.pdf' where
brand=$$PROVERA$$; -- Provera
update drugs.brand set product_information_filename='roppulmo.pdf' where
brand=$$PULMOZYME$$; -- Pulmozyme
update drugs.brand set product_information_filename='pfppyrat.pdf' where
brand=$$PYRALIN EN$$; -- Pyralin
update drugs.brand set product_information_filename='gwplithm.pdf' where
brand=$$QUILONUM SR$$; -- Quilonum
update drugs.brand set product_information_filename='aspquina.pdf' where
brand=$$QUINATE$$; -- Quinate
update drugs.brand set product_information_filename='pfpralvt.pdf' where
brand=$$RALOVERA$$; -- Ralovera
update drugs.brand set product_information_filename='pfpralot.pdf' where
brand=$$RALOZAM$$; -- Ralozam
update drugs.brand set product_information_filename='pfprapaa.pdf' where
brand=$$RAPAMUNE$$; -- Rapamune
update drugs.brand set product_information_filename='mkprebet.pdf' where
brand=$$REBETOL$$; -- Rebetol
update drugs.brand set product_information_filename='sgprebif.pdf' where
brand=$$REBIF 44$$; -- Rebif
update drugs.brand set product_information_filename='aspredip.pdf' where
brand=$$REDIPRED$$; -- Redipred
update drugs.brand set product_information_filename='cjpreflu.pdf' where
brand=$$REFLUDAN$$; -- Refludan
update drugs.brand set product_information_filename='nvprgtin.pdf' where
brand=$$REGITINE$$; -- Regitine
update drugs.brand set product_information_filename='pfprelii.pdf' where
brand=$$RELISTOR$$; -- Relistor
update drugs.brand set product_information_filename='pfprelxt.pdf' where
brand=$$RELPAX$$; -- Relpax
update drugs.brand set product_information_filename='lypreopr.pdf' where
brand=$$REOPRO$$; -- Reopro
update drugs.brand set product_information_filename='gwprepre.pdf' where
brand=$$REPREVE$$; -- Repreve
update drugs.brand set product_information_filename='swpreson.pdf' where
brand=$$RESONIUM-A$$; -- Resonium
update drugs.brand set product_information_filename='afprespr.pdf' where
brand=$$RESPRIM FORTE$$; -- Resprim
update drugs.brand set product_information_filename='vipretro.pdf' where
brand=$$RETROVIR$$; -- Retrovir
update drugs.brand set product_information_filename='pfprevat.pdf' where
brand=$$REVATIO$$; -- Revatio
update drugs.brand set product_information_filename='bqprevia.pdf' where
brand=$$REVIA$$; -- Revia
update drugs.brand set product_information_filename='cjprevli.pdf' where
brand=$$REVLIMID$$; -- Revlimid
update drugs.brand set product_information_filename='gwprevod.pdf' where
brand=$$REVOLADE$$; -- Revolade
update drugs.brand set product_information_filename='bqpreyat.pdf' where
brand=$$REYATAZ$$; -- Reyataz
update drugs.brand set product_information_filename='nvpriaor.pdf' where
brand=$$RIAMET$$; -- Riamet
update drugs.brand set product_information_filename='swprifad.pdf' where
brand=$$RIFADIN$$; -- Rifadin
update drugs.brand set product_information_filename='swprilut.pdf' where
brand=$$RILUTEK$$; -- Rilutek
update drugs.brand set product_information_filename='roprivot.pdf' where
brand=$$RIVOTRIL$$; -- Rivotril
update drugs.brand set product_information_filename='afprixad.pdf' where
brand=$$RIXADONE$$; -- Rixadone
update drugs.brand set product_information_filename='roproacc.pdf' where
brand=$$ROACCUTANE$$; -- Roaccutane
update drugs.brand set product_information_filename='roprocal.pdf' where
brand=$$ROCALTROL$$; -- Rocaltrol
update drugs.brand set product_information_filename='roprocep.pdf' where
brand=$$ROCEPHIN$$; -- Rocephin
update drugs.brand set product_information_filename='roprfpfs.pdf' where
brand=$$ROFERON-A$$; -- Roferon-A
update drugs.brand set product_information_filename='afproxim.pdf' where
brand=$$ROXIMYCIN$$; -- Roximycin
update drugs.brand set product_information_filename='swprulid.pdf' where
brand=$$RULIDE$$; -- Rulide
update drugs.brand set product_information_filename='swprythm.pdf' where
brand=$$RYTHMODAN$$; -- Rythmodan
update drugs.brand set product_information_filename='swpsabri.pdf' where
brand=$$SABRIL$$; -- Sabril
update drugs.brand set product_information_filename='pfpsalaa.pdf' where
brand=$$SALAZOPYRIN$$; -- Salazopyrin
update drugs.brand set product_information_filename='nvpsimal.pdf' where
brand=$$SANDIMMUN$$; -- Sandimmun
update drugs.brand set product_information_filename='nvpsmgor.pdf' where
brand=$$SANDOMIGRAN 0.5$$; -- Sandomigran
update drugs.brand set product_information_filename='mkpsaphr.pdf' where
brand=$$SAPHRIS$$; -- Saphris
update drugs.brand set product_information_filename='nvpsebor.pdf' where
brand=$$SEBIVO$$; -- Sebivo
update drugs.brand set product_information_filename='afpselge.pdf' where
brand=$$SELGENE$$; -- Selgene
update drugs.brand set product_information_filename='anpsenst.pdf' where
brand=$$SENSIPAR$$; -- Sensipar
update drugs.brand set product_information_filename='appsequa.pdf' where
brand=$$SEQUASE$$; -- Sequase
update drugs.brand set product_information_filename='smpserct.pdf' where
brand=$$SERC$$; -- Serc
update drugs.brand set product_information_filename='gwpserev.pdf' where
brand=$$SEREVENT ACCUHALER$$; -- Serevent
update drugs.brand set product_information_filename='sgpserop.pdf' where
brand=$$SEROPHENE$$; -- Serophene
update drugs.brand set product_information_filename='mfpsevre.pdf' where
brand=$$SEVREDOL$$; -- Sevredol
update drugs.brand set product_information_filename='afpsical.pdf' where
brand=$$SICAL$$; -- Sical
update drugs.brand set product_information_filename='bypsifro.pdf' where
brand=$$SIFROL$$; -- Sifrol
update drugs.brand set product_information_filename='pfpsimpt.pdf' where
brand=$$SIMPLOTAN$$; -- Simplotan
update drugs.brand set product_information_filename='nvpsmlin.pdf' where
brand=$$SIMULECT$$; -- Simulect
update drugs.brand set product_information_filename='pfpsinec.pdf' where
brand=$$SINEQUAN$$; -- Sinequan
update drugs.brand set product_information_filename='mkpsingu.pdf' where
brand=$$SINGULAIR$$; -- Singulair
update drugs.brand set product_information_filename='swpskeli.pdf' where
brand=$$SKELID$$; -- Skelid
update drugs.brand set product_information_filename='nvpslsor.pdf' where
brand=$$SLOW-K$$; -- Slow
update drugs.brand set product_information_filename='nvpslkor.pdf' where
brand=$$SLOW-K$$; -- Slow-K
update drugs.brand set product_information_filename='swpsofrd.pdf' where
brand=$$SOFRADEX$$; -- Sofradex
update drugs.brand set product_information_filename='swpsofra.pdf' where
brand=$$SOFRAMYCIN$$; -- Soframycin
update drugs.brand set product_information_filename='pfpsoluv.pdf' where
brand=$$SOLU-CORTEF$$; -- Solu-Cortef
update drugs.brand set product_information_filename='pfpsolmv.pdf' where
brand=$$SOLU-MEDROL$$; -- Solu-Medrol
update drugs.brand set product_information_filename='afpsomid.pdf' where
brand=$$SOMIDEM$$; -- Somidem
update drugs.brand set product_information_filename='aspspank.pdf' where
brand=$$SPAN-K$$; -- Span-K
update drugs.brand set product_information_filename='bypspiri.pdf' where
brand=$$SPIRIVA$$; -- Spiriva
update drugs.brand set product_information_filename='bqpspryc.pdf' where
brand=$$SPRYCEL$$; -- Sprycel
update drugs.brand set product_information_filename='swpsteme.pdf' where
brand=$$STEMETIL$$; -- Stemetil
update drugs.brand set product_information_filename='swpstemz.pdf' where
brand=$$STEMZINE$$; -- Stemzine
update drugs.brand set product_information_filename='gwpstiep.pdf' where
brand=$$STIEPROX LIQUID$$; -- Stieprox
update drugs.brand set product_information_filename='mkpstocr.pdf' where
brand=$$STOCRIN$$; -- Stocrin
update drugs.brand set product_information_filename='lypstrat.pdf' where
brand=$$STRATTERA$$; -- Strattera
update drugs.brand set product_information_filename='mkpstrob.pdf' where
brand=$$STROMECTOL$$; -- Stromectol
update drugs.brand set product_information_filename='rcpsubtx.pdf' where
brand=$$SUBUTEX$$; -- Subutex
update drugs.brand set product_information_filename='afpsulpr.pdf' where
brand=$$SULPRIX$$; -- Sulprix
update drugs.brand set product_information_filename='afpsumat.pdf' where
brand=$$SUMATAB$$; -- Sumatab
update drugs.brand set product_information_filename='swpsurga.pdf' where
brand=$$SURGAM$$; -- Surgam
update drugs.brand set product_information_filename='aspsurmo.pdf' where
brand=$$SURMONTIL$$; -- Surmontil
update drugs.brand set product_information_filename='pfpsutec.pdf' where
brand=$$SUTENT$$; -- Sutent
update drugs.brand set product_information_filename='nvpsymor.pdf' where
brand=$$SYMMETREL 100$$; -- Symmetrel
update drugs.brand set product_information_filename='pfpsynan.pdf' where
brand=$$SYNAREL$$; -- Synarel
update drugs.brand set product_information_filename='nvpsytin.pdf' where
brand=$$SYNTOCINON$$; -- Syntocinon
update drugs.brand set product_information_filename='nvpmetin.pdf' where
brand=$$SYNTOMETRINE$$; -- Syntometrine
update drugs.brand set product_information_filename='afpsyque.pdf' where
brand=$$SYQUET$$; -- Syquet
update drugs.brand set product_information_filename='afptacid.pdf' where
brand=$$TACIDINE$$; -- Tacidine
update drugs.brand set product_information_filename='afptamat.pdf' where
brand=$$TAMATE$$; -- Tamate
update drugs.brand set product_information_filename='iaptambo.pdf' where
brand=$$TAMBOCOR$$; -- Tambocor
update drugs.brand set product_information_filename='roptamif.pdf' where
brand=$$TAMIFLU$$; -- Tamiflu
update drugs.brand set product_information_filename='roptarce.pdf' where
brand=$$TARCEVA$$; -- Tarceva
update drugs.brand set product_information_filename='swptargo.pdf' where
brand=$$TARGOCID$$; -- Targocid
update drugs.brand set product_information_filename='nvptasor.pdf' where
brand=$$TASIGNA$$; -- Tasigna
update drugs.brand set product_information_filename='asptazac.pdf' where
brand=$$TAZAC$$; -- Tazac
update drugs.brand set product_information_filename='pfptazev.pdf' where
brand=$$TAZOCIN EF$$; -- Tazocin
update drugs.brand set product_information_filename='asptazop.pdf' where
brand=$$TAZOPIP$$; -- Tazopip
update drugs.brand set product_information_filename='viptelzr.pdf' where
brand=$$TELZIR$$; -- Telzir
update drugs.brand set product_information_filename='afptemaz.pdf' where
brand=$$TEMAZE$$; -- Temaze
update drugs.brand set product_information_filename='mkptemod.pdf' where
brand=$$TEMODAL$$; -- Temodal
update drugs.brand set product_information_filename='apptenor.pdf' where
brand=$$TENORMIN$$; -- Tenormin
update drugs.brand set product_information_filename='afpteril.pdf' where
brand=$$TERIL$$; -- Teril
update drugs.brand set product_information_filename='asptevag.pdf' where
brand=$$TEVAGRASTIM$$; -- Tevagrastim
update drugs.brand set product_information_filename='cjpthalo.pdf' where
brand=$$THALOMID$$; -- Thalomid
update drugs.brand set product_information_filename='afpthiop.pdf' where
brand=$$THIOPRINE$$; -- Thioprine
update drugs.brand set product_information_filename='swptilad.pdf' where
brand=$$TILADE CFC-FREE$$; -- Tilade
update drugs.brand set product_information_filename='afptilod.pdf' where
brand=$$TILODENE$$; -- Tilodene
update drugs.brand set product_information_filename='gwptimen.pdf' where
brand=$$TIMENTIN$$; -- Timentin
update drugs.brand set product_information_filename='mkptimop.pdf' where
brand=$$TIMOPTOL$$; -- Timoptol
update drugs.brand set product_information_filename='mkptimxe.pdf' where
brand=$$TIMOPTOL$$; -- Timoptol-XE
update drugs.brand set product_information_filename='afptinal.pdf' where
brand=$$TINASIL$$; -- Tinasil
update drugs.brand set product_information_filename='nvptobih.pdf' where
brand=$$TOBI$$; -- TOBI
update drugs.brand set product_information_filename='mkptolvo.pdf' where
brand=$$TOLVON$$; -- Tolvon
update drugs.brand set product_information_filename='roptorad.pdf' where
brand=$$TORADOL$$; -- Toradol
update drugs.brand set product_information_filename='gwptracm.pdf' where
brand=$$TRACRIUM$$; -- Tracrium
update drugs.brand set product_information_filename='byptraje.pdf' where
brand=$$TRAJENTA$$; -- Trajenta
update drugs.brand set product_information_filename='afptrana.pdf' where
brand=$$TRANALPHA$$; -- Tranalpha
update drugs.brand set product_information_filename='swptrent.pdf' where
brand=$$TRENTAL$$; -- Trental
update drugs.brand set product_information_filename='pfptrift.pdf' where
brand=$$TRIFEME 28$$; -- Trifeme
update drugs.brand set product_information_filename='nvptrior.pdf' where
brand=$$TRILEPTAL$$; -- Trileptal
update drugs.brand set product_information_filename='pfptript.pdf' where
brand=$$TRIPHASIL 28$$; -- Triphasil
update drugs.brand set product_information_filename='swptrita.pdf' where
brand=$$TRITACE$$; -- Tritace
update drugs.brand set product_information_filename='viptrizi.pdf' where
brand=$$TRIZIVIR$$; -- Trizivir
update drugs.brand set product_information_filename='mkptruso.pdf' where
brand=$$TRUSOPT$$; -- Trusopt
update drugs.brand set product_information_filename='byptwyns.pdf' where
brand=$$TWYNSTA$$; -- Twynsta
update drugs.brand set product_information_filename='pfptygav.pdf' where
brand=$$TYGACIL$$; -- Tygacil
update drugs.brand set product_information_filename='gwptyker.pdf' where
brand=$$TYKERB$$; -- Tykerb
update drugs.brand set product_information_filename='gwptyphv.pdf' where
brand=$$TYPHERIX$$; -- Typherix
update drugs.brand set product_information_filename='afpulcyt.pdf' where
brand=$$ULCYTE$$; -- Ulcyte
update drugs.brand set product_information_filename='gwpultiv.pdf' where
brand=$$ULTIVA$$; -- Ultiva
update drugs.brand set product_information_filename='afpuremi.pdf' where
brand=$$UREMIDE$$; -- Uremide
update drugs.brand set product_information_filename='afpvaclv.pdf' where
brand=$$VACLOVIR$$; -- Vaclovir
update drugs.brand set product_information_filename='ropvalcy.pdf' where
brand=$$VALCYTE$$; -- Valcyte
update drugs.brand set product_information_filename='ropvaliu.pdf' where
brand=$$VALIUM$$; -- Valium
update drugs.brand set product_information_filename='gwpvaltr.pdf' where
brand=$$VALTREX$$; -- Valtrex
update drugs.brand set product_information_filename='nvpvalor.pdf' where
brand=$$VALVALA$$; -- Valvala
update drugs.brand set product_information_filename='mkpvaqta.pdf' where
brand=$$VAQTA PAEDIATRIC$$; -- Vaqta
update drugs.brand set product_information_filename='nvpvasor.pdf' where
brand=$$VASTIN$$; -- Vastin
update drugs.brand set product_information_filename='anpvecti.pdf' where
brand=$$VECTIBIX$$; -- Vectibix
update drugs.brand set product_information_filename='aspvenof.pdf' where
brand=$$VENOFER$$; -- Venofer
update drugs.brand set product_information_filename='bqpvepes.pdf' where
brand=$$VEPESID$$; -- Vepesid
update drugs.brand set product_information_filename='ropvesan.pdf' where
brand=$$VESANOID$$; -- Vesanoid
update drugs.brand set product_information_filename='afpvexaz.pdf' where
brand=$$VEXAZONE$$; -- Vexazone
update drugs.brand set product_information_filename='pfpvfend.pdf' where
brand=$$VFEND$$; -- Vfend
update drugs.brand set product_information_filename='pfpviagt.pdf' where
brand=$$VIAGRA$$; -- Viagra
update drugs.brand set product_information_filename='cjpvidaz.pdf' where
brand=$$VIDAZA$$; -- Vidaza
update drugs.brand set product_information_filename='bypviram.pdf' where
brand=$$VIRAMUNE$$; -- Viramune
update drugs.brand set product_information_filename='nvpvisor.pdf' where
brand=$$VISKEN 15$$; -- Visken
update drugs.brand set product_information_filename='nvpvidin.pdf' where
brand=$$VISUDYNE$$; -- Visudyne
update drugs.brand set product_information_filename='gwpvolbr.pdf' where
brand=$$VOLIBRIS$$; -- Volibris
update drugs.brand set product_information_filename='bqpvumon.pdf' where
brand=$$VUMON$$; -- Vumon
update drugs.brand set product_information_filename='mkpvytor.pdf' where
brand=$$VYTORIN$$; -- Vytorin
update drugs.brand set product_information_filename='gwpwelsu.pdf' where
brand=$$WELLVONE$$; -- Wellvone
update drugs.brand set product_information_filename='pfpxalce.pdf' where
brand=$$XALACOM$$; -- Xalacom
update drugs.brand set product_information_filename='pfpxalae.pdf' where
brand=$$XALATAN$$; -- Xalatan
update drugs.brand set product_information_filename='pfpxanat.pdf' where
brand=$$XANAX$$; -- Xanax
update drugs.brand set product_information_filename='swpxatra.pdf' where
brand=$$XATRAL$$; -- Xatral
update drugs.brand set product_information_filename='ropxelod.pdf' where
brand=$$XELODA$$; -- Xeloda
update drugs.brand set product_information_filename='ropxencp.pdf' where
brand=$$XENICAL$$; -- Xenical
update drugs.brand set product_information_filename='afpxergi.pdf' where
brand=$$XERGIC$$; -- Xergic
update drugs.brand set product_information_filename='anpxgeva.pdf' where
brand=$$XGEVA$$; -- Xgeva
update drugs.brand set product_information_filename='nvpxolin.pdf' where
brand=$$XOLAIR$$; -- Xolair
update drugs.brand set product_information_filename='appxylca.pdf' where
brand=$$XYLOCARD 500$$; -- Xylocard
update drugs.brand set product_information_filename='pfpxyntv.pdf' where
brand=$$XYNTHA$$; -- Xyntha
update drugs.brand set product_information_filename='mkpxyvio.pdf' where
brand=$$XYVION$$; -- Xyvion
update drugs.brand set product_information_filename='nvpzadop.pdf' where
brand=$$ZADITEN$$; -- Zaditen
update drugs.brand set product_information_filename='smpzanid.pdf' where
brand=$$ZANIDIP$$; -- Zanidip
update drugs.brand set product_information_filename='gwpzanta.pdf' where
brand=$$ZANTAC$$; -- Zantac
update drugs.brand set product_information_filename='pfpzaroa.pdf' where
brand=$$ZARONTIN$$; -- Zarontin
update drugs.brand set product_information_filename='pfpzavea.pdf' where
brand=$$ZAVEDOS$$; -- Zavedos
update drugs.brand set product_information_filename='afpzedac.pdf' where
brand=$$ZEDACE$$; -- Zedace
update drugs.brand set product_information_filename='gwpzefot.pdf' where
brand=$$ZEFFIX$$; -- Zeffix
update drugs.brand set product_information_filename='gwpzelta.pdf' where
brand=$$ZELITREX$$; -- Zelitrex
update drugs.brand set product_information_filename='gwpzentt.pdf' where
brand=$$ZENTEL$$; -- Zentel
update drugs.brand set product_information_filename='bqpzerit.pdf' where
brand=$$ZERIT$$; -- Zerit
update drugs.brand set product_information_filename='appzestr.pdf' where
brand=$$ZESTRIL$$; -- Zestril
update drugs.brand set product_information_filename='vipziage.pdf' where
brand=$$ZIAGEN$$; -- Ziagen
update drugs.brand set product_information_filename='afpzimst.pdf' where
brand=$$ZIMSTAT$$; -- Zimstat
update drugs.brand set product_information_filename='gwpzinta.pdf' where
brand=$$ZINNAT$$; -- Zinnat
update drugs.brand set product_information_filename='afpzirco.pdf' where
brand=$$ZIRCOL$$; -- Zircol
update drugs.brand set product_information_filename='pfpzitra.pdf' where
brand=$$ZITROCIN$$; -- Zitrocin
update drugs.brand set product_information_filename='mkpzocor.pdf' where
brand=$$ZOCOR$$; -- Zocor
update drugs.brand set product_information_filename='gwpzofra.pdf' where
brand=$$ZOFRAN$$; -- Zofran
update drugs.brand set product_information_filename='pfpzolot.pdf' where
brand=$$ZOLOFT$$; -- Zoloft
update drugs.brand set product_information_filename='fppzomai.pdf' where
brand=$$ZOMACTON$$; -- Zomacton
update drugs.brand set product_information_filename='nvpzomin.pdf' where
brand=$$ZOMETA$$; -- Zometa
update drugs.brand set product_information_filename='appzomig.pdf' where
brand=$$ZOMIG$$; -- Zomig
update drugs.brand set product_information_filename='afpzopra.pdf' where
brand=$$ZOPRAL$$; -- Zopral
update drugs.brand set product_information_filename='pfpzotft.pdf' where
brand=$$ZOTON FASTABS$$; -- Zoton
update drugs.brand set product_information_filename='smpzumen.pdf' where
brand=$$ZUMENON$$; -- Zumenon
update drugs.brand set product_information_filename='gwpzyban.pdf' where
brand=$$ZYBAN$$; -- Zyban
update drugs.brand set product_information_filename='afpzypio.pdf' where
brand=$$ZYPINE$$; -- Zypine;
update drugs.brand set product_information_filename='lypzyprx.pdf' where
brand=$$ZYPREXA$$; -- Zyprexa;
update drugs.brand set product_information_filename='pcpzyrtc.pdf' where
brand=$$ZYRTEC$$; -- Zyrtec
update drugs.brand set product_information_filename='pfpzyvoa.pdf' where
brand=$$ZYVOX$$; -- Zyvox


truncate db.lu_version;
insert into db.lu_version (lu_major,lu_minor) values (0, 180);

