drop view drugs.vwdrugs;
drop view clin_prescribing.vwprescribeditems;

update drugs.product set pack_size=NULL where not original_pbs_name is null; -- NULL for all PBS drugs as this info comes only from drugs.pbs.quantity now
alter table drugs.product add column units_per_pack integer default 1;
delete from drugs.product where pk='27604589-9c77-442c-ad6d-148ebccd962c'; -- extra Yazmin that shouldn't be there.

-- setting units_per_pack for non-PBS drugs
-- RICHARD: are these right and are there any more??
update drugs.product set pack_size=4, units_per_pack=28 where pk='71e0c731-dd8e-4080-95df-c1e74c72d19a'; -- Diane and friends
update drugs.product set pack_size=4, units_per_pack=28 where pk='628b0f30-7a8a-45ad-abdb-d405c8f4bce9'; -- Yazmin

-- finally kill off the concept of "day" as a unit
update drugs.product set amount=null,amount_unit=null where amount_unit=6;

-- settings units_per_pack for PBS drugs: autogenerated using Ian's black magic.
 update drugs.product set units_per_pack=30 where pk = 'd9781150-b514-4ce5-bffa-d7021671d3a2';
 update drugs.product set units_per_pack=30 where pk = '5f680ffb-bc52-4084-9b8f-282575be5f49';
 update drugs.product set units_per_pack=30 where pk = '539f73f4-b97b-492e-8e9f-d920703961f5';
 update drugs.product set units_per_pack=60 where pk = '3d1c7d29-cfa4-48ef-8322-6f53aedc7e14';
 update drugs.product set units_per_pack=30 where pk = '751795fc-1916-45ed-accc-7db8a848a181';
 update drugs.product set units_per_pack=30 where pk = '8bb2ef59-d571-4d21-a0b4-ddc88eddea49';
 update drugs.product set units_per_pack=30 where pk = '2c1319cc-ad3a-4e2f-a54e-600d2d297195';
 update drugs.product set units_per_pack=30 where pk = '9eb61de8-3c89-472e-9c13-ee926d536fc3';
 update drugs.product set units_per_pack=30 where pk = 'e347d641-2930-4856-8a75-f4e5dfc23c4a';
 update drugs.product set units_per_pack=30 where pk = '188b2521-bca1-4410-8101-0b6186028eed';
 update drugs.product set units_per_pack=30 where pk = '5017c797-dd93-4323-89ac-b3633a109b16';
 update drugs.product set units_per_pack=30 where pk = '9b08cc95-ad06-4abe-b3ce-068f5f26e386';
 update drugs.product set units_per_pack=36 where pk = '4b3045ad-9420-429f-93cb-b3c6e5cefd47';
 update drugs.product set units_per_pack=60 where pk = '7fb9464a-c798-4445-aecc-1dd6cf05c501';
 update drugs.product set units_per_pack=30 where pk = 'cdd213a7-fe51-4191-a959-a1c6813dcd18';
 update drugs.product set units_per_pack=30 where pk = '00fc7498-36f0-4c72-b347-cdf47ef1685d';
 update drugs.product set units_per_pack=30 where pk = '42998cb5-3224-4d24-ab80-e5e755879968';
 update drugs.product set units_per_pack=30 where pk = '19e2b19e-ee31-4c58-adb9-4fbf38c8468c';
 update drugs.product set units_per_pack=30 where pk = 'f0474a7a-3c61-4670-9f71-a790633e3d55';
 update drugs.product set units_per_pack=30 where pk = '111d7f9b-18d8-439e-bd0d-909f5d6c1412';
 update drugs.product set units_per_pack=30 where pk = '88bee9bd-f25d-4a3a-9b9e-ad8a2c908dba';
 update drugs.product set units_per_pack=200 where pk = '8dbd70a6-1f66-48cb-b7a4-d4889e482df6';
 update drugs.product set units_per_pack=75 where pk = '77158b79-cc1c-45ba-9131-0e9745e92743';
 update drugs.product set units_per_pack=25 where pk = '19509460-c962-4ea2-8c70-095dc7de54a5';
 update drugs.product set units_per_pack=10 where pk = '6a2238ac-a3f2-4786-95fa-f5d94545ce2f';
 update drugs.product set units_per_pack=12 where pk = 'c2a74c99-1d30-4680-805f-131db6dade9e';
 update drugs.product set units_per_pack=30 where pk = '8eda259f-41a6-4312-8051-f52193993c61';
 update drugs.product set units_per_pack=30 where pk = 'aca61760-e5dd-41d6-8b28-b78ff30a00a1';
 update drugs.product set units_per_pack=50 where pk = '57814b6c-a697-492d-b505-5d91a7611377';
 update drugs.product set units_per_pack=120 where pk = 'c3c5d7e5-f92d-41d3-a315-f79b23cddb7c';
 update drugs.product set units_per_pack=100 where pk = 'c80a7f2a-3866-47cb-bd6c-27a73ddca890';
 update drugs.product set units_per_pack=50 where pk = '6904dec1-3255-4bb5-92ee-abae805b51b0';
 update drugs.product set units_per_pack=50 where pk = 'adb27acd-3987-4bfe-903e-c9bbb43af486';
 update drugs.product set units_per_pack=25 where pk = '0d7862ba-d0e9-409b-a71f-a28a3503cc38';
 update drugs.product set units_per_pack=100 where pk = 'c870effc-6513-4f22-9244-3b1dfa53d81c';
 update drugs.product set units_per_pack=50 where pk = '3a0e5de7-8a63-4d34-a5b1-ac0d2cc8c3c9';
 update drugs.product set units_per_pack=50 where pk = '0e4e31dd-abac-412f-abc8-338b5d00f2fa';
 update drugs.product set units_per_pack=50 where pk = 'feffc77f-359c-417d-a5e2-62603ea5154f';
 update drugs.product set units_per_pack=50 where pk = '57a68f20-277a-40cd-8c93-7636f1ec87e7';
 update drugs.product set units_per_pack=50 where pk = 'cfac4586-30cb-4631-a694-e87b2897dd0a';
 update drugs.product set units_per_pack=100 where pk = 'd697e1a2-1d02-414f-8669-f8edc8c6df80';
 update drugs.product set units_per_pack=100 where pk = 'b212e1f6-684d-4f53-9e8e-fd2279598694';
 update drugs.product set units_per_pack=100 where pk = '4da993d4-562a-48d6-8ebc-19f0c9df7dc9';
 update drugs.product set units_per_pack=50 where pk = '4c34cf89-2d34-48eb-9af3-74eaabc3a21d';
 update drugs.product set units_per_pack=51 where pk = '941c0f64-ff93-4dd7-b188-9a8f84fc974d';
 update drugs.product set units_per_pack=50 where pk = '17ec6cc3-e6ad-446b-93e7-a4310f50759a';
 update drugs.product set units_per_pack=50 where pk = '6dfdf016-cd80-4680-abbd-708e24f2ef40';
 update drugs.product set units_per_pack=50 where pk = '226174cc-923b-449a-89c2-ba71e44b0b4f';
 update drugs.product set units_per_pack=50 where pk = '0aca3892-c56b-4e4a-b3a2-a453b49552c7';
 update drugs.product set units_per_pack=50 where pk = 'c21c86d7-d1ba-4dfd-af89-5bfb176576ee';
 update drugs.product set units_per_pack=50 where pk = 'c5fd4948-564f-4479-b50c-b0598ca21c00';
 update drugs.product set units_per_pack=50 where pk = '19d7cf6e-c338-4a83-9c2e-ad48f4a87c6b';
 update drugs.product set units_per_pack=50 where pk = '1b50858f-77e8-45e8-971c-74a0826021bf';
 update drugs.product set units_per_pack=100 where pk = '3b8ff298-735c-4b99-9a4a-140a5b0c7a65';
 update drugs.product set units_per_pack=50 where pk = 'ebaa5c89-6057-456b-8738-b20d17bd38c4';
 update drugs.product set units_per_pack=50 where pk = '2be96cd4-62fb-42e8-9813-0a8c48aef700';
 update drugs.product set units_per_pack=50 where pk = '098ea66e-319a-46d7-914b-0f6369ff4fab';
 update drugs.product set units_per_pack=50 where pk = '86ec88d0-406b-41a1-b7c2-f35db619b1fd';
 update drugs.product set units_per_pack=100 where pk = '1a964083-7602-4746-b402-713052ec0cdc';
 update drugs.product set units_per_pack=50 where pk = '8f7d38ac-c4da-416f-b9f0-efcc3df18233';
 update drugs.product set units_per_pack=50 where pk = '960271e9-19e7-4586-b428-c84cbd6d9e86';
 update drugs.product set units_per_pack=12 where pk = 'd4f431ca-b090-405a-80ab-d561966a08ca';
 update drugs.product set units_per_pack=12 where pk = 'ffd5b9cf-6ac6-4d78-bce6-9c9be290f083';
 update drugs.product set units_per_pack=12 where pk = 'af1e42f1-5645-4d3a-80af-10c0b650d534';
 update drugs.product set units_per_pack=100 where pk = 'd2bea379-6fb3-40e0-9cea-ef9529f351a5';
 update drugs.product set units_per_pack=3 where pk = '710dc06b-6db7-4f68-b24d-7cf52f2a8197';
 update drugs.product set units_per_pack=5 where pk = '969819c8-da9a-410c-8862-a8dc35bb9411';
 update drugs.product set units_per_pack=5 where pk = '2a362908-5164-4ad2-bf65-fe86cfdcbe22';
 update drugs.product set units_per_pack=5 where pk = 'ad7a95b6-2044-426f-87c5-efbd56531936';
 update drugs.product set units_per_pack=30 where pk = '7663b156-ce2c-4046-8a8c-23b840da6582';
 update drugs.product set units_per_pack=5 where pk = 'db72f87b-e7f2-4263-8e39-3aa4fa61f919';
 update drugs.product set units_per_pack=30 where pk = '41afe0da-6899-4758-b669-6b2157178977';
 update drugs.product set units_per_pack=28 where pk = 'c6fd5b83-fa51-4996-b96e-74edd65d0cfe';
 update drugs.product set units_per_pack=28 where pk = '0f1720fd-231b-4833-a004-4a633d2fe5ed';
 update drugs.product set units_per_pack=28 where pk = '54857133-3a78-4b2b-986a-b99a75ba1673';
 update drugs.product set units_per_pack=7 where pk = '023e8f72-2e5c-4cdc-9012-219fd0371ee1';
 update drugs.product set units_per_pack=7 where pk = 'f048fce9-7908-41d4-b0b9-6b7f1f6220d6';
 update drugs.product set units_per_pack=7 where pk = '5ac3bc9d-1195-4f19-bfbd-3a0324e04cad';
 update drugs.product set units_per_pack=10 where pk = '5cfe923e-5723-4aa7-b10f-bb65862a66d8';
 update drugs.product set units_per_pack=28 where pk = '24425ab2-2782-42c4-beea-ce053ac88eb6';
 update drugs.product set units_per_pack=28 where pk = 'b983d85f-42b0-4f36-aae5-c8c0a4665e84';
 update drugs.product set units_per_pack=28 where pk = '750d9273-3835-46c6-bdb5-5f8a6cbb5752';
 update drugs.product set units_per_pack=28 where pk = '4f1a1184-0df9-4d0a-92a2-bbc1cb5ef570';
 update drugs.product set units_per_pack=15 where pk = '7a4fc560-c97e-4393-b0a8-970e949b9afc';
 update drugs.product set units_per_pack=2 where pk = '7a75b1f8-42bb-48c5-867c-95b8cb191950';
 update drugs.product set units_per_pack=30 where pk = 'ec4c465b-674c-40ec-8972-240bfca26731';
 update drugs.product set units_per_pack=24 where pk = '794dac5b-5f9a-47f1-9d7b-405b143b6b53';
 update drugs.product set units_per_pack=10 where pk = '8900353b-e1f0-4a98-8698-6e99fe79c1aa';
 update drugs.product set units_per_pack=5 where pk = '36edb11d-e3b9-48d3-9425-942d7e69c968';
 update drugs.product set units_per_pack=30 where pk = 'f36499f0-0a9c-41c0-ad65-beabf0d517d8';
 update drugs.product set units_per_pack=30 where pk = '612ee2a7-2d41-4ff5-bdb9-6f12ec7139f7';
 update drugs.product set units_per_pack=28 where pk = '61c5e4cf-603f-4cda-9e65-09386b70aa2e';
 update drugs.product set units_per_pack=12 where pk = '5aaf62f3-4bc6-4c75-9622-3de05a433334';
 update drugs.product set units_per_pack=12 where pk = '42c47733-a7b5-45b3-a46a-f5a9e34460c8';
 update drugs.product set units_per_pack=30 where pk = '613cf26c-9e49-49b5-bc76-6500dbc9142f';
 update drugs.product set units_per_pack=4 where pk = '8a290594-eddd-47fa-b8c3-2448c50520d2';
 update drugs.product set units_per_pack=100 where pk = '9d25a02a-3398-4a9d-9be9-21bb6f9a7057';
 update drugs.product set units_per_pack=12 where pk = 'c65e8c1e-9dd4-4c73-ac24-6fea851ececc';
 update drugs.product set units_per_pack=100 where pk = 'b54267d8-2fe9-4d84-b488-bceba001193d';
 update drugs.product set units_per_pack=30 where pk = 'c97dd36f-0881-4738-9a14-60c1b4b94c62';
 update drugs.product set units_per_pack=10 where pk = 'b678db6f-6c46-40b2-962c-f73f5b3336b2';
 update drugs.product set units_per_pack=10 where pk = '69dcf7e9-acf6-4186-8136-36a7ffe02761';
 update drugs.product set units_per_pack=12 where pk = '66dabcad-bb10-4c2a-831d-094ab8ffd7c2';
 update drugs.product set units_per_pack=30 where pk = 'f760eef3-a6b3-4a4b-ad1a-9e89e0328495';
 update drugs.product set units_per_pack=30 where pk = '2172cfb2-e423-492b-baf0-e83470012c8a';
 update drugs.product set units_per_pack=30 where pk = '6d02c05c-4078-4828-a286-3e88e9e2b26b';
 update drugs.product set units_per_pack=24 where pk = '6c6231aa-8d7f-42a2-bd75-c1dbeff4241b';
 update drugs.product set units_per_pack=28 where pk = 'af132ec0-fa28-44da-aab5-dc5dd532eaae';
 update drugs.product set units_per_pack=8 where pk = '5a0646dd-0604-41f8-be49-738b64f0a8eb';
 update drugs.product set units_per_pack=8 where pk = 'de9c06af-17a5-4ca0-a476-f5d546eced6d';
 update drugs.product set units_per_pack=8 where pk = '8a3b46b5-0d60-4cc6-8c27-1293fc913d15';
 update drugs.product set units_per_pack=8 where pk = '8ad6e58b-0c19-4ba0-8210-6ffc7620b2ad';
 update drugs.product set units_per_pack=8 where pk = 'fda4e340-5ff3-4e3e-8793-9774b44dc49e';
 update drugs.product set units_per_pack=10 where pk = '84c89cdf-280f-46e3-9d6c-25bc9361a514';
 update drugs.product set units_per_pack=15 where pk = 'e0a27a72-15fa-48fc-84b8-60ca980393d3';
 update drugs.product set units_per_pack=8 where pk = '23f765eb-a9dc-4f99-bd61-f0183a12f6c4';
 update drugs.product set units_per_pack=4 where pk = 'b4c6dcd4-55d2-4207-a3cc-725e001b6cdf';
 update drugs.product set units_per_pack=4 where pk = '2166823c-b485-414e-989e-3ac499415d1d';
 update drugs.product set units_per_pack=8 where pk = '3259d70a-f756-4cb0-9f64-2ae5ba507fe3';
 update drugs.product set units_per_pack=28 where pk = '80b60345-3af3-420e-bf03-93e86903e6d1';
 update drugs.product set units_per_pack=8 where pk = '35750296-8d2f-4b78-bafd-35868cfc73f2';
 update drugs.product set units_per_pack=8 where pk = '0cb8df04-ba5d-4480-9c12-7720a578af95';
 update drugs.product set units_per_pack=4 where pk = 'fba00821-f956-410a-8907-1bbb00d2a35a';
 update drugs.product set units_per_pack=4 where pk = '22b75ceb-58c1-4b8e-a102-ecc39817bedf';
 update drugs.product set units_per_pack=10 where pk = '397ac5a9-55c5-473e-a233-21c523c8c6cf';
 update drugs.product set units_per_pack=10 where pk = '4c36d06b-1209-4696-b206-a8f22b25ebf7';
 update drugs.product set units_per_pack=3 where pk = 'afdea006-d2bc-4615-a89a-fe44e9bed6ce';
 update drugs.product set units_per_pack=7 where pk = '49d6f778-cf2a-4618-9781-a3d6f05e7d31';
 update drugs.product set units_per_pack=7 where pk = '27a33c67-1006-41ae-b95c-72752fefea70';
 update drugs.product set units_per_pack=7 where pk = 'ca98e73d-33f9-447e-b9c6-f86190c198d3';
 update drugs.product set units_per_pack=7 where pk = '097e8458-d9e8-4dd5-b07c-1a8116d6971c';
 update drugs.product set units_per_pack=7 where pk = '9a220b75-0c2f-4dac-8fc7-4ce73ebf2408';
 update drugs.product set units_per_pack=7 where pk = '276e6b96-5afa-456a-b844-582995bbdc40';
 update drugs.product set units_per_pack=10 where pk = '8cabe374-f1f6-48bb-b77c-4a05abed65d2';
 update drugs.product set units_per_pack=5 where pk = 'f165c377-0b31-494d-a4f6-a2adad28fa7f';
 update drugs.product set units_per_pack=30 where pk = '2aa39877-bc9e-40e0-8816-c7ce240e9e78';
 update drugs.product set units_per_pack=30 where pk = 'cbfeb91c-044a-4299-bec8-f6edf35e26e4';
 update drugs.product set units_per_pack=8 where pk = '8d028695-2e3e-4592-ad46-87458f6c87ee';
 update drugs.product set units_per_pack=8 where pk = '1423fde1-8340-4978-9cf4-71373a4638d8';
 update drugs.product set units_per_pack=5 where pk = '49a26c63-5964-4e14-af1a-8fb575bbabb2';
 update drugs.product set units_per_pack=60 where pk = '6267a78d-cdb1-4572-87c2-ae5a7ff850f7';
 update drugs.product set units_per_pack=30 where pk = '9803b3e5-5bdf-435c-930c-a43971799fc9';
 update drugs.product set units_per_pack=30 where pk = 'c8f4e582-edc9-4712-9d83-363cff34cc26';
 update drugs.product set units_per_pack=4 where pk = '4553a1b9-779b-460c-9dc4-daab74446ba5';
 update drugs.product set units_per_pack=2 where pk = 'af4f5e06-8d40-4284-b9b1-ddddd8e5b546';
 update drugs.product set units_per_pack=60 where pk = '2edb1d84-ff8a-464a-bd61-c1c616a4f305';
 update drugs.product set units_per_pack=60 where pk = 'a41b5c98-a35a-4942-9f7b-8a16e0f6d18e';
 update drugs.product set units_per_pack=2 where pk = '6bcd2e94-e93c-45ad-b136-022b55334f3a';
 update drugs.product set units_per_pack=6 where pk = 'a912a432-8c8b-4239-b677-82aed153a21e';
 update drugs.product set units_per_pack=10 where pk = '25283c1e-1fb9-4aeb-b4df-891191d277e9';
 update drugs.product set units_per_pack=10 where pk = '9b2eecf1-0ff3-463c-8a54-2855dd8bc012';
 update drugs.product set units_per_pack=5 where pk = 'a694e812-4483-43ec-b1da-703f8996d0bc';
 update drugs.product set units_per_pack=30 where pk = '27e6bf50-af4a-490e-84d0-78a690d79b73';
 update drugs.product set units_per_pack=10 where pk = '201e1f19-4086-461c-896c-aa8116b4faed';
 update drugs.product set units_per_pack=10 where pk = '6c1db7a0-8d52-4f0b-b924-94f9be093e4d';
 update drugs.product set units_per_pack=3 where pk = '7e04346e-a1c9-4d33-b0de-88f534839baf';
 update drugs.product set units_per_pack=3 where pk = '459fa375-0c7d-43e4-8a4f-3edbc14b6073';
 update drugs.product set units_per_pack=3 where pk = 'daa8ff58-13a9-49cd-b34b-08d866f74960';
 update drugs.product set units_per_pack=3 where pk = 'c433a20d-732f-4d3b-abc8-00fc68721215';
 update drugs.product set units_per_pack=3 where pk = '14625d77-c854-4e47-b8a0-70695311206b';
 update drugs.product set units_per_pack=30 where pk = '0415d13c-7e80-4447-aa42-ece56637a89e';
 update drugs.product set units_per_pack=30 where pk = 'e9827432-4810-413d-b14f-d89daa880679';
 update drugs.product set units_per_pack=30 where pk = '18dfb532-0c6e-4ec3-bc47-2bc853f23edc';
 update drugs.product set units_per_pack=30 where pk = '0e018afb-f1b9-4510-9ff9-a2b4bc0f8369';
 update drugs.product set units_per_pack=30 where pk = '6dcaa13b-50c1-4fe9-89e7-582522fa0515';
 update drugs.product set units_per_pack=30 where pk = '23e60665-a993-48b4-8d84-a0c49c82536f';
 update drugs.product set units_per_pack=3 where pk = '75ce2b9d-a56a-4ac6-8bcb-111214699688';
 update drugs.product set units_per_pack=5 where pk = '79fe308b-bc35-4227-a7d6-bd92bdc5741f';
 update drugs.product set units_per_pack=5 where pk = '99bae59b-6c9e-4e4a-8a1c-6b3feeeacc8c';
 update drugs.product set units_per_pack=30 where pk = '942edfa3-ed1d-4526-9bb2-ec3aeb9621ba';
 update drugs.product set units_per_pack=5 where pk = '26372e83-6336-4208-ae7f-60a1be9f3f49';
 update drugs.product set units_per_pack=3 where pk = '19b762c2-4dd0-44b9-bbeb-3dc48dd52e52';
 update drugs.product set units_per_pack=7 where pk = '3cb44169-5357-42cc-91ad-c31bd915a766';
 update drugs.product set units_per_pack=4 where pk = 'e9c51994-a2a0-4331-96e1-91da48bb9727';
 update drugs.product set units_per_pack=2 where pk = 'b3617db7-c670-4d9d-9139-9bdf9e79e5ef';
 update drugs.product set units_per_pack=5 where pk = 'dba58a2f-99e9-42b4-afaa-5890237c7209';
 update drugs.product set units_per_pack=2 where pk = '047c551e-9fb2-49ea-b3a7-57d25e2c187e';
 update drugs.product set units_per_pack=30 where pk = '4473b569-1003-405a-9c41-ca0e78176a10';
 update drugs.product set units_per_pack=30 where pk = 'e495c336-dd7c-4219-bf63-39ce2d62857b';
 update drugs.product set units_per_pack=5 where pk = '4c6f2d0a-9600-41e2-9d46-f1482b12875b';
 update drugs.product set units_per_pack=4 where pk = 'a2a36bfa-e041-402d-bf71-732463feb63a';
 update drugs.product set units_per_pack=4 where pk = 'ed23fb8e-551a-4e23-9a6f-c6873b9ff13a';
 update drugs.product set units_per_pack=6 where pk = '8bce29e1-20df-47c0-a1b6-9872181546a3';
 update drugs.product set units_per_pack=6 where pk = '123cdfcf-73cb-4322-af0f-d041440cac9d';
 update drugs.product set units_per_pack=60 where pk = '8a993296-9315-4adc-863c-f9411685ffa1';
 update drugs.product set units_per_pack=8 where pk = '34048145-04a9-49de-ba7c-77afe36f42ef';
 update drugs.product set units_per_pack=8 where pk = 'be6989e8-011d-4474-abb9-b58029f3f6c3';
 update drugs.product set units_per_pack=8 where pk = '969c4dcb-a8d8-4b0a-85aa-792285316af7';
 update drugs.product set units_per_pack=12 where pk = 'acd50ed6-1f26-472b-b368-c801bc996491';
 update drugs.product set units_per_pack=8 where pk = 'e49a62ea-1b66-413a-a9aa-563392f1f07f';
 update drugs.product set units_per_pack=5 where pk = '8cbed4e5-fdcc-408a-ad4f-045135211ef5';
 update drugs.product set units_per_pack=5 where pk = 'f0ea5e70-44d1-4816-88e3-ec658c5a25f1';
 update drugs.product set units_per_pack=5 where pk = '0ce068d8-12ec-482b-b4d1-0c56c0d1536f';
 update drugs.product set units_per_pack=30 where pk = '97cf6a11-523e-44c1-9e77-ba3f42bb7709';
 update drugs.product set units_per_pack=30 where pk = '3ad95821-d98d-4165-bf53-04ca20ecf40b';
 update drugs.product set units_per_pack=2 where pk = 'e161637d-06fa-44ee-87f0-5cda3bf6b264';
 update drugs.product set units_per_pack=5 where pk = '8c8ea8e7-6517-4864-bd75-06a1fdd5f01c';
 update drugs.product set units_per_pack=5 where pk = 'f97479de-d866-49d8-9d1c-d6b00feb7dd6';
 update drugs.product set units_per_pack=3 where pk = 'f0b9f328-11f2-4b91-ba4f-c7ee59b2bbb2';
 update drugs.product set units_per_pack=30 where pk = '26999a66-a639-41ec-9878-3c2a6be66238';
 update drugs.product set units_per_pack=30 where pk = '2ae2b3c5-a283-4e71-bd46-3b49d71ad329';
 update drugs.product set units_per_pack=10 where pk = '96b68a75-9773-45e5-b719-da066e77360b';
 update drugs.product set units_per_pack=5 where pk = '2c531b82-5ecb-4e75-8f38-b2a302af8154';
 update drugs.product set units_per_pack=30 where pk = 'c1736f87-3aca-4e3f-8653-84896ee91b50';
 update drugs.product set units_per_pack=30 where pk = 'b01458a7-0199-45cc-9852-b5f287fd9a18';
 update drugs.product set units_per_pack=5 where pk = 'f890d0f4-543a-4c56-bd8a-0920bc3d3e7b';
 update drugs.product set units_per_pack=30 where pk = 'e0117dc0-aabb-4882-9bdc-a91f9ff8abea';
 update drugs.product set units_per_pack=30 where pk = 'bad05c2d-e82a-43c0-a5b7-e431ea4f64b8';
 update drugs.product set units_per_pack=30 where pk = '7af0ec5b-2e13-41f0-bad4-cdb514c1baf6';
 update drugs.product set units_per_pack=10 where pk = 'ac182fbc-5286-4478-8bcc-543ee2853699';
 update drugs.product set units_per_pack=30 where pk = '89cd50d6-6351-4094-aac6-87ae2a8c5b63';
 update drugs.product set units_per_pack=50 where pk = '928bd166-0cea-4503-8fdc-83dd9f76ab9c';
 update drugs.product set units_per_pack=30 where pk = '89b71544-a5f5-4bc8-bac3-9e3256951fc2';
 update drugs.product set units_per_pack=30 where pk = '1a178afa-a2eb-41ce-b1a4-5525bab144d9';
 update drugs.product set units_per_pack=30 where pk = '446e9bcd-2a6d-467c-b281-5f6180c6ec6d';
 update drugs.product set units_per_pack=8 where pk = 'ba69b789-8e1d-40f6-ae29-089aac2edc01';
 update drugs.product set units_per_pack=30 where pk = '7b481f6d-ac8f-4195-b047-e08913e450e6';
 update drugs.product set units_per_pack=10 where pk = '971eaa5e-a42e-4f60-8453-c57d319585db';
 update drugs.product set units_per_pack=36 where pk = '1e57a94a-b72a-419b-be14-261b9078630c';
 update drugs.product set units_per_pack=20 where pk = '2fcc8003-e6fa-43aa-b5bd-dfa4921ce3f3';
 update drugs.product set units_per_pack=28 where pk = '23b21183-4042-4ae2-a00a-51eddf3e2880';
 update drugs.product set units_per_pack=18 where pk = 'd313d43f-a8bd-4ebf-af14-79cc2b5db32d';
 update drugs.product set units_per_pack=6 where pk = '7371dd96-3842-4d5c-9a47-d6db90894fef';
 update drugs.product set units_per_pack=60 where pk = '1c34ecba-9c49-40a4-b0a3-b188aaf3795e';
 update drugs.product set units_per_pack=60 where pk = '69b1708c-6cf7-4054-b065-1eb79560a835';
 update drugs.product set units_per_pack=36 where pk = 'a18c997e-a22c-44f0-8111-7af15eda136f';
 update drugs.product set units_per_pack=14 where pk = '2375c31a-b2bd-45ad-a149-c2cc7d99ebe4';
 update drugs.product set units_per_pack=14 where pk = 'a703e378-50c4-4062-9d21-c5f1c6abba85';
 update drugs.product set units_per_pack=36 where pk = 'e4632668-e6c8-457b-bba0-98c38245d319';
 update drugs.product set units_per_pack=60 where pk = '0877ac8e-5575-450d-b7d0-f5ffec826d2e';
 update drugs.product set units_per_pack=60 where pk = 'a5ec2957-5eb5-4167-8987-c47de464a837';
 update drugs.product set units_per_pack=2 where pk = 'f962a5ab-469c-4134-81e1-f7067e9260ee';
 update drugs.product set units_per_pack=30 where pk = '7a6b362f-1754-48da-95bf-04b907cea25f';
 update drugs.product set units_per_pack=10 where pk = '7b5af2b5-bc38-4ac4-b7cb-4fce7cc99827';
 update drugs.product set units_per_pack=10 where pk = '1d1de054-d9e0-4433-bdc2-9fb939720748';
 update drugs.product set units_per_pack=10 where pk = 'ad1a33ad-a828-4a7c-8b11-015332d8a3b1';

-- and now fix the functions and view.


drop function drugs.format_packsize(double precision, integer, integer);
drop function drugs.display_strength(text, double precision, integer);

CREATE OR REPLACE FUNCTION drugs.format_amount(double precision, integer, integer)
 RETURNS text AS
$BODY$
declare
 r text;
 i text;
begin
 r := '';
 -- now add amount and amount_unit
 if not $1 is null then
   select into i abbrev_text from common.lu_units where pk = $2;
   r := $1 || i;
 end if;
 if $3 <> 1 then
   i := $3::text;
   if r <> '' then
     r:= r || ' x ' || i;
   else
     r := '(pack of ' || i || ')';
   end if;
 end if;
 RETURN r;
END;
$BODY$
 LANGUAGE 'plpgsql' VOLATILE
 COST 100; 

comment on function drugs.format_amount(double precision, integer, integer) is 'formats the amount and units per pack appropriately for display
Parameters are in order:
- the value for product.amount
- the value for product.amount_unit
- the value for product.units_per_pack

Note: previously this function called format_packsize, but now product.pack_size not involved in this function,
putting in this value is the responsibility the client';


create or replace view drugs.vwdrugs as  
SELECT (brand.pk || COALESCE(vwpbs.pbscode, 
''::character varying)::text) || COALESCE(vwpbs.restriction_code, ''::character varying)::text AS pk_view, 
brand.fk_product, brand.fk_company, brand.brand, brand.pk AS fk_brand, brand.price, brand.from_pbs,
product.atccode, product.generic, product.salt, product.fk_form, product.strength, 
drugs.format_strength(product.strength) AS display_strength, drugs.format_amount(product.amount, 
product.amount_unit, product.units_per_pack) AS display_packsize, 
product.units_per_pack, product.salt_strength, product.free_comment, 
product.fk_schedule, product.updated_at, product.pack_size, 
product.amount, product.amount_unit, schedules.schedule, form.form, 
brand.product_information_filename, brand.product_information_filename_user, 
coalesce(vwpbs.quantity,product.pack_size) as quantity, 
vwpbs.max_rpt, vwpbs.pbscode, vwpbs.chapter, atc.atcname, company.company, vwpbs.restrictionflag, 
vwpbs.pbs_type, vwpbs.restriction, vwpbs.restriction_type, vwpbs.restriction_code, vwpbs.streamlined,
atc1.atccode As Class_code, atc1.atcname As Class_name
   FROM drugs.brand brand
   JOIN drugs.product ON brand.fk_product = product.pk
   JOIN drugs.form ON product.fk_form = form.pk
   JOIN drugs.atc ON product.atccode::text = atc.atccode
   LEFT JOIN drugs.company ON company.code::text = brand.fk_company::text
   LEFT JOIN drugs.vwpbs ON product.pk = vwpbs.fk_product
   LEFT JOIN drugs.schedules ON schedules.pk = product.fk_schedule
   Left JOIN drugs.atc atc1 On "substring"(product.atccode:: text, 1, 4) = atc1.atccode;

CREATE OR REPLACE VIEW clin_prescribing.vwprescribeditems AS
SELECT prescribed.pk AS pk_view, medications.pk AS fk_medication, medications.start_date, 
medications.last_date, medications.active, 
medications.deleted AS medication_deleted, medications.fk_generic_product, 
consult.pk AS fk_consult, consult.consult_date AS date_script_written, 
consult.fk_patient, product.generic, brand.brand, product.strength, 
brand.product_information_filename, form.form, brand.pk AS fk_brand, 
prescribed.pk AS fk_prescribed, prescribed.repeats, prescribed.date_on_script, 
prescribed.quantity, prescribed_for.prescribed_for, 
prescribed.deleted AS prescribed_deleted, prescribed.authority_reason, 
prescribed.print_reason, instructions.instruction, 
vwstaff.wholename AS staff_prescribed_wholename, vwstaff.title AS staff_prescribed_title, 
vwstaff.provider_number,
product.atccode, product.salt, product.fk_form, product.fk_schedule, product.salt_strength,
prescribed.fk_instruction,
prescribed.fk_prescribed_for, prescribed.pbscode, prescribed.fk_lu_pbs_script_type, 
prescribed.restriction_code, 
prescribed.fk_code, lu_pbs_script_type.type AS pbs_script_type, restriction.streamlined, 
restriction.restriction, 
restriction.restriction_type, schedules.schedule,
drugs.format_strength(product.strength) AS display_strength, 
drugs.format_amount(product.amount, product.amount_unit, 
product.units_per_pack) AS display_packsize, product.units_per_pack
  FROM clin_consult.consult
  JOIN admin.vwstaff ON consult.fk_staff = vwstaff.fk_staff
  JOIN clin_prescribing.prescribed ON consult.pk = prescribed.fk_consult
  JOIN clin_prescribing.medications medications ON prescribed.fk_medication = medications.pk
  JOIN clin_prescribing.prescribed_for ON prescribed.fk_prescribed_for = prescribed_for.pk
  JOIN clin_prescribing.instructions ON prescribed.fk_instruction = instructions.pk
  JOIN clin_prescribing.lu_pbs_script_type ON prescribed.fk_lu_pbs_script_type = lu_pbs_script_type.pk
  LEFT JOIN drugs.restriction ON prescribed.pbscode = restriction.pbscode::text AND prescribed.restriction_code = restriction.code::text
  LEFT JOIN drugs.brand ON prescribed.fk_brand = brand.pk
  JOIN drugs.product ON medications.fk_generic_product = product.pk
  LEFT JOIN drugs.schedules ON product.fk_schedule = schedules.pk
  JOIN drugs.form ON product.fk_form = form.pk; 

truncate db.lu_version;
insert into db.lu_version(lu_major, lu_minor)values(0, 204);

