create table import_export.lu_misspelt_user_request_tags
(pk serial primary key,
 tag text not null) ;
 
 alter table import_export.lu_misspelt_user_request_tags owner to easygp;
 grant all on table import_export.lu_misspelt_user_request_tags to easygp;
 grant all on table import_export.lu_misspelt_user_request_tags to staff;

insert into import_export.lu_misspelt_user_request_tags(tag) values ('radi');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('imag'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('path');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('dr'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('u/s');  
insert into import_export.lu_misspelt_user_request_tags(tag) values ('xray'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('BMD');   
insert into import_export.lu_misspelt_user_request_tags(tag) values ('s&n');   
insert into import_export.lu_misspelt_user_request_tags(tag) values ('sullivan nicolaides'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('ct'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('mri'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('ecg');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('barium');  
insert into import_export.lu_misspelt_user_request_tags(tag) values ('anaemia');  
insert into import_export.lu_misspelt_user_request_tags(tag) values ('nerve cond');  
insert into import_export.lu_misspelt_user_request_tags(tag) values ('inr');  
insert into import_export.lu_misspelt_user_request_tags(tag) values ('pulm test');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('histo'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('lavert'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('breastscreen'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('bowel screen');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('x-ray');  
insert into import_export.lu_misspelt_user_request_tags(tag) values ('xr '); 
insert into import_export.lu_misspelt_user_request_tags(tag) values (' xr'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values (' x ray');  
insert into import_export.lu_misspelt_user_request_tags(tag) values (' scan'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('doppler'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('bonescan');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('haematology'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('audiomety');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('audiometry'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('chest');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('24hr'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('24 hr'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('urine micr'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('breasrscreen'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('mammogram'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('BP'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('FNA'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('PAP'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('results'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('ultrasound');  
insert into import_export.lu_misspelt_user_request_tags(tag) values ('audiology'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('holter'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('nat hearing');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('symbion'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('s & n'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('echo'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('spiro');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('pacemaker'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('us'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('shoulder'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('hands');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('bowescab'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('boweslcan'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('lungscan'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('pulmonary'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('blood pressure report'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('biopsy'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('bone density'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('mammorgam'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('mammo'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('cytology'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('opg'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('thyroid'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('hips'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('densitometry'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('bowelscan'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('bowel cancer screening');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('bowelcancer screening'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('bowelscreen'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('biochem');
insert into import_export.lu_misspelt_user_request_tags(tag) values ('bowescan'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('s@n'); 
insert into import_export.lu_misspelt_user_request_tags(tag) values ('bone mineral');

truncate db.lu_version;
insert into db.lu_version (lu_major,lu_minor) values (0, 223);

