
SET search_path = common, pg_catalog;

create table common.lu_occupations_temp
   (pk serial primary key,
   occupation text not null,
   referrer_type character(1) DEFAULT 'o'::bpchar
   );

INSERT INTO lu_occupations_temp VALUES (1, 'accountant', 'o');
INSERT INTO lu_occupations_temp VALUES (2, 'account manager', 'o');
INSERT INTO lu_occupations_temp VALUES (3, 'acute case manager', 'o');
INSERT INTO lu_occupations_temp VALUES (4, 'addiction medicine registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (5, 'addiction medicine specialist', 's');
INSERT INTO lu_occupations_temp VALUES (6, 'admin assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (7, 'administration manager', 'o');
INSERT INTO lu_occupations_temp VALUES (8, 'administration officer', 'o');
INSERT INTO lu_occupations_temp VALUES (9, 'administrator', 'o');
INSERT INTO lu_occupations_temp VALUES (10, 'admin officer', 'o');
INSERT INTO lu_occupations_temp VALUES (11, 'aged care ain', 'o');
INSERT INTO lu_occupations_temp VALUES (12, 'air-conditioning mechanic', 'o');
INSERT INTO lu_occupations_temp VALUES (13, 'airframe fitter', 'o');
INSERT INTO lu_occupations_temp VALUES (14, 'airline pilot', 'o');
INSERT INTO lu_occupations_temp VALUES (15, 'allergist & immunologist', 's');
INSERT INTO lu_occupations_temp VALUES (16, 'aluminium fabricator', 'o');
INSERT INTO lu_occupations_temp VALUES (17, 'ambulance officer', 'o');
INSERT INTO lu_occupations_temp VALUES (18, 'anaesthetic registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (19, 'anaesthetist', 's');
INSERT INTO lu_occupations_temp VALUES (20, 'anaesthetist & intensivist', 's');
INSERT INTO lu_occupations_temp VALUES (21, 'anatomical pathologist', 's');
INSERT INTO lu_occupations_temp VALUES (22, 'apprentice boilermaker', 'o');
INSERT INTO lu_occupations_temp VALUES (23, 'apprentice carpenter', 'o');
INSERT INTO lu_occupations_temp VALUES (24, 'apprentice joiner', 'o');
INSERT INTO lu_occupations_temp VALUES (25, 'apprentice welder', 'o');
INSERT INTO lu_occupations_temp VALUES (26, 'aerial and satellite dish installer', 'o');
INSERT INTO lu_occupations_temp VALUES (27, 'artist', 'o');
INSERT INTO lu_occupations_temp VALUES (29, 'asphalter', 'o');
INSERT INTO lu_occupations_temp VALUES (30, 'assistant director', 'o');
INSERT INTO lu_occupations_temp VALUES (31, 'nursing assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (32, 'associate professor', 'o');
INSERT INTO lu_occupations_temp VALUES (33, 'audiologist', 'o');
INSERT INTO lu_occupations_temp VALUES (34, 'audiometrist', 'o');
INSERT INTO lu_occupations_temp VALUES (35, 'auto electrician', 'o');
INSERT INTO lu_occupations_temp VALUES (36, 'baby', 'o');
INSERT INTO lu_occupations_temp VALUES (37, 'baker', 'o');
INSERT INTO lu_occupations_temp VALUES (38, 'bakery manager', 'o');
INSERT INTO lu_occupations_temp VALUES (39, 'bank clerk', 'o');
INSERT INTO lu_occupations_temp VALUES (40, 'banker', 'o');  
INSERT INTO lu_occupations_temp VALUES (41, 'bank manager', 'o');
INSERT INTO lu_occupations_temp VALUES (42, 'bank officer', 'o');
INSERT INTO lu_occupations_temp VALUES (43, 'bar and gaming attendant', 'o');
INSERT INTO lu_occupations_temp VALUES (44, 'barmaid', 'o');
INSERT INTO lu_occupations_temp VALUES (45, 'barman', 'o');
INSERT INTO lu_occupations_temp VALUES (46, 'bar manager', 'o');
INSERT INTO lu_occupations_temp VALUES (48, 'beauty therapist', 'o');
INSERT INTO lu_occupations_temp VALUES (49, 'bereavement counsellor - adult', 'o');
INSERT INTO lu_occupations_temp VALUES (50, 'bistro assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (51, 'boilermaker', 'o'); 
INSERT INTO lu_occupations_temp VALUES (53, 'book binder', 'o');
INSERT INTO lu_occupations_temp VALUES (54, 'booking officer', 'o');
INSERT INTO lu_occupations_temp VALUES (55, 'bookkeeper', 'o');
INSERT INTO lu_occupations_temp VALUES (56, 'bowel surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (57, 'bread carter', 'o');
INSERT INTO lu_occupations_temp VALUES (58, 'brickies'' labourer', 'o');
INSERT INTO lu_occupations_temp VALUES (59, 'bricklayer', 'o');
INSERT INTO lu_occupations_temp VALUES (60, 'builder', 'o');
INSERT INTO lu_occupations_temp VALUES (61, 'building contractor', 'o');
INSERT INTO lu_occupations_temp VALUES (62, 'building supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (63, 'building surveyor', 'o');
INSERT INTO lu_occupations_temp VALUES (64, 'bus driver', 'o');
INSERT INTO lu_occupations_temp VALUES (65, 'business coach', 'o');
INSERT INTO lu_occupations_temp VALUES (66, 'business equipment technician', 'o');
INSERT INTO lu_occupations_temp VALUES (67, 'businessman', 'o');
INSERT INTO lu_occupations_temp VALUES (68, 'business manager', 'o');
INSERT INTO lu_occupations_temp VALUES (69, 'business owner', 'o');
INSERT INTO lu_occupations_temp VALUES (70, 'business person', 'o');
INSERT INTO lu_occupations_temp VALUES (71, 'butcher', 'o');
INSERT INTO lu_occupations_temp VALUES (72, 'cabinetmaker', 'o');
INSERT INTO lu_occupations_temp VALUES (73, 'cake decorator', 'o');
INSERT INTO lu_occupations_temp VALUES (74, 'call-centre consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (75, 'cane-cutter', 'o');
INSERT INTO lu_occupations_temp VALUES (76, 'canteen assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (77, 'car detailer', 'o');
INSERT INTO lu_occupations_temp VALUES (78, 'cardiologist', 's');
INSERT INTO lu_occupations_temp VALUES (79, 'cardiologist - electrophysiologist', 's');
INSERT INTO lu_occupations_temp VALUES (80, 'cardiologist - interventional', 's');
INSERT INTO lu_occupations_temp VALUES (81, 'cardiology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (82, 'cardio-thoracic registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (83, 'cardio-thoracic surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (84, 'career medical officer', 'g');
INSERT INTO lu_occupations_temp VALUES (85, 'carer', 'o');
INSERT INTO lu_occupations_temp VALUES (86, 'care service employee', 'o');
INSERT INTO lu_occupations_temp VALUES (87, 'caretaker shopping centre', 'o');
INSERT INTO lu_occupations_temp VALUES (88, 'care worker', 'o');
INSERT INTO lu_occupations_temp VALUES (89, 'carpenter', 'o');
INSERT INTO lu_occupations_temp VALUES (90, 'carpenter site supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (91, 'carpet layer', 'o');
INSERT INTO lu_occupations_temp VALUES (92, 'carpet salesman', 'o');
INSERT INTO lu_occupations_temp VALUES (93, 'cartoon character', 'o');
INSERT INTO lu_occupations_temp VALUES (94, 'car wagon fitter', 'o');
INSERT INTO lu_occupations_temp VALUES (95, 'case manager', 'o');
INSERT INTO lu_occupations_temp VALUES (96, 'cashier', 'o');
INSERT INTO lu_occupations_temp VALUES (97, 'casual receptionist', 'o');
INSERT INTO lu_occupations_temp VALUES (98, 'casual shop assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (99, 'catchment officer', 'o');
INSERT INTO lu_occupations_temp VALUES (100, 'cement renderer', 'o');
INSERT INTO lu_occupations_temp VALUES (101, 'ceo cardiology clinic', 'o');
INSERT INTO lu_occupations_temp VALUES (102, 'chartered accountant', 'o');
INSERT INTO lu_occupations_temp VALUES (103, 'chef', 'o');
INSERT INTO lu_occupations_temp VALUES (104, 'chemical pathologist', 's');
INSERT INTO lu_occupations_temp VALUES (105, 'chemist', 'o');
INSERT INTO lu_occupations_temp VALUES (106, 'chemist''s assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (107, 'chicken farmer', 'o');
INSERT INTO lu_occupations_temp VALUES (108, 'chief executive officer', 'o');
INSERT INTO lu_occupations_temp VALUES (109, 'child care assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (110, 'child carer - casual', 'o');
INSERT INTO lu_occupations_temp VALUES (111, 'child care worker', 'o');
INSERT INTO lu_occupations_temp VALUES (112, 'child minder', 'o');
INSERT INTO lu_occupations_temp VALUES (113, 'child psychiatrist', 's');
INSERT INTO lu_occupations_temp VALUES (114, 'child psychiatry registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (115, 'chiropractor', 'o');
INSERT INTO lu_occupations_temp VALUES (116, 'cinema owner', 'o');
INSERT INTO lu_occupations_temp VALUES (117, 'civil construction supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (118, 'civil engineer', 'o');
INSERT INTO lu_occupations_temp VALUES (119, 'claims manager', 'o');
INSERT INTO lu_occupations_temp VALUES (120, 'cleaner', 'o');
INSERT INTO lu_occupations_temp VALUES (121, 'cleaning business owner', 'o');
INSERT INTO lu_occupations_temp VALUES (123, 'clerical support staff', 'o');
INSERT INTO lu_occupations_temp VALUES (124, 'clerical worker', 'o');
INSERT INTO lu_occupations_temp VALUES (125, 'clerk', 'o');
INSERT INTO lu_occupations_temp VALUES (126, 'clinical geneticist', 's');
INSERT INTO lu_occupations_temp VALUES (127, 'clinical genetics registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (128, 'clinical nurse consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (129, 'clinical pharmacologist', 's');
INSERT INTO lu_occupations_temp VALUES (130, 'clinical pharmacology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (131, 'clinical psychologist', 'o');
INSERT INTO lu_occupations_temp VALUES (132, 'clinic research data manager', 'o');
INSERT INTO lu_occupations_temp VALUES (133, 'club manager', 'o');
INSERT INTO lu_occupations_temp VALUES (134, 'coal miner', 'o');
INSERT INTO lu_occupations_temp VALUES (135, 'coal miner fitter', 'o');
INSERT INTO lu_occupations_temp VALUES (136, 'colorectal surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (137, 'colorectal and general surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (138, 'commission agent', 'o');
INSERT INTO lu_occupations_temp VALUES (139, 'community worker', 'o');
INSERT INTO lu_occupations_temp VALUES (140, 'company director', 'o');
INSERT INTO lu_occupations_temp VALUES (141, 'company manager', 'o');
INSERT INTO lu_occupations_temp VALUES (142, 'company owner', 'o');
INSERT INTO lu_occupations_temp VALUES (143, 'computer aided design draughtsman', 'o');
INSERT INTO lu_occupations_temp VALUES (144, 'computer consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (145, 'computer programmer', 'o');
INSERT INTO lu_occupations_temp VALUES (146, 'computer technician', 'o');
INSERT INTO lu_occupations_temp VALUES (147, 'concretor', 'o');
INSERT INTO lu_occupations_temp VALUES (148, 'construction manager', 'o');
INSERT INTO lu_occupations_temp VALUES (149, 'construction supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (150, 'consultant', 's');
INSERT INTO lu_occupations_temp VALUES (151, 'consultant physician/geriatrician', 's');
INSERT INTO lu_occupations_temp VALUES (152, 'contract cleaner', 'o');
INSERT INTO lu_occupations_temp VALUES (153, 'conveyor maintenance', 'o');
INSERT INTO lu_occupations_temp VALUES (154, 'cook', 'o');
INSERT INTO lu_occupations_temp VALUES (155, 'corporate consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (156, 'cosmetic industry', 'o');
INSERT INTO lu_occupations_temp VALUES (157, 'cosmetic plastic surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (158, 'counselling psychologist', 'o');
INSERT INTO lu_occupations_temp VALUES (159, 'counsellor', 'o');
INSERT INTO lu_occupations_temp VALUES (160, 'courier', 'o');
INSERT INTO lu_occupations_temp VALUES (161, 'court registrar', 'o');
INSERT INTO lu_occupations_temp VALUES (162, 'crane chaser', 'o');
INSERT INTO lu_occupations_temp VALUES (163, 'crane driver', 'o');
INSERT INTO lu_occupations_temp VALUES (164, 'crane truck driver', 'o');
INSERT INTO lu_occupations_temp VALUES (165, 'crew manager', 'o');
INSERT INTO lu_occupations_temp VALUES (166, 'crew member', 'o');
INSERT INTO lu_occupations_temp VALUES (167, 'customer contact officer (fines)', 'o');
INSERT INTO lu_occupations_temp VALUES (168, 'customer service assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (169, 'customer service consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (170, 'customer service officer', 'o');
INSERT INTO lu_occupations_temp VALUES (171, 'dancer', 'o');
INSERT INTO lu_occupations_temp VALUES (172, 'database manager', 'o');
INSERT INTO lu_occupations_temp VALUES (173, 'deli assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (174, 'delivery', 'o');
INSERT INTO lu_occupations_temp VALUES (175, 'delivery driver', 'o');
INSERT INTO lu_occupations_temp VALUES (176, 'dental lab manager', 'o');
INSERT INTO lu_occupations_temp VALUES (177, 'dental nurse', 'o');
INSERT INTO lu_occupations_temp VALUES (178, 'dental prosthetist', 'o');
INSERT INTO lu_occupations_temp VALUES (179, 'dental technician', 'o');
INSERT INTO lu_occupations_temp VALUES (180, 'dentist', 'o');
INSERT INTO lu_occupations_temp VALUES (181, 'dermatologist', 's');
INSERT INTO lu_occupations_temp VALUES (182, 'dermatology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (183, 'design engineer', 'o');
INSERT INTO lu_occupations_temp VALUES (184, 'developer', 'o');
INSERT INTO lu_occupations_temp VALUES (185, 'diabetes educator', 'o');
INSERT INTO lu_occupations_temp VALUES (186, 'diabetologist', 's');
INSERT INTO lu_occupations_temp VALUES (187, 'diesel mechanic', 'o');
INSERT INTO lu_occupations_temp VALUES (188, 'dietitian', 'o');
INSERT INTO lu_occupations_temp VALUES (189, 'directional driller', 'o');
INSERT INTO lu_occupations_temp VALUES (190, 'disability pensioner', 'o');
INSERT INTO lu_occupations_temp VALUES (191, 'distribution manager', 'o');
INSERT INTO lu_occupations_temp VALUES (192, 'district officer', 'o');
INSERT INTO lu_occupations_temp VALUES (193, 'doctor', 'g');
INSERT INTO lu_occupations_temp VALUES (194, 'dog groomer', 'o');
INSERT INTO lu_occupations_temp VALUES (195, 'dogman', 'o');
INSERT INTO lu_occupations_temp VALUES (196, 'domestic', 'o');
INSERT INTO lu_occupations_temp VALUES (197, 'domestic supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (198, 'doorman', 'o');
INSERT INTO lu_occupations_temp VALUES (200, 'draughtsman', 'o');
INSERT INTO lu_occupations_temp VALUES (201, 'dress maker', 'o');
INSERT INTO lu_occupations_temp VALUES (202, 'driver', 'o');
INSERT INTO lu_occupations_temp VALUES (203, 'driver examiner', 'o');
INSERT INTO lu_occupations_temp VALUES (204, 'driving instructor', 'o');
INSERT INTO lu_occupations_temp VALUES (205, 'drover', 'o');
INSERT INTO lu_occupations_temp VALUES (207, 'drug and alcohol counsellor', 'o');
INSERT INTO lu_occupations_temp VALUES (208, 'drug representative', 'o');
INSERT INTO lu_occupations_temp VALUES (209, 'dry cleaner', 'o');
INSERT INTO lu_occupations_temp VALUES (210, 'educational consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (211, 'electronics technican', 'o');
INSERT INTO lu_occupations_temp VALUES (213, 'electrical consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (214, 'electrical contractor', 'o');
INSERT INTO lu_occupations_temp VALUES (215, 'electrical engineer', 'o');
INSERT INTO lu_occupations_temp VALUES (216, 'electrical fitter', 'o');
INSERT INTO lu_occupations_temp VALUES (217, 'electrical maintenance service', 'o');
INSERT INTO lu_occupations_temp VALUES (218, 'electrical trades assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (219, 'electrical wholesaler', 'o');
INSERT INTO lu_occupations_temp VALUES (220, 'electrician', 'o');
INSERT INTO lu_occupations_temp VALUES (221, 'electrician''s labourer', 'o');
INSERT INTO lu_occupations_temp VALUES (222, 'emergency physician', 's');
INSERT INTO lu_occupations_temp VALUES (223, 'emergency registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (224, 'employment consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (225, 'endocrinologist', 's');
INSERT INTO lu_occupations_temp VALUES (226, 'endocrinology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (227, 'engine driver', 'o');
INSERT INTO lu_occupations_temp VALUES (228, 'engineer', 'o');
INSERT INTO lu_occupations_temp VALUES (229, 'engineering surveyor', 'o');
INSERT INTO lu_occupations_temp VALUES (230, 'engineer - mechanical', 'o');
INSERT INTO lu_occupations_temp VALUES (232, 'ent - head & neck surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (233, 'ent registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (234, 'ent surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (235, 'ent surgeon - paediatric', 's');
INSERT INTO lu_occupations_temp VALUES (236, 'environmental consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (237, 'environmental economist', 'o');
INSERT INTO lu_occupations_temp VALUES (238, 'epidemiologist', 's');
INSERT INTO lu_occupations_temp VALUES (239, 'estimator', 'o');
INSERT INTO lu_occupations_temp VALUES (240, 'exercise physiologist', 'o');
INSERT INTO lu_occupations_temp VALUES (241, 'exercise therapist', 'o');
INSERT INTO lu_occupations_temp VALUES (242, 'factory worker', 'o');
INSERT INTO lu_occupations_temp VALUES (243, 'falls intake coordinator', 'o');
INSERT INTO lu_occupations_temp VALUES (244, 'family day care', 'o');
INSERT INTO lu_occupations_temp VALUES (245, 'family day care worker', 'o');
INSERT INTO lu_occupations_temp VALUES (246, 'farmer', 'o');
INSERT INTO lu_occupations_temp VALUES (247, 'farm hand', 'o');
INSERT INTO lu_occupations_temp VALUES (248, 'fencing contractor', 'o');
INSERT INTO lu_occupations_temp VALUES (249, 'finance broker', 'o');
INSERT INTO lu_occupations_temp VALUES (251, 'finance officer', 'o');
INSERT INTO lu_occupations_temp VALUES (252, 'financial adviser', 'o');
INSERT INTO lu_occupations_temp VALUES (253, 'financial planner', 'o');
INSERT INTO lu_occupations_temp VALUES (255, 'fireman', 'o');
INSERT INTO lu_occupations_temp VALUES (256, 'fish monger', 'o');
INSERT INTO lu_occupations_temp VALUES (257, 'fitter', 'o');
INSERT INTO lu_occupations_temp VALUES (259, 'fitter and turner', 'o');
INSERT INTO lu_occupations_temp VALUES (260, 'fitter machinist', 'o');
INSERT INTO lu_occupations_temp VALUES (261, 'food services coordinator', 'o');
INSERT INTO lu_occupations_temp VALUES (262, 'foreman', 'o');
INSERT INTO lu_occupations_temp VALUES (263, 'forensic pathologist', 's');
INSERT INTO lu_occupations_temp VALUES (264, 'forensic psychiatrist', 's');
INSERT INTO lu_occupations_temp VALUES (265, 'forensic psychologist', 'o');
INSERT INTO lu_occupations_temp VALUES (266, 'forest ranger', 'o');
INSERT INTO lu_occupations_temp VALUES (267, 'forklift driver', 'o');
INSERT INTO lu_occupations_temp VALUES (268, 'forklift driver- booking officer', 'o');
INSERT INTO lu_occupations_temp VALUES (269, 'forklift mechanic', 'o');
INSERT INTO lu_occupations_temp VALUES (270, 'free lance stylist', 'o');
INSERT INTO lu_occupations_temp VALUES (271, 'fruit and vegetable packer', 'o');
INSERT INTO lu_occupations_temp VALUES (272, 'fruit supplier', 'o');
INSERT INTO lu_occupations_temp VALUES (274, 'furniture removalist', 'o');
INSERT INTO lu_occupations_temp VALUES (275, 'garbage contractor', 'o');
INSERT INTO lu_occupations_temp VALUES (276, 'gardener', 'o');
INSERT INTO lu_occupations_temp VALUES (277, 'gas controller', 'o');
INSERT INTO lu_occupations_temp VALUES (278, 'gastroenterologist', 's');
INSERT INTO lu_occupations_temp VALUES (279, 'gastroenterologist and hepatologist', 's');
INSERT INTO lu_occupations_temp VALUES (280, 'gastroenterologist and hepatologist - paediatric', 's');
INSERT INTO lu_occupations_temp VALUES (281, 'gastroenterology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (282, 'general and abdominal surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (283, 'general and oncological surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (284, 'general assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (285, 'general hand', 'o');
INSERT INTO lu_occupations_temp VALUES (286, 'general & laparoscopic surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (287, 'general manager', 'o');
INSERT INTO lu_occupations_temp VALUES (288, 'general practice registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (289, 'general practitioner', 'g');
INSERT INTO lu_occupations_temp VALUES (290, 'general surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (291, 'general work', 'o');
INSERT INTO lu_occupations_temp VALUES (292, 'genetic counsellor', 'o');
INSERT INTO lu_occupations_temp VALUES (293, 'geologist', 'o');
INSERT INTO lu_occupations_temp VALUES (294, 'geotechnician', 'o');
INSERT INTO lu_occupations_temp VALUES (295, 'geriatrician', 's');
INSERT INTO lu_occupations_temp VALUES (296, 'geriatric registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (297, 'gis data acquisition officer', 'o');
INSERT INTO lu_occupations_temp VALUES (298, 'glass worker', 'o');
INSERT INTO lu_occupations_temp VALUES (299, 'glazier', 'o');
INSERT INTO lu_occupations_temp VALUES (300, 'graphic artist', 'o');
INSERT INTO lu_occupations_temp VALUES (301, 'graphic designer.', 'o');
INSERT INTO lu_occupations_temp VALUES (302, 'gynaecological oncologist', 's');
INSERT INTO lu_occupations_temp VALUES (303, 'gynaecologist', 's');
INSERT INTO lu_occupations_temp VALUES (304, 'gynaecology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (305, 'haematologist', 's');
INSERT INTO lu_occupations_temp VALUES (306, 'haematology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (307, 'hairdresser', 'o');
INSERT INTO lu_occupations_temp VALUES (309, 'hand therapist', 'o');
INSERT INTO lu_occupations_temp VALUES (311, 'health and safety manager', 'o');
INSERT INTO lu_occupations_temp VALUES (312, 'health information manager', 'o');
INSERT INTO lu_occupations_temp VALUES (313, 'hepatopancreatobilliary & upper gi surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (314, 'high school teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (315, 'home care worker', 'o');
INSERT INTO lu_occupations_temp VALUES (316, 'home duties', 'o');
INSERT INTO lu_occupations_temp VALUES (317, 'horse trainer', 'o');
INSERT INTO lu_occupations_temp VALUES (318, 'horticulturalist', 'o');
INSERT INTO lu_occupations_temp VALUES (319, 'horticulturalist supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (320, 'hospital assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (321, 'hospital cleaner', 'o');
INSERT INTO lu_occupations_temp VALUES (322, 'hospitality', 'o');
INSERT INTO lu_occupations_temp VALUES (323, 'hospitality teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (324, 'house cleaner', 'o');
INSERT INTO lu_occupations_temp VALUES (325, 'house duties', 'o');
INSERT INTO lu_occupations_temp VALUES (326, 'house keeper', 'o');
INSERT INTO lu_occupations_temp VALUES (327, 'house wife', 'o');
INSERT INTO lu_occupations_temp VALUES (328, 'human resouce manager', 'o');
INSERT INTO lu_occupations_temp VALUES (329, 'human resources officer', 'o');
INSERT INTO lu_occupations_temp VALUES (330, 'hydrographer', 'o');
INSERT INTO lu_occupations_temp VALUES (331, 'icu registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (332, 'immunologist', 's');
INSERT INTO lu_occupations_temp VALUES (333, 'immunology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (334, 'industrial economist', 'o');
INSERT INTO lu_occupations_temp VALUES (335, 'infant teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (336, 'infectious diseases registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (337, 'information technology manager', 'o');
INSERT INTO lu_occupations_temp VALUES (338, 'injury management advisor', 'o');
INSERT INTO lu_occupations_temp VALUES (339, 'installer', 'o');
INSERT INTO lu_occupations_temp VALUES (340, 'instrument maker', 'o');
INSERT INTO lu_occupations_temp VALUES (341, 'instrument technician', 'o');
INSERT INTO lu_occupations_temp VALUES (342, 'insurance broker', 'o');
INSERT INTO lu_occupations_temp VALUES (343, 'insurance officer', 'o');
INSERT INTO lu_occupations_temp VALUES (344, 'insurance operator', 'o');
INSERT INTO lu_occupations_temp VALUES (345, 'insurance underwriter', 'o');
INSERT INTO lu_occupations_temp VALUES (346, 'intern', 'g');
INSERT INTO lu_occupations_temp VALUES (347, 'invalid pensioner', 'o');
INSERT INTO lu_occupations_temp VALUES (348, 'investor', 'o');
INSERT INTO lu_occupations_temp VALUES (349, 'iron worker', 'o');
INSERT INTO lu_occupations_temp VALUES (350, 'it consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (351, 'it infrastructure manager', 'o');
INSERT INTO lu_occupations_temp VALUES (352, 'it manager', 'o');
INSERT INTO lu_occupations_temp VALUES (353, 'it project manager', 'o');
INSERT INTO lu_occupations_temp VALUES (354, 'ivf specialist', 's');
INSERT INTO lu_occupations_temp VALUES (355, 'jockey', 'o');
INSERT INTO lu_occupations_temp VALUES (356, 'joiner', 'o');
INSERT INTO lu_occupations_temp VALUES (357, 'laboratory analyst', 'o');
INSERT INTO lu_occupations_temp VALUES (358, 'labourer', 'o');
INSERT INTO lu_occupations_temp VALUES (359, 'landscaper', 'o');
INSERT INTO lu_occupations_temp VALUES (360, 'laundry worker', 'o');
INSERT INTO lu_occupations_temp VALUES (361, 'lawn mowing', 'o');
INSERT INTO lu_occupations_temp VALUES (362, 'lecturer', 'o');
INSERT INTO lu_occupations_temp VALUES (363, 'legal manager', 'o');
INSERT INTO lu_occupations_temp VALUES (364, 'legal secretary', 'o');
INSERT INTO lu_occupations_temp VALUES (365, 'legal support officer', 'o');
INSERT INTO lu_occupations_temp VALUES (366, 'liaison officer', 'o');
INSERT INTO lu_occupations_temp VALUES (367, 'librarian', 'o');
INSERT INTO lu_occupations_temp VALUES (368, 'library technician', 'o');
INSERT INTO lu_occupations_temp VALUES (369, 'lifeguard', 'o');
INSERT INTO lu_occupations_temp VALUES (370, 'linesman', 'o');
INSERT INTO lu_occupations_temp VALUES (371, 'locum cardiologist', 's');
INSERT INTO lu_occupations_temp VALUES (372, 'loss adjuster', 'o');
INSERT INTO lu_occupations_temp VALUES (373, 'lubrication fitter', 'o');
INSERT INTO lu_occupations_temp VALUES (374, 'machine operator', 'o');
INSERT INTO lu_occupations_temp VALUES (375, 'machinist', 'o');
INSERT INTO lu_occupations_temp VALUES (376, 'magistrate', 'o');
INSERT INTO lu_occupations_temp VALUES (377, 'mail courier', 'o');
INSERT INTO lu_occupations_temp VALUES (378, 'maintenance carpenter', 'o');
INSERT INTO lu_occupations_temp VALUES (379, 'maintenance planner', 'o');
INSERT INTO lu_occupations_temp VALUES (380, 'maintenance worker', 'o');
INSERT INTO lu_occupations_temp VALUES (381, 'maintenence supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (382, 'make up artist', 'o');
INSERT INTO lu_occupations_temp VALUES (383, 'manager', 'o');
INSERT INTO lu_occupations_temp VALUES (384, 'manufacturer', 'o');
INSERT INTO lu_occupations_temp VALUES (385, 'manufacturers agent', 'o');
INSERT INTO lu_occupations_temp VALUES (386, 'manufacturing', 'o');
INSERT INTO lu_occupations_temp VALUES (387, 'marine engineer', 'o');
INSERT INTO lu_occupations_temp VALUES (388, 'marketing', 'o');
INSERT INTO lu_occupations_temp VALUES (389, 'marketing manager', 'o');
INSERT INTO lu_occupations_temp VALUES (390, 'massage therapist', 'o');
INSERT INTO lu_occupations_temp VALUES (391, 'maxillo-facial registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (392, 'meat inspector', 'o');
INSERT INTO lu_occupations_temp VALUES (393, 'meat salesman', 'o');
INSERT INTO lu_occupations_temp VALUES (394, 'mechanic', 'o');
INSERT INTO lu_occupations_temp VALUES (395, 'mechanical engineer', 'o');
INSERT INTO lu_occupations_temp VALUES (396, 'medical administration registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (397, 'medical administrator', 's');
INSERT INTO lu_occupations_temp VALUES (398, 'medical oncologist', 's');
INSERT INTO lu_occupations_temp VALUES (399, 'medical oncology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (400, 'medical practitioner', 'g');
INSERT INTO lu_occupations_temp VALUES (401, 'medical receptionist', 'o');
INSERT INTO lu_occupations_temp VALUES (402, 'medical registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (403, 'medical representative', 'o');
INSERT INTO lu_occupations_temp VALUES (404, 'medical scientist', 'o');
INSERT INTO lu_occupations_temp VALUES (405, 'medical secretary', 'o');
INSERT INTO lu_occupations_temp VALUES (406, 'medical student', 'o');
INSERT INTO lu_occupations_temp VALUES (407, 'merchandiser', 'o');
INSERT INTO lu_occupations_temp VALUES (408, 'merchant seaman', 'o');
INSERT INTO lu_occupations_temp VALUES (409, 'metallurgist', 'o');
INSERT INTO lu_occupations_temp VALUES (410, 'meter reader', 'o');
INSERT INTO lu_occupations_temp VALUES (411, 'microbiologist', 's');
INSERT INTO lu_occupations_temp VALUES (412, 'migration agent', 'o');
INSERT INTO lu_occupations_temp VALUES (413, 'milk vendor', 'o');
INSERT INTO lu_occupations_temp VALUES (414, 'mine deputy', 'o');
INSERT INTO lu_occupations_temp VALUES (415, 'mine manager', 'o');
INSERT INTO lu_occupations_temp VALUES (416, 'mine worker', 'o');
INSERT INTO lu_occupations_temp VALUES (418, 'mining engineer', 'o');
INSERT INTO lu_occupations_temp VALUES (419, 'minister of religion', 'o');
INSERT INTO lu_occupations_temp VALUES (420, 'motor body trimmer', 'o');
INSERT INTO lu_occupations_temp VALUES (421, 'motor car dealer', 'o');
INSERT INTO lu_occupations_temp VALUES (422, 'motor mechanic', 'o');
INSERT INTO lu_occupations_temp VALUES (423, 'musician', 'o');
INSERT INTO lu_occupations_temp VALUES (424, 'music teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (425, 'nail technician', 'o');
INSERT INTO lu_occupations_temp VALUES (426, 'natural resource project officer', 'o');
INSERT INTO lu_occupations_temp VALUES (427, 'neck and general surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (429, 'neonatologist', 's');
INSERT INTO lu_occupations_temp VALUES (430, 'nephrologist', 's');
INSERT INTO lu_occupations_temp VALUES (431, 'neurologist - adult', 's');
INSERT INTO lu_occupations_temp VALUES (432, 'neurology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (433, 'neuropsychologist', 'o');
INSERT INTO lu_occupations_temp VALUES (434, 'neurosurgeon', 's');
INSERT INTO lu_occupations_temp VALUES (436, 'night watchman', 'o');
INSERT INTO lu_occupations_temp VALUES (437, 'nrma patrolman', 'o');
INSERT INTO lu_occupations_temp VALUES (438, 'nuclear medicine physician', 's');
INSERT INTO lu_occupations_temp VALUES (439, 'nuclear medicine registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (440, 'nurse', 'o');
INSERT INTO lu_occupations_temp VALUES (441, 'nurse - ain', 'o');
INSERT INTO lu_occupations_temp VALUES (442, 'nurse - disability', 'o');
INSERT INTO lu_occupations_temp VALUES (443, 'nurse - psychiatric', 'o');
INSERT INTO lu_occupations_temp VALUES (445, 'nurse''s aide', 'o');
INSERT INTO lu_occupations_temp VALUES (447, 'obstetrician and gynaecologist', 's');
INSERT INTO lu_occupations_temp VALUES (448, 'obstetric registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (449, 'occupational medicine registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (450, 'occupational nursing', 'o');
INSERT INTO lu_occupations_temp VALUES (451, 'occupational physician', 's');
INSERT INTO lu_occupations_temp VALUES (452, 'occupational therapist', 'o');
INSERT INTO lu_occupations_temp VALUES (453, 'office administrator', 'o');
INSERT INTO lu_occupations_temp VALUES (454, 'office clerk', 'o');
INSERT INTO lu_occupations_temp VALUES (456, 'office duties and retail', 'o');
INSERT INTO lu_occupations_temp VALUES (457, 'office equipment engineer', 'o');
INSERT INTO lu_occupations_temp VALUES (458, 'office manager', 'o');
INSERT INTO lu_occupations_temp VALUES (459, 'office worker', 'o');
INSERT INTO lu_occupations_temp VALUES (460, 'operations assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (461, 'ophthalmic surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (462, 'ophthalmologist', 'o');
INSERT INTO lu_occupations_temp VALUES (463, 'ophthalmologist & plastic surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (464, 'ophthalmology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (465, 'optometrist', 'o');
INSERT INTO lu_occupations_temp VALUES (466, 'oral & maxillofacial surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (467, 'oral surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (468, 'orthodontist', 'o');
INSERT INTO lu_occupations_temp VALUES (469, 'orthopaedic registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (470, 'orthopaedic surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (471, 'orthopaedic surgeon - foot & ankle', 'o');
INSERT INTO lu_occupations_temp VALUES (472, 'orthopaedic surgeon - general', 's');
INSERT INTO lu_occupations_temp VALUES (473, 'orthopaedic surgeon - hand', 's');
INSERT INTO lu_occupations_temp VALUES (474, 'orthopaedic surgeon - hip & knee', 's');
INSERT INTO lu_occupations_temp VALUES (475, 'orthopaedic surgeon -  paediatric', 's');
INSERT INTO lu_occupations_temp VALUES (476, 'orthopaedic surgeon - upper limb', 's');
INSERT INTO lu_occupations_temp VALUES (477, 'packing team leader', 'o');
INSERT INTO lu_occupations_temp VALUES (478, 'paediatric allergist and immunologist', 's');
INSERT INTO lu_occupations_temp VALUES (479, 'paediatric cardiologist', 's');
INSERT INTO lu_occupations_temp VALUES (480, 'paediatric emergency physician', 's');
INSERT INTO lu_occupations_temp VALUES (481, 'paediatric endocrinologist', 's');
INSERT INTO lu_occupations_temp VALUES (482, 'paediatric haematologist', 's');
INSERT INTO lu_occupations_temp VALUES (483, 'paediatrician', 's');
INSERT INTO lu_occupations_temp VALUES (484, 'paediatrician - behaviour', 's');
INSERT INTO lu_occupations_temp VALUES (485, 'paediatrician - general', 's');
INSERT INTO lu_occupations_temp VALUES (486, 'paediatric infectious diseases physician', 's');
INSERT INTO lu_occupations_temp VALUES (487, 'paediatric nephrologist', 's');
INSERT INTO lu_occupations_temp VALUES (488, 'paediatric neurologist', 's');
INSERT INTO lu_occupations_temp VALUES (489, 'paediatric nuclear medicine physician', 's');
INSERT INTO lu_occupations_temp VALUES (490, 'paediatric oncologist', 's');
INSERT INTO lu_occupations_temp VALUES (491, 'paediatric palliative care physician', 's');
INSERT INTO lu_occupations_temp VALUES (492, 'paediatric physiotherapist', 'o');
INSERT INTO lu_occupations_temp VALUES (493, 'paediatric registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (494, 'paediatric respiratory physician', 's');
INSERT INTO lu_occupations_temp VALUES (495, 'paediatric rheumatologist', 's');
INSERT INTO lu_occupations_temp VALUES (496, 'paediatric surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (497, 'paediatric surgical registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (498, 'paediatric urologist', 's');
INSERT INTO lu_occupations_temp VALUES (499, 'pain medicine registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (500, 'pain physician', 's');
INSERT INTO lu_occupations_temp VALUES (501, 'painter', 'o');
INSERT INTO lu_occupations_temp VALUES (502, 'paint tinter', 'o');
INSERT INTO lu_occupations_temp VALUES (503, 'palliative care physician', 's');
INSERT INTO lu_occupations_temp VALUES (504, 'palliative care registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (505, 'panelbeater', 'o');
INSERT INTO lu_occupations_temp VALUES (506, 'pantry maid', 'o');
INSERT INTO lu_occupations_temp VALUES (507, 'paramedic', 'o');
INSERT INTO lu_occupations_temp VALUES (508, 'part-time careers advisor', 'o');
INSERT INTO lu_occupations_temp VALUES (509, 'part-time cleaner', 'o');
INSERT INTO lu_occupations_temp VALUES (510, 'part-time clerical assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (511, 'part-time office worker', 'o');
INSERT INTO lu_occupations_temp VALUES (512, 'part-time teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (513, 'pastoral carer', 'o');
INSERT INTO lu_occupations_temp VALUES (514, 'pastry chef', 'o');
INSERT INTO lu_occupations_temp VALUES (515, 'pathologist', 's');
INSERT INTO lu_occupations_temp VALUES (516, 'pathology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (517, 'pathology technician', 'o');
INSERT INTO lu_occupations_temp VALUES (518, 'pensioner', 'o');
INSERT INTO lu_occupations_temp VALUES (519, 'personal assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (520, 'personal trainer', 'o');
INSERT INTO lu_occupations_temp VALUES (521, 'personel officer', 'o');
INSERT INTO lu_occupations_temp VALUES (522, 'pest controller', 'o');
INSERT INTO lu_occupations_temp VALUES (523, 'pharmaceutical company representative', 'o');
INSERT INTO lu_occupations_temp VALUES (524, 'pharmacist', 'o');
INSERT INTO lu_occupations_temp VALUES (525, 'pharmacy assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (526, 'phlebotomist', 'o');
INSERT INTO lu_occupations_temp VALUES (527, 'phone system installater', 'o');
INSERT INTO lu_occupations_temp VALUES (528, 'photographer', 'o');
INSERT INTO lu_occupations_temp VALUES (529, 'photo shop assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (530, 'photo studio manager', 'o');
INSERT INTO lu_occupations_temp VALUES (531, 'physical education teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (532, 'physician', 's');
INSERT INTO lu_occupations_temp VALUES (533, 'physician & allergist', 's');
INSERT INTO lu_occupations_temp VALUES (534, 'physician - breast', 's');
INSERT INTO lu_occupations_temp VALUES (535, 'physician - general', 's');
INSERT INTO lu_occupations_temp VALUES (536, 'physician - infectious disease', 's');
INSERT INTO lu_occupations_temp VALUES (537, 'physician - musculoskeletal', 's');
INSERT INTO lu_occupations_temp VALUES (538, 'physician - renal', 's');
INSERT INTO lu_occupations_temp VALUES (539, 'physician''s aide', 'o');
INSERT INTO lu_occupations_temp VALUES (540, 'physiotherapist', 'o');
INSERT INTO lu_occupations_temp VALUES (541, 'physiotherapy aide', 'o');
INSERT INTO lu_occupations_temp VALUES (542, 'plant fitter', 'o');
INSERT INTO lu_occupations_temp VALUES (543, 'plant mechanic', 'o');
INSERT INTO lu_occupations_temp VALUES (544, 'plant operator', 'o');
INSERT INTO lu_occupations_temp VALUES (545, 'plasterer', 'o');
INSERT INTO lu_occupations_temp VALUES (546, 'plastic, reconstructive & hand surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (547, 'plastics registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (548, 'plastic surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (549, 'plumber', 'o');
INSERT INTO lu_occupations_temp VALUES (550, 'podiatrist', 'o');
INSERT INTO lu_occupations_temp VALUES (551, 'poker machine clerk', 'o');
INSERT INTO lu_occupations_temp VALUES (552, 'police officer', 'o');
INSERT INTO lu_occupations_temp VALUES (553, 'pool builder', 'o');
INSERT INTO lu_occupations_temp VALUES (554, 'pool inspector', 'o');
INSERT INTO lu_occupations_temp VALUES (555, 'postal delivery officer', 'o');
INSERT INTO lu_occupations_temp VALUES (556, 'postal worker', 'o');
INSERT INTO lu_occupations_temp VALUES (558, 'post office licensee', 'o');
INSERT INTO lu_occupations_temp VALUES (559, 'poultry farmer', 'o');
INSERT INTO lu_occupations_temp VALUES (560, 'practice manager', 'o');
INSERT INTO lu_occupations_temp VALUES (561, 'pre-school teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (562, 'pricing clerk', 'o');
INSERT INTO lu_occupations_temp VALUES (563, 'primary school teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (564, 'prime minister', 'o');
INSERT INTO lu_occupations_temp VALUES (565, 'principal research engineer', 'o');
INSERT INTO lu_occupations_temp VALUES (566, 'printer', 'o');
INSERT INTO lu_occupations_temp VALUES (567, 'printing machinist', 'o');
INSERT INTO lu_occupations_temp VALUES (568, 'prison officer', 'o');
INSERT INTO lu_occupations_temp VALUES (569, 'private secretary', 'o');
INSERT INTO lu_occupations_temp VALUES (570, 'process worker', 'o');
INSERT INTO lu_occupations_temp VALUES (571, 'production operator', 'o');
INSERT INTO lu_occupations_temp VALUES (572, 'production shift foreman', 'o');
INSERT INTO lu_occupations_temp VALUES (573, 'product manager', 'o');
INSERT INTO lu_occupations_temp VALUES (574, 'professional fisherman', 'o');
INSERT INTO lu_occupations_temp VALUES (575, 'professor engineering', 'o');
INSERT INTO lu_occupations_temp VALUES (576, 'project manager', 'o');
INSERT INTO lu_occupations_temp VALUES (577, 'project officer', 'o');
INSERT INTO lu_occupations_temp VALUES (578, 'property manager', 'o');
INSERT INTO lu_occupations_temp VALUES (579, 'prospector', 'o');
INSERT INTO lu_occupations_temp VALUES (580, 'psychiatric nurse', 'o');
INSERT INTO lu_occupations_temp VALUES (581, 'psychiatrist', 's');
INSERT INTO lu_occupations_temp VALUES (582, 'psychiatry registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (583, 'psychogeriatrician', 's');
INSERT INTO lu_occupations_temp VALUES (584, 'psychogeriatric registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (585, 'psychologist', 'o');
INSERT INTO lu_occupations_temp VALUES (586, 'public health physician', 's');
INSERT INTO lu_occupations_temp VALUES (587, 'public health registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (588, 'public servant', 'o');
INSERT INTO lu_occupations_temp VALUES (589, 'purchasing officer', 'o');
INSERT INTO lu_occupations_temp VALUES (590, 'radiation oncologist', 's');
INSERT INTO lu_occupations_temp VALUES (591, 'radiation oncology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (592, 'radiologist', 's');
INSERT INTO lu_occupations_temp VALUES (593, 'radiology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (594, 'radio operator', 'o');
INSERT INTO lu_occupations_temp VALUES (595, 'rail worker', 'o');
INSERT INTO lu_occupations_temp VALUES (596, 'real estate agent', 'o');
INSERT INTO lu_occupations_temp VALUES (597, 'real estate valuer', 'o');
INSERT INTO lu_occupations_temp VALUES (598, 'receptionist', 'o');
INSERT INTO lu_occupations_temp VALUES (599, 'recycler', 'o');
INSERT INTO lu_occupations_temp VALUES (600, 'regional manager', 'o');
INSERT INTO lu_occupations_temp VALUES (601, 'registered nurse', 'o');
INSERT INTO lu_occupations_temp VALUES (602, 'registered psychologist', 'o');
INSERT INTO lu_occupations_temp VALUES (603, 'registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (604, 'registrar - neurosurgery', 'g');
INSERT INTO lu_occupations_temp VALUES (605, 'rehabilitation consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (606, 'rehabilitation medicine physician', 's');
INSERT INTO lu_occupations_temp VALUES (607, 'rehabilitation paediatrician', 's');
INSERT INTO lu_occupations_temp VALUES (608, 'rehabilitation registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (609, 'rehabilitation specialist', 'o');
INSERT INTO lu_occupations_temp VALUES (610, 'renal registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (611, 'representative', 'o');
INSERT INTO lu_occupations_temp VALUES (612, 'research co-ordinator', 'o');
INSERT INTO lu_occupations_temp VALUES (613, 'residential home worker', 'o');
INSERT INTO lu_occupations_temp VALUES (614, 'resident medical officer', 'g');
INSERT INTO lu_occupations_temp VALUES (615, 'respiratory physician', 's');
INSERT INTO lu_occupations_temp VALUES (616, 'respiratory registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (617, 'respiratory & sleep physician', 's');
INSERT INTO lu_occupations_temp VALUES (618, 'restauranter', 'o');
INSERT INTO lu_occupations_temp VALUES (619, 'restaurant worker', 'o');
INSERT INTO lu_occupations_temp VALUES (620, 'retail', 'o');
INSERT INTO lu_occupations_temp VALUES (621, 'retail sales', 'o');
INSERT INTO lu_occupations_temp VALUES (622, 'retired', 'o');
INSERT INTO lu_occupations_temp VALUES (623, 'return to work co-ordinator', 'o');
INSERT INTO lu_occupations_temp VALUES (624, 'rheumatologist', 's');
INSERT INTO lu_occupations_temp VALUES (625, 'rheumatology clinical nurse specialist', 'o');
INSERT INTO lu_occupations_temp VALUES (626, 'rheumatology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (627, 'rigger', 'o');
INSERT INTO lu_occupations_temp VALUES (628, 'risk management consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (629, 'road builder', 'o');
INSERT INTO lu_occupations_temp VALUES (630, 'rocket scientist', 'o');
INSERT INTO lu_occupations_temp VALUES (631, 'roofer', 'o');
INSERT INTO lu_occupations_temp VALUES (632, 'roof plumber', 'o');
INSERT INTO lu_occupations_temp VALUES (633, 'roof tiler', 'o');
INSERT INTO lu_occupations_temp VALUES (634, 'safety trainer', 'o');
INSERT INTO lu_occupations_temp VALUES (635, 'sailor', 'o');
INSERT INTO lu_occupations_temp VALUES (636, 'sales and service co-ordinator', 'o');
INSERT INTO lu_occupations_temp VALUES (637, 'sales assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (638, 'sales consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (639, 'salesman', 'o');
INSERT INTO lu_occupations_temp VALUES (640, 'sales manager', 'o');
INSERT INTO lu_occupations_temp VALUES (641, 'salesperson', 'o');
INSERT INTO lu_occupations_temp VALUES (643, 'sales representative', 'o');
INSERT INTO lu_occupations_temp VALUES (644, 'sandblaster', 'o');
INSERT INTO lu_occupations_temp VALUES (645, 'scaffolder', 'o');
INSERT INTO lu_occupations_temp VALUES (646, 'school administrator', 'o');
INSERT INTO lu_occupations_temp VALUES (647, 'school assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (648, 'school cleaner', 'o');
INSERT INTO lu_occupations_temp VALUES (649, 'school counsellor', 'o');
INSERT INTO lu_occupations_temp VALUES (650, 'school crossing supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (651, 'school learning support officer', 'o');
INSERT INTO lu_occupations_temp VALUES (652, 'school principal', 'o');
INSERT INTO lu_occupations_temp VALUES (653, 'school teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (654, 'seamstress', 'o');
INSERT INTO lu_occupations_temp VALUES (656, 'secretary', 'o');
INSERT INTO lu_occupations_temp VALUES (657, 'secretary - legal', 'o');
INSERT INTO lu_occupations_temp VALUES (658, 'section manageress', 'o');
INSERT INTO lu_occupations_temp VALUES (659, 'security consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (660, 'security guard', 'o');
INSERT INTO lu_occupations_temp VALUES (661, 'security technician', 'o');
INSERT INTO lu_occupations_temp VALUES (662, 'self-employed', 'o');
INSERT INTO lu_occupations_temp VALUES (663, 'self-employed consultant', 'o');
INSERT INTO lu_occupations_temp VALUES (664, 'self-employed wholesaler', 'o');
INSERT INTO lu_occupations_temp VALUES (665, 'senior firefighter', 'o');
INSERT INTO lu_occupations_temp VALUES (666, 'sergeant of police', 'o');
INSERT INTO lu_occupations_temp VALUES (667, 'service assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (668, 'service supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (669, 'service technician', 'o');
INSERT INTO lu_occupations_temp VALUES (670, 'sex therapist', 'o');
INSERT INTO lu_occupations_temp VALUES (671, 'sexual health physician', 's');
INSERT INTO lu_occupations_temp VALUES (672, 'sexual health registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (673, 'sex worker', 'o');
INSERT INTO lu_occupations_temp VALUES (674, 'shearer', 'o');
INSERT INTO lu_occupations_temp VALUES (675, 'sheep drover', 'o');
INSERT INTO lu_occupations_temp VALUES (676, 'sheet metal worker', 'o');
INSERT INTO lu_occupations_temp VALUES (677, 'sherriff''s officer', 'o');
INSERT INTO lu_occupations_temp VALUES (678, 'shift co-ordinator', 'o');
INSERT INTO lu_occupations_temp VALUES (679, 'shift manager', 'o');
INSERT INTO lu_occupations_temp VALUES (680, 'shipping clerk', 'o');
INSERT INTO lu_occupations_temp VALUES (681, 'shop assisant', 'o');
INSERT INTO lu_occupations_temp VALUES (682, 'shop assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (683, 'shop manager', 'o');
INSERT INTO lu_occupations_temp VALUES (684, 'shop owner', 'o');
INSERT INTO lu_occupations_temp VALUES (685, 'shop security officer', 'o');
INSERT INTO lu_occupations_temp VALUES (686, 'shorthand typist', 'o');
INSERT INTO lu_occupations_temp VALUES (687, 'shoulder physician', 's');
INSERT INTO lu_occupations_temp VALUES (688, 'sign writer', 'o');
INSERT INTO lu_occupations_temp VALUES (689, 'singer', 'o');
INSERT INTO lu_occupations_temp VALUES (690, 'site coordinator', 'o');
INSERT INTO lu_occupations_temp VALUES (691, 'small businessman', 'o');
INSERT INTO lu_occupations_temp VALUES (692, 'social welfare worker', 'o');
INSERT INTO lu_occupations_temp VALUES (693, 'software systems engineer', 'o');
INSERT INTO lu_occupations_temp VALUES (694, 'soldier', 'o');
INSERT INTO lu_occupations_temp VALUES (695, 'sole parent pensioner', 'o');
INSERT INTO lu_occupations_temp VALUES (696, 'solicitor', 'o');
INSERT INTO lu_occupations_temp VALUES (697, 'solicitor''s clerk', 'o');
INSERT INTO lu_occupations_temp VALUES (698, 'sound technician', 'o');
INSERT INTO lu_occupations_temp VALUES (699, 'spare parts supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (700, 'special education teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (701, 'spectrum manager', 'o');
INSERT INTO lu_occupations_temp VALUES (702, 'speech pathologist', 'o');
INSERT INTO lu_occupations_temp VALUES (703, 'speech therapist', 'o');
INSERT INTO lu_occupations_temp VALUES (704, 'spinal & orthopaedic surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (705, 'sports medicine registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (706, 'sports physician', 's');
INSERT INTO lu_occupations_temp VALUES (707, 'staff manager', 'o');
INSERT INTO lu_occupations_temp VALUES (708, 'staff specialist diabetic clinic', 's');
INSERT INTO lu_occupations_temp VALUES (709, 'stage manager', 'o');
INSERT INTO lu_occupations_temp VALUES (711, 'steel fixer', 'o');
INSERT INTO lu_occupations_temp VALUES (712, 'steel worker', 'o');
INSERT INTO lu_occupations_temp VALUES (713, 'stevedore', 'o');
INSERT INTO lu_occupations_temp VALUES (714, 'storeman', 'o');
INSERT INTO lu_occupations_temp VALUES (715, 'store manager', 'o');
INSERT INTO lu_occupations_temp VALUES (716, 'storeman - driver', 'o');
INSERT INTO lu_occupations_temp VALUES (717, 'store manger', 'o');
INSERT INTO lu_occupations_temp VALUES (718, 'storeperson', 'o');
INSERT INTO lu_occupations_temp VALUES (719, 'strip club dancer', 'o');
INSERT INTO lu_occupations_temp VALUES (720, 'student', 'o');
INSERT INTO lu_occupations_temp VALUES (721, 'student actor', 'o');
INSERT INTO lu_occupations_temp VALUES (722, 'student - ain', 'o');
INSERT INTO lu_occupations_temp VALUES (723, 'student - high school', 'o');
INSERT INTO lu_occupations_temp VALUES (724, 'supermarket manager', 'o');
INSERT INTO lu_occupations_temp VALUES (725, 'supervisior', 'o');
INSERT INTO lu_occupations_temp VALUES (726, 'supervisor', 'o');
INSERT INTO lu_occupations_temp VALUES (727, 'support learning officer', 'o');
INSERT INTO lu_occupations_temp VALUES (728, 'support services officer', 'o');
INSERT INTO lu_occupations_temp VALUES (729, 'support worker', 'o');
INSERT INTO lu_occupations_temp VALUES (730, 'surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (731, 'surgeon - breast', 's');
INSERT INTO lu_occupations_temp VALUES (732, 'surgeon - thoracic', 's');
INSERT INTO lu_occupations_temp VALUES (733, 'surgical registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (734, 'surveyor', 'o');
INSERT INTO lu_occupations_temp VALUES (735, 'swimming instructor', 'o');
INSERT INTO lu_occupations_temp VALUES (736, 'systems trainer', 'o');
INSERT INTO lu_occupations_temp VALUES (737, 'tab agent', 'o');
INSERT INTO lu_occupations_temp VALUES (738, 'tafe teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (739, 'tafe teacher - science', 'o');
INSERT INTO lu_occupations_temp VALUES (740, 'tailor', 'o');
INSERT INTO lu_occupations_temp VALUES (741, 'talley clerk', 'o');
INSERT INTO lu_occupations_temp VALUES (742, 'tanker driver', 'o');
INSERT INTO lu_occupations_temp VALUES (743, 'taxation office investigator', 'o');
INSERT INTO lu_occupations_temp VALUES (744, 'taxi driver', 'o');
INSERT INTO lu_occupations_temp VALUES (745, 'taxi operator', 'o');
INSERT INTO lu_occupations_temp VALUES (746, 'teacher', 'o');
INSERT INTO lu_occupations_temp VALUES (747, 'teacher - adult education', 'o');
INSERT INTO lu_occupations_temp VALUES (748, 'teacher - headmaster', 'o');
INSERT INTO lu_occupations_temp VALUES (749, 'teacher - high school', 'o');
INSERT INTO lu_occupations_temp VALUES (750, 'teacher high school special ed', 'o');
INSERT INTO lu_occupations_temp VALUES (751, 'teacher - kindergarten', 'o');
INSERT INTO lu_occupations_temp VALUES (752, 'school librarian', 'o');
INSERT INTO lu_occupations_temp VALUES (753, 'teacher - mathematics', 'o');
INSERT INTO lu_occupations_temp VALUES (754, 'teacher - nursing', 'o');
INSERT INTO lu_occupations_temp VALUES (755, 'teacher - pre-school', 'o');
INSERT INTO lu_occupations_temp VALUES (756, 'teacher - primary school', 'o'); -- duplicate
INSERT INTO lu_occupations_temp VALUES (758, 'teacher - principal', 'o');
INSERT INTO lu_occupations_temp VALUES (759, 'teacher - tafe', 'o');
INSERT INTO lu_occupations_temp VALUES (760, 'teacher - trades', 'o');
INSERT INTO lu_occupations_temp VALUES (761, 'technical assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (762, 'technical officer', 'o');
INSERT INTO lu_occupations_temp VALUES (763, 'telemarketer', 'o');
INSERT INTO lu_occupations_temp VALUES (764, 'telephonist', 'o');
INSERT INTO lu_occupations_temp VALUES (765, 'telephone fault operator', 'o');
INSERT INTO lu_occupations_temp VALUES (766, 'telephony technician', 'o');
INSERT INTO lu_occupations_temp VALUES (767, 'tennis coach', 'o');
INSERT INTO lu_occupations_temp VALUES (768, 'territory manager', 'o');
INSERT INTO lu_occupations_temp VALUES (769, 'testing technician', 'o');
INSERT INTO lu_occupations_temp VALUES (770, 'tiler', 'o');
INSERT INTO lu_occupations_temp VALUES (771, 'tool maker', 'o');
INSERT INTO lu_occupations_temp VALUES (772, 'town planner', 'o');
INSERT INTO lu_occupations_temp VALUES (773, 'tow-truck driver', 'o');
INSERT INTO lu_occupations_temp VALUES (774, 'toymaker', 'o');
INSERT INTO lu_occupations_temp VALUES (775, 'trade assistant', 'o');
INSERT INTO lu_occupations_temp VALUES (776, 'traffic facilitator', 'o');
INSERT INTO lu_occupations_temp VALUES (777, 'train controller', 'o');
INSERT INTO lu_occupations_temp VALUES (778, 'train driver', 'o');
INSERT INTO lu_occupations_temp VALUES (779, 'trainee telecommunications', 'o');
INSERT INTO lu_occupations_temp VALUES (780, 'trainee train driver', 'o');
INSERT INTO lu_occupations_temp VALUES (781, 'trainer advisor', 'o');
INSERT INTO lu_occupations_temp VALUES (782, 'trainer racehorse', 'o');
INSERT INTO lu_occupations_temp VALUES (783, 'training officer', 'o');
INSERT INTO lu_occupations_temp VALUES (784, 'transplant surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (785, 'tree surgeon', 'o');
INSERT INTO lu_occupations_temp VALUES (786, 'truck driver', 'o');
INSERT INTO lu_occupations_temp VALUES (787, 'truck driver/operator', 'o');
INSERT INTO lu_occupations_temp VALUES (788, 'tunnel borer', 'o');
INSERT INTO lu_occupations_temp VALUES (789, 'tutor', 'o');
INSERT INTO lu_occupations_temp VALUES (790, 'tyre fitter', 'o');
INSERT INTO lu_occupations_temp VALUES (791, 'tyre retailer', 'o');
INSERT INTO lu_occupations_temp VALUES (792, 'undermanager', 'o');
INSERT INTO lu_occupations_temp VALUES (793, 'unemployed', 'o');
INSERT INTO lu_occupations_temp VALUES (794, 'union official', 'o');
INSERT INTO lu_occupations_temp VALUES (795, 'university lecturer', 'o');
INSERT INTO lu_occupations_temp VALUES (796, 'university professor', 'o');
INSERT INTO lu_occupations_temp VALUES (797, 'urogynaecologist', 's');
INSERT INTO lu_occupations_temp VALUES (798, 'urological surgeon', 'o');
INSERT INTO lu_occupations_temp VALUES (799, 'urologist', 's');
INSERT INTO lu_occupations_temp VALUES (800, 'urologist & transplant surgeon', 'o');
INSERT INTO lu_occupations_temp VALUES (801, 'urology registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (802, 'uro-oncologist', 'o');
INSERT INTO lu_occupations_temp VALUES (803, 'vascular & endovascular surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (804, 'vascular registrar', 'g');
INSERT INTO lu_occupations_temp VALUES (805, 'vascular surgeon', 's');
INSERT INTO lu_occupations_temp VALUES (806, 'veterinary nurse', 'o');
INSERT INTO lu_occupations_temp VALUES (807, 'waitress', 'o');
INSERT INTO lu_occupations_temp VALUES (808, 'ward clerk', 'o');
INSERT INTO lu_occupations_temp VALUES (809, 'wardsman', 'o');
INSERT INTO lu_occupations_temp VALUES (810, 'wardsperson', 'o');
INSERT INTO lu_occupations_temp VALUES (811, 'water proofer', 'o');
INSERT INTO lu_occupations_temp VALUES (812, 'waterside worker', 'o');
INSERT INTO lu_occupations_temp VALUES (813, 'welder', 'o');
INSERT INTO lu_occupations_temp VALUES (814, 'welfare worker', 'o');
INSERT INTO lu_occupations_temp VALUES (815, 'wholesaler', 'o');
INSERT INTO lu_occupations_temp VALUES (816, 'window dresser', 'o');
INSERT INTO lu_occupations_temp VALUES (817, 'wire worker', 'o');
INSERT INTO lu_occupations_temp VALUES (818, 'workcover assessor', 'o');
INSERT INTO lu_occupations_temp VALUES (819, 'work place trainer', 'o');
INSERT INTO lu_occupations_temp VALUES (820, 'workshop manager', 'o');
INSERT INTO lu_occupations_temp VALUES (821, 'writer', 'o');
INSERT INTO lu_occupations_temp VALUES (822, 'yacht captain', 'o');
INSERT INTO lu_occupations_temp VALUES (823, 'youth worker', 'o');

SELECT pg_catalog.setval('lu_occupations_temp_pk_seq', 824, true);

truncate table db.lu_version;
insert into db.lu_version (lu_major,lu_minor) values (0, 270);
