----------------------------------------------------------------------------------------
--  IAN THE ICPC2 TABLES
--   		ALTER TABLE coding.icpc2_link_keyword_term add constraint "icpc2_link_keyword_term_fk_term_fkey" foreign key (fk_term) references  (pk);
--   		ALTER TABLE coding.icpc2_link_keyword_term add constraint "icpc2_link_keyword_term_fk_keyword_fkey" foreign key (fk_keyword) references  (pk);
-- 
--- *IAN * Special case to consider THE CODING.GENERIC_TERMS NEEDS A PRIMARY KEY
-- 		Someone (not me) either you or horst said this:
-- 		coding.generic_terms does not have a primary key. While it is possible to create a composite primary key constraint (code, coding system),
-- 		the table referring to the foreign key would then also need TWO columns for the constraint. Much better to create a primary key!!
-- 		ALTER TABLE clin_history.health_issue_templates add constraint "health_issue_templates_fk_code_fkey" foreign key (fk_code) references  coding.generic_terms(code);
-- 		ALTER TABLE clin_workcover.visits add constraint "visits_fk_code_fkey" foreign key (fk_code) references   coding.generic_terms(pk);
-- 		ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_provisional_diagnosis_fkey" foreign key (fk_provisional_diagnosis) references  (pk);
-- 		ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_actual_diagnosis_fkey" foreign key (fk_actual_diagnosis) references  (pk);
--
-- IAN      	 This can never be down as fk_row can refer to any table
-- 		ALTER TABLE clin_consult.progressnotes add constraint "progressnotes_fk_row_fkey" foreign key (fk_row) references  (pk);
---------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE clin_mentalhealth.mentalhealth_plan add constraint "mentalhealth_plan_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE clin_history.recreational_drugs add constraint "recreational_drugs_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE contacts.data_employees add constraint "fk_branch_fkey" FOREIGN KEY (fk_branch) REFERENCES contacts.data_branches(pk);
ALTER TABLE clin_vaccination.vaccinations add constraint "vaccinations_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE clin_certificates.medical_certificates add constraint "medical_certificates_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE clin_workcover.claims add constraint "claims_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE clin_workcover.claims add constraint "claims_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_workcover.claims add constraint "claims_fk_occupation_fkey" foreign key (fk_occupation) references common.lu_occupations (pk);
ALTER TABLE blobs.images add constraint "images_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_consult.consult add constraint "consult_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_consult.consult add constraint "consult_fk_patient_fkey" foreign key (fk_patient) references clerical.data_patients (pk);
ALTER TABLE clin_mentalhealth.mentalhealth_plan add constraint "mentalhealth_plan_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_mentalhealth.mentalhealth_plan add constraint "mentalhealth_plan_fk_coding_system_fkey" foreign key (fk_coding_system) references coding.lu_systems (pk);
ALTER TABLE coding.generic_terms add constraint "generic_terms_fk_coding_system_fkey" foreign key (fk_coding_system) references coding.lu_systems (pk);
ALTER TABLE clin_history.past_history add constraint "past_history_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_history.past_history add constraint "past_history_fk_coding_system_fkey" foreign key (fk_coding_system) references coding.lu_systems (pk);
ALTER TABLE clin_procedures.surgical_packs add constraint "surgical_packs_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_procedures.surgical_packs add constraint "surgical_packs_fk_clinic_fkey" foreign key (fk_clinic) references admin.clinics (pk);
ALTER TABLE clin_measurements.patients_defaults add constraint "patients_defaults_fk_patient_fkey" foreign key (fk_patient) references clerical.data_patients (pk);
ALTER TABLE clin_consult.lu_audit_reasons add constraint "lu_audit_reasons_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE chronic_disease_management.patients_with_hba1c_not_diabetic add constraint "patients_with_hba1c_not_diabetic_fk_patient_fkey" foreign key (fk_patient) references clerical.data_patients (pk);
ALTER TABLE admin.link_staff_clinics add constraint "link_staff_clinics_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE admin.link_staff_clinics add constraint "link_staff_clinics_fk_clinic_fkey" foreign key (fk_clinic) references admin.clinics (pk);
ALTER TABLE chronic_disease_management.diabetes_group_allied_health_services add constraint "diabetes_group_allied_health_services_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE chronic_disease_management.diabetes_group_allied_health_services add constraint "diabetes_group_allied_health_services_fk_employee_fkey" foreign key (fk_employee) references contacts.data_employees (pk);
ALTER TABLE chronic_disease_management.diabetes_group_allied_health_services add constraint "diabetes_group_allied_health_services_fk_document_form_fkey" foreign key (fk_document_form) references documents.documents (pk);
ALTER TABLE chronic_disease_management.diabetes_group_allied_health_services add constraint "diabetes_group_allied_health_services_fk_branch_fkey" foreign key (fk_branch) references contacts.data_branches (pk);
ALTER TABLE clin_certificates.medical_certificates add constraint "medical_certificates_fk_coding_system_fkey" foreign key (fk_coding_system) references coding.lu_systems (pk);
ALTER TABLE clin_certificates.medical_certificates add constraint "medical_certificates_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE documents.documents add constraint "documents_fk_staff_destination_fkey" foreign key (fk_staff_destination) references admin.staff (pk);
ALTER TABLE documents.documents add constraint "documents_fk_staff_filed_document_fkey" foreign key (fk_staff_filed_document) references admin.staff (pk);
ALTER TABLE documents.documents add constraint "documents_fk_patient_fkey" foreign key (fk_patient) references clerical.data_patients (pk);
ALTER TABLE clin_history.family_conditions add constraint "family_conditions_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE clin_history.family_conditions add constraint "family_conditions_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_history.family_members add constraint "family_members_fk_occupation_fkey" foreign key (fk_occupation) references common.lu_occupations (pk);
ALTER TABLE clin_measurements.inr_dose_management add constraint "inr_dose_management_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE clin_prescribing.authority_script_number add constraint "authority_script_number_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE admin.clinics add constraint "clinics_fk_branch_fkey" foreign key (fk_branch) references contacts.data_branches (pk);
ALTER TABLE clin_history.occupational_history add constraint "occupational_history_fk_occupation_fkey" foreign key (fk_occupation) references common.lu_occupations (pk);
ALTER TABLE clin_history.occupational_history add constraint "occupational_history_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE clin_history.occupational_history add constraint "occupational_history_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_allergies.allergies add constraint "allergies_fk_coding_system_fkey" foreign key (fk_coding_system) references coding.lu_systems (pk);
ALTER TABLE admin.staff_clinical_toolbar add constraint "staff_clinical_toolbar_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_requests.lu_form_header add constraint "lu_form_header_fk_branch_fkey" foreign key (fk_branch) references contacts.data_branches (pk);
ALTER TABLE clerical.inventory add constraint "inventory_fk_person_purchased_from_fkey" foreign key (fk_person_purchased_from) references contacts.data_persons (pk);
ALTER TABLE clerical.inventory add constraint "inventory_fk_employee_purchased_from_fkey" foreign key (fk_employee_purchased_from) references contacts.data_employees (pk);
ALTER TABLE clerical.inventory add constraint "inventory_fk_branch_purchased_from_fkey" foreign key (fk_branch_purchased_from) references contacts.data_branches (pk);
ALTER TABLE clin_prescribing.prescribed add constraint "prescribed_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_procedures.lu_last_surgical_pack add constraint "lu_last_surgical_pack_fk_clinic_fkey" foreign key (fk_clinic) references admin.clinics (pk);
ALTER TABLE clin_history.social_history add constraint "social_history_fk_progressnote_confidential_fkey" foreign key (fk_progressnote_confidential) references clin_consult.progressnotes (pk);
ALTER TABLE clin_history.social_history add constraint "social_history_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_prescribing.prescribed_for_habits add constraint "prescribed_for_habits_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_recalls.lu_recall_intervals add constraint "lu_recall_intervals_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_procedures.staff_skin_procedure_defaults add constraint "staff_skin_procedure_defaults_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_requests.user_default_type add constraint "user_default_type_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE admin.tips_seen add constraint "tips_seen_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE coding.usr_codes_weighting add constraint "usr_codes_weighting_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE coding.usr_codes_weighting add constraint "usr_codes_weighting_fk_coding_system_fkey" foreign key (fk_coding_system) references coding.lu_systems (pk);
--ALTER TABLE defaults.incoming_message_handling add constraint "incoming_message_handling_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
--ALTER TABLE defaults.incoming_message_handling add constraint "incoming_message_handling_fk_employee_fkey" foreign key (fk_employee) references contacts.data_employees (pk);
--ALTER TABLE defaults.incoming_message_handling add constraint "incoming_message_handling_fk_branch_fkey" foreign key (fk_branch) references contacts.data_branches (pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_branch_fkey" foreign key (fk_branch) references contacts.data_branches (pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_document_fkey" foreign key (fk_document) references documents.documents (pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_pasthistory_fkey" foreign key (fk_pasthistory) references clin_history.past_history (pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_progressnote_user_fkey" foreign key (fk_progressnote_user) references clin_consult.progressnotes (pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clerical.task_component_notes add constraint "task_component_notes_fk_staff_made_note_fkey" foreign key (fk_staff_made_note) references admin.staff (pk);
ALTER TABLE clerical.data_patients add constraint "data_patients_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE admin.clinic_rooms add constraint "clinic_rooms_fk_clinic_fkey" foreign key (fk_clinic) references admin.clinics (pk);
ALTER TABLE clerical.task_components add constraint "task_components_fk_staff_filed_fkey" foreign key (fk_staff_filed) references admin.staff (pk);
ALTER TABLE clerical.task_components add constraint "task_components_fk_staff_allocated_fkey" foreign key (fk_staff_allocated) references admin.staff (pk);
ALTER TABLE clerical.task_components add constraint "task_components_fk_staff_completed_fkey" foreign key (fk_staff_completed) references admin.staff (pk);
ALTER TABLE clerical.task_components add constraint "task_components_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clerical.tasks add constraint "tasks_fk_staff_must_finalise_fkey" foreign key (fk_staff_must_finalise) references admin.staff (pk);
ALTER TABLE clerical.tasks add constraint "tasks_fk_staff_finalised_task_fkey" foreign key (fk_staff_finalised_task) references admin.staff (pk);
ALTER TABLE clerical.tasks add constraint "tasks_fk_staff_filed_task_fkey" foreign key (fk_staff_filed_task) references admin.staff (pk);
ALTER TABLE documents.observations add constraint "observations_fk_document_fkey" foreign key (fk_document) references documents.documents (pk);
ALTER TABLE clin_recalls.sent add constraint "sent_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_consult.lu_progressnote_templates add constraint "lu_progressnote_templates_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_mentalhealth.team_care_members add constraint "team_care_members_fk_branch_fkey" foreign key (fk_branch) references contacts.data_branches (pk);
ALTER TABLE clin_mentalhealth.team_care_members add constraint "team_care_members_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE clin_mentalhealth.team_care_members add constraint "team_care_members_fk_employee_fkey" foreign key (fk_employee) references contacts.data_employees (pk);
ALTER TABLE clerical.bookings add constraint "bookings_fk_clinic_fkey" foreign key (fk_clinic) references admin.clinics (pk);
ALTER TABLE clin_certificates.certificate_reasons add constraint "certificate_reasons_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE admin.global_preferences add constraint "global_preferences_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE admin.global_preferences add constraint "global_preferences_fk_clinic_fkey" foreign key (fk_clinic) references admin.clinics (pk);
ALTER TABLE clin_prescribing.instruction_habits add constraint "instruction_habits_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_history.family_links add constraint "family_links_fk_patient_fkey" foreign key (fk_patient) references clerical.data_patients (pk);
ALTER TABLE clin_history.team_care_members add constraint "team_care_members_fk_branch_fkey" foreign key (fk_branch) references contacts.data_branches (pk);
ALTER TABLE clin_history.team_care_members add constraint "team_care_members_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE clin_history.team_care_members add constraint "team_care_members_fk_employee_fkey" foreign key (fk_employee) references contacts.data_employees (pk);
ALTER TABLE clin_history.team_care_members add constraint "team_care_members_fk_document_allied_health_form_fkey" foreign key (fk_document_allied_health_form) references documents.documents (pk);
ALTER TABLE clin_referrals.inclusions add constraint "inclusions_fk_document_fkey" foreign key (fk_document) references documents.documents (pk);
ALTER TABLE admin.staff add constraint "staff_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE contacts.data_persons add constraint "data_persons_fk_occupation_fkey" foreign key (fk_occupation) references common.lu_occupations (pk);
ALTER TABLE documents.signed_off add constraint "signed_off_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE documents.signed_off add constraint "signed_off_fk_document_fkey" foreign key (fk_document) references documents.documents (pk);
ALTER TABLE clin_referrals.referrals add constraint "referrals_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE clin_referrals.referrals add constraint "referrals_fk_branch_fkey" foreign key (fk_branch) references contacts.data_branches (pk);
ALTER TABLE clin_referrals.referrals add constraint "referrals_fk_address_fkey" foreign key (fk_address) references contacts.data_addresses (pk);
ALTER TABLE clin_referrals.referrals add constraint "referrals_fk_employee_fkey" foreign key (fk_employee) references contacts.data_employees (pk);
ALTER TABLE clin_referrals.referrals add constraint "referrals_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_referrals.referrals add constraint "referrals_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE clin_workcover.visits add constraint "visits_fk_coding_system_fkey" foreign key (fk_coding_system) references coding.lu_systems (pk);
ALTER TABLE clin_workcover.visits add constraint "visits_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE clin_workcover.visits add constraint "visits_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_measurements.inr_plan add constraint "inr_plan_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE chronic_disease_management.diabetes_annual_cycle_of_care add constraint "diabetes_annual_cycle_of_care_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_requests.notes add constraint "notes_fk_staff_fkey" foreign key (fk_staff) references admin.staff (pk);
ALTER TABLE clin_procedures.lu_anaesthetic_agent add constraint "lu_anaesthetic_agent_fk_lu_route_administration_fkey" foreign key (fk_lu_route_administration) references common.lu_route_administration (pk);
ALTER TABLE clin_mentalhealth.mentalhealth_plan add constraint "mentalhealth_plan_fk_lu_risk_to_others_fkey" foreign key (fk_lu_risk_to_others) references clin_mentalhealth.lu_risk_to_others (pk);
ALTER TABLE clin_mentalhealth.mentalhealth_plan add constraint "mentalhealth_plan_fk_lu_plan_type_fkey" foreign key (fk_lu_plan_type) references clin_mentalhealth.lu_plan_type (pk);
ALTER TABLE clin_history.recreational_drugs add constraint "recreational_drugs_fk_lu_route_administration_fkey" foreign key (fk_lu_route_administration) references common.lu_route_administration (pk);
ALTER TABLE clin_history.recreational_drugs add constraint "recreational_drugs_fk_lu_substance_frequency_fkey" foreign key (fk_lu_substance_frequency) references common.lu_units (pk);
ALTER TABLE clin_history.recreational_drugs add constraint "recreational_drugs_fk_lu_substance_amount_units_fkey" foreign key (fk_lu_substance_amount_units) references common.lu_units (pk);
ALTER TABLE clin_history.team_care_members add constraint "team_care_members_fk_team_care_arrangement_fkey" foreign key (fk_team_care_arrangement) references clin_history.team_care_arrangements (pk);
ALTER TABLE clin_pregnancy.ante_natal_care_summary add constraint "ante_natal_care_summary_fk_subreligion_fkey" foreign key (fk_subreligion) references common.lu_sub_religions (pk);
ALTER TABLE clin_pregnancy.ante_natal_care_summary add constraint "ante_natal_care_summary_fk_religion_fkey" foreign key (fk_religion) references common.lu_religions (pk);
ALTER TABLE clin_pregnancy.pregnancies add constraint "pregnancies_fk_lu_placenta_position_fkey" foreign key (fk_lu_placenta_position) references clin_pregnancy.lu_placenta_position (pk);
ALTER TABLE clin_pregnancy.pregnancies add constraint "pregnancies_fk_lu_contraception_method_fkey" foreign key (fk_lu_contraception_method) references clin_pregnancy.lu_contraception_methods (pk);
ALTER TABLE clin_measurements.patients_defaults add constraint "patients_defaults_fk_lu_type_fkey" foreign key (fk_lu_type) references clin_measurements.lu_type (pk);
ALTER TABLE clin_requests.link_forms_requests_requests_results add constraint "link_forms_requests_requests_results_fk_forms_requests_fkey" foreign key (fk_forms_requests) references clin_requests.forms_requests (pk);
ALTER TABLE contacts.data_persons add constraint "data_persons_fk_sex_fkey" foreign key (fk_sex) references contacts.lu_sex (pk);
ALTER TABLE contacts.data_persons add constraint "data_persons_fk_marital_fkey" foreign key (fk_marital) references contacts.lu_marital (pk);
ALTER TABLE contacts.data_persons add constraint "data_persons_fk_title_fkey" foreign key (fk_title) references contacts.lu_title (pk);
ALTER TABLE clin_requests.lu_requests add constraint "lu_requests_fk_laterality_fkey" foreign key (fk_laterality) references common.lu_laterality (pk);
ALTER TABLE clin_mentalhealth.k10_results add constraint "k10_results_fk_lu_k10_component_fkey" foreign key (fk_lu_k10_component) references clin_mentalhealth.lu_k10_components (pk);
ALTER TABLE clin_recalls.lu_templates add constraint "lu_templates_fk_lu_appointment_length_fkey" foreign key (fk_lu_appointment_length) references common.lu_appointment_length (pk);
ALTER TABLE clin_certificates.medical_certificates add constraint "medical_certificates_fk_lu_fitness_fkey" foreign key (fk_lu_fitness) references clin_certificates.lu_fitness (pk);
ALTER TABLE clin_certificates.medical_certificates add constraint "medical_certificates_fk_lu_illness_temporality_fkey" foreign key (fk_lu_illness_temporality) references clin_certificates.lu_illness_temporality (pk);
ALTER TABLE documents.documents add constraint "documents_fk_unmatched_patient_fkey" foreign key (fk_unmatched_patient) references clerical.data_patients (pk);
ALTER TABLE documents.documents add constraint "documents_fk_sending_entity_fkey" foreign key (fk_sending_entity) references documents.sending_entities (pk);
ALTER TABLE documents.documents add constraint "documents_fk_lu_request_type_fkey" foreign key (fk_lu_request_type) references clin_requests.lu_request_type (pk);
ALTER TABLE documents.documents add constraint "documents_fk_lu_display_as_fkey" foreign key (fk_lu_display_as) references documents.lu_display_as (pk);
ALTER TABLE documents.documents add constraint "documents_fk_lu_urgency_fkey" foreign key (fk_lu_urgency) references common.lu_urgency (pk);
ALTER TABLE documents.documents add constraint "documents_fk_referral_fkey" foreign key (fk_referral) references clin_referrals.referrals (pk);
ALTER TABLE clin_history.family_conditions add constraint "family_conditions_fk_member_fkey" foreign key (fk_member) references clin_history.family_members (pk);
alter table common.lu_countries add constraint code_unique unique  (country_code);
ALTER TABLE clin_history.family_members add constraint "family_members_fk_country_birth_fkey" foreign key (fk_country_birth) references common.lu_countries (country_code);
ALTER TABLE clin_history.family_members add constraint "family_members_fk_relationship_fkey" foreign key (fk_relationship) references common.lu_family_relationships (pk);
ALTER TABLE clin_requests.request_providers add constraint "request_providers_fk_lu_request_type_fkey" foreign key (fk_lu_request_type) references clin_requests.lu_request_type (pk);
ALTER TABLE coding.lu_icpc2_plain_language_mapper add constraint "lu_icpc2_plain_language_mapper_fk_icpc2_term_fkey" foreign key (fk_icpc2_term) references   coding.icpc2_terms  (pk);
ALTER TABLE clerical.lu_inventory_items add constraint "lu_inventory_items_fk_lu_inventory_category_fkey" foreign key (fk_lu_inventory_category) references clerical.lu_inventory_categories (pk);
ALTER TABLE clin_requests.notes add constraint "notes_fk_lu_type_fkey" foreign key (fk_lu_type) references clin_requests.lu_request_type (pk);
ALTER TABLE clin_procedures.link_images_procedures add constraint "link_images_procedures_fk_image_fkey" foreign key (fk_image) references blobs.images (pk);
ALTER TABLE clin_procedures.link_images_procedures add constraint "link_images_procedures_fk_procedure_fkey" foreign key (fk_procedure) references  clin_procedures.skin_procedures (pk);
ALTER TABLE clin_referrals.referrals add constraint "referrals_fk_type_fkey" foreign key (fk_type) references clin_referrals.lu_type (pk);
ALTER TABLE clin_referrals.referrals add constraint "referrals_fk_lu_urgency_fkey" foreign key (fk_lu_urgency) references clin_referrals.lu_urgency (pk);
ALTER TABLE admin.staff add constraint "staff_fk_lu_staff_type_fkey" foreign key (fk_lu_staff_type) references   admin.lu_staff_type (pk);
ALTER TABLE admin.staff add constraint "staff_fk_role_fkey" foreign key (fk_role) references   admin.lu_staff_roles (pk);
ALTER TABLE admin.staff add constraint "staff_fk_status_fkey" foreign key (fk_status) references  admin.lu_staff_status (pk);
ALTER TABLE clin_procedures.lu_suture_type add constraint "lu_suture_type_fk_lu_site_fkey" foreign key (fk_lu_site) references  clin_procedures.lu_suture_site (pk);
ALTER TABLE clin_history.family_links add constraint "family_links_fk_member_fkey" foreign key (fk_member) references clin_history.family_members (pk);
ALTER TABLE clin_prescribing.instruction_habits add constraint "instruction_habits_fk_instruction_fkey" foreign key (fk_instruction) references  clin_prescribing.instructions (pk);
ALTER TABLE clin_mentalhealth.team_care_members add constraint "team_care_members_fk_organisation_fkey" foreign key (fk_organisation) references contacts.data_organisations (pk);
ALTER TABLE documents.sending_entities add constraint "sending_entities_fk_lu_message_display_style_fkey" foreign key (fk_lu_message_display_style) references documents.lu_message_display_style (pk);
ALTER TABLE documents.sending_entities add constraint "sending_entities_fk_lu_message_standard_fkey" foreign key (fk_lu_message_standard) references  documents.lu_message_standard (pk);
ALTER TABLE clin_vaccination.lu_schedules add constraint "lu_schedules_fk_season_fkey" foreign key (fk_season) references common.lu_seasons (pk);
ALTER TABLE clin_mentalhealth.team_care_members add constraint "team_care_members_fk_plan_fkey" foreign key (fk_plan) references clin_mentalhealth.mentalhealth_plan (pk);
ALTER TABLE clin_recalls.sent add constraint "sent_fk_recall_fkey" foreign key (fk_recall) references  clin_recalls.recalls(pk);
ALTER TABLE clin_recalls.sent add constraint "sent_fk_contact_method_fkey" foreign key (fk_contact_method) references  contacts.lu_contact_type(pk);
UPDATE  clin_recalls.recalls set fk_interval_unit=NULL where fk_interval_unit=0;
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_interval_unit_fkey" foreign key (fk_interval_unit) references  common.lu_units(pk);
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_contact_method_fkey" foreign key (fk_contact_method) references  contacts.lu_contact_type(pk);
UPDATE clin_recalls.recalls SET fk_appointment_length=3 where fk_appointment_length>3;
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_appointment_length_fkey" foreign key (fk_appointment_length) references common.lu_appointment_length(pk);
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_urgency_fkey" foreign key (fk_urgency) references common.lu_urgency(pk);
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_sent_fkey" foreign key (fk_sent) references clin_recalls.sent(pk);
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_template_fkey" foreign key (fk_template) references clin_recalls.lu_templates(pk);
ALTER TABLE clin_procedures.staff_skin_procedure_defaults add constraint "staff_skin_procedure_defaults_fk_lu_procedure_type_fkey" foreign key (fk_lu_procedure_type) references clin_procedures.lu_procedure_type(pk);
ALTER TABLE clin_procedures.staff_skin_procedure_defaults add constraint "staff_skin_procedure_defaults_fk_lu_anaesthetic_agent_fkey" foreign key (fk_lu_anaesthetic_agent) references clin_procedures.lu_anaesthetic_agent(pk);
ALTER TABLE clin_requests.user_default_type add constraint "user_default_type_fk_lu_type_fkey" foreign key (fk_lu_type) references  clin_requests.lu_request_type(pk);
ALTER TABLE admin.staff_clinical_toolbar add constraint "staff_clinical_toolbar_fk_module_fkey" foreign key (fk_module) references  admin.lu_clinical_modules(pk);
--ALTER TABLE defaults.incoming_message_handling add constraint "incoming_message_handling_fk_lu_message_standard_fkey" foreign key (fk_lu_message_standard) references defaults.lu_message_standard(pk);
--ALTER TABLE defaults.incoming_message_handling add constraint "incoming_message_handling_fk_lu_message_display_style_fkey" foreign key (fk_lu_message_display_style) references defaults.lu_message_display_style(pk);
ALTER TABLE clin_measurements.lu_type add constraint "lu_type_fk_unit_fkey" foreign key (fk_unit) references common.lu_units(pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_lu_repair_type_fkey" foreign key (fk_lu_repair_type) references  clin_procedures.lu_repair_type(pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_lu_anaesthetic_agent_fkey" foreign key (fk_lu_anaesthetic_agent) references clin_procedures.lu_anaesthetic_agent(pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_form_fkey" foreign key (fk_form) references clin_requests.forms(pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_lu_procedure_type_fkey" foreign key (fk_lu_procedure_type) references clin_procedures.lu_procedure_type(pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_lu_skin_preparation_fkey" foreign key (fk_lu_skin_preparation) references clin_procedures.lu_skin_preparation(pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_lu_anterior_posterior_fkey" foreign key (fk_lu_anterior_posterior) references common.lu_anatomical_localisation(pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_skin_suture_fkey" foreign key (fk_skin_suture) references  clin_procedures.lu_suture_type(pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_lu_lateralisation_fkey" foreign key (fk_lu_lateralisation) references  common.lu_laterality(pk);
ALTER TABLE clerical.task_component_notes add constraint "task_component_notes_fk_task_component_fkey" foreign key (fk_task_component) references  clerical.task_components(pk);
ALTER TABLE clerical.data_patients add constraint "data_patients_fk_payer_person_fkey" foreign key (fk_payer_person) references  contacts.data_persons(pk);
ALTER TABLE clerical.data_patients add constraint "data_patients_fk_lu_default_billing_level_fkey" foreign key (fk_lu_default_billing_level) references billing.lu_default_billing_level(pk);
ALTER TABLE clerical.data_patients add constraint "data_patients_fk_doctor_fkey" foreign key (fk_doctor) references admin.staff(pk);
ALTER TABLE clerical.data_patients add constraint "data_patients_fk_lu_private_health_fund_fkey" foreign key (fk_lu_private_health_fund) references clerical.lu_private_health_funds(pk);
ALTER TABLE clerical.data_patients add constraint "data_patients_fk_next_of_kin_fkey" foreign key (fk_next_of_kin) references  contacts.data_persons(pk);
ALTER TABLE clerical.data_patients add constraint "data_patients_fk_payer_fkey" foreign key (fk_payer_person) references  contacts.data_persons(pk);
ALTER TABLE clerical.data_patients add constraint "data_patients_fk_payer_branch_fkey" foreign key (fk_payer_branch) references  contacts.data_branches(pk);
ALTER TABLE clin_recalls.links_forms add constraint "links_forms_fk_recall_fkey" foreign key (fk_recall) references clin_recalls.recalls(pk);
ALTER TABLE clin_recalls.links_forms add constraint "links_forms_fk_form_fkey" foreign key (fk_form) references clin_recalls.forms(pk);
ALTER TABLE clerical.task_components add constraint "task_components_fk_role_fkey" foreign key (fk_role) references admin.lu_staff_roles(pk);
ALTER TABLE clerical.task_components add constraint "task_components_fk_urgency_fkey" foreign key (fk_urgency) references  common.lu_urgency(pk);
ALTER TABLE clerical.task_components add constraint "task_components_fk_task_fkey" foreign key (fk_task) references clerical.tasks(pk);
ALTER TABLE clerical.tasks add constraint "tasks_fk_role_can_finalise_fkey" foreign key (fk_role_can_finalise) references  admin.lu_staff_roles(pk);
ALTER TABLE clerical.tasks add constraint "tasks_fk_row_fkey" foreign key (fk_row) references  documents.documents(pk);
ALTER TABLE clin_vaccination.vaccinations add constraint "vaccinations_fk_site_fkey" foreign key (fk_site) references common.lu_site_administration (pk);
ALTER TABLE clin_prescribing.prescribed add constraint "prescribed_fk_progress_note_fkey" foreign key (fk_progress_note) references clin_consult.progressnotes (pk);
ALTER TABLE clin_prescribing.prescribed add constraint "prescribed_fk_prescribed_for_fkey" foreign key (fk_prescribed_for) references clin_prescribing.prescribed_for (pk);
ALTER TABLE clin_prescribing.prescribed add constraint "prescribed_fk_instruction_fkey" foreign key (fk_instruction) references clin_prescribing.instructions (pk);
ALTER TABLE contacts.data_persons add constraint "data_persons_fk_ethnicity_fkey" foreign key (fk_ethnicity) references common.lu_ethnicity (pk);
ALTER TABLE clin_consult.progressnotes add constraint "progressnotes_fk_section_fkey" foreign key (fk_section) references clin_consult.lu_progressnotes_sections (pk);
ALTER TABLE clerical.data_family_members add constraint "data_family_members_fk_family_fkey" foreign key (fk_family) references clerical.data_families (pk);
ALTER TABLE clin_workcover.visits add constraint "visits_fk_lu_visit_type_fkey" foreign key (fk_lu_visit_type) references  clin_workcover.lu_visit_type(pk);
ALTER TABLE clin_workcover.visits add constraint "visits_fk_caused_by_employment_fkey" foreign key (fk_caused_by_employment) references  clin_workcover.lu_caused_by_employment(pk);
ALTER TABLE common.lu_sub_religions add constraint "lu_sub_religions_fk_religion_fkey" foreign key (fk_religion) references  common.lu_religions(pk);
ALTER TABLE clin_mentalhealth.clozapine_record add constraint "clozapine_record_fk_observation_neutrophil_count_fkey" foreign key (fk_observation_neutrophil_count) references  documents.observations (pk);
ALTER TABLE clin_mentalhealth.clozapine_record add constraint "clozapine_record_fk_observation_white_cell_count_fkey" foreign key (fk_observation_white_cell_count) references documents.observations  (pk);
ALTER TABLE clerical.inventory add constraint "inventory_fk_image_fkey" foreign key (fk_image) references blobs.images(pk);
ALTER TABLE clin_history.occupations_exposures add constraint "occupations_exposures_fk_occupational_exposure_fkey" foreign key (fk_lu_occupational_exposure) references  clin_history.lu_occupational_exposures(pk);
ALTER TABLE clin_measurements.measurements add constraint "measurements_fk_type_fkey" foreign key (fk_type) references clin_measurements.lu_type(pk);
ALTER TABLE clin_vaccination.lu_vaccines add constraint "lu_vaccines_fk_route_fkey" foreign key (fk_route) references common.lu_route_administration(pk);
ALTER TABLE clin_vaccination.lu_vaccines add constraint "lu_vaccines_fk_form_fkey" foreign key (fk_form) references clin_vaccination.lu_formulation(pk);
ALTER TABLE clin_procedures.staff_skin_procedure_defaults add constraint "staff_skin_procedure_defaults_fk_user_provider_defaults_fkey" foreign key (fk_user_provider_defaults) references clin_requests.user_provider_defaults (pk);
ALTER TABLE clin_procedures.staff_skin_procedure_defaults add constraint "staff_skin_procedure_defaults_fk_lu_skin_preparation_fkey" foreign key (fk_lu_skin_preparation) references clin_procedures.lu_skin_preparation (pk);
ALTER TABLE clin_procedures.staff_skin_procedure_defaults add constraint "staff_skin_procedure_defaults_fk_lu_repair_type_fkey" foreign key (fk_lu_repair_type) references clin_procedures.lu_repair_type (pk);
ALTER TABLE clin_vaccination.lu_vaccines add constraint "lu_vaccines_fk_description_fkey" foreign key (fk_description) references  clin_vaccination.lu_descriptions(pk); 
ALTER TABLE clin_history.social_history add constraint "social_history_fk_responsible_person_fkey" foreign key (fk_responsible_person) references  contacts.data_persons(pk);
ALTER TABLE clin_referrals.inclusions add constraint "inclusions_fk_referral_fkey" foreign key (fk_referral) references clin_referrals.referrals(pk);
ALTER TABLE import_export.lu_demographics_field_templates add constraint "lu_demographics_field_templates_fk_source_program_fkey" foreign key (fk_source_program) references import_export.lu_source_program(pk);
ALTER TABLE clin_prescribing.prescribed_for_habits add constraint "prescribed_for_habits_fk_prescribed_for_fkey" foreign key (fk_prescribed_for) references  clin_prescribing.prescribed_for(pk);
ALTER TABLE clin_recalls.lu_recall_intervals add constraint "lu_recall_intervals_fk_reason_fkey" foreign key (fk_reason) references  clin_recalls.lu_reasons (pk);
ALTER TABLE clerical.bookings add constraint "bookings_fk_lu_appointment_status_fkey" foreign key (fk_lu_appointment_status) references clerical.lu_appointment_status(pk); 
ALTER TABLE clerical.bookings add constraint "bookings_fk_lu_reason_not_billed_fkey" foreign key (fk_lu_reason_not_billed) references billing.lu_reasons_not_billed(pk);
ALTER TABLE clerical.bookings add constraint "bookings_fk_lu_appointment_icon_fkey" foreign key (fk_lu_appointment_icon) references clerical.lu_appointment_icons(pk);
-- ALTER TABLE defaults.incoming_message_handling add constraint "incoming_message_handling_fk_blob_fkey" foreign key (fk_blob) references  blobs.blobs(pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_subcutaneous_suture_fkey" foreign key (fk_subcutaneous_suture) references  clin_procedures.lu_suture_type (pk);
ALTER TABLE clin_procedures.staff_skin_procedure_defaults add constraint "staff_skin_procedure_defaults_fk_subcutaneous_suture_fkey" foreign key (fk_subcutaneous_suture) references clin_procedures.lu_suture_type (pk);
ALTER TABLE clin_procedures.staff_skin_procedure_defaults add constraint "staff_skin_procedure_defaults_fk_skin_suture_fkey" foreign key (fk_skin_suture) references clin_procedures.lu_suture_type (pk);
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_reason_fkey" foreign key (fk_reason) references  clin_recalls.lu_reasons(pk);
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_status_fkey" foreign key (fk_status) references clin_recalls.lu_status(pk);
ALTER TABLE clin_recalls.lu_recall_intervals add constraint "lu_recall_intervals_fk_interval_unit_fkey" foreign key (fk_interval_unit) references common.lu_units (pk);
ALTER TABLE clin_consult.consult add constraint "consult_fk_type_fkey" foreign key (fk_type) references clin_consult.lu_consult_type (pk);
ALTER table clin_vaccination.vaccinations add constraint "vaccinations_fk_laterality_fkey" foreign key (fk_laterality) references common.lu_laterality (pk);
ALTER TABLE clin_history.past_history add constraint "past_history_fk_laterality_fkey" foreign key (fk_laterality) references common.lu_laterality (pk);
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_recalls.recalls add constraint "recalls_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE contacts.data_persons add constraint "data_persons_fk_image_fkey" foreign key (fk_image) references blobs.images (pk);
ALTER TABLE clin_mentalhealth.k10_results add constraint "k10_results_fk_plan_fkey" foreign key (fk_plan) references clin_mentalhealth.mentalhealth_plan (pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_progressnote_auto_fkey" foreign key (fk_progressnote_auto) references clin_consult.progressnotes (pk);
ALTER TABLE clin_requests.lu_link_provider_user_requests add constraint "lu_link_provider_user_requests_fk_lu_request_fkey" foreign key (fk_lu_request) references clin_requests.lu_requests(pk);
ALTER TABLE clin_workcover.visits add constraint "visits_fk_claim_fkey" foreign key (fk_claim) references  clin_workcover.claims(pk);
ALTER TABLE clin_procedures.skin_procedures add constraint "skin_procedures_fk_lu_site_fkey" foreign key (fk_lu_site) references   common.lu_anatomical_site (pk);
ALTER TABLE clin_measurements.measurements add constraint "measurements_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE clin_history.social_history add constraint "social_history_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE clin_consult.progressnotes add constraint "progressnotes_fk_consult_fkey" foreign key (fk_consult) references clin_consult.consult (pk);
ALTER TABLE contacts.data_persons add constraint "data_persons_fk_language_fkey" foreign key (fk_language) references common.lu_languages (pk);
ALTER TABLE clin_prescribing.prescribed_for_habits add constraint "prescribed_for_habits_fk_generic_product_fkey" foreign key (fk_generic_product) references drugs.product (pk);
ALTER TABLE clerical.data_family_members add constraint "data_family_members_fk_patient_fkey" foreign key (fk_patient) references clerical.data_patients (pk);
alter table drugs.brand add constraint "brand_fk_company_fkey" foreign key (fk_company) references drugs.company (code);
ALTER TABLE clin_requests.request_providers add constraint "request_providers_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE clin_requests.request_providers add constraint "request_providers_fk_employee_fkey" foreign key (fk_employee) references contacts.data_employees (pk);
ALTER TABLE clin_requests.request_providers add constraint "request_providers_fk_default_branch_fkey" foreign key (fk_default_branch) references contacts.data_branches (pk);
ALTER TABLE clin_requests.request_providers add constraint "request_providers_fk_headoffice_branch_fkey" foreign key (fk_headoffice_branch) references contacts.data_branches (pk);
ALTER TABLE documents.sending_entities add constraint "sending_entities_fk_lu_request_type_fkey" foreign key (fk_lu_request_type) references  clin_requests.lu_request_type (pk); 
ALTER TABLE documents.sending_entities add constraint "sending_entities_fk_branch_fkey" foreign key (fk_branch) references contacts.data_branches (pk);
ALTER TABLE documents.sending_entities add constraint "sending_entities_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE documents.documents add constraint "documents_fk_request_fkey" foreign key (fk_request) references clin_requests.forms (pk);
ALTER TABLE documents.documents add constraint "documents_fk_unmatched_staff_fkey" foreign key (fk_unmatched_staff) references  documents.unmatched_staff (pk);
ALTER TABLE chronic_disease_management.diabetes_group_allied_health_services add constraint "diabetes_group_allied_health_services_fk_document_history_items_fkey" foreign key (fk_document_history_items) references documents.documents (pk);
ALTER TABLE contacts.lu_misspelt_towns add constraint "lu_misspelt_towns_fk_town_fkey" foreign key (fk_town) references contacts.lu_towns (pk);
ALTER TABLE contacts.links_employees_comms add constraint "links_employees_comms_fk_comm_fkey" foreign key (fk_comm) references contacts.data_communications (pk);
ALTER TABLE contacts.links_employees_comms add constraint "links_employees_comms_fk_employee_fkey" foreign key (fk_employee) references contacts.data_employees (pk);
ALTER TABLE contacts.links_persons_comms add constraint "links_persons_comms_fk_comm_fkey" foreign key (fk_comm) references  contacts.data_communications (pk);
ALTER TABLE clin_prescribing.prescribed add constraint "prescribed_fk_medication_fkey" foreign key (fk_medication) references  clin_prescribing.medications(pk);
ALTER TABLE contacts.data_addresses add constraint "data_addresses_fk_lu_address_type_fkey" foreign key (fk_lu_address_type) references  contacts.lu_address_types(pk);
ALTER TABLE contacts.links_persons_addresses add constraint "links_persons_addresses_fk_address_fkey" foreign key (fk_address) references contacts.data_addresses (pk);
ALTER TABLE contacts.data_branches add constraint "data_branches_fk_category_fkey" foreign key (fk_category) references  contacts.lu_categories(pk);
ALTER TABLE contacts.data_branches add constraint "data_branches_fk_address_fkey" foreign key (fk_address) references contacts.data_addresses (pk);
ALTER TABLE contacts.data_branches add constraint "data_branches_fk_organisation_fkey" foreign key (fk_organisation) references  contacts.data_organisations(pk);
ALTER TABLE clin_history.past_history add constraint "past_history_fk_progressnote_fkey" foreign key (fk_progressnote) references clin_consult.progressnotes (pk);
ALTER TABLE contacts.data_employees add constraint "data_employees_fk_status_fkey" foreign key (fk_status) references  contacts.lu_employee_status (pk);
ALTER TABLE contacts.data_employees add constraint "data_employees_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE contacts.data_employees add constraint "data_employees_fk_occupation_fkey" foreign key (fk_occupation) references common.lu_occupations (pk);
ALTER TABLE documents.sending_entities add constraint "sending_entities_fk_employee_fkey" foreign key (fk_employee) references contacts.data_employees (pk);
ALTER TABLE contacts.data_communications add constraint "data_communications_fk_type_fkey" foreign key (fk_type) references  contacts.lu_contact_type (pk);
ALTER TABLE contacts.links_persons_addresses add constraint "links_persons_addresses_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE contacts.data_addresses add constraint "data_addresses_fk_town_fkey" foreign key (fk_town) references contacts.lu_towns (pk);
ALTER TABLE clin_prescribing.instruction_habits add constraint "instruction_habits_fk_generic_product_fkey" foreign key (fk_generic_product) references drugs.product (pk);
ALTER TABLE contacts.links_persons_comms add constraint "links_persons_comms_fk_person_fkey" foreign key (fk_person) references contacts.data_persons (pk);
ALTER TABLE clin_prescribing.medications add constraint "medications_fk_generic_product_fkey" foreign key (fk_generic_product) references drugs.product (pk);
ALTER TABLE clin_prescribing.prescribed add constraint "prescribed_fk_brand_fkey" foreign key (fk_brand) references  drugs.brand(pk);
ALTER TABLE clin_measurements.inr_dose_management add constraint "inr_dose_management_fk_observation_fkey" foreign key (fk_observation) references documents.observations (pk);
ALTER TABLE clin_history.occupations_exposures add constraint "occupations_exposures_fk_occupational_history_fkey" foreign key (fk_occupational_history) references clin_history.occupational_history (pk);
ALTER TABLE clin_workcover.claims add constraint "claims_fk_branch_fkey" foreign key (fk_branch) references contacts.data_branches (pk);
-- ALTER TABLE clerical.bookings add constraint "bookings_fk_patient_fkey" foreign key (fk_patient) references clerical.data_patients (pk);

update db.lu_version set lu_minor = 476;