' Gambas module file

' Gambas class file

' Copyright (C) 2008-2016 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'
' DATABASE calls for staff meeting stuff
'----------------------------------------------------------------------

Public Function Issues_Get() As Collection
   
  Return modDBConnect.exec_query_collection("Select * from clerical.vwStaffMeetingIssues where finalised is false and deleted is false order by date_logged") 
   
End
