' Gambas module file

' general interface routines to appointments database
' Copyright (C) 2008-2011 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------
Public Function Patients_Seen(date_seen As String, Optional fk_staff As Integer = 0, bShowAudits As Boolean = False) As Collection 

   Dim sql As String

   sql = "Select * from clin_consult.vwPatientConsults WHERE date(consult_date) = '" & date_seen & "'::date "
   If fk_staff Then
      sql &= " AND fk_staff = " & fk_staff 
   End If
   If bShowAudits = False Then
      sql &= " AND linked_table is null" 
   Endif
   Return modDBConnect.exec_query_collection(sql)
   
End

'''List sessions for a given user
Public Function Sessions_List(fk_staff As Integer) As Collection

  Return modDBConnect.exec_query_row("select * from clerical.sessions where fk_staff =  " & fk_staff)
   
End

'''Save a session
Public Sub Sessions_Save(row As CRow)
   
  row.Save("clerical.sessions", "pk") 
   
End

'''Delete session
Public Sub Sessions_Delete(row As CRow)
   
  modDBConnect.exec_query("delete from clerical.sessions where pk = " & row!pk) 
   
End

'''Lists all appointments on a given day for given doctor<br/>
'''day1: the date, set to Null for all time (returns max 500 results)<br/>
'''fk_staff: the staff member, -1 for all staff<br/>
'''timeunit: the unit to compare by, "day" for appointments that day, "week" for the whole week, "month", etc.
Public Function Appt_List(Optional day1 As Date = Null, fk_staff As Integer = -1, timeunit As String = "day") As Collection
   
   Dim sql As String

   sql = ""
   If Not IsNull(day1) Then
     sql = Format$(day1, "yyyy-mm-dd")
     sql = Subst$("date_trunc('&2',begin) = date_trunc('&2',timestamp '&1')", sql, timeunit)
   Endif
   If fk_staff <> -1 Then
     If sql <> "" Then sql &= " and "
     sql &= "fk_staff = " & fk_staff
   Endif
   If sql = "" Then sql = "1=1"
   sql = "select * from clerical.bookings where " & sql & " order by begin limit 500"
   Return modDBConnect.exec_query_row(sql)
   
End

Public Function Appointments_GetWeek(start_date As Date, fk_staff As Integer, fk_clinic As Integer) As Collection
   
  Dim sql As String
  'date_trunc('week', begin) =date_trunc( 'week', &1)
  sql = "Select * from clerical.vwAppointments where "
  sql &= "date_trunc('week', begin) =date_trunc('week','" & Now & "')"
  Return modDBConnect.exec_query_collection(sql) 
   
End
Public Function Appointment_icons_get() As Collection
   
  Return modDBConnect.exec_query_collection("Select * from clerical.lu_appointment_icons") 
   
End

Public Function Appointments_GetDay(appointment_date As Date, fk_staff As Integer, fk_clinic As Integer) As Collection
   
  Dim sql As String
  sql = "Select * from clerical.vwAppointments where date_trunc('day', begin) = '" & Format$(appointment_date, "dd/mm/yyyy") & "'" 
  sql &= " AND fk_staff = " & fk_staff & " AND fk_clinic = " & fk_clinic
  Return modDBConnect.exec_query_collection(sql)
End


'''Save an appointment
Public Sub Appointment_Save(row As CRow)
   
  row.Save("clerical.bookings", "pk") 
   
End

'''Mark appointment as deleted
Public Sub Apptment_Delete(row As Crow)
   
  modDBConnect.exec_query("update clerical.bookings set deleted='t' where pk = " & row!pk) 
   
End
