' Gambas module file
' Copyright (C) 2008-2011 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------
Public Function Patients_Seen(date_seen As String, Optional fk_staff As Integer = 0, bShowAudits As Boolean = False) As Collection 

   Dim sql As String

   sql = "Select * from clin_consult.vwPatientConsults WHERE date(consult_date) = '" & date_seen & "'::date "
   If fk_staff Then
      sql &= " AND fk_staff = " & fk_staff 
   End If
   If bShowAudits = False Then
      sql &= " AND linked_table is null" 
   Endif
   Return modDBConnect.exec_query_collection(sql)
   
End
