' Gambas module file

Public Function Descriptors_Get(Optional descriptor As String = "", Optional limit As Integer = 100) As Collection
   
   Dim sql As String
   
   sql = "Select * from clerical.schedule where descriptor ILIKE $$%" & descriptor
   sql &= "%$$ order by cast(mbs_item as int), descriptor LIMIT " & limit
   Return modDBConnect.exec_query_collection(sql)
   
End

Public Function Descriptors_Save(old_data As Collection, pk_descriptor As Integer, new_data As Collection)
   
   If pk_descriptor = -1 Then
      
   Else
      modDBConnect.update("clerical.schedule", old_data[pk_descriptor], new_data)
   End If  
   
End

Public Function Fee_types_Get() As Collection
   
  Return modDBConnect.exec_query_collection("Select * from clerical.lu_billing_type") 
   
End

Public Function Descriptors_Brief_Get(searchtext As String, Optional limit As Integer = 100) As Collection 
   Dim sql As String
   
   sql = "Select * from clerical.schedule where descriptor_brief ILIKE $$%" & searchtext
   sql &= "%$$ order by cast(mbs_item as int), descriptor LIMIT " & limit
   Return modDBConnect.exec_query_collection(sql)

End

Public Function Items_Get(item As String, fk_lu_billing_type As Integer) As Collection
   '---------------------------------------------
   'Gets list of item numbers and associated fees
   '--------------------------------------------- 

   Return modDBConnect.exec_query_collection("Select * From clerical.vwFees where mbs_item = $$" & item & "$$ AND fk_lu_billing_type = " & fk_lu_billing_type)
   
End
