' Gambas module file

Public Function Descriptors_Get(Optional descriptor As String = "", ama_mbs_or_both As String = "mbs", Optional limit As Integer = 500) As Collection
   
   Dim sql As String
   Dim searchcomponents As New String[]
   Dim component As String 
 '  searchcomponents = Split(descriptor, ",", "", True)
   
   If InStr(descriptor, ",") Then 
       searchcomponents = Split(Descriptor, ",")
   Else
       searchcomponents = New String[0] 
       searchcomponents.Add(descriptor, 0)
   End If    
   
   Print searchcomponents
   sql = "Select * from clerical.schedule where  " 'descriptor ILIKE $$%" & descriptor & "%$$ "
   For Each component In searchcomponents
     sql &= "descriptor ILIKE $$%" & component & "%$$ " & " AND "
   Next
   sql = Left(sql, Len(sql) - 4)
   Print sql
   
   ' Select Case ama_mbs_or_both
   '   Case "mbs"
   '       sql &= " AND ama_item is null "
   '       
   '   Case "ama"
   '        " AND ama_item is not null "
   '   Case "both" 
   '      
   ' End Select
   sql &= " order by cast(mbs_item as int), descriptor   LIMIT " & limit
   Return modDBConnect.exec_query_collection(sql)
   
End

Public Function Descriptors_Save(old_data As Collection, pk_descriptor As Integer, new_data As Collection)
   
   If pk_descriptor = -1 Then
      
   Else
      modDBConnect.update("clerical.schedule", old_data[pk_descriptor], new_data)
   End If  
   
End

Public Function Fee_types_Get() As Collection
   
  Return modDBConnect.exec_query_collection("Select * from clerical.lu_billing_type") 
   
End

Public Function Descriptors_Brief_Get(searchtext As String, Optional limit As Integer = 100) As Collection 
   Dim sql As String
   
   sql = "Select * from clerical.schedule where descriptor_brief ILIKE $$%" & searchtext
   sql &= "%$$ order by cast(mbs_item as int), descriptor LIMIT " & limit
   Return modDBConnect.exec_query_collection(sql)

End

Public Function Items_Get(item As String, fk_lu_billing_type As Integer) As Collection
   '---------------------------------------------
   'Gets list of item numbers and associated fees
   '---------------------------------------------
   Dim sItem As String
    
   If fk_lu_billing_type = const.Billingtype_AMA Then
      sItem = "ama_item"
   Else
      sitem = "mbs_item"
   Endif
   Return modDBConnect.exec_query_collection("Select * From clerical.vwFees WHERE " & sItem & " ILIKE $$" & item & "$$")   ' AND fk_lu_billing_type = " & fk_lu_billing_type)
   
End
Public Function Schedule_Search_Query(search As String) As String

  Dim r As Regexp

  r = New Regexp(search, "^[0-9]+$")
  If r.Offset <> -1 Then Return "mbs_item = '" & search & "'"
  r = New Regexp(search, "^[a-z]+[0-9]+$", Regexp.Caseless)
  If r.Offset <> -1 Then Return "ama_item = '" & search & "'"
  ' escape % in search string
  search = Replace$(search, "%", "\\%")
  Return "descriptor ilike $$%" & search & "%$$"

End

Public Function Schedule_Search_Query1(search As String) As String

  Dim r As Regexp

  If search = "" Then Return 
  r = New Regexp(search, "^[0-9]+$")
  If r.Offset <> -1 Then Return "mbs_item"
  r = New Regexp(search, "^[a-z]+[0-9]+$", Regexp.Caseless)
  If r.Offset <> -1 Then Return "ama_item"
  ' escape % in search string
  search = Replace$(search, "%", "\\%")
  Return "descriptor"

End
