' Gambas module file

' Gambas class file

' Copyright (C) 2008-2012 Dr. Richard Terry  rterry@pacific.net.au

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------
' Billing Stuff
'-------------------------------------------------------------------------------

Public Function Veteran_Card_Types_Get() As Collection
   
   Return modDBConnect.exec_query_collection("Select * from clerical.lu_veteran_card_type")
   
End

Public Function Centrelink_Card_Types_Get() As Collection
   
   Return modDBConnect.exec_query_collection("Select * from clerical.lu_centrelink_card_type")
   
End

Public Function Health_Funds_Get() As Collection
   
   Return modDBConnect.exec_query_collection("Select * from clerical.lu_private_health_funds")
   
End

Public Function Billing_Types_Get() As Collection
   
   Return modDBConnect.exec_query_collection("Select * from clerical.lu_billing_type")
   
End

