' Gambas module file

' " (Select count (pk_document) from Documents.vwDocuments where fk_lu_provider_type=contacts.lu_categories.pk "
'   "  and "
'   "       concluded = false and deleted = False  AND fk_staff_destination = 1 "
'   "  ) as total"
'   

Public Function Inbox_Document_Count(fk_staff As Integer) As Result
   '-----------------------------------------------------------------------------------------------
   'IAN FIXME combine me into one clever query  
   'Gets all the different types of documents outstanding, and works out how many in each category
   'note:  fk_lu_provider_type is not null is included because a msh_sending_entity may not have
   'been allocated to a real provider
   '----------------------------------------------------------------------------------------------
   Dim sql As String 
   Dim doc_types As Collection 
   Dim doc_type As Collection 
   Dim final As Collection 
   Dim R As Result 
   sql = "SELECT distinct fk_lu_provider_type as pk_lu_provider_type, provider_type FROM documents.vwdocuments "
         "where concluded = false and deleted = False  AND fk_lu_provider_type is not null AND fk_staff_destination = "
   sql &= fk_staff & " ORDER BY fk_lu_Provider_type "
   doc_types = modDBConnect.exec_query_collection(sql)
   sql = ""
   If doc_types.count Then 
      For Each doc_type In doc_types
           sql &= " Select count(pk_document) as total, ('" & doc_type!provider_type & "'::TEXT) as provider_type " 
           sql &= "From documents.vwDocuments Where concluded = False And deleted = False AND fk_staff_destination = " & fk_staff 
           sql &= " AND fk_lu_provider_type =  " & doc_type!pk_lu_provider_type
           sql &= " UNION "
      Next
      sql = Left(sql, Len(sql) - 6)
      R = modDBConnect.exec_query(sql)  
   End If   
   Return R   
End
Public Sub Staff_Tasks_Get_Notes(fk_task As Integer) As Collection 
   '-----------------------------------------------------------------
   'Gets any notes associated with the staff task
   '-----------------------------------------------------------------
  '  Return modDBConnect.exec_query_collection("Select * from admin.vwTasksNotes where fk_task =  " & fk_task & " ORDER BY date")
   ' Return modDBConnect.exec_query_collection("Select * from clerical.task_component_notes where fk_task_component =  " & fk_component & " ORDER BY date")
   Return modDBConnect.exec_query_collection("Select * from clerical.vwtaskscomponentsnotes where fk_task =  " & fk_task & " ORDER BY date")
   
End
Public Sub Staff_Tasks_Get_Notes_old(fk_task As Integer) As Collection 
   '-----------------------------------------------------------------
   'Gets any notes associated with the staff task
   '-----------------------------------------------------------------
  '  Return modDBConnect.exec_query_collection("Select * from admin.vwTasksNotes where fk_task =  " & fk_task & " ORDER BY date")
    Return modDBConnect.exec_query_collection("Select * from clerical.vwTasksNotes where fk_task =  " & fk_task & " ORDER BY date")
End
Public Sub Staff_Tasks_Get_as_Result(fk_staff As Integer, Optional bOutstanding As Boolean = True) As Result
   '-----------------------------------------------------------------
   'Gets staff tasks, usually outstanding unless doing an audit check
   '-----------------------------------------------------------------
   Dim sql As String
   sql = "Select * from Documents.vwStaffTasks_Documents WHERE fk_staff_allocated = " & fk_staff
   sql &= " AND date_finalised is null ORDER BY fk_urgency"
   Return modDBConnect.exec_query(sql)
  
End

Public Sub Staff_Tasks_Get_For_Patient(fk_patient As Integer) As Collection
  
  Dim sql As String  
  sql = "Select * from clerical.vwStaffTasksComponents where fk_patient = " & fk_patient
  Return modDBConnect.exec_query_collection(sql)
  
End
Public Sub Staff_Tasks_Get_Associated(fk_task As Integer, fk_staff_allocated As Integer) As Collection
   '---------------------------------------------------------------------------------------
   'Gets all task components bar that for the staff member viewing their own tasks
   'these are placed in list on the screen so the staff member can see who else is involved
   '---------------------------------------------------------------------------------------
   Dim sql As String  
   sql = "Select * from clerical.vwTasksComponents where fk_task = " & fk_task
   sql &= " AND fk_staff_allocated <> " & fk_staff_allocated
   Return modDBConnect.exec_query_collection(sql)
  
End

Public Sub Staff_Tasks_Get(fk_staff_allocated_task As Integer, fk_staff_filed_task As Integer, bfk_staff_only As Boolean, Optional fk_schema As Integer = 0, Optional fk_table As Integer = 0, Optional fk_row As Integer = 0, Optional completed As Integer = 0) As Collection
   '----------------------------------------------------------------------------------
   'Gets staff tasks
   ' Parameters: fk_staff_allocated_task = the staff person who was allocated the task
   '           : fk_staff_filed_task     = the staff person who filed the task
   '           : completed  0 = not completed 1 = completed 2 = either
   '-----------------------------------------------------------------------------------
   Dim sql As String
   If fk_staff_allocated_task Then 
       sql = "Select * from  Clerical.vwTasksComponents WHERE fk_staff_allocated  "
      If bfk_staff_only = True Then 
         sql &= "="
      Else
         sql &= "<>"
      End If
      sql &= fk_staff_allocated_task
   End If
   If fk_staff_filed_task Then
      sql = "Select * from  Clerical.vwTasksComponents WHERE fk_staff_filed_task  =" & fk_staff_filed_task & " AND fk_staff_allocated <>" & fk_staff_filed_task
   Endif
   If fk_row Then
     sql &= " AND fk_schema = " & fk_schema & " AND fk_table = " & fk_table & " AND fk_row = " & fk_row
   Endif
 '  sql &= " AND date_finalised is "
 '  sql &= " AND date_component_completed is " 
   Select Case completed
     Case 0
         sql &= " AND date_component_completed is null " 
     Case 1
        sql &= " AND date_component_completed is not null " 
     Case 2  'hence will be either
   End Select
    sql &= "  AND task_deleted = False and component_deleted = False  ORDER BY fk_urgency" 'and date_component_completed is null
   Print sql
   Return modDBConnect.exec_query_collection(sql)
  
End

Public Sub Staff_Tasks_Get_old(fk_staff_allocated As Integer, bfk_staff_only As Boolean, Optional fk_schema As Integer = 0, Optional fk_table As Integer = 0, Optional fk_row As Integer = 0, Optional bCompleted As Boolean = False) As Collection
   '-----------------------------------------------------------------
   'Gets staff tasks, usually outstanding unless doing an audit check
   '-----------------------------------------------------------------
   Dim sql As String
  
   sql = "Select * from  Clerical.vwTasksComponents WHERE fk_staff_allocated  "
   If bfk_staff_only = True Then 
      sql &= "="
   Else
      sql &= "<>"
   End If
   sql &= fk_staff_allocated
   If fk_row Then
     sql &= " AND fk_schema = " & fk_schema & " AND fk_table = " & fk_table & " AND fk_row = " & fk_row
   Endif
 '  sql &= " AND date_finalised is "
   sql &= " AND date_component_completed is " 
   If bCompleted Then
     sql &= " not "  
   End If
    sql &= "  null AND task_deleted = False and component_deleted = False  ORDER BY fk_urgency" 'and date_component_completed is null
   Print sql
   Return modDBConnect.exec_query_collection(sql)
  
End
Public Sub Staff_Tasks_Get_old1(fk_staff As Integer, bfk_staff_only As Boolean, Optional fk_schema As Integer = 0, Optional fk_table As Integer = 0, Optional fk_row As Integer = 0, Optional bCompleted As Boolean = False) As Collection
   '-----------------------------------------------------------------
   'Gets staff tasks, usually outstanding unless doing an audit check
   '-----------------------------------------------------------------
   Dim sql As String
   sql = "Select * from admin.vwStaffTasks WHERE fk_staff_allocated  "
   If bfk_staff_only = True Then 
      sql &= "="
   Else
      sql &= "<>"
   End If
   sql &= fk_staff
   If fk_row Then
     sql &= " AND fk_schema = " & fk_schema & " AND fk_table = " & fk_table & " AND fk_row = " & fk_row
   Endif
 
  ' sql = "Select * from admin.vwStaffTasks WHERE fk_staff_allocated = " & fk_staff
   sql &= " AND date_finalised is "
   If bCompleted Then
     sql &= " not " 
   Endif
   sql &= " null and Deleted = False ORDER BY fk_urgency"

   Return modDBConnect.exec_query_collection(sql)
  
End
