' Gambas module file

Public Function Shift_Create(fk_staff As Variant, Optional set_date As Date) As Collection
   '--------------------------------------------------------------
   'creates entry in clerical.staff_shifts table, returns the key
   ' CREATE TABLE clerical.staff_shifts
   ' (
   '   pk serial primary key,
   '   shift_date timestamp without time zone NOT NULL,
   '   fk_staff integer NOT NULL references admin.staff(pk)
   '
   ' );
   '
   '--------------------------------------------------------------

   Dim sql As String

   sql = "insert into clerical.staff_shifts "
   "(shift_date, fk_staff) "
   "VALUES ("
   If IsNull(set_date) Then
      sql &= "now(),"
   Else
      sql &= "$$" & Format(set_date, "yyyy-mm-dd hh:MM") & "$$,"
   Endif
   sql &= modDBConnect.currentUser!fk_staff
   ' sql &= fk_type & ","
   sql &= ") returning shift_date, pk"
   Return modDBConnect.exec_query_first(sql)

End

Public Function Staff_Messages_Get_All(for_last_x_days As String) As Collection

   Dim sql As String

   sql = "Select * from clerical.vwStaffMessages where staff_note_deleted is false "
   sql &= "AND shift_date >(CURRENT_DATE - INTERVAL '" & for_last_x_days & "day')::date "
   sql &= "ORDER BY shift_date DESC, time_logged ASC"
   Print sql
   Return modDBConnect.exec_query_collection(sql)

End

' retreives 'sticky poster notes' for the office, optionally for a staff member
Public Function Staff_Messages_Get_Outstanding(Optional fk_staff_destination As Variant = Null, Optional fk_staff_logged As Variant) As Collection

   Dim sql As String

   sql = "Select * from clerical.vwStaffMessages WHERE completed Is False "
   sql &= " AND staff_note_deleted is false "

   If Not IsNull(fk_staff_destination) Then
      sql &= " AND fk_staff_destination = " & fk_staff_destination
   Endif
   sql &= " order by shift_date DESC, time_logged  ASC"

   Return modDBConnect.exec_query_collection(sql)

End

Public Function Shift_Update(pk_consult As Variant, fk_type As Variant)

   Dim sql As String

   sql = "Update clerical.staff_shifts set fk_type= " & fk_type
   sql &= "WHERE pk= " & pk_consult
   modDBConnect.exec_query(sql)

End

Public Function Notes_Types_Get() As Collection

   Return modDBConnect.exec_query_collection("Select * from clerical.lu_staff_message_type order by type ASC")

End

Public Function Staff_Notes_Table_Row_Template() As String
   'Used in this module and FSTaffNotes

   Return ""
   "<COL WIDTH=5%>"
   "<COL WIDTH=5%>"
   "<COL WIDTH=10%>"
   "<COL WIDTH=75%>"
   "<COL WIDTH=10%>"
   "<TR VALIGN=TOP>"
   "<TD WIDTH=5%>"
   "col1"
   "</TD>"
   "<TD WIDTH=5%>"
   "col2"
   "</TD>"
   "<TD WIDTH=10%>"
   "col3"
   "</TD>"
   "<TD WIDTH=75%>"
   "col4"
   "</TD>"
   "<TD WIDTH=10%>"
   "col5"
   "</TD>"
   "</TR>"

End

Public Function Offices_Messages_Create_HTML(last_x_days As String) As String

   Dim sStart As String
   Dim sRowTemplate As String
   Dim sEnd As String
   Dim staff_notes As Collection = Staff_Messages_Get_All(last_x_days)
   Dim note As Collection
   Dim sHtml As String
   Dim sDate As String
   Dim sTime As String
   Dim sNote As String
   Dim sStatus As String
   Dim last_date As Date
   Dim sStaff_Logged As String

   sStart = "<HTML>"
   "<BODY><HR>"
   "<TABLE WIDTH=100% BORDER=0 CELLPADDING=5 CELLSPACING=1 >"
   sRowTemplate = Staff_Notes_Table_Row_Template()
   sEnd = "</TABLE></BODY></HTML>"
   sHtml = sStart
   For Each note In staff_notes
      sDate = Format(note!shift_date, "dd/mm/yyyy")
      sTime = Format(Time(note!time_logged), "hh:nn")
      sNote = "<B>To "
      If IsNull(note!staff_destination_wholename) Then
         sNote &= " Any Staff "
      Else
         sNote &= note!staff_destination_wholename
      Endif
      sStaff_Logged = note!staff_destination_wholename
      sNote &= " - Category: " & note!type & "</B>"
      sNote &= note!notes
      sHtml &= sRowTemplate
      If modUtil.IsSameDay(note!shift_date, last_date) Then
         sHtml = Replace(sHtml, "col1", "")
      Else
         sHtml = Replace(sHtml, "col1", sDate)
      End If
      sHtml = Replace(sHtml, "col2", sTime)
      If sStaff_Logged <> note!staff_logged_wholename
         sHtml = Replace(sHtml, "col3", note!staff_logged_wholename)
      Else
         sHtml = Replace(sHtml, "col3", "")
      End If
      sStaff_Logged = note!staff_logged_wholename
      sHtml = Replace(sHtml, "col4", sNote)
      If note!completed Then sStatus = "Done" Else sStatus = ""
      sHtml = Replace(sHtml, "col5", sStatus)
      last_date = note!shift_date
   Next
   Return sHTml & sEnd

End
