' Gambas module file

Public Function Shift_Create(fk_staff As Variant, Optional set_date As Date) As Collection
   '--------------------------------------------------------------
   'creates entry in clerical.staff_shifts table, returns the key
   ' CREATE TABLE clerical.staff_shifts
   ' (
   '   pk serial primary key,
   '   shift_date timestamp without time zone NOT NULL,
   '   fk_staff integer NOT NULL references admin.staff(pk)
   '  
   ' );
   ' 
   '--------------------------------------------------------------
   ' 

   Dim sql As String
   sql = "insert into clerical.staff_shifts "
   "(shift_date, fk_staff) "
   "VALUES ("
   If IsNull(set_date) Then
      sql &= "now(),"
   Else
      sql &= "$$" & Format(set_date, "yyyy-mm-dd hh:MM") & "$$,"
   Endif
   sql &= modDBConnect.currentUser!fk_staff 
 ' sql &= fk_type & ","
   sql &= ") returning shift_date, pk"
   Return modDBConnect.exec_query_first(sql)
   
End

Public Function Staff_Notes_Get() As Collection
   
  Return modDBConnect.exec_query_collection("Select * from clerical.vwStaffNotes order by shift_date, completed ASC")
   
End

Public Function Shift_Update(pk_consult As Variant, fk_type As Variant)
   
   Dim sql As String
   
   sql = "Update clerical.staff_shifts set fk_type= " & fk_type
   sql &= "WHERE pk= " & pk_consult
   modDBConnect.exec_query(sql)

End

Public Function Notes_Types_Get() As Collection
   
  Return modDBConnect.exec_query_collection("Select * from clerical.lu_staff_notes_type order by type ASC") 
   
End
