' Gambas module file

' Copyright (C) 2008-2015 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'
' A module to interface with the backend for recreational drugs
' ---------------------------------------------------------------------

Public Function Recreational_Drugs_Get() As Collection
   '-------------------------------------------------------------
   'returns a collection of recreational drugs which can be used
   'If a drug is missing please email me
   '------------------------------------------ ------------------
   
   Return modDBConnect.exec_query_collection("Select * from common.vwRecreationalDrugs order by drug")
   
End

Public Function Recreational_Drugs_Used(fk_patient As Integer) As Collection
   
   Return modDBConnect.exec_query_collection("Select * from clin_history.vwRecreationalDrugsUsed where fk_patient =" & fk_patient & " AND deleted = FALSE")
   
End

' Public Function SmokingStatus(cons As CConsult) As Integer
'    '--------------------------------------------------------------------
'    'Returns an interger value as per const.value for smoking status
'    'Note that to ensure the patient's e.g smoking history has been taken
'    'we have a field that must be postively saved drug_never_used
'    'if no smoking info returns 'smoking not known constant'
'    '--------------------------------------------------------------------
'    
'    Dim substance As Collection
'    
'    For Each substance In cons!recreationaldrugs
'       If substance!drug = "nicotine" Then
'          If substance!never_used_drug Then 
'             Return const.cSmokerNever
'          Else    
'             If IsNull(substance!age_last_used) Then
'                Return const.cSmokerCurrent
'             Else
'                Return const.cSmokerPast    
'             End If   
'          Endif
'       End If 
'    Next
'    Return const.cSmokerUnknown
'    
' End

Public Function SmokingStatus_String(cons As CConsult) As String
   '--------------------------------------------------------------------
   'Returns text of the smoking status
   'Note that to ensure the patient's e.g smoking history has been taken
   'we have a field that must be postively saved drug_never_used
   'if no smoking info returns 'smoking not known constant'
   '--------------------------------------------------------------------
   
   Dim substance As Collection
   
   For Each substance In cons!recreationaldrugs
      If substance!drug = "nicotine" Then
         If substance!never_used_drug Then 
            Return "NEVER SMOKED"
         Else    
            If IsNull(substance!age_last_used) Then
               Return "CURRENT SMOKER" 
            Else
               Return "EX-SMOKER CEASED AGE " & Str(substance!age_last_used)
            End If   
         Endif
         Break
      End If 
   Next
   
End
Public Function OtherDrugsStatus_String(cons As Cconsult) As String
   '-----------------------------------------
   'Returns a list of 'other drugs used'
   'Called by FPregnancy.Habits_Update_Data()
   '-----------------------------------------
   Dim substance As Collection
   Dim sString As String
   
   For Each substance In cons!recreationaldrugs
      If substance!drug <> "alcohol" And substance!drug <> "nicotine" Then
         sstring &= substance!drug & " age last used "
         If Not IsNull(substance!age_last_used) Then
            sString &= Str(substance!age_last_used)
         Else
            sstring &= "?"
         Endif
         sstring &= ","
      Endif
   Next
   Return Left(sString, Len(sString) - 1) 
End

Public Function AlcoholStatus_String(cons As CConsult) As String
   '--------------------------------------------------------------------
   'Returns text of the smoking status
   'Note that to ensure the patient's e.g smoking history has been taken
   'we have a field that must be postively saved drug_never_used
   'if no smoking info returns 'smoking not known constant'
   '--------------------------------------------------------------------
   
   Dim substance As Collection
   Dim sString As String
   
   For Each substance In cons!recreationaldrugs
      If substance!drug = "alcohol" Then
         If substance!never_used_drug Then 
            Return "NEVER DRANK"
         Else    
            If IsNull(substance!age_last_used) Then
               sString = "CURRENT DRINKER " 
               If Not IsNull(substance!substance_amount) Then
                  sString &= Str(substance!substance_amount) & " gms"
               Else
                  sString &= "?gms"
               End If
               If Not IsNull(substance!fk_lu_substance_frequency) Then  
                  Select Case substance!fk_lu_substance_frequency
                     Case const.Units_day
                        sString &= " per day"
                     Case const.Units_month
                        sString &= " per month"
                     Case const.Units_week
                        sString &= " per week"
                  End Select
               End If   
               Return sString
            Else
               Return "EX-DRINKER CEASED AGE " & Str(substance!age_last_used)
            End If   
         Endif
         Break
      End If 
   Next
   
End
