' Gambas module file

' Copyright (C) 2008-2013 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'
' A module to interface with the backend for recreational drugs
' ---------------------------------------------------------------------

Public Function Recreational_Drugs_Get() As Collection
   '-------------------------------------------------------------
   'returns a collection of recreational drugs which can be used
   'If a drug is missing please email me
   '------------------------------------------ ------------------
   
   Return modDBConnect.exec_query_collection("Select * from common.vwRecreationalDrugs order by drug")
   
End

Public Function Recreational_Drugs_Used(fk_patient As Integer) As Collection
   Return 
   Return modDBConnect.exec_query_collection("Select * from clin_history.vwRecreationalDrugsUsed where fk_patient =" & fk_patient & " AND deleted = FALSE")
   
End

Public Function SmokingStatus(cons As CConsult) As Integer
   '--------------------------------------------------------------------
   'Returns an interger value as per const.value for smoking status
   'Note that to ensure the patient's e.g smoking history has been taken
   'we have a field that must be postively saved drug_never_used
   'if no smoking info returns 'smoking not known constant'
   '--------------------------------------------------------------------
   
   Dim substance As Collection
   
   For Each substance In cons!recreationaldrugs
      If substance!drug = "nicotine" Then
         If substance!never_used_drug Then 
            Return const.cSmokerNever
         Else    
            If IsNull(substance!age_last_used) Then
               Return const.cSmokerCurrent
            Else
              Return const.cSmokerPast    
            End If   
         Endif
      End If 
   Next
   Return const.cSmokerUnknown

End
