.TH "easygp" "1" "October 2010" "Debian" "User Commands"
.SH "NAME"
easygp \- the EasyGP graphical client
.SH "SYNOPSIS"
.B easygp
[\fIoption\fR]
.SH "DESCRIPTION"
\fBEasyGP\fR is a fully-featured graphical medical records and
prescribing program for Australian GPs and specialists.

Extensive online documentation is available from
within the program. Press the F1 key within any screen and context-
specific help  will be shown.

.SH "ONLINE VIDEOS"

Videos demonstrating use of the program are available at
http://easygp.net.ay/videos 

.SH "OPTIONS"

With no options the graphical client is run. Options
allow alternative functions to be performed.

.TP 
\fB\-h\fR
display help and exit
.TP 
\fB\-v\fR
display version
.TP 
\fB\--import-files\fR
Scans the import directories and import HL7 or PIT
.TP
\fB\--receive-file\fR
Receive a HL7 or PIT file on standard input
.TP
\fB\--unit-tests\fR
Run unit tests

.SH "AVAILABILITY"
The latest version of Gambas can always be obtained from
\fBhttp://easygp.net.au/\fR

.SH "REPORTING BUGS"
Report bugs to <easygp@ozdocit.org>.

.SH "SEE ALSO"

\fBeasygp(8)\fR in the easygp-server package details how to care for the database.

.SH "COPYRIGHT"
Copyright \(co 2008-2010 Richard Terry <rterry@pacific.net.au>, 
Ian Haywood <ihaywood3@gmail.com>
.PP 
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
