#!/bin/bash

E_BADARGS=85

if [ ! -n "$1" ]
then
  echo "Usage: `basename $0` .changes"
  echo
  echo "Uploads the EasyGP binary and sources to the ozdocit.org server given the .changes file"
  echo "generated by debuild"
  exit $E_BADARGS
fi  
OLDPWD=`pwd`
cd ~/debian/ftp
reprepro --ignore=wrongdistribution include easygp $OLDPWD/$1
rsync -ravz . ihaywood@ozdocit.org:/home/ftp/pub/
