#!/bin/bash
set -e

E_BADARGS=85

if [ ! -n "$1" ]
then
  echo "Usage: `basename $0` .changes"
  echo
  echo "Uploads the EasyGP binary and sources to the ozdocit.org server given the .changes file"
  echo "generated by debuild"
  exit $E_BADARGS
fi
OLDPWD=`pwd`
if [ -d /home/ian/debian ] ; then
   BASE=/home/ian/debian
else
   BASE=/home/ian
fi

if [ "$1" = "cron" ] ; then
    cd $BASE
    rm -f *.changes
    cd $BASE/easygp
    SVN=`svn update | grep 'revision' | sed -e 's/.*revision \([0-9]*\)./\1/'`
    echo SVN version is $SVN
    OLDSVN=`cat $BASE/oldsvn`
    if [ "$OLDSVN" = "$SVN" ] ; then exit 0 ; fi
    echo $SVN > $BASE/oldsvn
    cd $BASE/easygp/db
    ./update-db.sh
    MAJOR=`psql -tA -c "select lu_major from db.lu_version" easygp -U easygp`
    MINOR=`psql -tA -c "select lu_minor from db.lu_version" easygp -U easygp`
    DBVERSION=$MAJOR.$MINOR
    NEWVERSION=svn$SVN
    echo new version is $NEWVERSION
    NEWVERSION=$DBVERSION$NEWVERSION
    echo new version is $NEWVERSION
    cd $BASE/easygp
    sed --in-place -e 1s/[0-9\\.]\*svn[0-9]\*/$NEWVERSION/ debian/changelog
    debuild || true
    cd $BASE
    CHANGES=$BASE/`ls *.changes`
else
  CHANGES=$OLDPWD/$1
fi

cd $BASE/ftp
reprepro --ignore=wrongdistribution include easygp $CHANGES
rsync -ravz . ihaywood@ozdocit.org:/home/ftp/pub/
