' Gambas module file

'Gambas class file
' Copyright (C) 2008-2013 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.

'all the constants for the field numbers go here
Public Const PID_Name As Integer = 5
Public Const PID_RecNum As Integer = 3
Public Const PID_Birthdate As Integer = 7
Public Const PID_Sex As Integer = 8
Public Const PID_Aka As Integer = 9
Public Const PID_Race As Integer = 10
Public Const PID_Address As Integer = 11
Public Const PID_Street As Integer = 0
Public Const PID_Address_Other As Integer = 1
Public Const PID_Town As Integer = 2
Public Const PID_State As Integer = 3
Public Const PID_Postcode As Integer = 4
Public Const PID_Country As Integer = 5
Public Const PID_Country_Code As Integer = 12
Public Const PID_SSN As Integer = 19
Public Const ORC_Ordering_Provider As Integer = 12
Public Const PV1_Attending As Integer = 7   'attending
Public Const PV1_Requesting As Integer = 8  'referring
Public Const PV1_Consulting As Integer = 9  'consulting - fixme
Public Const PRD_consulting As Integer = 2
Public Const Medicare_number As Integer = 0
Public Const MSH_Sending_Application As Integer = 2
Public Const MSH_Sending_Facility As Integer = 3
Public Const RQ_Provider_Provider_Number As Integer = 0
Public Const RQ_Provider_Surname As Integer = 1
Public Const RQ_Provider_Firstname As Integer = 2
Public Const RQ_Provider_Middle As Integer = 3
Public Const RQ_Provider_Title As Integer = 5

Public Const OBR_Our_Reference As Integer = 2
Public Const OBR_Episode As Integer = 3
Public Const OBR_Episode_ID As Integer = 0
Public Const OBR_Episode_Number As Integer = 0
Public Const OBR_Request As Integer = 4
Public Const OBR_Request_Name As Integer = 1

Public Const OBR_Request_Date As Integer = 6
Public Const OBR_Collect_Date As Integer = 7
Public Const OBR_End_Date As Integer = 8

Public Const OBR_Clinical_Notes As Integer = 13
Public Const OBR_Requesting_Provider As Integer = 16
Public Const OBR_CopyTo As Integer = 28
Public Const OBR_Principal_Result_Interpreter As Integer = 32 'true number = 32
