' Gambas module file

Public Function HL7FilesNames_GetImported(fk_sending_entity As Integer, filter As String) As Result
   '---------------------------------------------------------------------------------------------------
   'Gets names of all hl7 files imported into the database, by sending entity and optional text filter
   '--------------------------------------------------------------------------------------------------
   Dim sql As String
   sql = "Select distinct source_file From documents.vwdocuments where fk_sending_entity =" & fk_sending_entity
   If filter <> "" Then
      sql &= " AND source_file  ILIKE $$%" & filter & "%$$"
   Endif
   sql &= "order by source_file ASC"
  Return modDBConnect.exec_query(sql)
  
End

