' Gambas module file

'Public Function HL7FilesNames_GetImported(fk_sending_entity As Integer, Optional include_filter As String = "", Optional exclude_filter As String = "") As Result

Public Function HL7FilesNames_GetImported(sending_entity_keys As String[], Optional include_filter As String = "", Optional exclude_filter As String = "") As Result
   '---------------------------------------------------------------------------------------------------
   'Gets names of all hl7 files imported into the database, by sending entity and optional text filter
   'for one or more entity. This is because separate trading companies share or have shared
   'common sending mechanisms with same file prefixes.
   '--------------------------------------------------------------------------------------------------
   Dim sql As String
   Dim key As Integer
   sql = "Select distinct source_file From documents.vwdocuments where ("
   For Each key In sending_entity_keys
      sql &= "fk_sending_entity = " & key & " OR "
   Next
   sql = Left(sql, Len(sql) - 4) & ") " 
   If include_filter <> "" Then
      sql &= " AND source_file  ILIKE $$%" & include_filter & "%$$"
   Endif
   If exclude_filter
      sql &= " AND source_file  NOT ILIKE $$%" & exclude_filter & "%$$"
   Endif
   
   sql &= " ORDER BY source_file ASC"
  Return modDBConnect.exec_query(sql)
  
End

Public Function HL7FilesNames_GetImported_RT(Optional bDeleted As Boolean) As Result
  
  'again IAN forget this it's all temporary, just trying to clean up my HDD
   Dim sql As String = "Select distinct source_file From documents.vwdocuments"
   If bDeleted Then
     sql &= " AND deleted = False"
   Endif
   Return modDBConnect.exec_query(sql)
End

