' Gambas module file
' Copyright (C) 2008-2011 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.

Public $Result As Result
Public sql As String

Public Function Request_Default_Mark_Deleted(requestdefaults As Collection, old_pk As Integer, new_data As Collection) As Boolean
   '-------------------------------------
   'Marks as deleted a default preference
   '-------------------------------------
  
   new_data!deleted = True
   Return modDBConnect.update("clin_requests.user_provider_defaults", RequestDefaults[old_pk], new_data, "pk_default")
End

Public Function RequestType_DefaultsSave(old_data As Collection, pk_view As Integer, requestdefaults As Collection) As Integer
   '-----------------------------------------------------------------------------
   'Saves the default organisation, branch, and category of request for each user
   '-----------------------------------------------------------------------------
   If pk_view < 0 Then
      requestdefaults!fk_requestdefault = modDBConnect.insert("clin_requests.user_provider_defaults", requestdefaults)
   Else
      modDBConnect.update("clin_requests.user_provider_defaults", old_data[pk_view], requestdefaults, "pk_default")
   End If
   '------------------------------------------------------------------------
   'if this provider will be the default for the ordering section, save that
   '------------------------------------------------------------------------
   
End

Public Function User_Provider_Defaults_Get(fk_staff As Integer) As Collection 
   '--------------------------------------------------------------------
   ''Returns a collection of defaults for a particular user for
   'providers eg pathology, radiology etc
   'I've not used  modDBConnect.currentUser!fk_staff as this routine
   'could be called by an admin setting defaults for a staff member
   'who is not personally logged on
   '---------------------------------------------------------------------
    Return modDBConnect.exec_query_collection("Select * from clin_requests.vwUserProviderDefaults WHERE fk_staff =" & fk_staff & " AND deleted = FALSE ORDER BY request_type")
End

Public Sub Prescription_Coordinates_Save_Defaults()
   'Save defaults for prescribing
  

End
' Public Function Prescription_Workstation_Printer_Save(PTR As cWorkstationPrinter) As Boolean
' '    '------------------------------------------------------------------------  
' '    'saves the default workstation printer for a clinic and computer hostname
' '    'FIXME proper method of returning a flag if fails
' '    '------------------------------------------------------------------------
' '    $Result = modDBConnect.BeginTrans()
' '    sql = " INSERT INTO defaults.lu_link_printer_task("
' '          "fk_clinic, hostname, fk_task, printer)"
' '          "VALUES("
' '    sql &= gvar.staff_member.clinic.pk_branch & ","
' '    sql &= "$$" & Application.Host & "$$,"
' '    sql &= gvar.defaults_PrintingTask_Prescription & ","
' '    sql &= "$$" & System.Host & "$$)"
' '    $Result = modDBConnect.exec_query(sql)
' '    $Result = modDBConnect.CommitTrans()
' '    Return True
' '    
'  End 

