' Gambas module file

' Gambas class file
' Copyright (C) 2008-2014 Dr. Richard Terry
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'-------------------------------------------------------------------------------------

Public Function ProgressNotes_Codes_Get_For_Patient(fk_patient As Integer) As Collection
   '----------------------------------------------------------------------------
   'Returns a collection of progress notes codes for the patients progress notes
   '----------------------------------------------------------------------------
   
   Dim sql As String
   
   sql = "Select * from clin_Consult.vwProgressNotesCodes where fk_patient = " & fk_patient & " AND deleted = false ORDER BY fk_progressnote " 
   Return modDBConnect.exec_query_collection(sql)
   
End

Public Function ToDo_Next_Visit_Get(fk_patient As Integer) As Collection 
   '-------------------------------------------------------------------------------------
   'Gets the todo's for the next visit. This is a  carry forward 
   'Free text String Of things To Do Next visit by anyone Of the same role, Until deleted
   '-------------------------------------------------------------------------------------

   Dim sql As String
   
   Sql = "Select * from clin_consult.vwNextVisit where fk_patient = " & fk_patient 
   sql &= " AND fk_role = " & modDBConnect.currentUser!fk_role 
   Return modDBConnect.exec_query_first(sql)
   
End

Public Function ProgressNote_Code(fk_progressnote As Integer, code_text As String, Optional actual_codes As String[] = Null)
   '-------------------------------------------------
   'First up attempt at auto-coding of progress notes
   '-------------------------------------------------
   
   Dim progress_note_Code As New CRow  
   Dim R As Result
   
   R = modDBConnect.exec_query("Select * from clin_consult.progressnotes_codes where fk_progressnote = " & fk_progressnote)  'Is There coding For this progress note
   If R.count <> 0 Then
      progress_note_code.put_unchanged(R!pk, "pk")
   End If   
   progress_note_code!fk_progressnote = fk_progressnote
   If const.coding_system_in_use = const.coding_icpcPlus Then
      Select Case code_text
         Case "prescription written"
            progress_note_code!fk_code = const.icpc2_prescription_code
         Case "pathology request"
            '  If fk_lu_request_type = const.Request_Type_Pathology Or fk_lu_request_type = const.Request_Type_Radiology Then
            '       progress_note_code!fk_progressnote = request_form!fk_progressnote
            '  Select Case fk_lu_request_type
            '   Case const.Request_Type_Pathology
            '     progress_note_code!fk_code = const.icpc2_pathology_test_code
            '  Case const.Request_Type_Radiology
            '    progress_note_code!fk_code = const.icpc2_radiology_test_code
            ' End Select
            
      End Select
      progress_note_code.Save("clin_consult.progressnotes_codes", "pk") 
   End If  
   
End
