' Gambas module file

' Gambas class file
' Copyright (C) 2008-2013 Dr. Richard Terry
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'-------------------------------------------------------------------------------------

Public Function ProgressNotes_Codes_Get_For_Patient(fk_patient As Integer) As Collection
   '----------------------------------------------------------------------------
   'Returns a collection of progress notes codes for the patients progress notes
   '----------------------------------------------------------------------------
   
   Dim sql As String
   
   sql = "Select * from clin_Consult.vwProgressNotesCodes where fk_patient = " & fk_patient & " AND deleted = false ORDER BY fk_progressnote " 
   Return modDBConnect.exec_query_collection(sql)
   
End
