' Gambas module file

Public Function Patient_Images_Get(fk_patient As Integer) As Collection
   'If image hasn't got an md5sum it is not in the progress notes
   'fixme - need to include images from procedures and patient photographs.   
   Return modDBConnect.exec_query_collection("Select * From blobs.vwPatientImages where fk_patient = " & fk_patient & " and md5sum is not null order by consult_date")
 '    Return modDBConnect.exec_query_collection("Select * From blobs.vwPatientImages where fk_patient = " & fk_patient) ' & " and md5sum is not null order by consult_date")
End

