#!/bin/sh
# install SQL generated by:
pg_dump -O -s -x -T 'coding.icd10' -T 'coding.icd10_*' -T 'coding.icpc2_*' -T 'coding.vwicpc*' test-30june12 | grep -v richard > easygp.schema.sql
pg_dump -O -t "*.lu_*" -a test-30june12 > easygp.data.sql
