.TH "easygp" "8" "October 2010" "Debian" "System Adminstration"
.SH "NAME"
easygp \- database administration

.SH "INTRODUCTION"

This manpage documents how to create and maintain a EasyGP
database.

Maintaining a database does require some limited command-line
work. This is not difficult, and often in practice the only way as the
EasyGP server system will be a separate server machine which may have no video card.

.SH "PLATFORM"

These instructions are written for Linux Ubuntu. Other Linux distros
and MacOS X will work fine but some of the shell commands will vary,
you will need to check the manual for your distro or ask an
expert. The main difference is in root access, on Ubuntu you
type "sudo" before each command, on most other systems you type "su"
at the start to get a root shell and then proceed without the "sudo".

In principle Windows could be used as a server but given the client
requires Linux it is unclear why anyone would ever want to do this.

.SH "PROMPT"

"$" below refers to your command-line prompt, type the letters after it but not the "$" itself.
Similarly "<something>" means something you need to substitute, like a local network address or a password, 
not the literal < and > themselves.

.SH "INSTALLATION"

.SS "Accessing the server"

 First you need to obtain the IP or domain name of the server. Second you need shell access to the server,
this is usually by opening a console and typing

$   ssh <your.server.ip.address>

.SS "Installing postgresql"

Postgresql version 8.4 or higher is required, all recent Linux systems will have this available.

$    sudo apt-get install postgresql postgresql-contrib

.SS "Download EasyGP"

If you are reading this file on the client computer, you need to install
the files on the server too. Use this command:

$    svn co svn://easygp.net.au/easygp/trunk/db/

Make sure the directory containing this README is the current directory.

.SS "Configure the server"

The main issue with configuring servers is getting the host access permissions right.
Many distros have settings that are far too conservative, others too liberal.

The file pg_hba.conf.example in this directory contains the settings I use, to copy across do

$    sudo cp pg_hba.conf.example /etc/postgresql/9.1/main/pg_hba.conf

Unfortunately the location of this file varies a lot. So for version 8.1 postgres it will
be elsewhere, as for on different distros.

You then need to restart the server for these settings to take effect.

$    sudo /etc/init.d/postgresql restart
    
.SS "Create the administrator login"

$    sudo su postgres -c "psql template1"

You are  now logged in as the postgres super-user (NB not
the same as the system super-user) and can enter commands at the postgresql prompt

Create the login to control the EasyGP installation. It must be
called "easygp", you don't get any choice at all. (You
can create other users later.)

$    create role easygp login createrole password '<your password>';

Also a group should be created for ordinary users. Note this MUST
be called "staff", again you don't get a choice here.

$    create role staff nologin admin easygp;


.SS "Create the database"

$    create database easygp owner easygp;

The name doesn't have to be "easygp", but it is strongly recommended
you stick to this name unless you really know
what you are doing. It does need to be owned by user
"easygp" in all cases. 
Various database options such as TABLESPACE can be added here if you know
what you are doing, see the PostgreSQL documentation at www.postgresql.org

.SS "Re-connect to the new database"

$    \\c easygp

.SS "Install the database"

$   \\i easygp.schema.sql

$   \\i easygp.data.sql

Each command will give a lot of output including warnings, but no errors.
If there are errors please cut and paste them into an e-mail and forward
to a developer (see the AUTHORS file)

.SS "Install a coding system"

EasyGP needs at least one disease coding system installed. Options are ICPC-2,
ICD-10, in the near future, FreeCodes. You can install more than one system.
Order is important, the last system installed is the 'preferred' system
that will be used first for searching for disease codes, usually this is
will be ICPC-2 or FreeCodes. 
    
.TP 1
ICD-10
     
    ICD-10 is owned by the WHO, there are few restrictions on its use and a copy is
    included with EasyGP, it can be installed with one command.
    It is very specific but not very convenient, so it is usually the 'backup'
    system with another one (ICPC-2 or FreeCodes) installed as the preferred system.
    
    $    \\i coding/icd10_import_gambas.sql

.TP 1
ICPC-2 Plus
    
    ICPC-2 Plus is a GP-centric coding system developed by the Family Medicine
    Research Centre at the University of Sydney. ICPC-2 Plus is proprietary,
    a licence must be purchased and a copy of the code files obtained.
    How this is done is up to the user, the EasyGP developers cannot provide
    copies of ICPC-2.
    
    This may mean unpacking a provided .ZIP file (at the shell prompt, use 
    "\q" to get out of postgres)
    
    $   unzip <the zip file>
    
    The unpacked files must be in the current directory (where this README file is), 
    so if the zip file puts them in a subdirectory, you need to copy them back.
    
    $   cp <the directory>/* .
    
    Finally you can run the provided script (now back in postgres)
    
    $   \\i coding/icpc2_import_gambas.sql
    
.TP 1
FreeCodes
    
    FreeCodes is a basic coding system developed by Ian Haywood, using a set
    of terms provided by Richard Terry and Malcolm Ireland, they are mapped to
    ICD10. It is also provided free with EasyGP.
    
    $    \\i coding/freecodes_import_gambas.sql


.SS "Installing drug database"

Currently only a standard drug database is supported, this is 
included in the existing SQL files.

.SS "Completion"

The process is complete, you can now use the client, which should display the 
setup wizard. You log on to the client using the username and password of the 
administrator account created above. 


.SH "MAINTAINING THE DATABASE"


.SS "Coding System"

If you are using ICPC-2 new versions are published every few months. They 
need to be unpacked into the same db/ directory as for installation, and then
(in postgres) run the update script.

$   \i coding/icpc2_update.sql


.SS "Drug Update"

Every month an update file is provided of new PBS drugs and some new private drugs
contributed by users. E-mail Ian Haywood <ian@haywood.id.au> to be put on the distribution
list. The file provided is an LZMA compressed sql file. Download it and as the "easygp" user
do

$  lzcat pbs-XX.sql.lzma | psql easygp

The script will take some time to run and should produce no output. 

.SS "New Database Versions"

Scripts to update the database to a new version are in trunk/db/updates in svn.
Once you have downloaded a new version you can runthe updates via the update-db.sh script
in trunk/db. 

$ svn update
$ cd trunk/db
$ ./update-db.sh

.SH "ONLINE SERVICES"

Online services such as Medicare Online, Medicare HI Service and the PCEHR are
accessed via a daemon with runs on the server only, written in python. It
is available in trunk/db/python in the svn repository, or /usr/share/easygp/python
if you have installed the packages.

The daemon should be run without arguments.

$  python trunk/db/python/daemon.py

It will run continuously in the background. See the easygp.conf(8) manpage for details
on how to st up the daemon  including installing keys.

.SH "BACKUP"

To be written.

.SH "AUTHORS"


Written by Dr. Ian Haywood
