Insert into common.lu_ethnicity(ethnicity)values('Admiralty Islander');
Insert into common.lu_ethnicity(ethnicity)values('Afghani');
Insert into common.lu_ethnicity(ethnicity)values('African');
Insert into common.lu_ethnicity(ethnicity)values('African (or cultural group of African origin)');
Insert into common.lu_ethnicity(ethnicity)values('African American');
Insert into common.lu_ethnicity(ethnicity)values('Aitutaki Islander');
Insert into common.lu_ethnicity(ethnicity)values('Albanian');
Insert into common.lu_ethnicity(ethnicity)values('Algerian');
Insert into common.lu_ethnicity(ethnicity)values('American (US)');
Insert into common.lu_ethnicity(ethnicity)values('Arab');
Insert into common.lu_ethnicity(ethnicity)values('Argentinian');
Insert into common.lu_ethnicity(ethnicity)values('Armenian');
Insert into common.lu_ethnicity(ethnicity)values('Asian');
Insert into common.lu_ethnicity(ethnicity)values('Assyrian');
Insert into common.lu_ethnicity(ethnicity)values('Atiu Islander');
Insert into common.lu_ethnicity(ethnicity)values('Austral Islander');
Insert into common.lu_ethnicity(ethnicity)values('Australian');
Insert into common.lu_ethnicity(ethnicity)values('Australian Aboriginal');
Insert into common.lu_ethnicity(ethnicity)values('Austrian');
Insert into common.lu_ethnicity(ethnicity)values('Bangladeshi');
Insert into common.lu_ethnicity(ethnicity)values('Belau/Palau Islander');
Insert into common.lu_ethnicity(ethnicity)values('Belgian');
Insert into common.lu_ethnicity(ethnicity)values('Bengali');
Insert into common.lu_ethnicity(ethnicity)values('Bismark Archipelagoan');
Insert into common.lu_ethnicity(ethnicity)values('Bolivian');
Insert into common.lu_ethnicity(ethnicity)values('Bougainvillean');
Insert into common.lu_ethnicity(ethnicity)values('Brazilian');
Insert into common.lu_ethnicity(ethnicity)values('British');
Insert into common.lu_ethnicity(ethnicity)values('Bulgarian');
Insert into common.lu_ethnicity(ethnicity)values('Burgher');
Insert into common.lu_ethnicity(ethnicity)values('Burmese');
Insert into common.lu_ethnicity(ethnicity)values('Byelorussian');
Insert into common.lu_ethnicity(ethnicity)values('Canadian');
Insert into common.lu_ethnicity(ethnicity)values('Caroline Islander');
Insert into common.lu_ethnicity(ethnicity)values('Celtic');
Insert into common.lu_ethnicity(ethnicity)values('Central American Indian');
Insert into common.lu_ethnicity(ethnicity)values('Channel Islander');
Insert into common.lu_ethnicity(ethnicity)values('Chilean');
Insert into common.lu_ethnicity(ethnicity)values('Chinese');
Insert into common.lu_ethnicity(ethnicity)values('Colombian');
Insert into common.lu_ethnicity(ethnicity)values('Cook Island Maori');
Insert into common.lu_ethnicity(ethnicity)values('Cornish');
Insert into common.lu_ethnicity(ethnicity)values('Corsican');
Insert into common.lu_ethnicity(ethnicity)values('Costa Rican');
Insert into common.lu_ethnicity(ethnicity)values('Creole (Latin America)');
Insert into common.lu_ethnicity(ethnicity)values('Creole (US)');
Insert into common.lu_ethnicity(ethnicity)values('Croat/Croatian');
Insert into common.lu_ethnicity(ethnicity)values('Cypriot Unspecified');
Insert into common.lu_ethnicity(ethnicity)values('Czech');
Insert into common.lu_ethnicity(ethnicity)values('Dalmatian');
Insert into common.lu_ethnicity(ethnicity)values('Danish');
Insert into common.lu_ethnicity(ethnicity)values('Dutch');
Insert into common.lu_ethnicity(ethnicity)values('Easter Islander');
Insert into common.lu_ethnicity(ethnicity)values('Ecuadorian');
Insert into common.lu_ethnicity(ethnicity)values('Egyptian');
Insert into common.lu_ethnicity(ethnicity)values('English');
Insert into common.lu_ethnicity(ethnicity)values('Estonian');
Insert into common.lu_ethnicity(ethnicity)values('European');
Insert into common.lu_ethnicity(ethnicity)values('Falkland Islander/Kelper');
Insert into common.lu_ethnicity(ethnicity)values('Fijian');
Insert into common.lu_ethnicity(ethnicity)values('Fijian (except Fiji Indian/Indo-Fijian)');
Insert into common.lu_ethnicity(ethnicity)values('Fijian Indian/Indo-Fijian');
Insert into common.lu_ethnicity(ethnicity)values('Filipino');
Insert into common.lu_ethnicity(ethnicity)values('Finnish');
Insert into common.lu_ethnicity(ethnicity)values('Flemish');
Insert into common.lu_ethnicity(ethnicity)values('French');
Insert into common.lu_ethnicity(ethnicity)values('Gaelic');
Insert into common.lu_ethnicity(ethnicity)values('Gambier Islander');
Insert into common.lu_ethnicity(ethnicity)values('German');
Insert into common.lu_ethnicity(ethnicity)values('Greek (incl Greek Cypriot)');
Insert into common.lu_ethnicity(ethnicity)values('Greenlander');
Insert into common.lu_ethnicity(ethnicity)values('Guadalcanalian');
Insert into common.lu_ethnicity(ethnicity)values('Guam Islander/Chamorro');
Insert into common.lu_ethnicity(ethnicity)values('Guatemalan');
Insert into common.lu_ethnicity(ethnicity)values('Gujarati');
Insert into common.lu_ethnicity(ethnicity)values('Guyanese');
Insert into common.lu_ethnicity(ethnicity)values('Hawaiian');
Insert into common.lu_ethnicity(ethnicity)values('Honduran');
Insert into common.lu_ethnicity(ethnicity)values('Hong Kong Chinese');
Insert into common.lu_ethnicity(ethnicity)values('Hungarian');
Insert into common.lu_ethnicity(ethnicity)values('I-Kiribati/Gilbertese');
Insert into common.lu_ethnicity(ethnicity)values('Icelander');
Insert into common.lu_ethnicity(ethnicity)values('Indian');
Insert into common.lu_ethnicity(ethnicity)values('Indonesian (incl Javanese/Sundanese/Sumatran)');
Insert into common.lu_ethnicity(ethnicity)values('Inuit/Eskimo');
Insert into common.lu_ethnicity(ethnicity)values('Iranian/Persian');
Insert into common.lu_ethnicity(ethnicity)values('Iraqi');
Insert into common.lu_ethnicity(ethnicity)values('Irish');
Insert into common.lu_ethnicity(ethnicity)values('Israeli/Jewish/Hebrew');
Insert into common.lu_ethnicity(ethnicity)values('Italian');
Insert into common.lu_ethnicity(ethnicity)values('Jamaican');
Insert into common.lu_ethnicity(ethnicity)values('Japanese');
Insert into common.lu_ethnicity(ethnicity)values('Jordanian');
Insert into common.lu_ethnicity(ethnicity)values('Kampuchean Chinese');
Insert into common.lu_ethnicity(ethnicity)values('Kanaka/Kanak');
Insert into common.lu_ethnicity(ethnicity)values('Kenyan');
Insert into common.lu_ethnicity(ethnicity)values('Khmer/Kampuchean/Cambodian');
Insert into common.lu_ethnicity(ethnicity)values('Korean');
Insert into common.lu_ethnicity(ethnicity)values('Kurd');
Insert into common.lu_ethnicity(ethnicity)values('Lao/Laotian');
Insert into common.lu_ethnicity(ethnicity)values('Latin American/Hispanic');
Insert into common.lu_ethnicity(ethnicity)values('Latvian');
Insert into common.lu_ethnicity(ethnicity)values('Lebanese');
Insert into common.lu_ethnicity(ethnicity)values('Libyan');
Insert into common.lu_ethnicity(ethnicity)values('Lithuanian');
Insert into common.lu_ethnicity(ethnicity)values('Macedonian');
Insert into common.lu_ethnicity(ethnicity)values('Malaitian');
Insert into common.lu_ethnicity(ethnicity)values('Malay/Malayan');
Insert into common.lu_ethnicity(ethnicity)values('Malaysian Chinese');
Insert into common.lu_ethnicity(ethnicity)values('Maltese');
Insert into common.lu_ethnicity(ethnicity)values('Malvinian (Spanish-speaking Falkland Islander)');
Insert into common.lu_ethnicity(ethnicity)values('Mangaia Islander');
Insert into common.lu_ethnicity(ethnicity)values('Manihiki Islander');
Insert into common.lu_ethnicity(ethnicity)values('Manus Islander');
Insert into common.lu_ethnicity(ethnicity)values('Manx');
Insert into common.lu_ethnicity(ethnicity)values('Marianas Islander');
Insert into common.lu_ethnicity(ethnicity)values('Marquesas Islander');
Insert into common.lu_ethnicity(ethnicity)values('Marshall Islander');
Insert into common.lu_ethnicity(ethnicity)values('Mauke Islander');
Insert into common.lu_ethnicity(ethnicity)values('Mauritian');
Insert into common.lu_ethnicity(ethnicity)values('Mexican');
Insert into common.lu_ethnicity(ethnicity)values('Middle Eastern');
Insert into common.lu_ethnicity(ethnicity)values('Mitiaro Islander');
Insert into common.lu_ethnicity(ethnicity)values('Moroccan');
Insert into common.lu_ethnicity(ethnicity)values('Nauru Islander');
Insert into common.lu_ethnicity(ethnicity)values('Nepalese');
Insert into common.lu_ethnicity(ethnicity)values('New Britain Islander');
Insert into common.lu_ethnicity(ethnicity)values('New Caledonian');
Insert into common.lu_ethnicity(ethnicity)values('New Georgian');
Insert into common.lu_ethnicity(ethnicity)values('New Irelander');
Insert into common.lu_ethnicity(ethnicity)values('New Zealand European/Pakeha');
Insert into common.lu_ethnicity(ethnicity)values('New Zealand Maori');
Insert into common.lu_ethnicity(ethnicity)values('Nicaraguan');
Insert into common.lu_ethnicity(ethnicity)values('Nigerian');
Insert into common.lu_ethnicity(ethnicity)values('Niuean');
Insert into common.lu_ethnicity(ethnicity)values('North American Indian');
Insert into common.lu_ethnicity(ethnicity)values('Norwegian');
Insert into common.lu_ethnicity(ethnicity)values('Ocean Islander/Banaban');
Insert into common.lu_ethnicity(ethnicity)values('Omani');
Insert into common.lu_ethnicity(ethnicity)values('Orkney Islander');
Insert into common.lu_ethnicity(ethnicity)values('Other African nec');
Insert into common.lu_ethnicity(ethnicity)values('Other or not Specified');
Insert into common.lu_ethnicity(ethnicity)values('Other Pacific Island Groups');
Insert into common.lu_ethnicity(ethnicity)values('Other Pacific Island nec');
Insert into common.lu_ethnicity(ethnicity)values('Other Southeast Asian');
Insert into common.lu_ethnicity(ethnicity)values('Pacific Island');
Insert into common.lu_ethnicity(ethnicity)values('Pakistani');
Insert into common.lu_ethnicity(ethnicity)values('Palestinian');
Insert into common.lu_ethnicity(ethnicity)values('Palmerston Islander');
Insert into common.lu_ethnicity(ethnicity)values('Panamanian');
Insert into common.lu_ethnicity(ethnicity)values('Papuan/New Guinean/Irian Jayan');
Insert into common.lu_ethnicity(ethnicity)values('Paraguayan');
Insert into common.lu_ethnicity(ethnicity)values('Penrhyn Islander');
Insert into common.lu_ethnicity(ethnicity)values('Peruvian');
Insert into common.lu_ethnicity(ethnicity)values('Phoenix Islander');
Insert into common.lu_ethnicity(ethnicity)values('Pitcairn Islander');
Insert into common.lu_ethnicity(ethnicity)values('Polish');
Insert into common.lu_ethnicity(ethnicity)values('Portuguese');
Insert into common.lu_ethnicity(ethnicity)values('Puerto Rican');
Insert into common.lu_ethnicity(ethnicity)values('Pukapuka Islander');
Insert into common.lu_ethnicity(ethnicity)values('Punjabi');
Insert into common.lu_ethnicity(ethnicity)values('Rakahanga Islander');
Insert into common.lu_ethnicity(ethnicity)values('Rarotongan');
Insert into common.lu_ethnicity(ethnicity)values('Romanian/Rumanian');
Insert into common.lu_ethnicity(ethnicity)values('Romany/Gypsy');
Insert into common.lu_ethnicity(ethnicity)values('Rotuman/Rotuman Islander');
Insert into common.lu_ethnicity(ethnicity)values('Russian');
Insert into common.lu_ethnicity(ethnicity)values('Samoan');
Insert into common.lu_ethnicity(ethnicity)values('Santa Cruz Islander');
Insert into common.lu_ethnicity(ethnicity)values('Sardinian');
Insert into common.lu_ethnicity(ethnicity)values('Scottish (Scots)');
Insert into common.lu_ethnicity(ethnicity)values('Serb/Serbian');
Insert into common.lu_ethnicity(ethnicity)values('Seychelles Islander');
Insert into common.lu_ethnicity(ethnicity)values('Shetland Islander');
Insert into common.lu_ethnicity(ethnicity)values('Sikh');
Insert into common.lu_ethnicity(ethnicity)values('Singaporean Chinese');
Insert into common.lu_ethnicity(ethnicity)values('Sinhalese');
Insert into common.lu_ethnicity(ethnicity)values('Slavic/Slav');
Insert into common.lu_ethnicity(ethnicity)values('Slovak');
Insert into common.lu_ethnicity(ethnicity)values('Slovene/Slovenian');
Insert into common.lu_ethnicity(ethnicity)values('Society Islander (including Tahitian)');
Insert into common.lu_ethnicity(ethnicity)values('Solomon Islander');
Insert into common.lu_ethnicity(ethnicity)values('Somali');
Insert into common.lu_ethnicity(ethnicity)values('South African');
Insert into common.lu_ethnicity(ethnicity)values('South American Indian');
Insert into common.lu_ethnicity(ethnicity)values('South Slav (formerly Yugoslav)');
Insert into common.lu_ethnicity(ethnicity)values('Southeast Asian');
Insert into common.lu_ethnicity(ethnicity)values('Spanish');
Insert into common.lu_ethnicity(ethnicity)values('Sri Lankan');
Insert into common.lu_ethnicity(ethnicity)values('Sri Lankan Tamil');
Insert into common.lu_ethnicity(ethnicity)values('Swedish');
Insert into common.lu_ethnicity(ethnicity)values('Swiss');
Insert into common.lu_ethnicity(ethnicity)values('Syrian');
Insert into common.lu_ethnicity(ethnicity)values('Taiwanese Chinese');
Insert into common.lu_ethnicity(ethnicity)values('Tamil');
Insert into common.lu_ethnicity(ethnicity)values('Thai/Tai/Siamese');
Insert into common.lu_ethnicity(ethnicity)values('Tibetan');
Insert into common.lu_ethnicity(ethnicity)values('Tokelauan');
Insert into common.lu_ethnicity(ethnicity)values('Tongan');
Insert into common.lu_ethnicity(ethnicity)values('Torres Strait Islander/Thursday Islander');
Insert into common.lu_ethnicity(ethnicity)values('Tuamotu Islander');
Insert into common.lu_ethnicity(ethnicity)values('Tunisian');
Insert into common.lu_ethnicity(ethnicity)values('Turkish (incl Turkish Cypriot)');
Insert into common.lu_ethnicity(ethnicity)values('Tuvalu Islander/Ellice Islander');
Insert into common.lu_ethnicity(ethnicity)values('Ugandan');
Insert into common.lu_ethnicity(ethnicity)values('Ukrainian');
Insert into common.lu_ethnicity(ethnicity)values('Uruguayan');
Insert into common.lu_ethnicity(ethnicity)values('Vanuatu Islander/New Hebridean');
Insert into common.lu_ethnicity(ethnicity)values('Venezuelan');
Insert into common.lu_ethnicity(ethnicity)values('Vietnamese');
Insert into common.lu_ethnicity(ethnicity)values('Vietnamese Chinese');
Insert into common.lu_ethnicity(ethnicity)values('Wake Islander');
Insert into common.lu_ethnicity(ethnicity)values('Wallis Islander');
Insert into common.lu_ethnicity(ethnicity)values('Welsh');
Insert into common.lu_ethnicity(ethnicity)values('West Indian/Caribbean');
Insert into common.lu_ethnicity(ethnicity)values('Yap Islander');
Insert into common.lu_ethnicity(ethnicity)values('Yemeni');