' Gambas module file

' Copyright (C) 2008-2013 Dr. Richard Terry Dr. Ian Haywood

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------

Public Function Allergies_Get(fk_patient As Integer) As Collection
   '--------------------------------------------
   'Gets the patients allergies and sensitivites
   '--------------------------------------------
  Return modDBConnect.exec_query_collection("select * from clin_allergies.vwallergies where fk_patient = &1" & " and deleted = False", [fk_patient]) 
   
End


Public Function ATC_Get(atcname As String) As Collection
   
  Dim sql As String
  
  sql = "Select distinct atccode as pk, atccode, atcname from drugs.atc where atcname ILIKE $$%" & atcname & "%$$  "
  sql &= "AND atcname <> '' order by atcname limit 20 "
  Return modDBConnect.exec_query_collection(sql)
  
End

Public Function ATC_Code_Get_Class(code As String) As Result
 
 
  Return modDBConnect.exec_query("Select distinct atccode as pk, * from drugs.atc where atccode ILIKE $$" & code & "$$")

  
End

Public Function Reaction_save(the_reaction As String) As Integer
   '-----------------------------------------------------------
   'Saves the free text of a reaction if does not already exist
   '-----------------------------------------------------------
   Dim R As Result
   Dim reaction As New CRow
   
   R = modDBConnect.exec_query("Select * from clin_allergies.lu_reaction where reaction = $$" & Lower(the_reaction) & "$$")
   If R.count Then Return R!pk
   reaction!reaction = the_reaction
   reaction.Save("clin_allergies.lu_reaction", "pk")
   Return reaction!pk
   
   
   
End
