' Gambas module file

' Copyright (C) 2008-2012 Dr. Richard Terry Dr. Ian Haywood

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------

Public Function Allergies_Get(fk_patient As Integer) As Collection
   
  Return modDBConnect.exec_query_row("select * from clin_allergies.vwallergies where pk = &1", [fk_patient]) 
   
End

Public Function Reactions_Get(reaction As String) As Collection
   
  Return modDBConnect.exec_query_collection("Select * from clin_allergies.lu_reaction where reaction ILIKE $$%" & reaction & "%$$ Order by reaction")
   
End

Public Function Reaction_save(the_reaction As String) As Integer
   '-----------------------------------------------------------
   'Saves the free text of a reaction if does not already exist
   '-----------------------------------------------------------
   Dim R As Result
   Dim reaction As New CRow
   
   R = modDBConnect.exec_query("Select * from clin_allergies.lu_reaction where reaction = $$" & Lower(the_reaction) & "$$")
   If R.count Then Return R!pk
   reaction!reaction = the_reaction
   reaction.Save("clin_allergies.lu_reaction", "pk")
   Return reaction!pk
   
   
   
End
