' Gambas module file
' Copyright (C) 2008-2010 Dr. Richard Terry, Dr. Ian Haywood

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.

Public Sub Main()   

   modPrinting.Printers_Load()
   modPrinting.PrintHtml("<html><body>Foo <b>Bar</b> <i>Baz</i></body></html>")
   If Logon() Then
     If modAdminDBI.Clinics_Setup() Then
       FMain.Show()
     Else
        If FSetupWizard.ShowModal() = 1 Then
          FMain.Show()
        Endif
     Endif
   Endif
End
  
Private Function Logon() As Boolean

   Dim result As String
   Dim host As String
   Dim username As String
   Dim dbase As String
   Dim password As String
   Dim FLogOn As New FrmLogon
   
   host = Settings["Autoconnect/host", Null]
   If Not IsNull(host) Then
     username = Settings["Autoconnect/username", User.Name]
     dbase = Settings["Autoconnect/database", "easygp"]
     If host = "unix" Then host = ""
     password = Settings["Autoconnect/password", ""]
     result = modDBConnect.dbConnect_global(host, dbase, username, password)
     If result = "success" Then Return True
   Endif
  ' okay, none of that worked, use the logon dialogue box
  Select Case FLogOn.ShowModal()
  Case 1
      Return True
  Case 0
      Return False
  End Select
End



