# Gambas Action File 3.0

{ Actions
  { Action graph
    Text = "Graph"
    Shortcut = ""
  }
  { Action re-order
    Text = "Re-Order Today's Date"
    Shortcut = ""
  }
  { Action tbSections
    Text = ""
    Picture = "icons/24/tim_enotes_green_2424.png"
  }
}

