# Gambas Action File 3.0

{ Actions
  { Action add to all
    Text = "Add employee to ALL branches"
    Shortcut = ""
  }
  { Action web
    Text = "Visit Website"
    Shortcut = ""
    Picture = "icons/16/firefox_1616.png"
  }
}

