' Gambas module file
' Copyright (C) 2008-2011 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.

Private $Result As Result
Private sql As String

' Public Function provider_types_get(listview1 As ListView)
' 
'   ' Dim sProvidertype As String
'   ' Dim AllProviders As collection
'   ' sProvidertype = txtProviderType.Text
'    '--------------------------------------------------
'    'Returns a listview filled with types of providers
'    'E.g Radiology/Pathology/Physiotherapy
'    'listbox key being the pk of clin_requests.lu_types
'    '----------------------------------------------------
' 
'    sql = "Select * From clin_requests.lu_type  ORDER BY type ASC"
'    $Result = modDBConnect.exec_query(sql)
'    If $Result.count Then 
'              
'           listview1.Clear
'              For Each $Result 
'                    listview1.Add(Str$($Result!pk), $Result!type)
'             Next 
'          '   listview1.tag = txtProviderType
'             listview1.Raise
'             listview1.Visible = True
'        Else 
'            'empty recordset
'           listview1.Visible = False
'        End If  
'  End
'  Public Sub User_Defaults_Get(staff As cDBUser)
'    'retrieves a collection  of defaults for current user for request forms.
'    'Dim DefaultRequests As Collection
'    Dim aRequestDefault As cRequestDefault
'    sql = "Select * from clin_requests.user_defaults_for_types where fk_staff =" & staff.fk_staff
'    $Result = modDBConnect.exec_query(sql)
'    
'    staff.RequestDefaults = New Collection
'    If $Result.count Then
'       For Each $Result
'          aRequestDefault = New cRequestDefault
'          aRequestDefault.pk_default = $Result!pk
'          aRequestDefault.fk_lu_type = $Result!fk_lu_type
'          aRequestDefault.fk_staff = $Result!fk_staff
'          aRequestDefault.fk_branch = $Result!fk_branch
'          aRequestDefault.fk_organisation = $Result!fk_organisation
'          staff.RequestDefaults.Add(aRequestDefault, $Result!pk)
'       Next
'          
'    End If
' End
Public Sub User_defaults_Save_From_Contact_Manager(def As CRequestDefault)
   '---------------------------------------------------------------------------
   'The user is using the contacts manager, and has selected a provider category
   'FIXME - THERE IS NO VALIDATION OF THIS IN CONTACTS AS YET
   'to create as a default for the request section
   'First check if there is an entry for this user/category
   '----------------------------------------------------------------------------

   sql = "SELECT * From clin_requests.user_defaults_for_types WHERE "
   sql &= "fk_staff = " & def.fk_staff & " AND  fk_lu_type = " & def.fk_lu_type
   $Result = modDBConnect.exec_query(sql)
   If $Result.count Then
      def.pk_default = $Result!pk
   End If
   Default_Save(def)
   
End

Public Sub User_Defaults_Save(def As CRequestDefault)
   '   Saves Or updates user defaults, fix me make loop of all provider types
   
   ' sql = "INSERT INTO clin_requests.user_defaults_branches(fk_staff, fk_lu_type, fk_branch, fk_organisation) "
   '      "VALUES(  "
   ' sql = sql & fk_staff & "," & fk_lu_type & "," & fk_branch & "," & fk_organisation & ")"
   ' $Result = modDBConnect.exec_query(sql)
   $Result = modDBConnect.exec_query("BEGIN")
   Default_Save(def)
   $Result = modDBConnect.exec_query("COMMIT")

End

Public Sub Default_Save(def As CRequestDefault)
   '---------------------------------------------------
   'Saves a single RequestDefault for the current user
   '---------------------------------------------------

   If def.pk_default = 0 Then
      sql = "insert into clin_requests.user_defaults_for_types "
      "(fk_staff, fk_lu_type, fk_organisation, fk_branch) "
      "VALUES ("
      sql &= def.fk_staff & "," & def.fk_lu_type & "," 
      sql &= def.fk_organisation & "," & def.fk_branch & ")"
   Else
      '-------------------------------------------------------------
      'existing default for this staff member and type, so update it
      '-------------------------------------------------------------
      sql = "UPDATE clin_requests.user_defaults_for_types SET "
      sql = sql & "fk_organisation = " & def.fk_organisation & ","
      sql = sql & "fk_branch = " & def.fk_branch
      sql = sql & " WHERE pk = " & def.pk_default 
   End If
   $Result = modDBConnect.exec_query(sql)
   
End

Public Sub Providers_Get_For_Type(lv As Listview, provider_type As Integer, tl As TextLabel) 
   'Gets a list of providers for a given type  the organisation head office

   sql = "Select * from contacts.vwOrganisationsEmployees "
   "WHERE fk_employee = 0 AND head_office = True AND fk_category = "
   sql = sql & provider_type
    $Result = modDBConnect.exec_query(sql)
   If $Result.count Then 
      tl.Visible = False  
      lv.Clear
      For Each $Result 
         lv.Add(Str$($Result!fk_organisation), $Result!organisation)
      Next 
      '   listview1.tag = txtProviderType
      lv.Raise
      lv.Visible = True
   Else 
      'empty recordset
      lv.Visible = False
      tl.text = "<P><B>No providers found</B><P>"
      "No providers were found for this type of service "
      "in the contacts database. You should add these "
      "before proceeding"
      tl.Visible = True
   End If  

End

