' Gambas module file

' Copyright (C) 2008-2013 Dr. Richard Terry Dr. Ian Haywood

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.

' GLOBAL VARIABLES
' these will be eliminated over time

Public icpc2_immunization_code As String = "A44043"
Public icpc2_pathology_test_code As String = "A38002"
Public icpc2_radiology_test_code As String = "A41010"
Public globalstring As String
Public pcehrconsent_consented As Integer = 0
Public pcehrconsent_notconsented As Integer = 2
Public Const ProgressNotes_Date_Display_Date_Ascending As Integer = 0
Public Const ProgressNotes_Date_Display_Date_Descending As Integer = 1
Public iClinicalNotesDisplayOrder As Integer
Public Const Billingtype_AMA As Integer = 1
Public Const Billingtype_DVA_Non_LM0 As Integer = 2
Public Const Billingtype_DVA_LM0 As Integer = 3
Public Const Billingtype_Health_Care_Card_Concession As Integer = 4
Public Const Billingtype_Pensioner_Concession As Integer = 5
Public Const Billingtype_Private As Integer = 6
Public Const Billingtype_Transport_Accident_Commision_Victoria As Integer = 7
Public Const Billingtype_Scheduled_Fee As Integer = 8
Public Const Billingtype_Workcover As Integer = 9
' "1";"Bulk Bill"
' "2";"Private"
' "3";"Health Care Card Concession"
' "4";"Pensioner Concession"
' "5";"Medico-Legal"
' "1"; "None"
' "2"; "Commonwealth Seniors Health Card"
' "3"; "Health Care Card"
' "4"; "Pensioner Concession Card"

Public Const Centrelink_Concession_Card_None As Integer = 1
Public Const Centrelink_Concession_Card_Seniors_Health_Card As Integer = 2
Public Const Centrelink_Concession_Card_Health_Care_Card As Integer = 3
Public Const Centrelink_Concession_Card_Pensioner_concession_card As Integer = 4

Public Const cSmokerNever As Integer = 0
Public Const cSmokerPast As Integer = 1
Public Const cSmokerCurrent As Integer = 2
Public Const cSmokerUnknown As Integer = 3
Public Const cRecreational_Drug_Nicotine As Integer = 1
Public Const cRecreational_Drug_Alcohol As Integer = 2

Public Const Billing_Accounts_Paid As Integer = 0
Public Const Billing_Accounts_Unpaid As Integer = 1
Public Const Billing_Accounts_All As Integer = 2
Public Const Billing_Default_Level_BulkBill As Integer = 1
Public Const Billing_Default_Level_Private As Integer = 2
Public Const Billing_Default_Level_HealthCareCardConcession As Integer = 3
Public Const Billing_Default_Level_PensionerConcession As Integer = 4
Public Const Billing_Default_Level_MedicoLegal As Integer = 5

Public Const BulkBilling_Type_Medicare As Integer = 1
Public Const BulkBilling_Type_Veteran As Integer = 2
'Public Const TextBox_Focus_Background As ?? Color.rgb(95, 255, 175)
'fixme when stable load from backend
Public Const healthIssue_Major As Integer = 1
Public Const healthIssue_Significant As Integer = 2
Public Const HealthState_Inactive As Integer = 3

Public Const pbs_script_type_pbs As Integer = 1
Public Const pbs_script_type_pbs_authority As Integer = 2
Public Const pbs_script_type_pbs_authority_streamlined As Integer = 3
Public Const pbs_script_type_pbs_authority_increased_quantity As Integer = 4
Public Const pbs_script_type_rpbs As Integer = 5
Public Const pbs_script_type_rpbs_authority As Integer = 6
Public Const pbs_script_type_rpbs_authority_streamlined As Integer = 7
Public Const pbs_script_type_rpbs_authority_increased_quantity As Integer = 8
Public Const pbs_script_type_private As Integer = 9
Public Const pbs_script_type_section100 As Integer = 10

Public pbs_script_types As String[]

Public Const cSortASC As Integer = 1
Public Const cSortDESC As Integer = 2

Public Const cTaskRestriction_user As Integer = 1                     'display tasks for the user
Public Const cTaskRestriction_role As Integer = 2                     'display tasks for a role e.g all for secetaries
Public Const cTaskRestriction_document As Integer = 3                 'display tasks attatched to a document
Public Const cTaskRestriction_UserMustComplete As Integer = 4         'display tasks the user alone must finalise

Public Const cTaskCompletionNo As Integer = 1
Public Const cTaskCompletionYes As Integer = 2
Public Const cTaskCompletionAny As Integer = 3
' -------------
' Printer types
' -------------
Public Const Paper_Plain As Integer = 1
Public Const Paper_Script As Integer = 2
Public Const Paper_Request As Integer = 3
Public Const Paper_Long As Integer = 4
'-------
'seasons
'-------
Public Const season_summer As Integer = 1
Public Const season_autumn As Integer = 2
Public Const season_winter As Integer = 3
Public Const season_spring As Integer = 4

'-------------------------------------------------------
'document archiving see Documents.lu_storage_site
'-------------------------------------------------------
Public Const consult_type_at_Surgery As Integer = 1
Public Const document_message_standard_hl7 As Integer = 1
Public Const document_message_standard_pit As Integer = 2
Public Const document_message_standard_none As Integer = 3
Public Const schema_documents As Integer = 15 '?hard code these and put in the rest?
Public Const document_archive_filesystem As Integer = 1
Public Const document_archive_url As Integer = 2

Public Const Document_Display_As_Letter As Integer = 1
Public Const Document_Display_As_Result As Integer = 2
Public Const Document_Display_As_Certificate As Integer = 3
Public Const Document_Display_As_Image As Integer = 4
Public sDocumentType As String[]

Public Const ScanType_pdf As Integer = 1
Public Const ScanType_Image As Integer = 2
Public Const orientation_landscape As Integer = 2
Public Const orientation_portrait As Integer = 1
Public Const HealthState_Excellent As Integer = 1
Public Const HealthState_VeryGood As Integer = 2
Public Const HealthState_Good As Integer = 3
Public Const HealthState_Fair As Integer = 4
Public Const HealthState_Poor As Integer = 5
Public Const HealthState_Indeterminate As Integer = 6

Public K10_questions As Collection

Public Const aboriginality_none As Integer = 0
Public Const aboriginality_aboriginal As Integer = 1
Public Const aboriginality_Torres_Strait_Islander As Integer = 2
Public Const language_english As Integer = 22 'common
Public Const defaults_PrintingTask_Prescription As Integer = 1
Public Const defaults_PrintingTask_BriefPI As Integer = 5
Public Const defaults_PrintingTask_FullPI As Integer = 6
'some ethnicities for importing data for conventience
Public Const ethnicity_australian As Integer = 18
Public Const ethnicity_australian_aboriginal As Integer = 19
Public Const ethnicity_british As Integer = 29
Public Const ethnicity_canadian As Integer = 34
Public Const ethnicity_chinese As Integer = 40
Public Const ethnicity_vietnamese As Integer = 211
Public Const ethnicity_American As Integer = 10
Public Const ethnicity_Austrian As Integer = 20
Public Const ethnicity_brazilian As Integer = 28
Public Const ethnicity_Chilean As Integer = 39
Public Const ethnicity_Cypriot_Unspecified As Integer = 49
Public Const ethnicity_Dutch As Integer = 53
Public Const ethnicity_French As Integer = 67
Public Const ethnicity_German As Integer = 70
Public Const ethnicity_Greek As Integer = 71
Public Const ethnicity_Hungarian As Integer = 81
Public Const ethnicity_Indian As Integer = 84
Public Const ethnicity_Indonesian As Integer = 85
Public Const ethnicity_Irish As Integer = 89
Public Const ethnicity_Italian As Integer = 91
Public Const ethnicity_Malay_Malayan As Integer = 109
Public Const ethnicity_Korean As Integer = 99
Public Const ethnicity_Lebanese As Integer = 104
Public Const ethnicity_Mauritian As Integer = 121
Public Const ethnicity_Mexican As Integer = 122
Public Const ethnicity_New_Zealand_Maori As Integer = 133
Public Const ethnicity_New_Zealand_European As Integer = 132
Public Const ethnicity_Polish As Integer = 158
Public Const ethnicity_Russian As Integer = 168
Public Const ethnicity_South_African As Integer = 185
Public Const ethnicity_Spanish As Integer = 189
Public Const ethnicity_japanese As Integer = 93
Public Const ethnicity_Cambodian_Khmer As Integer = 98
Public Const ethnicity_swedish As Integer = 192
Public Const ethnicity_Swiss As Integer = 193
Public Const ethnicity_Thai_Tai_Siamese As Integer = 197
Public Const ethnicity_Romanian As Integer = 165
Public Const ethnicity_Romanian_Gypsy As Integer = 166
Public Const ethnicity_Ukrainian As Integer = 207

Public Const defaults_PrintingTask_Pathology As Integer = 2
Public Const defaults_PrintingTask_Workcover As Integer = 3
Public Const defaults_PrintingTask_PlainPaper As Integer = 4

Public pregnancy_categories As Collection

Public Const PrivateHealthFund_None As Integer = 1
Public Const AnatomicalLocation_Left As Integer = 1
Public Const AnatomicalLocation_Right As Integer = 2
Public Const AnatomicalLocation_Both As Integer = 3
Public Const AnatomicalLocation_LeftRight As Integer = 4
Public Const AnatomicalLocation_Superior As Integer = 5
Public Const AnatomicalLocation_Inferior As Integer = 6
Public Const AnatomicalLocation_Anterior As Integer = 7
Public Const AnatomicalLocation_Posterior As Integer = 8
Public Const AnatomicalLocation_Medial As Integer = 9
Public Const AnatomicalLocation_MedioLateral As Integer = 10
Public Const AnatomicalLocation_Lateral As Integer = 11
Public Const AnatomicalLocation_Proximal As Integer = 12
Public Const AnatomicalLocation_Distal As Integer = 13
Public Const AnatomicalLocation_Proximodistal As Integer = 14
Public Const AnatomicalLocation_Erect As Integer = 15
Public Const AnatomicalLocation_Supine As Integer = 16
Public Const AnatomicalLocation_Cephalic As Integer = 17
Public Const AnatomicalLocation_Caudal As Integer = 18
Public Const AnatomicalLocation_Dorsal As Integer = 19
Public Const AnatomicalLocation_Ventral As Integer = 20
Public Const AnatomicalLocation_Horizontal As Integer = 21
Public Const AnatomicalLocation_Transverse As Integer = 22
Public Const AnatomicalLocation_Sagittal As Integer = 23
Public Const AnatomicalLocation_Coronal As Integer = 24
Public Const AnatomicalLocation_Ipsilateral As Integer = 25
Public Const AnatomicalLocation_Contralateral As Integer = 26
Public Const AnatomicalLocation_Superficial As Integer = 27
Public Const AnatomicalLocation_Deep As Integer = 28
Public Const AnatomicalLocation_Mid As Integer = 52
'complete the above 29>51
Public Const cScopeCurrentUser As Integer = 1
Public Const cScopeAllUsers As Integer = 2

Public Const cDisplay_All As Integer = 1
Public Const cDisplay_Current As Integer = 2

Public Const certificate_type_medical As Integer = 1
Public Const certificate_type_workcover As Integer = 2
Public Const certificate_type_government As Integer = 3
Public Const certificate_type_insurance As Integer = 4

Public Const coding_none_selected As Integer = 0
Public Const coding_icpcPlus As Integer = 1
Public Const coding_icd10 As Integer = 2
Public Const coding_freecodes As Integer = 3
Public Const coding_snomed As Integer = 4
Public Const coding_docle As Integer = 5
Public Const coding_loinc As Integer = 6

Public Const mentalhealth_assessmentdistresstool_DASS As Integer = 1
Public Const mentalhealth_assessmentdistresstool_K10 As Integer = 2

Public Const mentalhealth_risk_none As Integer = 1
Public Const mentalhealth_risk_low As Integer = 2
Public Const mentalhealth_risk_medium As Integer = 3
Public Const mentalhealth_risk_high As Integer = 4
Public Const mentalhealth_risk_undefined As Integer = 5
Public Const mentalhealth_plantype_initial As Integer = 1
Public Const mentalhealth_plantype_review As Integer = 2
Public smentalhealth_risk As New String[] 'was 6

Public Const coding_role_diagnosis As Integer = 1
Public Const coding_role_symptom As Integer = 2 ' a non-diagnostic reason for consult
Public Const coding_role_pathology As Integer = 3
Public Const coding_role_radiology As Integer = 4
Public Const coding_role_anatomy As Integer = 5
Public Const coding_role_operation As Integer = 6

Public Const ImportDemographics_Rebuild As Integer = 0
Public Const ImportDemographics_Update As Integer = 1
Public Const ImportDemographics_AddNew As Integer = 2

'Schema Admin  lu_staff_type, in no particular order, names for no particular reason just embryonic
Public Const StaffType_Administrative As Integer = 0
Public Const StaffType_Maintenance As Integer = 1
Public Const StaffType_Medical As Integer = 2
Public Const StaffType_MentalHealth As Integer = 3
Public Const StaffType_Nursing As Integer = 4
Public Const StaffType_Paramedical As Integer = 5
Public Const StaffType_Secretarial As Integer = 6
Public Const StaffType_Specialist As Integer = 7
Public Const StaffType_Locum As Integer = 8

'Schema admin Working Status in no particular order, names for no particular reason just embryonic
Public Const StaffStatus_Active As Integer = 0
Public Const StaffStatus_InActive As Integer = 1
Public Const StaffStatus_LeftOrganisation As Integer = 2
Public Const StaffStatus_OnLeave As Integer = 3
'key to clerical.lu_active_status for patients
Public Const PatientStatus_Active As Integer = 1
Public Const PatientStatus_Inactive As Integer = 2

Public Const Veteran_Entitlement_None As Integer = 1
Public Const Veteran_Entitlement_Full As Integer = 2
Public Const Veteran_Entitlement_Specific As Integer = 3
Public Const Veteran_Entitlement_WarWidow As Integer = 4
Public Const Concession_Entitlement_None As Integer = 1

'schema admin lu_roles in no particular order, names for no particular reason just embryonic
Public Const StaffRole_SysAdmin As Integer = 0
Public Const StaffRole_Clinical As Integer = 1
Public Const StaffRole_Clerical As Integer = 2
Public Const StaffRole_Both As Integer = 3
Public Const StaffRole_Doctor As Integer = 1
' "0";"sysadmin"
' "1";"doctor"
' "2";"dentist"
' "3";"locum""
' "4";"student"
' "5";"registered nurse"
' "6";"practice manager"
' "7";"secretary"
' "8";"information technology"
' "9";"counselor"
' "10";"enrolled nurse"
' "11";"dietitian"
' "12";"psychologist"
'

Public Const cAuditAction_Insert As Integer = 1
Public Const cAuditAction_Edit As Integer = 2
Public Const cAuditAction_Delete As Integer = 3 'I don't think this is used (is - check the inbox)
Public Const cAuditAction_MarkDeleted As Integer = 4
Public Const cAuditAction_Reversal As Integer = 5
Public Const cAuditAction_Completed As Integer = 6
Public Const cAuditAction_CompletedWithExplanation As Integer = 7
Public Const cAuditAction_CompletedRepeatSameInterval As Integer = 8
Public Const cAuditAction_CompletedRepeatNewInterval As Integer = 9
Public Const cAuditAction_Refused As Integer = 10
Public Const cAuditAction_RefusedWithExplanation As Integer = 11
Public Const cAuditAction_MakeActive As Integer = 12
Public Const cAuditAction_MakeInactive As Integer = 13
Public Const cAuditAction_MakeSignificant As Integer = 14
Public Const cAuditAction_MakeMajor As Integer = 15
Public Const cAuditAction_NotDue As Integer = 16
Public Const cAuditAction_OverDue As Integer = 17
Public Const cAuditAction_ReminderSent As Integer = 18
Public Const cAuditAction_ArrangedNotCompleted As Integer = 19
Public Const cAuditAction_FileImport As Integer = 20
Public Const cAuditAction_ViewedAndFiledDocument As Integer = 21
Public Const cAuditAction_StaffTaskAllocated As Integer = 22
Public Const cAuditAction_StaffTaskFinalised As Integer = 23
Public Const cAuditAction_NoteOnTask As Integer = 24
Public Const cAuditAction_TaskComponentFinalised As Integer = 25
Public Const cAuditAction_ScannedDocumentImported As Integer = 26
Public Const cAuditAction_ReScheduled As Integer = 27
Public Const cAuditAction_DeleteDuplicateDocument As Integer = 28
Public Const cAuditAction_DeletePreliminaryResult As Integer = 29
Public Const cAuditAction_UnDelete As Integer = 30
Public Const cAuditAction_DocumentDisplayModeChanged As Integer = 31
Public Const cAuditAction_Refile As Integer = 32
Public Const cAuditAction_DeleteSentInError As Integer = 33
Public Const cAuditAction_MovedToLibrary As Integer = 34
Public Const cAuditAction_ProgressNoteEdited As Integer = 35

Public sAuditAction As New String[]
' Public Const cAuditAction_MarkDeleted As Integer = 4
'fix me these need to be eliminated
Public Const cScratchPadItem_Active As Integer = 1
Public Const cScratchPadItem_Inactive As Integer = 2

Public Const globalpreference_archive_filesystem As Integer = 1
Public Const globalpreference_archive_database As Integer = 2
Public Const globalpreference_archive_web As Integer = 3
'Type of progress note
Public Const cSection_GeneralNotes As Integer = 0
Public Const cSection_PastHistory As Integer = 1
Public Const cSection_progressnotes As Integer = 2
Public Const cSection_FamilyHistory As Integer = 3
Public Const cSection_SocialHistory As Integer = 4
Public Const cSection_OccupationalHistory As Integer = 5
Public Const cSection_Measurements As Integer = 6
Public Const cSection_Excisions As Integer = 7
Public Const cSection_Inbox As Integer = 8
Public Const cSection_Travel As Integer = 9
Public Const cSection_Workcover As Integer = 10
Public Const cSection_MentalHealth As Integer = 11
Public Const cSection_AnnualCheckup As Integer = 12
Public Const cSection_StaffTasks As Integer = 13
Public Const cSection_Referrals As Integer = 14
Public Const cSection_Vaccination As Integer = 15
Public Const cSection_Requests As Integer = 16
Public Const cSection_Recalls As Integer = 17
Public Const cSection_Prescriptions As Integer = 18
Public Const cSection_allergies As Integer = 19
Public Const cSection_Documents As Integer = 20
Public Const cSection_Images As Integer = 21    'fixme in back end
Public Const cSection_CarePlan As Integer = 22   'fixme in back end
Public Const cSection_MedicalCertificates As Integer = 23   'fixme in back end
Public Const cSection_HealthSummary As Integer = 24             'fixme not in the back end
Public Const cSection_RecreationalDrugs As Integer = 25    'fixme not in the back end
Public Const cSection_INR_Management As Integer = 26   'fixme not in the backend.
'type of consultation
Public Const Inbox_Pathology As Integer = 1
Public Const Inbox_Imaging As Integer = 2
Public Const Inbox_Provider_letters As Integer = 3
Public Const Inbox_ScannedDocuments As Integer = 4

Public Const ConsultType_Rooms As Integer = 1
Public Const ConsultType_Telephone As Integer = 2
Public Const ConsultType_HomeVisit As Integer = 3
Public Const ConsultType_Email As Integer = 4
Public Const ConsultType_CaseConference As Integer = 5
Public Const ConsultType_NursingHome As Integer = 6
Public Const ConsultType_TeleConference As Integer = 7
Public Const ConsultType_ReviewOfCorrespondance As Integer = 8 'eg Doctor is checking the inbox/letters etc

Public Const ConsultType_NotesPatientNotPresent As Integer = 9
Public Const ConsultType_DataImport As Integer = 10
Public Const ConsultType_AuditNote As Integer = 11
Public Const ConsultType_Added_From_Inbox As Integer = 12

'Reference table: common.lu_laterality
Public Const LateralityNone As Integer = 0
Public Const LateralityLeft As Integer = 1
Public Const LateralityRight As Integer = 2
Public Const LateralityBoth As Integer = 3
Public Const LateralityMidline As Integer = 4
Public LateralityText As New String[] 'was 5

'common lu_appointment_length
Public Const AppointmentLengthBrief As Integer = 0
Public Const AppointmentLengthStandard As Integer = 1
Public Const AppointmentLengthLong As Integer = 2
Public Const AppointmentLengthProlonged As Integer = 3

'clerical.lu_appointment_status
Public Const Appointment_Status_Completed As Integer = 4
'common lu_contact_method
Public Const Procedure_Suturetype_Skin As Integer = 2
Public Const Procedure_Suturetype_Subcutaneous As Integer = 1

Public Const ContactMethodLetter As Integer = 0
Public Const ContactMethodEmail As Integer = 12
Public Const ContactMethodPhone As Integer = 2
Public Const ContactMethodMobile As Integer = 2
Public Const AddressType_Home As Integer = 0
Public Const AddressType_Work As Integer = 1
Public Const AddressType_POBox As Integer = 2
Public Const AddressType_Parents As Integer = 3
Public Const AddressType_NursingHome As Integer = 4
Public Const AddressType_Refuge As Integer = 5

Public Const drugform_tablet As Integer = 59

Public Const AllowKeys_Letters As Integer = 1
Public Const AllowKeys_NumbersOnly As Integer = 2
Public Const AllowKeys_BP As Integer = 3
Public Const AllowKeys_NumbersDecimal As Integer = 4
Public Const AllowKeys_AgeFormat As Integer = 5
Public Const AllowKeys_SQLCrash As Integer = 6
Public Const AllowKeys_DateFormat As Integer = 7 'allow on eg mm/dd/yyyy
Public Const AllowKeys_Date_DWMY As Integer = 8 ' allow eg mm / dd / yyy Or 'y' or 'Y' or 'm' or 'M'
Public Const AllowKeys_YesNo As Integer = 9
Public Const AllowKeys_InputMask As Integer = 10
Public Const AllowKeys_Numbers_D_M_Y As Integer = 11 'allows eg 10M or 10D or 10Y
Public Const AllowKeys_AtoZ As Integer = 12
Public Const AllowKeys_AtoZ_UpDown_Arrows As Integer = 13
Public Const AllowKeys_Letters_Numbers As Integer = 14
Public Const AllowKeys_Letters_Numbers_slash_dash_period As Integer = 15
Public Const AllowKeys_Letters_Numbers_slash_apostrophe_dash As Integer = 16
Public Const AllowKeys_money As Integer = 17

Public Const Suturesite_SubCutaneous As Integer = 1
Public Const SutureSite_Skin As Integer = 2

'Care Planning
Public Const cCarePlanTemplateNone As Integer = 0      'create care plan from scratch
Public Const cCarePlanTemplateExisting As Integer = 1  'use an existing template
Public Const cCarePlanTemplateNew As Integer = 2       'make a whole new template

'Message box buttons
Public Const Yes As Integer = 1
Public Const No As Integer = 2

'for contacts same as contacts.lu_contact_type, ie way people are contacted
Public Const CommModalityHome As Integer = 0
Public Const CommModalityWork As Integer = 1
Public Const CommModalityFax As Integer = 2
Public Const CommModalityEmail As Integer = 3
Public Const CommModalityMobile As Integer = 4
Public Const CommModalityVOIP As Integer = 5
Public Const CommModalityWeb As Integer = 6
Public Const CommModalityPhone As Integer = 7
Public Const CommModalityTollFree As Integer = 8
Public Const CommModalityLetter As Integer = 9
Public Const CommModalityPhoneAfterHours As Integer = 10

Public CommModalityTextFull As New String[] 'was 10
Public CommModalityTextBrief As New String[] 'was 10

'security access clinical only in some fashion
Public Const Security_Clinical_Full As Integer = 0
Public Const Security_Clinical_ReadOnly As Integer = 1

'security acess clerical only in some fashion
Public Const Security_Clerical_Full As Integer = 2
Public Const Security_Clerical_ReadOnly As Integer = 3

'security acess both clerical and clerical only in some fashion
Public Const Security_Clinical_Full_Clerical_Full As Integer = 4
Public Const Security_Clinical_Full_Clerical_ReadOnly As Integer = 5
Public Const Security_Clerical_Full_Clinical_ReadyOnly As Integer = 6

'sex
Public Const cSexMale As Integer = 0
Public Const cSexFemale As Integer = 1
Public Const cSexUnknown As Integer = 2
'------------------------------------------------------------
'These should be same as contacts.lu_title table primary key
'------------------------------------------------------------
Public Const ctitleMr As Integer = 0
Public Const ctitleMrs As Integer = 1
Public Const ctitleMaster As Integer = 2
Public Const ctitleMiss As Integer = 3
Public Const ctitleDr As Integer = 4
Public Const ctitleProf As Integer = 5
Public Const ctitleMs As Integer = 6
Public Const ctitleUnKnown As Integer = 7

'Status Bar Constants
Public Const cStatusMsg_Info As Integer = 0
Public Const cStatusMsg_Warning As Integer = 1
Public Zoom As New Integer[] 'was 7

'Drug Reference Full
Public Const DrugRefFull_SearchProduct As Integer = 0
Public Const DrugRefFull_SearchGeneric As Integer = 1
Public Const DrugRefFull_SearchIndication As Integer = 2

'----------------------------------------------------------------
'Referrals: in the same order as the clin_referrals.lu_type table
'----------------------------------------------------------------
Public Const ReferralType_Opinion As Integer = 1
Public Const ReferralType_OpinionAndManagement As Integer = 2
Public Const ReferralType_RequestForInvestigation As Integer = 3
Public Const ReferralType_Feedback As Integer = 4
Public Const ReferralType_Indefinate As Integer = 5
Public Const ReferralType_ImmediateTreatment As Integer = 6
Public Const ReferralType_Education As Integer = 7
Public Const ReferralType_Admission As Integer = 8
Public Const ReferralType_Management As Integer = 9
Public Const ReferralType_Recall As Integer = 10
Public Const ReferralType_ImportedLetter As Integer = 11
Public Const ReferralType_ImportedRecall As Integer = 12
Public Const ReferralType_NonMedicare As Integer = 13

'note the mix up database contacts.lu_type = the comm_type, not this. FIXME
Public Const contacttype_organisation As Integer = 1
Public Const contacttype_employee As Integer = 2
Public Const contacttype_person As Integer = 3
Public Const contacttype_patient As Integer = 4
Public Const contacttype_branch As Integer = 5
Public Const contacttype_PersonsAndPatients As Integer = 6

'-------
'Recalls
'-------
Public Const UrgencyLevelRoutine As Integer = 1
Public Const UrgencyLevelModerate As Integer = 2
Public Const UrgencyLevelUrgent As Integer = 3
Public Const UrgencyLevelMustNotMiss As Integer = 4
'status
Public Const RecallNotDue As Integer = 1
Public Const RecallOverdue As Integer = 2
Public Const RecallReminderSent As Integer = 3
Public Const RecallArrangedNotCompleted As Integer = 4
Public Const RecallCompleted As Integer = 5
Public Const RecallRefused As Integer = 6
'status eg 0 = outstanding, 1 = arranged not completed, 2 = completed 3 = refused

'Database stuff
Public Const Database_Type_Postgresql As Integer = 0
Public Const Database_Type_Mysql As Integer = 1
Public Const Database_Type_SqlLite As Integer = 2
Public Const Database_Type_ODBC As Integer = 3
Public Const Database_Type_Firebird As Integer = 4

'Workcover stuff
Public Const Workcover_VisitType_Initial As Integer = 1
Public Const Workcover_VisitType_Progress As Integer = 2
Public Const Workcover_VisitType_Final As Integer = 3
Public Const Workcover_VisitType_InitialAndFinal As Integer = 4

Public Const Workcover_Fitness_PreInjury As Integer = 1
Public Const Workcover_Fitness_Unfit As Integer = 2
Public Const Workcover_Fitness_Suitable As Integer = 3
Public Const Workcover_Fitness_PermanantlyModified As Integer = 4

Public Const Workcover_CausedByEmployment_Yes As Integer = 1
Public Const Workcover_CausedByEmployment_No As Integer = 2
Public Const Workcover_CausedByEmployment_Uncertain As Integer = 3

'----------------------------------------------------------
'types of requests from clin_requests.lu_request_type table
'----------------------------------------------------------
Public Const Request_Type_Pathology As Integer = 1
Public Const Request_Type_Radiology As Integer = 2
Public Const Request_Type_Physiotherapy As Integer = 3
Public Const Request_Type_Cardiovascular As Integer = 4
Public Const Request_Type_Vascular As Integer = 5
Public Const Request_Type_Neurology As Integer = 6
Public Const Request_Type_Obstetrics As Integer = 7
Public Const Request_Type_Respiratory As Integer = 8
Public Const Request_Type_Podiatry As Integer = 9
Public Const Request_Type_Audiology As Integer = 10
Public Const Request_Type_NuclearMedicine As Integer = 11
Public Const Request_Type_Ophthalmology As Integer = 12
Public Const Request_Type_Gastroenterology As Integer = 13

'request specific
Public Const Request_CopyTo_Person As Integer = 1
Public Const Request_CopyTo_Organisation As Integer = 2  'fix me, fix this overall lack of
'distinction between branch and organisation
Public Const Request_CopyTo_Employee As Integer = 3    'employee always lives in a branch/organisation
Public Const Request_CopyTo_Patient As Integer = 4
Public Const Request_CopyTo_AnyPatient As Integer = 5

'units of measurements = common.lu_units table
Public Units_Text As Collection
Public Const Units_stat As Integer = 1
Public Const Units_millisecond As Integer = 2
Public Const Units_second As Integer = 3
Public Const Units_minute As Integer = 4
Public Const Units_hour As Integer = 5
Public Const Units_day As Integer = 6
Public Const Units_week As Integer = 7
Public Const Units_month As Integer = 8
Public Const Units_year As Integer = 9
Public Const Units_nanometer As Integer = 10
Public Const Units_micrometer As Integer = 11
Public Const Units_millimeter As Integer = 12
Public Const Units_centimeter As Integer = 13
Public Const Units_meter As Integer = 14
Public Const Units_kilometer As Integer = 15
'16-20 current radiofrequency HZ measurments not used

Public Const Units_micromole As Integer = 21
Public Const Units_millimole As Integer = 22

Public Const Units_mole As Integer = 23
Public Const Units_decilitre As Integer = 24
Public Const Units_centilitre As Integer = 25
Public Const Units_millilitre As Integer = 26
Public Const Units_microlitre As Integer = 27
Public Const Units_nanolitre As Integer = 28
Public Const Units_picolitre As Integer = 29
Public Const Units_femtolitre As Integer = 30
Public Const Units_litre As Integer = 31
Public Const Units_degree As Integer = 32
Public Const Units_picogram As Integer = 33
Public Const Units_milligram As Integer = 34
Public Const Units_gram As Integer = 35
Public Const Units_kilogram As Integer = 36
Public UnitsText As New String[] 'was 37
''these are probably temporary as stupid way
Public Measurement_Types As Collection
Public Const Measurement_BP As Integer = 1
Public Const Measurement_Weight As Integer = 2
Public Const Measurement_PeakFlow As Integer = 3
Public Const Measurement_Height As Integer = 4

'These will be moved into the database as 'must do' graphing FIXME
'i.e even if these results are normal they will be traphed in the inbox
Public Loinc_EGFR As String = "33914-3"
Public Loinc_HBA1c As String = "4548-4"
Public Loinc_HBA1c_ngsp As String = "17858-6"
Public Loinc_hbaic_fcc As String = "59261-8"
Public Loinc_INR As String = "6301-6"
Public Loinc_UltraSensPSA As String = "35741-8"
Public Loinc_TotalPSA As String = "2857-1"
Public Loinc_Spot_RUAlbCreatRatio As String = "14959-1"
Public Loinc_Spot_ProtCreatRatio As String = "2890-2"
Public Loinc_Spot_Urine_Albumin As String = "14957-5"
Public Loinc_CEA As String = "2039-6"
Public loinc_Timed_UrineAlbumin_Excretion As String = "14956-7"

Public Loinc_LDL As String = "22748-8"
Public Loinc_TotalCholesterol As String = "14647-2"
Public Loinc_HDL As String = "14646-4"
Public Loinc_Triglycerides As String = "14927-8"
Public Loinc_FreeT3 As String = "14928-6"
Public Loinc_FreeF4 As String = "14920-3"
Public Loinc_TSH As String = "3016-3"
Public Loinc_CReactiveProtein As String = "1988-5"
Public Loinc_ESR As String = ""
Public Loinc_UricAcid As String = "3084-1"
Public Loinc_Creatinine_Serum As String = "14682-9"

Public Const ClinicalNotesSection_PastHistory As Integer = 1
Public Const ClinicalNotesSection_FamilyHistory As Integer = 2
Public Const ClinicalNotesSection_Prescriptions As Integer = 3
Public Const ClinicalNotesSection_Requests As Integer = 4
Public Const ClinicalNotesSection_ReferralLetter As Integer = 5
Public Const ClinicalNotesSection_Measurements As Integer = 6
Public Const ClinicalNotesSection_GeneralNotes As Integer = 7
Public Const ClinicalNotesSection_Vaccination As Integer = 8
Public Const ClinicalNotesSection_Travel As Integer = 9
Public Const ClinicalNotesSection_Workcover As Integer = 10
Public Const ClinicalNotesSection_MentalHealth As Integer = 11
Public Const ClinicalNotesSection_AnnualCheckup As Integer = 12
Public Const ClinicalNotesSection_SocialHistory As Integer = 13
Public Const ClinicalNotesSection_Recalls As Integer = 14
Public Const ClinicalNotesSection_ScratchPad As Integer = 15
Public Const ClinicalNotesSection_Inbox As Integer = 16
Public Current_ClinicalNotes_Section As Integer
'----------------
'File i/o errors
'----------------
Public Const File_ioError_Out_of_memory As Integer = 1
Public Const File_ioError_Access_Forbidden As Integer = 43
Public Const File_ioError_File_is_directory As Integer = 46
Public Const File_ioError_File_Non_Existant As Integer = 45
Public Const File_ioError_Device_Full As Integer = 37
Public Const File_ioError_FileExists As Integer = 38
Public Const File_ioError_DirectoryExists As Integer = 38 'check this ?? FIXME
Public Const File_ioError_System_Error As Integer = 42
Public File_Errors As String[]

'----------------------------------
'routes of substance administration
'----------------------------------
Public Const route_administration_intramuscular As Integer = 1
Public Const route_administration_subcutaneous As Integer = 2
Public Const route_administration_intramuscular_or_subcutaneous As Integer = 3
Public Const route_administration_intradermal As Integer = 4
Public Const route_administration_oral As Integer = 5
Public Const route_administration_intranasal As Integer = 6
Public Const route_administration_inhaled As Integer = 7
Public Const route_administration_topical As Integer = 8
Public Const route_administration_intravenous As Integer = 11
'allergies
Public Const ReactionType_Allergy As Integer = 1
Public Const ReactionType_Sensitivity As Integer = 2

Public ReactionSpecificity_Class As String = "c"
Public ReactionSpecificity_Brand As String = "b"
Public ReactionSpecificity_Generic As String = "g"
Public Clinical_Toolbuttons As Collection

Public User_Synonyms As Collection

Public Function Synonyms() As Collection
   '--------------------------------------------------------------
   'Loads synonyms for user terms/pathology terms from the backend
   'called by FInbox, FClinical, FSendRecalls
   '--------------------------------------------------------------

   If IsNull(User_Synonyms) Then
      User_Synonyms = modInboxDBI.Sender_User_Synonyms_get()
   Endif
   Return User_Synonyms

End

Public Sub init()

   Dim collection_member As Collection

   zoom.Add(20)
   zoom.Add(60)
   zoom.Add(70)
   zoom.Add(75)
   zoom.Add(85)
   zoom.Add(95)
   CommModalityTextFull.resize(10)
   CommModalityTextFull[0] = "Home"
   CommModalityTextFull[1] = "Work"
   CommModalityTextFull[2] = "Fax"
   CommModalityTextFull[3] = "Email"
   CommModalityTextFull[4] = "Mobile"
   CommModalityTextFull[5] = "Voip"
   CommModalityTextFull[6] = "www"
   CommModalityTextFull[7] = "Phone"
   CommModalityTextFull[8] = "Toll Free"
   CommModalityTextFull[9] = "Letter"
   CommModalityTextBrief.Resize(10)
   CommModalityTextBrief[0] = "H"
   CommModalityTextBrief[1] = "W"
   CommModalityTextBrief[2] = "F"
   CommModalityTextBrief[3] = "E"
   CommModalityTextBrief[4] = "M"
   CommModalityTextBrief[5] = "V"
   CommModalityTextBrief[6] = "I"
   CommModalityTextBrief[7] = "P"
   CommModalityTextBrief[8] = "TF"
   CommModalityTextBrief[9] = "L"
   LateralityText.Resize(5)
   LateralityText[LateralityNone] = "none"
   LateralityText[LateralityLeft] = "left"
   LateralityText[LateralityRight] = "right"
   LateralityText[LateralityBoth] = "both"
   LateralityText[LateralityMidline] = "midline"
   smentalhealth_risk.Resize(6)
   smentalhealth_risk[const.mentalhealth_risk_none] = "None"
   smentalhealth_risk[const.mentalhealth_risk_medium] = "Medium"
   smentalhealth_risk[const.mentalhealth_risk_low] = "Low"
   smentalhealth_risk[const.mentalhealth_risk_high] = "High"
   smentalhealth_risk[const.mentalhealth_risk_undefined] = "Undefined"
   unitstext.resize(10) 'fix me most unused in the array, use .Add

   'FIXME load these from backend.
   sAuditAction.resize(36) 'one more than needed 0=not used
   sAuditAction[cAuditAction_Insert] = "insert"
   sAuditAction[cAuditAction_Edit] = "edit"
   sAuditAction[cAuditAction_Delete] = "delete"
   sAuditAction[cAuditAction_MarkDeleted] = "mark deleted"
   sAuditAction[cAuditAction_Reversal] = "reversal"
   sAuditAction[cAuditAction_Completed] = "completed"
   sAuditAction[cAuditAction_CompletedWithExplanation] = "completed with explanation"
   sAuditAction[cAuditAction_CompletedRepeatSameInterval] = "completed repeat same interval"
   sAuditAction[cAuditAction_CompletedRepeatNewInterval] = "completed repeat new interval"
   sAuditAction[cAuditAction_Refused] = "refused"
   sAuditAction[cAuditAction_RefusedWithExplanation] = "refused with explanation"
   sAuditAction[cAuditAction_MakeActive] = "make active"
   sAuditAction[cAuditAction_MakeInactive] = "make inactive"
   sAuditAction[cAuditAction_MakeSignificant] = "make significant"
   sAuditAction[cAuditAction_MakeMajor] = "make major"
   sAuditAction[cAuditAction_NotDue] = "not due"
   sAuditAction[cAuditAction_OverDue] = "overdue"
   sAuditAction[cAuditAction_ReminderSent] = "reminder sent"
   sAuditAction[cAuditAction_ArrangedNotCompleted] = "arranged not completed"
   sAuditAction[cAuditAction_FileImport] = "file import"
   sAuditAction[cAuditAction_ViewedAndFiledDocument] = "viewed and filed document"
   sAuditAction[cAuditAction_StaffTaskAllocated] = "staff task allocated"
   sAuditAction[cAuditAction_StaffTaskFinalised] = "staff task finalised"
   sAuditAction[cAuditAction_NoteOnTask] = "note on task"
   sAuditAction[cAuditAction_TaskComponentFinalised] = "task component finalised"
   sAuditAction[cAuditAction_ScannedDocumentImported] = "scanned document imported"
   sAuditAction[cAuditAction_ReScheduled] = "re-scheduled"
   sAuditAction[cAuditAction_DeleteDuplicateDocument] = "delete - duplicate document"
   sAuditAction[cAuditAction_DeletePreliminaryResult] = "delete - preliminary result"
   sAuditAction[cAuditAction_UnDelete] = "undelete"
   sAuditAction[cAuditAction_DocumentDisplayModeChanged] = "document display mode changed"
   sAuditAction[cAuditAction_Refile] = "return for re-filing"
   sAuditAction[cAuditAction_DeleteSentInError] = "delete - sent in error"
   sAuditAction[cAuditAction_MovedToLibrary] = "moved to library"
   sAuditAction[cAuditAction_ProgressNoteEdited] = "progress notes edited"

   pbs_script_types = New String[11]     'fixme get me from backend or cache 0 not used
   pbs_script_types[pbs_script_type_pbs] = "PBS"
   pbs_script_types[pbs_script_type_pbs_authority] = "PBS AUTHORITY"
   pbs_script_types[pbs_script_type_pbs_authority_streamlined] = "PBS AUTHORITY STREAMLINED"
   pbs_script_types[pbs_script_type_rpbs] = "RPBS"
   pbs_script_types[pbs_script_type_rpbs_authority] = "RPBS AUTHORITY"
   pbs_script_types[pbs_script_type_rpbs_authority_streamlined] = "RPBS AUTHORITY STREAMLINED"
   pbs_script_types[pbs_script_type_private] = "PRIVATE"
   pbs_script_types[pbs_script_type_section100] = "SECTION 100"
   pbs_script_types[pbs_script_type_pbs_authority_increased_quantity] = "PBS AUTHORITY INCREASED QUANTITY"
   pbs_script_types[pbs_script_type_rpbs_authority_increased_quantity] = "RPBS AUTHORITY INCREASED QUANTITY"

   sDocumentType = New String[5]
   sDocumentType[const.Document_Display_As_Certificate] = "Certificate"
   sDocumentType[const.Document_Display_As_Image] = "Image"
   sDocumentType[const.Document_Display_As_Letter] = "Letter"
   sDocumentType[const.Document_Display_As_Result] = "Result"

   'FIXME at some point just import these, but check how text in fields fits in first
   '------------------
   'init units as text
   '------------------
   UnitsText[Units_week] = "week"
   UnitsText[Units_year] = "year"
   UnitsText[Units_day] = "day"
   UnitsText[Units_month] = "month"

   File_Errors = New String[47]
   File_Errors[1] = "Out of Memory"
   File_Errors[37] = "Device Full"
   File_Errors[38] = "File Exists"
   File_Errors[42] = "I/O System Error"
   File_Errors[43] = "Access Forbidden"
   File_Errors[45] = "File Non Existant"
   File_Errors[46] = "File is a Directory"

   units_text = modMeasurementsDBI.Units_Get_Text()
   Measurement_Types = modMeasurementsDBI.Get_Types()
   Clinical_Toolbuttons_Refresh()

End

Public Sub Clinical_Toolbuttons_Refresh()

   Clinical_Toolbuttons = modStartUp.Clinical_Modules_Get()

End
