' Gambas module file
' Copyright (C) 2008,2009 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------
' Database routines for EasyGP.Common schema
'----------------------------------------------------------------------

Public Function Seasons_Get(Optional season As String) As Collection

   Dim sql As String
   sql = "Select * from common.lu_seasons "
   If season <> "" Then
      sql &= " WHERE season ILIKE $$%" & season & "%$$ "
   Endif
   Return modDBConnect.exec_query_collection(sql)
   
End

Public Function Religions_Get(Optional sub_religion As String) As Collection
   '-----------------------------------------------------------------
   'Returns a collection of religion/subreligion where the collection 
   'pk_view is a compound key (see the def of this view)
   '-----------------------------------------------------------------
   
   Dim sql As String

   sql = "Select * from common.vwReligions "
   If sub_religion <> "" Then
      sql &= "WHERE sub_religion ILIKE $$%" & sub_religion & "%$$"
   End If
   Return modDBConnect.exec_query_collection(sql)
   
End

Public Function occupations_get(occupation As String) As Collection 
   '----------------------------------------------------------
   'Retrieves a list of occupations from common.lu_occupations
   '----------------------------------------------------------

   Return modDBConnect.exec_query_collection("SELECT * from common.lu_occupations WHERE occupation ILIKE $$%" & occupation & "%$$ LIMIT 20")

End

Public Function occupation_save(occupation As String) As Integer
   '--------------------------------------------------
   'Insert a new occupation into common.lu_occupations
   'and returns the primary key of that table
   '--------------------------------------------------

   Dim sql As String   
   Dim $Result As Result 

   sql = "INSERT INTO common.lu_occupations (occupation) "
   "VALUES ($$"
   sql = sql & Trim(occupation) & "$$) returning pk " 
   $Result = modDBConnect.exec_query(sql)
   Return $Result!pk   

End
