' Gambas module file

' Copyright (C) 2008-2013 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'----------------------------------------------------------------------
' Database routines for EasyGP.Common schema
'----------------------------------------------------------------------

Public Function Seasons_Get(Optional season As String) As Collection
   
   Dim sql As String
   
   sql = "Select * from common.lu_seasons "
   If season <> "" Then
      sql &= " WHERE season ILIKE $$%" & season & "%$$ "
   Endif
   Return modDBConnect.exec_query_collection(sql)
   
End

Public Function Religions_Get(Optional sub_religion As String) As Collection
   '-----------------------------------------------------------------
   'Returns a collection of religion/subreligion where the collection 
   'pk_view is a compound key (see the def of this view)
   '-----------------------------------------------------------------
   
   Dim sql As String
   
   sql = "Select * from common.vwReligions "
   If sub_religion <> "" Then
      sql &= "WHERE sub_religion ILIKE $$%" & sub_religion & "%$$"
   End If
   Return modDBConnect.exec_query_collection(sql)
   
End

Public Function Drug_Formulations_Get(Optional form As String = "", Optional bsorted As Boolean = False) As Collection 
   '-------------------------------------
   'Retrieves a list of drug formulations
   '-------------------------------------
   
   Dim sql As String
   
   sql = "SELECT * from common.lu_formulation WHERE form ILIKE $$%" & form & "%$$ "
   If bsorted Then
      sql &= " SORT DESC"
   Endif
   Return modDBConnect.exec_query_collection(sql)
   
End

Public Function Sites_Administration_Get(Optional site As String = "") As Collection 
   '--------------------------------------------------------
   'Retrieves a list of sites of administration eg 'deltoid'
   '--------------------------------------------------------

   Return modDBConnect.exec_query_collection("SELECT * from common.lu_site_administration WHERE site ILIKE $$%" & site & "%$$")

End

Public Function Routes_Administration_Get(Optional route As String = "", Optional bsorted As Boolean = False) As Collection 
   '------------------------------------------------------------------
   'Retrieves a list of routes of administration with optional sorting
   '------------------------------------------------------------------
   
   Dim sql As String
   
   sql = "SELECT * from common.lu_route_administration WHERE route ILIKE $$%" & route & "%$$ "
   If bsorted Then
      sql &= " SORT DESC"
   Endif
   Return modDBConnect.exec_query_collection(sql)
   
End

Public Function occupations_get(occupation As String) As Collection 
   '----------------------------------------------------------
   'Retrieves a list of occupations from common.lu_occupations
   '----------------------------------------------------------
   
   Return modDBConnect.exec_query_collection("SELECT * from common.lu_occupations WHERE occupation ILIKE $$%" & occupation & "%$$ LIMIT 20")
   
End

Public Function Occupation_Save(occupation As String) As Integer
   '------------------------------------------------------------
   'Insert a new occupation into common.lu_occupations if needed
   'which is auto-capitalised eg 'General Manager'
   'and returns the primary key of that table
   '------------------------------------------------------------
   
   Dim $result As Result
   
   $result = modDBConnect.exec_query("Select * from common.lu_occupations WHERE occupation ILIKE $$" & Trim(occupation) & "$$")
   If $result.count Then   
      Return $result!pk
   Else
      $Result = modDBConnect.exec_query("INSERT INTO common.lu_occupations (occupation) VALUES ($$" & modStrings.CapitaliseWord(Trim(occupation)) & "$$) returning pk")
      Return $Result!pk
   End If      
End

