' Gambas module file

'probably temporary till talk to IAN

Public Function Organisations_Fill_Popup_List(lv As Listview, txtBox As Textbox) As Collection 
   '-----------------------------------------------------------------------------
   'Given a listview, returns it filled with organisations or an empty collection
   'CALLED BY FMetadata.Organisations_Get(..)
   '-----------------------------------------------------------------------------  
   Dim organisations As New Collection 
   Dim organisation As Collection 
   Dim sMsg As String 
   Dim x As Integer
   
   Message.Info("Richard Stop here modmetdata.organisations_get, something else is using this")
   lv.Clear()
   If Trim(txtBox.text) = "" Then
      lv.Visible = False
   Else
      Organisations = modUtil.Copy_Collection_Keyed_Sequentially(modContactsDBI.Organisations_Get(Trim(txtBox.text)))
      If Organisations.count Then 
        For Each organisation In Organisations
            sMsg = organisation!organisation & " " & organisation!branch & " " 
            sMsg &= Trim(organisation!street1 & " " & organisation!street2) & " " & organisation!town & " " & organisation!postcode 
            lv.Add(x, sMsg)
        
            Inc x 
         Next
         lv.Visible = True
         lv.tag = txtBox
      Else
         lv.Visible = False   
      End If
   End If
   Return organisations
End

Public Function Employee_Fill_Popup_List(lv As ListView, txtbox As Textbox) As Collection 
   Dim Organisations As New Collection
   Dim employee As Collection  
   Dim sMsg As String 
   
   lv.Clear()
   If Trim(txtBox.text) = "" Then
      lv.Visible = False
   Else
      Organisations = modContactsDBI.Employees_In_Organisations_Find(Trim(txtBox.text))
      If Organisations.count Then 
        For Each employee In Organisations
            sMsg = employee!wholename & " " & employee!organisation & " " & employee!branch & " " 
            sMsg &= Trim(employee!street1 & " " & employee!street2) & " " & employee!town & " " & employee!postcode 
            lv.Add(employee!pk_view, sMsg)
         Next
         lv.Visible = True
         lv.tag = txtBox
      Else
         lv.Visible = False   
      End If
    End If
    Return organisations
End

Public Function Persons_Fill_Popup_List(lv As ListView, txtbox As Textbox, contact_type As Integer) As Collection
   '-----------------------------------------------------
   'Returns a collection or people
   'const.contacttype_patient or const.contacttype_person
   'CALLED BY FMetadata.Person_Get(...)
   '-----------------------------------------------------
   Dim persons As New Collection
   Dim person As Collection 
   
   lv.Clear()  
   If Trim(txtBox.text) = "" Then
      lv.Visible = False
   Else
         Persons = modContactsDBI.Person_Get(Trim(txtBox.text), contact_type) 
         Persons.Remove("sql_in_english")
         
         If Persons.count Then 
           lv.Clear()
            For Each Person In Persons
              lv.Add(Person!pk_view, Person!firstname & " " & Person!surname & " (" & Person!occupation & ") " & Trim(Person!street1 & " " & Person!street2) & " " & Person!town)
            Next 
           lv.Visible = True
           lv.Raise
           lv.tag = txtBox
         Else
           lv.Visible = False  
         End If
  End If
   Return persons
   
   


End
