' Gambas module file

' Gambas class file

' Copyright (C) 2008-2015 Dr Richard TERRY

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'
' PURPOSE     A module to to query database about observations
'-----------------------------------------------------------------------

Public Sub Observation_Get_By_Loinc(loinc As String, Optional fk_patient As Integer = 0, bMostRecent As Boolean = False, Optional LIMIT As Integer = 1) As Collection   
   Dim sql As String
   
   sql = "Select * From Documents.vwObservations where loinc = $$" & loinc & "$$ "
   If fk_patient Then
      sql &= " AND fk_patient = " & fk_patient
   Endif
   If bMostRecent Then
      sql &= " ORDER by observation_date DESC "
   Endif
   sql &= " LIMIT " & LIMIT
   If limit = 1 Then Return modDBConnect.exec_query_first(SQL)
   
End

