' Gambas module file

' Copyright (C) 2008-2012 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
'---------------------------------------------------------------------
' A module for the database routines for pregnancies
' --------------------------------------------------------------------

Public Function Presentations_Get() As String[]
  '------------------------------------ 
  ' Return a list of baby presentations
  ' -----------------------------------
  Dim R As Result
  Dim p As New String[] 
  
  R = modDBConnect.exec_query("Select * from clin_pregnancy.lu_presentations") 
  If R.count Then
     For Each R
        p.Add(R!presentation)
     Next
  Endif
  Return p
End

Public Function Antenatal_Visits_Get(fk_patient As Integer) As Collection 
   
   Return modDBConnect.exec_query_collection("Select * from clin_pregnancy.vwAnteNatal_Visits where fk_patient =" & fk_patient)
   
End
