' Gambas module file

Public Sub Guess_UserName(cons As CConsult, synonyms As Collection, SelectedDocument As Collection, observations As Collection) As Collection
   
   Dim Guess As New Collection 
   Dim RequestOrdered As Collection 
   Dim synonym As Collection 
   Dim synonym_count As Integer 
   Dim all_synonyms As New Collection
   Dim item As Collection 
   Dim observation As Collection 
   
   If Not IsNull(SelectedDocument!fk_lu_provider_type) Then
      If SelectedDocument!fk_lu_provider_type > 3 Then                               'path, radiology, nuclear medicine FIXME HAS CHANGED
         guess!name = Guess_Letter_Content(observations)
         If guess!name Then Return guess
      End If
   End If
   
   guess = Guess_Radiology_From_Tag(SelectedDocument!tag)
   If guess!name <> "" Then Return guess
   
   If Not IsNull(cons) Then
      RequestOrdered = New Collection 
      For Each RequestOrdered In cons!requests_ordered
         If SelectedDocument!date_created = RequestOrdered!request_date Then
            If Lower$(SelectedDocument!tag) = Lower(RequestOrdered!item) Then
               guess!name = SelectedDocument!tag
               Return Guess
            End If
         End If       
      Next
   End If  
   
   guess!name = Guess_Request_Names_From_tag(SelectedDocument, observations)
   If guess!name <> "" Then Return guess
   
   If Not IsNull(SelectedDocument!fk_lu_provider_type) Then 
      For Each item In modRequestsDBI.requests_get_items(SelectedDocument!tag, SelectedDocument!fk_lu_provider_type)
         If Lower(item!item) = Lower(SelectedDocument!tag) Then
            guess!name = item!item 
            Return guess
         End If
      Next
   End If   
   
   guess!name = Guess_Request_Names_From_Observation(observations)
   If guess!name <> "" Then Return guess
   For Each synonym In synonyms                
      If Lower(synonym!provider_request_name) = Lower(SelectedDocument!tag) Then 
         all_synonyms.Add(synonym, all_synonyms.count)
         Inc synonym_count
      End If 
   Next  
   
   If synonym_count = 1 Then
      
      'In theory should have good match however, if user has mis-allocated the request laterality last time
      'then this could be wrong.
      For Each synonym In all_synonyms
         guess!name = synonym!user_request_name & ";"
         Select Case synonym!lateralisation
            Case const.LateralityLeft
               guess!laterality = const.LateralityLeft
            Case const.LateralityRight
               guess!laterality = const.LateralityRight
            Case Const.LateralityBoth
               guess!laterality = const.LateralityBoth
         End Select
         For Each Observation In observations
            If observation!value_type = "FT" Then
               If InStr(Lower(observation!value), "left") Then
                  guess!lateralisation = const.LateralityLeft
               Else If InStr(Lower(observation!value), "right") Then
                  guess!laterality = const.LateralityRight
               Endif
            Else
               If InStr(Lower(observation!value), "left") And InStr(Lower(observation!value), "right") Then
                  guess!laterality = const.LateralityBoth
               Endif
            Endif
         Next
         Return guess
      Next
   Else
      For Each Observation In observations
         If InStr(Lower(observation!value), Lower(synonym!user_request_name)) Then
            guess!name = synonym!user_request_name & ";"
            Return guess
            Break
         End If
      Next
   End If
   
   ' guess = Guess_Radiology_From_Tag(SelectedDocument!tag)
   ' If guess!name <> "" Then Return guess
   
   For Each synonym In synonyms                
      If Lower(synonym!provider_request_name) = Lower(SelectedDocument!tag) Then 
         guess!name = synonym!provider_request_name
         Return guess
      End If 
   Next  
   guess!name = Guess_Request_Names_From_Observation(observations)
   If guess!name <> "" Then Return guess
   
   guess = Guess_Request_Names_From_Parsing_Report(observations)
   If Guess!name Then Return Guess
   Return guess
   
End  

Public Function Guess_Letter_Content(observations As Collection) As String   
   
   Dim observation As Collection
   Dim From_pos As Integer
   Dim To_pos As Integer
   Dim diagnosis_guess As String
   Dim Lines As String[]
   Dim a_line As String
   
   For Each observation In observations
      Lines = Split(Replace(observation!value, "\\.br\\", "|"), "|", "", True)
      For Each a_line In Lines
         If Left(a_line, 3) = "Dx:" And Right(a_line) = ")" Then
            Return Trim(Replace$(a_line, "Dx:", "")) 
         End If
      Next    
   Next   
   
End  

Public Function Guess_Request_Names_From_tag(SelectedDocument As Collection, observations As Collection) As String
   
   Dim requestname As String  
   Dim sString As String 
   Dim observation As Collection 
   Dim bFaeces As Boolean 
   Dim bHaveCholesterol As Boolean
   
   Select Case Lower(SelectedDocument!tag)
      Case "master auto antibody (ato-0)"  
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "gastric parietal") Then
               If Not InStr(requestname, "Anti-gastric parietal cell antibody") Then
                  requestname &= "Anti-gastric parietal cell antibody;"
               Endif
            Endif
            If InStr(Lower(observation!identifier), "intrinsic factor") Then
               If Not InStr(requestname, "Intrinsic Factor Antibody") Then
                  requestname &= "Intrinsic Factor Antibody;"
               Endif
            Endif
            
         Next
      Case "referred immunology"
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "asca iga") Then
               If Not InStr(requestname, "ASCA IgA/IgG (Saccharomyces cerevisiae serology)") Then
                  requestname &= "ASCA IgA/IgG (Saccharomyces cerevisiae serology);"
               End If
            End If
         Next
      Case "anaemia screening"
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "rc folate") Then
               If Not InStr(Lower(requestname), "red cell folate") Then
                  requestname &= "Red Cell Folate;"
               End If
            End If
            If InStr(Lower(observation!identifier), "b12") Then
               If Not InStr(Lower(requestname), "vitamin b12") Then
                  requestname &= "Vitamin B12;"
               End If
            End If 
            If InStr(Lower(observation!identifier), "transferrin") Then
               If Not InStr(Lower(requestname), "Transferrin") Then
                  requestname &= "Transferrin;"
               End If
            End If 
         Next
      Case "kryptopyrroles urine"
         requestname &= "Kryptopyrroles Urine"
      Case "metals, r-urine"
         For Each observation In observations 
            If InStr(Lower(observation!value), "copper/creat") Or InStr(Lower(observation!identifier), "r-u-copper/creat") Then 
               If Not InStr(requestname, "Urine Copper/Creatinine Ratio;") Then
                  requestname &= "Urine Copper/Creatinine Ratio;"
               Endif
               
            Endif
         Next
         
      Case "vitamin b6 (vb6-0)"
         For Each observation In observations 
            If InStr(Lower(observation!value), "vitamin b6") Then 
               If Not InStr(requestname, "Vitamin B6") Then
                  Requestname &= "Vitamin B6;"
               Endif
            Endif
         Next
      Case "blood group antibodies (abs-0)"
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "rbc antibody screen") Then 
               If Not InStr(requestname, "Red blood cell antibody screen") Then
                  Requestname &= "Red blood cell antibody screen;"
               Endif
            Endif
         Next
      Case "glucose screen pregnancy (glp-0)"
         For Each observation In observations 
            If InStr(Lower(observation!value), "50 gm") Then
               If Not InStr(requestname, "GTT 50gm Pregnancy") Then
                  Requestname &= "GTT 50gm Pregnancy;"
               Endif
            Endif
         Next
         
      Case "cla"
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "cardiolipin igg") Or InStr(Lower(observation!identifier), "cardiolipin igm") Then
               If Not InStr(requestname, "Anti-cardiolipin antibody;") Then
                  requestname &= "Anti-cardiolipin antibody;"
               Endif
            Endif
            If InStr(Lower(observation!identifier), "beta2glycoprotein") Or InStr(Lower(observation!identifier), "beta2 glycoprotein") Or InStr(Lower(observation!identifier), "beta2 glycoprotein") Then
               If Not InStr(requestname, "Beta 2 Glycoprotein 1 (B2GP1) Antibodies") Then
                  requestname &= "Beta 2 Glycoprotein 1 (B2GP1) Antibodies;"
               Endif
            Endif
         Next
      Case "chlamydia pcr (chm-0)"
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "chlamydia") Then
               If Not InStr(requestname, "Chlamydia trachomatis PCR;") Then
                  requestname &= "Chlamydia trachomatis PCR;"
               Endif
            Endif
            If InStr(Lower(observation!identifier), "gonorrhoe") Then
               If Not InStr(requestname, "Neisseria gonorrhoeae PCR;") Then
                  requestname &= "Neisseria gonorrhoeae PCR;"
               Endif
            Endif
         Next
      Case "blood group / antibodies (bga-0)"
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "blood group") Then
               If Not InStr(requestname, "Blood Group;") Then 
                  requestname &= "Blood Group;"
               End If 
            Endif
            If InStr(Lower(observation!identifier), "antibody screen") Then
               If Not InStr(requestname, "Red blood cell antibody screen;") Then 
                  requestname &= "Red blood cell antibody screen;"
               End If 
            Endif
            
         Next
      Case "respiratory micro (res-0)", "general swab m/c/s (pus-0)"
         For Each observation In observations 
            If InStr(Lower(observation!value), "throat") Then
               If Not InStr(requestname, "Throat swab c&s;") Then 
                  requestname &= "Throat swab c&s;"
               End If   
            Endif
            If InStr(Lower(observation!value), "abscess") Then
               If Not InStr(requestname, "Pus swab c&s;") Then 
                  requestname &= "Pus swab c&s;"
               End If   
            Endif
            If InStr(Lower(observation!value), "ulcer") Then
               If Not InStr(requestname, "Pus swab c&s;") Then 
                  requestname &= "Pus swab c&s;"
               End If   
            Endif
            If InStr(Lower(observation!value), "mouth") Then
               If Not InStr(requestname, "Mouth swab c&s;") Then 
                  requestname &= "Mouth swab c&s;"
               End If   
            Endif
            If InStr(Lower(observation!value), "bartholins") Then
               If Not InStr(requestname, "Bartholins gland swab c&s;") Then 
                  requestname &= "Bartholins gland swab c&s;"
               End If 
            End If
            If InStr(Lower(observation!value), "calf") Then
               If Not InStr(requestname, "Pus swab c&s;") Then 
                  requestname &= "Pus swab c&s;"
               End If   
            Endif
            If InStr(Lower(observation!value), "eye") Then
               If Not InStr(requestname, "Eye swab c&s;") Then 
                  requestname &= "Eye swab c&s;"
               End If   
            Endif
            If InStr(Lower(observation!value), "foot") Or InStr(Lower(observation!value), "finger") Or InStr(Lower(observation!value), "neck") Or InStr(Lower(observation!value), "skin") Then
               If Not InStr(requestname, "Pus swab c&s") Then 
                  requestname &= "Pus swab c&s;"
               End If   
            Endif
            If InStr(Lower(observation!value), "axilla") Then
               If Not InStr(requestname, "Pus swab c&s") Then 
                  requestname &= "Pus swab c&s;"
               End If
            Endif
            If InStr(Lower(observation!value), "urethra") Then
               If Not InStr(requestname, "Urethral swab c&s;") Then 
                  requestname &= "Urethral swab c&s;"
               End If
            Endif
            If InStr(Lower(observation!value), "cervical") Then
               If Not InStr(requestname, "Cervical swab c&s;") Then 
                  requestname &= "Cervical swab c&s;"
               End If
            Endif
            If InStr(Lower(observation!value), "nose") Then
               If Not InStr(requestname, "Nose swab c&s;") Then 
                  requestname &= "Nose swab c&s;"
               End If   
            Endif
            If InStr(Lower(observation!value), "bursa") Then
               If Not InStr(requestname, "Bursa fluid: cells, crystals, culture;") Then 
                  requestname &= "Bursa fluid: cells, crystals, culture;"
               End If  
            Endif
            If InStr(Lower(observation!value), "wound") Or InStr(Lower(observation!value), "groin") Then
               If Not InStr(requestname, "Pus swab c&s;") Then 
                  requestname &= "Pus swab c&s;"
               End If
            Endif
            If InStr(Lower(observation!value), "toe") Then
               If Not InStr(requestname, "Pus swab c&s;") Then 
                  requestname &= "Pus swab c&s;"
               End If  
            Endif
            If InStr(Lower(observation!value), "arm") Then
               If Not InStr(requestname, "Pus swab c&s;") Then 
                  requestname &= "Pus swab c&s;"
               End If   
            Endif
            If InStr(Lower(observation!value), "face") Then
               If Not InStr(requestname, "Pus swab c&s;")
                  requestname &= "Pus swab c&s;"
               End If  
            Endif
            If InStr(Lower(observation!value), "sputum") Then
               If Not InStr(requestname, "Sputum culture - routine;") Then 
                  requestname &= "Sputum culture - routine;"
               End If   
            Endif
            If InStr(Lower(observation!value), "joint") Then
               If Not InStr(requestname, "Joint Fluid c&s") Then 
                  requestname &= "Joint Fluid c&s;"
               End If
            Endif
         Next
      Case ".jak2"
         Requestname &= "JAK-2 mutation for polycythaemia;"
      Case "serum c-peptide (cpp-0)"
         requestname &= "c-peptide"
      Case "measles, mumps / zoster (mmz-0)"
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "measles") Then
               If Not InStr(requestname, "Measles - EIA IgG IgM (CFT);") Then
                  requestname &= "Measles - EIA IgG IgM (CFT);"
               Endif
            Endif
            If InStr(Lower(observation!identifier), "mumps") Then
               If Not InStr(requestname, "Mumps - EIA IgG IgM (CFT);") Then
                  requestname &= "Mumps - EIA IgG IgM (CFT);"
               Endif
            Endif
         Next
      Case "electrocardiogram (ecg-0)"
         requestname &= "Ecg report only;"
      Case "hla b27 antigen (h27-0)"
         requestname &= "HLA B27;"
      Case "5 hyroxyindole acetic acd (hiu-0)"
         requestname &= "Hydroxy Indole Acetic Acid;"
      Case "clozaril/clozapine (czp-0)"
         requestname &= "Clozapine;"
      Case "sds pathology archive dat (sdp-0)"
         For Each observation In observations 
            If InStr(Lower(observation!value), "blood group") Then    
               If Not InStr(requestname, "Blood group")
                  requestname &= "Blood group;"
               End If
            End If   
            If InStr(Lower(observation!value), "pregnancy test") Then    
               If Not InStr(requestname, "HCG - Semi-quantitative (Pregnancy test)")
                  requestname &= "HCG - Semi-quantitative (Pregnancy test);"
               End If
            End If   
            If InStr(Lower(observation!value), "microbiological examination of") Then  
               If InStr(Lower(observation!value), "urine") Then  
                  If Not InStr(requestname, "MSU")
                     requestname &= "MSU;"
                  End If
               End If  
            End If    
         Next
      Case "serum chemistry (mba-0)"
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "sodium") Then 
               If Not InStr(Lower(requestname), "uec") Then 
                  requestname &= "UEC;"
               End If
            End If  
            If InStr(Lower(observation!value), "ggt") Then
               If Not InStr(requestname, "GGT (not on LFT profile)") Then
                  requestname &= "GGT (not on LFT profile);"
               End If
            End If         
            If InStr(Lower(observation!identifier), "potassium") Then
               If InStr(Lower(requestname), "potassium") And Not InStr(Lower(requestname), "uec") Then
                  requestname &= "Potassium;"
               End If
            End If
            
            If InStr(Lower(observation!identifier), "alt") Or InStr(Lower(observation!identifier), "ast") Then
               If Not InStr(Lower(requestname), "lfts;") Then 
                  requestname &= "LFTs;"
               End If
            End If  
            If InStr(Lower(observation!value), "alt") Or InStr(Lower(observation!identifier), "ast") Then
               If Not InStr(Lower(requestname), "lfts;") Then 
                  requestname &= "LFTs;"
               End If
            End If  
            
            If InStr(Lower(observation!identifier), "egfr") Then
               If Not InStr(Lower(requestname), "egfr") Then 
                  requestname &= "eGFR;" 
               End If
            End If 
            If InStr(Lower(observation!identifier), "glucose") Or InStr(Lower(observation!value), "glucose") Then
               If Not InStr(Lower(requestname), "bsl;") Then 
                  requestname &= "BSL;"
               End If
            End If         
            If InStr(Lower(observation!identifier), "creatinine ") And Not InStr(requestname, "UEC") Then 
               If Not InStr(Lower(requestname), "creatinine;") Then 
                  requestname &= "Creatinine;"
               End If
            End If           
            If InStr(Lower(observation!identifier), "calcium") Then 
               If Not InStr(Lower(requestname), "calcium;") Then 
                  requestname &= "Calcium;"
               End If
            End If   
            If InStr(Lower(observation!identifier), "magnesium") Then 
               If Not InStr(Lower(requestname), "magnesium;") Then 
                  requestname &= "Magnesium;"
               End If
            End If   
            If InStr(Lower(observation!identifier), "urate") Then 
               If Not InStr(Lower(requestname), "urate;") Then 
                  requestname &= "Urate;"
               End If
            End If   
            If InStr(Lower(observation!identifier), "ck") Or InStr(Lower(observation!identifier), "creatine kinase") Then 
               If Not InStr(Lower(requestname), "cpk;") Then 
                  requestname &= "CPK;"
               End If
            End If   
            If InStr(Lower(observation!value), "ck") Or InStr(Lower(observation!value), "creatine kinase") Then 
               If Not InStr(Lower(requestname), "cpk") Then 
                  requestname &= "CPK;"
               End If
            End If   
            If InStr(Lower(observation!value), "lactate dehydrogenase") Then 
               If Not InStr(Lower(requestname), "ldh") Then 
                  requestname &= "LDH;"
               End If
            End If   
            
            If InStr(Lower(observation!identifier), "lactate dehydrogenase") Then 
               If Not InStr(Lower(requestname), "LDH") Then 
                  requestname &= "LDH;"
               End If
            End If   
         Next
      Case "venous blood gas (vbg-0)"
         requestname &= "Venous blood gas;"
      Case "helicobacter pylori (hel-0)"
          requestname &= "Helicobacter Pylori antibodies;"
      Case "h.pylori breath"
         requestname &= "Helicobacter pylori breath test;"
      Case "genital swab m/c/s (gmc-0)"
         For Each observation In observations 
            If Lower(observation!value) = "high vaginal swab" Then
               If Not InStr(Lower(requestname), "high vaginal swab") Then
                  requestname &= "High vaginal swab c&s;"
               Endif
            Endif
            
            If Lower(observation!value) = "perianal" Then
               If Not InStr(Lower(requestname), "peri-anal swab c&s") Then
                  requestname &= "Peri-anal swab c&s;"
               Endif
            Endif
         Next
      Case "quantiferon gold tb (qtf-0)"
         requestname &= "quantiferon gold test for TB;"
      Case "influenza a + b (fla-0)"
         requestname &= "Influenza A IgA (EIA);Influenza B IgA (EIA);"
      Case "serum alpha fetoprotein (afp-0)"
         requestname &= "Alpha fetoprotein;"
      Case "lipid studies (lip-0)"
         For Each observation In observations 
            If observation!pit = False Then    
               If Lower(observation!identifier) = "cholesterol" Or InStr(Lower(observation!value), "cholesterol") Then
                  If Not InStr(requestname, "Cholesterol") Then  
                     requestname = "Cholesterol;"
                  End If   
               Endif
               If Lower(observation!identifier) = "triglyceride" Or InStr(Lower(observation!value), "triglyceride") Then
                  If Not InStr(requestname, "Triglycerides") Then 
                     requestname &= "Triglycerides;"
                  End If   
               Endif
               If Lower(observation!identifier) = "hdl cholesterol" Or InStr(Lower(observation!value), "hdl cholesterol") Then
                  If Not InStr(requestname, "HDL Cholesterol") Then   
                     requestname = "HDL Cholesterol;"  'remove the cholesterol;triglycerides
                  End If   
               Endif
               If Lower(observation!identifier) = "vldl cholesterol" Or InStr(Lower(observation!value), "vldl cholesterol") Then
                  If Not InStr(requestname, "VLDL Cholesterol") Then
                     requestname &= "VLDL Cholesterol;"
                  End If   
               Endif
            End If  
         Next
      Case "timed urine microalbumin (mat-0)"
         requestname &= "Timed urine microalbumin"
      Case "carbohydrate antigen 19-9 (c19-0)"
         requestname &= "CA 19-9 tumour marker"
      Case "protein electroph.(serum) (epg-0)"
         requestname &= "Protein Electrophoresis;"
      Case "anti leucocyte antibody (lla-0)"
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "anca") Then
               If Not InStr(requestname, "ANCA ") Then
                  requestname &= "ANCA (Anti-neutrophil cytoplasmic antibody);" 
               Endif
            Endif
         Next
      Case "rheumatic disease ab (rda-0)"
         For Each observation In observations 
            If InStr(Lower(observation!identifier), "rheumatoid factor") Then
               If Not InStr(requestname, "RF") Then
                  requestname &= "RF;" 
               Endif
            Endif   
            If InStr(Lower(observation!identifier), "ccp ab") Then
               If Not InStr(requestname, "Cyclic citrullinated peptide (CCP) antibodies;") Then
                  requestname &= "Cyclic citrullinated peptide (CCP) antibodies;" 
               Endif
            Endif
         Next
         '   
         
      Case "miscellaneous tests"
         For Each observation In observations 
            If InStr(Lower(observation!value), "kleihauer") Then
               If Not InStr(Lower(requestname), "kleihauer") Then 
                  requestname &= "Kleihauer test;"
               End If 
            End If  
            If InStr(Lower(observation!value), "monospot") Then
               If Not InStr(Lower(requestname), "monospot") Then 
                  requestname &= "Monospot;"
               End If 
            End If        
            
         Next
         
      Case "sendaways"
         For Each observation In observations
            If InStr(Lower(observation!value), "toxocara igg") Then
               If Not InStr(Lower(requestname), "toxocara igg") Then 
                  requestname &= "Toxocara IgG;"
               End If 
            End If        
            
         Next
      Case "ecg-tr", "ecg report only (ecr-0)"
         requestname &= "ECG report only;"
      Case "fruc"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "fructosamine") Then
               If Not InStr(Lower(requestname), "fructosamine;") Then 
                  requestname &= "Fructosamine;"
               End If 
            End If        
         Next    
      Case ".hpvdna"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "hpv") Then
               If Not InStr(Lower(requestname), "human papilloma virus;") Then 
                  requestname &= "HUMAN PAPILLOMAVIRUS DNA;"
               End If 
            End If 
            
         Next
         
      Case "anatomical pathology"
         For Each observation In observations
            If InStr(Lower(observation!value), "bone marrow biopsy") Then
               If Not InStr(Lower(requestname), "bone marrow biopsy") Then 
                  requestname &= "Bone marrow biopsy;"
               End If 
            End If        
         Next    
      Case "d039"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "factor v leiden") Then
               If Not InStr(Lower(requestname), "factor v leiden  genetic study") Then 
                  requestname &= "Factor V Leiden Genetic Study;"
               End If 
            End If
            If InStr(Lower(observation!value), "prothrombin gene") Then
               If Not InStr(Lower(requestname), "prothrombin gene") Then 
                  requestname &= "Prothrombin Gene Analysis;"
               End If 
            End If
            
            If InStr(Lower(observation!identifier), "prothrombin gene") Then 'Yes I know its stupid but you need both.
               If Not InStr(Lower(requestname), "prothrombin gene;") Then 
                  requestname &= "Prothrombin Gene Analysis;"
               End If 
            End If
            
         Next   
      Case ".ath"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "antithrombin") Then
               If Not InStr(Lower(requestname), "antithrombin") Then 
                  requestname &= "Antithrombin;"
               End If 
            End If
         Next
      Case "newcastle nuclear medicine consultation note"
         For Each observation In observations
            '         If observation!value_type = "NM" Then
            If Not IsNull(observation!value) Then
               
               If InStr(Lower(observation!value), "bone scan") Then
                  requestname = "Bone Scan;"
               End If
            Endif
            
            'End If
         Next  
      Case "s307"
         For Each observation In observations
            If InStr(Lower(observation!value), "dnase b") Then
               If Not InStr(requestname, "DNAse B Ab.Streptococcal") Then 
                  requestname &= "DNAse B Ab.Streptococcal;"
               End If  
            Endif
            If InStr(Lower(observation!identifier), "dnase b") Then
               If Not InStr(requestname, "DNAse B Ab.Streptococcal") Then 
                  requestname &= "DNAse B Ab.Streptococcal;"
               End If  
            Endif
         Next
      Case "drug screen-chain of cus. (dl-0)"
         requestname &= "Drug Screen - Pre Employment"
      Case "trace elements (ste-0)"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "aluminium") Then
               If Not InStr(requestname, "Aluminium") Then 
                  requestname &= "Aluminium;"
               End If  
            Endif
            If InStr(Lower(observation!identifier), "copper") Then
               If Not InStr(requestname, "Serum Copper") Then 
                  requestname &= "Serum Copper;"
               End If  
            Endif
            If InStr(Lower(observation!identifier), "zinc") Then 
               If Not InStr(requestname, "Serum Zinc") Then 
                  requestname &= "Serum Zinc;"
               End If  
            Endif
            If InStr(Lower(observation!identifier), "selenium") Then
               If Not InStr(requestname, "Selenium") Then 
                  requestname &= "Selenium;"
               End If  
            Endif
         Next
      Case "genital micro / culture (gmc-0)"
         For Each observation In observations
            If InStr(Lower(observation!value), "vaginal swab") Then  
               If Not InStr(requestname, "High Vaginal swab c&s") Then 
                  Requestname &= "High Vaginal swab c&s;"
               Endif
            End If
         Next
      Case "audiogram (aud-0)"
         requestname &= "Audiometry;"
      Case "cancer antigen 125 (125-0)"
         requestname &= "CA 125;"
      Case "c294"
         requestname &= "Creatinine - Urine;"
      Case "malaria parasite (mp-0)"
         requestname &= "Malaria ICT for Falciparum and Vixax;"
      Case "thiocyanate (tcy-0)"
         requestname &= "Thiocyanate;"
      Case "new drug screen (uds-0)"      
         requestname &= "Drug Screen Urine;"
      Case "alcohol (non-legal) (alc-0)"
         requestname &= "Alcohol urine;"
      Case "drugs"
         For Each observation In observations
            If InStr(Lower(observation!value), "urine") Then
               If Not InStr(requestname, "Urine Drug Screen") Then 
                  requestname &= "Urine Drug Screen;"
               End If   
            Endif       
            If Requestname = "" Then   
               If Not IsNull(observation!identifier) Then
                  requestname &= Loinc_Get_component(observation!loinc) & ";"
               Endif
            End If
         Next  
      Case "viral pcr panel"     'since when is MRSA viral?
         For Each observation In observations
            If InStr(Lower(observation!value), "b.pertussis pcr") Then
               If Not InStr(Lower(requestname), "bordetella pertussis pcr;") Then 
                  requestname &= "Bordetella Pertussis PCR;"
               End If 
            End If
            
            If InStr(Lower(observation!value), "mrsa") Then
               If Not InStr(Lower(requestname), "mrsa pcr;") Then 
                  requestname &= "MRSA PCR;"
               End If 
            End If
            If InStr(Lower(observation!value), "human papillomavirus dna") Then
               If Not InStr(Lower(requestname), "human papillomavirus dna;") Then 
                  requestname &= "HUMAN PAPILLOMAVIRUS DNA;"
               End If 
            End If
            
         Next
      Case "tvlcx"
         For Each observation In observations
            If Not InStr(requestname, "Trichomonas Vaginalis PCR") Then
               requestname &= "Trichomonas Vaginalis PCR;"
            Endif
         Next
      Case "sem-f"
         For Each observation In observations
            If Not InStr(requestname, "Semen analysis") Then
               requestname &= "Semen analysis;"
            Endif
         Next
      Case "anti leucocyte antibody (lla-0)"   'fixme - dosn't pick anything up
         For Each observation In observations
            If InStr(Lower(observation!value), "proteinase 3 ab") Then
               If Not InStr(requestname, "Proteinase 3 Ab") Then 
                  requestname &= "Proteinase 3 Ab;"
               End If 
            End If
            
            If InStr(Lower(observation!value), "myeloperoxidase") Then
               If Not InStr(requestname, " Myeloperoxidase Ab") Then 
                  requestname &= " Myeloperoxidase Ab;"
               End If 
            End If
            
         Next
      Case "C999 CONVERSION"
         'IRON STUDIES
         'HAEMOCHROMATOSIS GENE TESTING
      Case "somatomedin (som-0)"
         For Each observation In observations
            If InStr(Lower(observation!value), "somatomedin c") Then
               If Not InStr(requestname, "Somatomedin C") Then 
                  requestname &= "Somatomedin C"
               End If 
            End If
         Next
      Case "e histolica ab (eha-0)"
         For Each observation In observations
            If InStr(Lower(observation!value), "e. histolytica") Then
               If Not InStr(requestname, "Entamoeba histolytica Antibody;") Then 
                  requestname &= "Entamoeba histolytica Antibody;"
               End If 
            End If
         Next
      Case ".prots"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "protein s") Then
               If Not InStr(requestname, "Protein S") Then 
                  requestname &= "Protein S;"
               End If 
            End If
         Next
      Case ".protc"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "protein c") Then
               If Not InStr(requestname, "Protein C") Then 
                  requestname &= "Protein C;"
               End If 
            End If
         Next  
      Case ".apcr" ' Activated Protein C Resistance
         For Each observation In observations
            If InStr(Lower(observation!identifier), "activated protein c resistance") Then
               If Not InStr(requestname, "Activated Protein C Resistance") Then 
                  requestname &= "Activated Protein C Resistance;"
               End If 
            End If
         Next  
      Case "trace metals"
         For Each observation In observations
            If InStr(Lower(observation!value), "lead") Then
               If Not InStr(Lower(requestname), "lead blood;") Then 
                  requestname &= "Lead BLood;"
               End If 
            End If   
            If InStr(Lower(observation!value), "zinc") Then
               If Not InStr(Lower(requestname), "zinc;") Then 
                  requestname &= "Zinc;"
               End If 
            End If
            If InStr(Lower(observation!value), "copper") And Not InStr(Lower(observation!value), "copper/caerulo") Then
               If Not InStr(requestname, "Copper;") Then 
                  requestname &= "Copper;"
               End If 
            End If
            If InStr(Lower(observation!value), "caeruloplasmin") Then
               If Not InStr(requestname, "Caeruloplasmin") Then 
                  requestname &= "Caeruloplasmin;"
               End If 
            End If
            If InStr(Lower(observation!value), "copper/caerulo") Then
               If Not InStr(requestname, "Copper/Caeruloplasmin ratio") Then 
                  requestname &= "Copper/Caeruloplasmin ratio;"
               End If 
            End If
            If InStr(Lower(observation!value), "magnesium") Then
               If Not InStr(requestname, "Magnesium") Then 
                  requestname &= "Magnesium;"
               End If 
            End If
            
         Next
      Case "sensitive oestradiol (e2s-0)"
         For Each observation In observations
            If InStr(Lower(observation!value), "sensitive oestradiol") Then
               If Not InStr(requestname, "Sensitive Oestradiol Assay") Then 
                  requestname &= "Sensitive Oestradiol Assay;"
               End If
            End If
         Next
      Case "thyroid autoantibodies (taa-0)"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "anti thyroglobulin") Then
               If Not InStr(requestname, "Anti-thyroglobulin ab;") Then 
                  requestname &= "Anti-thyroglobulin ab;"
               End If
            End If
         Next
      Case "cf"
         requestname &= "Cystic Fibrosis Testing"
      Case "oestradiol ria"
         requestname &= "Sensitive Oestradiol Assay;"
      Case "therapeutic drug mon. (tdm-0)"
         For Each observation In observations
            If InStr(Lower(observation!value), "gent") Then
               If Not InStr(requestname, "Gentamicin") Then
                  requestname &= "Gentamicin;"
               Endif
            Endif
         Next
      Case "git testing"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "vitamin a") Then
               If Not InStr(requestname, "Vitamin A") Then
                  requestname &= "Vitamin A;"
               Endif
            Endif
         Next
      Case "mycab"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "mycoplasma") Then
               If Not InStr(requestname, "Mycoplasma pneumoniae - EIA IgM (CFT)") Then
                  requestname &= "Mycoplasma pneumoniae - EIA IgM (CFT);"
               Endif
            Endif
         Next
      Case "duttapath archive data (dut-0)"
         For Each observation In observations
            If InStr(Lower(observation!value), "histopathology") Then
               If Not InStr(requestname, "Histopathology") Then 
                  requestname &= "Histopathology;"
               End If 
            End If
         Next
      Case "x010", "x143"
         For Each observation In observations
            If InStr(Lower(observation!value), "wound swab") Then
               If Not InStr(Lower(requestname), "pus swab c&s;") Then 
                  requestname &= "Pus swab c&s;"
               End If 
            End If
            If InStr(Lower(observation!value), "vulval swab") Then
               If Not InStr(Lower(requestname), "vulval swab c&s;") Then 
                  requestname &= "Vulval swab c&s;"
               End If 
            End If
            If InStr(Lower(observation!value), "bursa") Then
               If Not InStr(requestname, "Bursa fluid: cells, crystals, culture") Then 
                  requestname &= "Bursa fluid: cells, crystals, culture;"
               End If 
            End If     
            If InStr(Lower(observation!value), "bartholins") Then
               If Not InStr(requestname, "Bartholins gland swab c&s;") Then 
                  requestname &= "Bartholins gland swab c&s;"
               End If 
            End If
            
            If InStr(Lower(observation!value), "axilla") Then
               If Not InStr(Lower(requestname), "axilla swab c&s;") Then 
                  requestname &= "Axilla swab c&s;"
               End If 
               
            End If  
            
            If InStr(Lower(observation!value), "skin swab") Then
               If Not InStr(Lower(requestname), "Pus swab c&s;") Then 
                  requestname &= "Pus swab c&s;"
               End If 
               
            End If  
            If InStr(Lower(observation!value), "nose") Or InStr(Lower(observation!value), "nasal") Then
               If Not InStr(Lower(requestname), "nose swab c&s;") Then 
                  requestname &= "Nose swab c&s;"
               End If 
            End If           
            If InStr(Lower(observation!value), "throat swab") Then
               If Not InStr(Lower(requestname), "throat swab c&s;") Then 
                  requestname &= "Throat swab c&s;"
               End If 
            End If  
            If InStr(Lower(observation!value), "eye swab") Then
               If Not InStr(Lower(requestname), "eye swab c&s;") Then 
                  requestname &= "Eye swab c&s;"
               End If 
            End If        
            
            If InStr(Lower(observation!value), "urethral swab") Then
               If Not InStr(Lower(requestname), "urethral swab c&s") Then 
                  requestname &= "Urethral swab c&s;"
               End If 
            End If   
            If InStr(Lower(observation!value), "cervical swab") Then
               If Not InStr(Lower(requestname), "cervical swab c&s") Then 
                  requestname &= "Cervical swab c&s;"
               End If 
            End If        
            
            If InStr(Lower(observation!value), "vaginal swab") Or InStr(Lower(observation!value), "genital swab") Then
               If Not InStr(Lower(requestname), "genitourinary - eg vaginal discharge, vaginal swab - Gram stain and aerobic culture;") Then 
                  requestname &= "Genitourinary - eg vaginal discharge, vaginal swab - Gram stain and aerobic culture;"
               End If 
            End If        
            If InStr(Lower(observation!value), "pus swab") Then
               If Not InStr(Lower(requestname), "pus swab c&s;") Then 
                  requestname &= "Pus swab c&s;"
               End If 
            End If        
            If InStr(Lower(observation!value), "abscess swab") Then
               If Not InStr(Lower(requestname), "pus swab c&s;") Then 
                  requestname &= "Pus swab c&s;"
               End If 
            End If        
            If InStr(Lower(observation!value), "mouth swab") Then
               If Not InStr(Lower(requestname), "mouth swab c&s;") Then 
                  requestname &= "Mouth swab c&s;"
               End If 
            End If    
            If InStr(Lower(observation!value), "ear") Then
               If Not InStr(requestname, "Ear Swab c&s") Then 
                  requestname &= "Ear Swab c&s;"
               End If 
            End If
            
         Next  
         
      Case "x012"    ', "hormone profile (hor-0)"
         For Each observation In observations
            If InStr(Lower(observation!value), "prolactin") Then
               If Not InStr(Lower(requestname), "prolactin;") Then 
                  requestname &= "Prolactin;"
               End If 
            End If
            If InStr(Lower(observation!value), "lh") Then
               If Not InStr(Lower(requestname), "lh") Then 
                  requestname &= "LH;"
               End If 
            End If        
            If InStr(Lower(observation!value), "fsh") Then
               If Not InStr(Lower(requestname), "fsh") Then 
                  requestname &= "FSH;"
               End If 
            End If
            If InStr(Lower(observation!value), "oestradiol") Then
               If Not InStr(Lower(requestname), "oestradiol") Then 
                  requestname &= "Oestradiol;"
               End If 
            End If
            
            If InStr(Lower(observation!value), "testosterone") Then
               If Not InStr(Lower(requestname), "testosterone") Then 
                  requestname &= "Testosterone;"
               End If 
            End If   
            If InStr(Lower(observation!value), "progesterone") Then
               If Not InStr(Lower(requestname), "progesterone") Then 
                  requestname &= "Progesterone;"
               End If 
            End If        
            
            If InStr(Lower(observation!value), "sex hormone binding") Then
               If Not InStr(Lower(requestname), "sex hormone binding globulin") Then 
                  requestname &= "Sex Hormone Binding Globulin;"
               End If 
            End If        
            
         Next
         
      Case "x013", "x038"
         For Each observation In observations
            If InStr(Lower(observation!value), "apolipoprotein (a)") Then
               If Not InStr(requestname, "Apolipoprotein a") Then
                  Requestname &= "Apolipoprotein a;"
               Endif
            Endif
            
            If InStr(Lower(observation!value), "pre employment") And InStr(Lower(observation!value), "urine drug analysis") Then
               If Not InStr(Lower(requestname), "Drug Screen - Pre Employment") Then
                  Requestname &= "Drug Screen - Pre Employment;"
               Endif
            Endif
            If (InStr(Lower(observation!value), "urine drug analysis") Or InStr(Lower(observation!value), "drug screen")) And Not InStr(Lower(observation!value), "pre employment") Then
               If Not InStr(Lower(requestname), "Drug Screen Urine") Then
                  Requestname &= "Drug Screen Urine;"
               Endif
            Endif
            If InStr(Lower(observation!value), "herpes") Then
               If Not InStr(Lower(requestname), "herpes") Then 
                  requestname &= "Herpes simplex virus PCR;"
               End If 
            End If     
            If InStr(Lower(observation!value), "clozapine") Then
               If Not InStr(Lower(requestname), "clozapine") Then
                  Requestname &= "Clozapine;"
               Endif
            Endif
            If InStr(Lower(observation!value), "worm identification") Then
               If Not InStr(Lower(requestname), "worm identification of species") Then
                  Requestname &= "Worm Identification of species;"
               Endif
            Endif
            If InStr(Lower(observation!value), "25-oh vitamin d") Or InStr(Lower(observation!value), "1,25 di-oh vitd") Then
               If Not InStr(Lower(requestname), "vitamin d") Then
                  requestname &= "Vitamin D;"
               End If
            End If 
            If InStr(Lower(observation!value), "acetylcholine receptor ab") Then
               If Not InStr(Lower(requestname), "anti-acetylcholine receptor antibody") Then
                  requestname &= "Anti-acetylcholine receptor antibody;"
               End If
            End If 
            If InStr(Lower(observation!value), "adrenal cortex") Then
               If Not InStr(requestname, "Anti-Adrenal antibody") Then
                  requestname &= "Anti-Adrenal antibody;"
               End If
            End If 
            
            If InStr(Lower(observation!value), "iodine") Then
               If InStr(Lower(observation!value), "urin") Then 
                  If Not InStr(Lower(requestname), "urinary iodine") Then
                     requestname &= "Urinary iodine;"
                  End If
               End If
            End If 
            If InStr(Lower(observation!value), "renin") Then
               If Not InStr(Lower(requestname), "renin") Then
                  requestname &= "Renin;"
               End If
            End If 
            If InStr(Lower(observation!value), "aldosterone") Then
               If Not InStr(Lower(requestname), "aldosterone") Then
                  requestname &= "Aldosterone;"
               End If
            End If 
            If InStr(Lower(observation!value), "first trimester screen") Then
               If Not InStr(Lower(requestname), "first trimester screen") Then
                  requestname &= "First Trimester Screen;"
               End If
            End If 
            If InStr(Lower(observation!value), "ch50") Then
               If Not InStr(requestname, "Total haemolytic complement (CH50)") Then
                  requestname &= "Total haemolytic complement (CH50);"
               End If
            End If 
            If InStr(Lower(observation!value), "strongyloides") Then
               If Not InStr(Lower(requestname), "strongyloides serology") Then
                  requestname &= "Strongyloides Serology;"
               End If
            End If 
            If InStr(Lower(observation!value), "anti-sperm antibodies") Then
               If Not InStr(Lower(requestname), "anti-sperm antibodies") Then
                  requestname &= "Anti-sperm Antibodies;"
               End If
            End If 
         Next
      Case "x014"
         For Each observation In observations
            If InStr(Lower(observation!value), "ecg report") Or InStr(Lower(observation!value), "ecg transmitted") Then
               If Not InStr(Lower(requestname), "ecg report only;") Then 
                  requestname &= "ECG report only;"
               End If 
            End If        
            If InStr(Lower(observation!value), "holter") Then
               If Not InStr(Lower(requestname), "24hr holter;") Then 
                  requestname = "24hr Holter Scan;"
               End If 
            End If   
            If InStr(Lower(observation!value), "spirometry") Then
               If Not InStr(Lower(requestname), "Spirometry;") Then 
                  requestname = "Spirometry;"
               End If 
            End If        
            
         Next    
         
      Case "x015", "msu"
         requestname = "MSU;"
      Case "x016"
         For Each observation In observations
            If InStr(Lower(observation!value), "pap") Or InStr(Lower(observation!value), "endocervical") Then
               If Not InStr(Lower(requestname), "pap") Then
                  requestname &= "Pap;"
               End If
            End If
            If InStr(Lower(observation!value), "cytopathology") Then
               If InStr(Lower(observation!value), "urine") Then
                  If Not InStr(Lower(requestname), "urine cytology") Then
                     requestname &= "Urine Cytology;"
                  End If
               End If
            End If
            If InStr(Lower(observation!value), "vaginal vault") Then
               If Not InStr(Lower(requestname), "vaginal vault smear") Then
                  requestname &= "Vaginal vault smear;"
               End If
            End If
            If InStr(Lower(observation!value), "fna") Then
               If Not InStr(Lower(requestname), "fna") Then
                  If InStr(Lower(requestname), "breast") Then
                     Requestname &= "FNA Breast"
                  Else
                     requestname &= "FNA;"
                  Endif
               End If
            End If
            
         Next
      Case "x024"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "dhm semen") Then
               If Not InStr(Lower(requestname), "semen analysis") Then
                  requestname &= "Semen Analysis"
               End If
            End If   
         Next
      Case "protein studies"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "immunoglobulin a") Then
               If Not InStr(Lower(requestname), "IgA") Then
                  requestname &= "IgA;"
               End If
            End If   
         Next
      Case "s-coeliac autoabs", "coeliac serology"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "transglutaminase") Or InStr(Lower(observation!identifier), "ttg iga") Then
               If Not InStr(Lower(requestname), "transglutaminase antibody") Then
                  requestname &= "Transglutaminase antibody;"
               End If
            End If
            If InStr(Lower(observation!identifier), "immunoglobulin a") Then
               If Not InStr(Lower(requestname), "IgA") Then
                  requestname &= "IgA;"
               End If
            End If
            
         Next
         
      Case ".anaemia"
         For Each observation In observations
            If InStr(Lower(observation!value), "iron") Then
               If Not InStr(Lower(requestname), "iron studies") Then
                  requestname &= "Iron studies incl. iron/TIBC;"
               End If
            End If
         Next
      Case "haemochromatosis gene sty (hmc-0)"
         Requestname &= "Haemachromatosis Gene Analysis;"
      Case ".coeliac hla dr/dq"
         requestname &= "Coeliac Genotyping;"
      Case "semen post vasectomy (spv-0)"
         requestname &= "Post vasectomy sperm count;"
      Case "x017", "serum chemistry (mba-0)"
         
         For Each observation In observations
            If observation!pit = False Then  
               If InStr(Lower(observation!value), "iron") Then
                  If Not InStr(Lower(requestname), "iron studies") Then
                     requestname &= "Iron studies incl. iron/TIBC;"
                  End If
               End If
               If InStr(Lower(observation!value), "protein epg") Then
                  If Not InStr(Lower(requestname), "Protein Electrophoresis") Then
                     requestname &= "Protein Electrophoresis;"
                  End If
               End If
               If InStr(Lower(observation!value), "zinc") Then
                  If Not InStr(requestname, "Serum zinc") Then
                     requestname &= "Serum zinc;"
                  End If
               End If
               If InStr(Lower(observation!value), "streptolysin") Then
                  If Not InStr(requestname, "Streptolysin O Ab;") Then
                     requestname &= "Streptolysin O Ab;"
                  End If
               End If
               If InStr(Lower(observation!value), "glucose-6-phosphate dehydrogenase") Then
                  If Not InStr(requestname, "Glucose-6-Phosphate Dehydrogenase") Then
                     requestname &= "Glucose-6-Phosphate Dehydrogenase;"
                  End If
               End If
               
               If InStr(Lower(observation!value), "cholesterol") And Not InStr(Lower(observation!value), "triglycerides") Then
                  If Not InStr(Requestname, "Cholesterol") Then
                     requestname &= "Cholesterol;"
                  End If
               End If
               If InStr(Lower(observation!value), "cholesterol") And InStr(Lower(observation!value), "triglycerides") Then
                  If Not InStr(Lower(requestname), "cholesterol and triglycerides") Then
                     requestname &= "Cholesterol and Triglycerides;"
                  End If
               End If
               If InStr(Lower(observation!value), "digoxin") Then
                  If Not InStr(Lower(requestname), "digoxin") Then
                     requestname &= "Digoxin;"
                  End If
               End If
               If InStr(Lower(observation!value), "phenytoin") Then
                  If Not InStr(requestname, "phenytoin") Then
                     requestname &= "Phenytoin;"
                  End If
               End If
               
               If InStr(Lower(observation!value), "potassium") Then
                  If Not InStr(Lower(requestname), "potassium") And Not InStr(Lower(requestname), "uec") Then
                     requestname &= "Potassium;"
                  End If
               End If
               If InStr(Lower(observation!value), "valproic") Then
                  If Not InStr(Lower(requestname), "valproate") Then
                     requestname &= "Valproate;"
                  End If
               End If
               
               If InStr(Lower(observation!value), "hdl") Then
                  If Not InStr(Lower(requestname), "hdl cholesterol") Then
                     requestname &= "HDL Cholesterol;"
                  End If
               End If
               If InStr(Lower(observation!value), "vitamin b12") Then
                  If Not InStr(Lower(requestname), "vitamin b12") Then
                     requestname &= "Vitamin B12;"
                  End If
               End If
               
               If InStr(Lower(observation!value), "total ck") Then
                  If Not InStr(Lower(requestname), "cpk") Then
                     requestname &= "CPK;"
                  End If
               End If
               If InStr(Lower(observation!value), "troponin") Then
                  If Not InStr(Lower(requestname), "troponin") Then
                     requestname &= "Troponin;"
                  End If
               End If
               
               If InStr(Lower(observation!value), "immunofixation") Then
                  If Not InStr(Lower(requestname), "serum immunofixation electrophoresis") Then
                     requestname &= "serum immunofixation electrophoresis;"
                  End If
               End If
               
               If InStr(Lower(observation!value), "angiotensin converting enzyme") Then
                  If Not InStr(Lower(requestname), "angiotensin converting enzyme (ace)") Then
                     requestname &= "Angiotensin converting enzyme (ACE);"
                  End If
               End If
               If InStr(Lower(observation!value), "vancomycin") Then
                  If Not InStr(Lower(requestname), "vancomycin") Then
                     requestname &= "Vancomycin;"
                  End If
               End If
               
               If InStr(Lower(observation!value), "ck isoenzyme") Then
                  If Not InStr(Lower(requestname), "ck") Then
                     requestname &= "CK;"
                  End If
               End If
               
               If InStr(Lower(observation!value), "homocysteine") Then
                  If Not InStr(Lower(requestname), "homocysteine") Then
                     requestname &= "Homocysteine;"
                  End If
               End If
               
               If InStr(Lower(observation!value), "gliadin") Then
                  If Not InStr(Lower(requestname), "anti-gliadin antibody") Then
                     requestname &= "Anti-gliadin antibody;"
                  End If
               End If
               If InStr(Lower(observation!value), "folate red cell") Then
                  If Not InStr(Lower(requestname), "red cell folate") Then
                     requestname &= "Red Cell Folate;"
                  End If
               End If
               
               If InStr(Lower(observation!value), "vitamen b12") Then
                  If InStr(Lower(observation!value), "folate") Then
                     If Not (InStr(Lower(observation!value), "vitamin b12 and folate")) Then
                        requestname &= "Vitamin B12 and Folate;"
                     End If
                  Else
                     If Not (InStr(Lower(observation!value), "vitamin b12")) Then
                        requestname &= "Vitamin B12;"
                     Endif
                  Endif
               End If   
               
               If InStr(Lower(observation!value), "25-oh vitamin d") Then
                  If Not InStr(Lower(requestname), "vitamin d") Then
                     requestname &= "Vitamin D;"
                  End If
               End If 
               If InStr(Lower(observation!value), "folate") Then
                  If InStr(Lower(observation!value), "vitamin b12") Then
                     If Not (InStr(Lower(observation!value), "vitamin b12 and folate")) Then
                        requestname &= "Vitamin B12 and Folate;"
                     End If
                  Else
                     If Not (InStr(Lower(observation!value), "folate")) Then
                        requestname &= "Folate;"
                     Endif
                  Endif
               End If   
               If InStr(Lower(observation!value), "cortisol") Then
                  If Not InStr(requestname, "Cortisol") Then
                     requestname &= "Cortisol;"
                  End If 
               End If
               
               If InStr(Lower(observation!value), "hba1c") Then
                  If Not InStr(Lower(requestname), "hba1c") Then
                     requestname &= "HBA1c;"
                  End If
               End If
               If InStr(Lower(observation!value), "egfr") Then
                  If Not InStr(Lower(requestname), "egfr") Then 
                     requestname &= "eGFR;" 
                  End If
               End If 
               If InStr(Lower(observation!value), "glucose") Then
                  If Not InStr(Lower(requestname), "bsl;") Then 
                     requestname &= "BSL;"
                  End If
               End If           
               If InStr(Lower(observation!value), "alt ") Then
                  If Not InStr(Lower(requestname), "lfts;") Then 
                     requestname &= "LFTs;"
                  End If
               End If           
               If InStr(Lower(observation!value), "sodium") Or InStr(Lower(observation!value), "na ") Then 'leave in the space
                  If Not InStr(Lower(requestname), "uec;") Then 
                     requestname &= "UEC;"
                  End If
               End If           
               If InStr(Lower(observation!value), "creatinine ") And Not InStr(requestname, "UEC") Then 'DO NOT MOVE THIS OUT OF ORDER
                  If Not InStr(Lower(requestname), "creatinine;") Then 
                     requestname &= "Creatinine;"
                  End If
               End If           
            End If  
         Next
      Case "_immunoglobulins"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "immunoglobulin g") Then
               If Not InStr(requestname, "IgG") Then
                  requestname &= "IgG;"
               End If 
            End If
            If InStr(Lower(observation!identifier), "immunoglobulin g") Then
               If Not InStr(requestname, "IgM") Then
                  requestname &= "IgM;"
               End If 
            End If
            If InStr(Lower(observation!identifier), "immunoglobulin a") Then
               If Not InStr(requestname, "IgA;") Then
                  requestname &= "IgA;"
               End If 
            End If   
         Next 
      Case ".ftest"
           For Each Observation In Observations
            If InStr(Lower(observation!identifier), "testosterone") Then
               If Not InStr(requestname, "Testosterone") Then
                  requestname &= "Testosterone;"
               End If 
            End If
           Next
      Case "x018"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "cardiolipin") Then
               If Not InStr(requestname, "cardiolipin") Then
                  requestname &= "Anti-cardiolipin antibody;"
               End If 
            End If
            If InStr(Lower(observation!value), "smooth muscle ab") Then
               If Not InStr(requestname, "Anti-smooth muscle antibody;") Then
                  requestname &= "Anti-smooth muscle antibody;"
               End If 
            End If
            
            If InStr(Lower(observation!value), "intrinsic factor ab") Then
               If Not InStr(requestname, "Intrinsic factor antibody") Then
                  requestname &= "Intrinsic factor antibody;"
               End If 
            End If
            If InStr(Lower(observation!value), "anti-thyroglobulin ab") Then
               If Not InStr(requestname, "Anti-thyroglobulin Ab") Then
                  requestname &= "Anti-thyroglobulin Ab;"
               End If 
            End If
            If InStr(Lower(observation!value), "mantoux") Then
               If Not InStr(Lower(requestname), "mantoux test") Then
                  requestname &= "Mantoux test;"
               End If 
            End If 
            If InStr(Lower(observation!value), "anti-microsomal ab") Then
               If Not InStr(requestname, "Anti-microsomal Ab") Then
                  requestname &= "Anti-microsomal Ab;"
               End If 
            End If
            
            If InStr(Lower(observation!value), "b2gp1") Then
               If Not InStr(requestname, "B2GP1") Then
                  requestname &= "Beta 2 Glycoprotein 1 (B2GP1) Antibodies;"
               End If 
            End If
            If InStr(Lower(observation!value), "immunoglobulin g") Then
               If Not InStr(requestname, "IgG") Then
                  requestname &= "IgG;"
               End If 
            End If
            If InStr(Lower(observation!value), "immunoglobulin g") Then
               If Not InStr(requestname, "IgM") Then
                  requestname &= "IgM;"
               End If 
            End If
            If InStr(Lower(observation!value), "immunoglobulin a") Then
               If Not InStr(requestname, "IgA;") Then
                  requestname &= "IgA;"
               End If 
            End If
            If InStr(Lower(observation!value), "ss-a") Then
               If Not InStr(requestname, "Anti-SS-A;") Then
                  requestname &= "Anti-SS-A;"
               End If 
            End If
            If InStr(Lower(observation!value), "ss-b") Then
               If Not InStr(requestname, "Anti-SS-B;") Then
                  requestname &= "Anti-SS-B;"
               End If 
            End If
            If InStr(Lower(observation!value), "jo-1") Then
               If Not InStr(requestname, "Anti-Jo-1 Antibody;") Then
                  requestname &= "Anti-Jo-1 Antibody;"
               End If 
            End If
            If InStr(Lower(observation!value), "rnp") Then
               If Not InStr(requestname, "Anti-RNP;") Then
                  requestname &= "Anti-RNP;"
               End If 
            End If
            If InStr(Lower(observation!value), "scl-70") Then
               If Not InStr(requestname, "Anti-Scl-70;") Then
                  requestname &= "Anti-Scl-70;"
               End If 
            End If
            If InStr(Lower(observation!value), "ena") Then
               If Not InStr(requestname, "Anti-ENA;") Then
                  requestname &= "Anti-ENA;"
               End If 
            End If
            
         Next
         
      Case "x019"
         For Each observation In observations
            If InStr(Lower(observation!value), "bordetella pertussis") Then
               If Not InStr(Lower(requestname), "bordetella pertussis pcr;") Then 
                  requestname &= "Bordetella Pertussis PCR;"
               End If 
            End If
            If InStr(Lower(observation!value), "neisseria gonorrhoeae") Then
               If Not InStr(Lower(requestname), "neisseria gonorrhoeae") Then 
                  requestname &= "Neisseria gonorrhoeae PCR;"
               End If 
            End If        
            If InStr(Lower(observation!value), "herpes") Then
               If Not InStr(Lower(requestname), "herpes") Then 
                  requestname &= "Herpes simplex virus PCR;"
               End If 
            End If        
            
         Next
         
      Case "x020", "fluid micro/culture (fld-0)", "fliud chemistries (cfl-0)", "fluid chemistries (cfl-0)" 'can't spell either
         
         For Each Observation In Observations
            If InStr(Lower(observation!value), "parvovirus") Then
               requestname &= "Human parvovirus - EIA IgG IgM;"
            End If
            If InStr(Lower(observation!value), "rubella") Then
               If Not InStr(requestname, "Rubella") Then
                  requestname &= "Rubella - EIA IgG/IgM;"
               Endif
            Endif
            
            If InStr(Lower(observation!value), "bordetella") Then
               requestname &= "Bordetella Pertussis IgA;"
            End If
            
            If InStr(Lower(observation!value), "mycoplasma pneumoniae") Then
               requestname &= "Mycoplasma pneumoniae - EIA IgM (CFT);"
            End If
            If InStr(Lower(observation!value), "barmah forest virus serology") Then
               requestname &= "Barmah Forest Virus Serology;"
            End If
            
            If InStr(Lower(observation!value), "cytomegalovirus") Then
               requestname &= "Cytomegalovirus - EIA IgG IgM;"
            End If
            If InStr(Lower(observation!value), "toxoplasma gondii") Then
               If Not InStr(observation!value, "Toxoplasma gondii - EIA IgG/IgM") Then   
                  requestname &= "Toxoplasma gondii - EIA IgG/IgM;"
               Endif
            End If
            If InStr(Lower(observation!value), "c trachomatis serology") Then
               If Not InStr(requestname, "Chlamydia antibody - IF or EIA") Then
                  requestname &= "Chlamydia antibody - IF or EIA;"
               Endif
            Endif
            If InStr(Lower(observation!value), "varicella-zoster") Then
               requestname &= "Varicella zoster virus - EIA or IF IgG/IgM;"
            Endif
            If InStr(Lower(observation!value), "ross river virus") Then
               If Not InStr(requestname, "Ross River - EIA or HI") Then 
                  requestname &= "Ross River - EIA or HI;"
               End If
            Endif
            If InStr(Lower(observation!value), "syphilis") Then
               requestname &= "Treponemal Ab (EIA);"
            End If
            If InStr(Lower(observation!value), "pleural", 0, gb.IgnoreCase) Then
               If InStr(Lower(SelectedDocument!tag), "micro") Then
                  If Not InStr(requestname, "Pleural fluid c&s;") Then
                     requestname = "Pleural fluid c&s;"
                  End If
               Else
                  If Not InStr(requestname, "Pleural fluid biochemistry;") Then
                     requestname &= "Pleural fluid biochemistry;"
                  End If
               End If  
            End If
            
         Next   
         
         If InStr(Lower(observation!value), "epstein-barr virus") Then
            If Not InStr(requestname, "Epstein Barr virus EIA IgG IgM") Then
               requestname &= "Epstein Barr virus EIA IgG IgM;"
            End If
         End If     
         If InStr(Lower(observation!value), "hiv") Then
            If Not InStr(Lower(requestname), "anti-hiv antibody") Then
               requestname &= "Anti-HIV Antibody;"
            End If
         End If
         
      Case "x023"
         For Each observation In observations
            If InStr(Lower(observation!value), "psa") Then
               If Not InStr(Lower(requestname), "psa;") Then 
                  requestname &= "PSA;"
               End If 
            End If        
         Next     
      Case "x026", "gluc challenge"
         For Each observation In observations
            If InStr(Lower(observation!value), "50") And InStr(Lower(observation!value), "gtt") Then
               If Not InStr(Lower(requestname), "gtt") Then 
                  requestname &= "GTT 50gm Pregnancy;"
               End If 
            End If  
            If InStr(Lower(observation!value), "75g") And InStr(Lower(observation!value), "gtt") Then
               If Not InStr(Lower(requestname), "gtt") Then 
                  requestname &= "GTT;"
               End If 
            End If        
            
         Next     
      Case "occult blood (ocb-0)", "occult blood (ocb-1)", "occult blood (ocb-2)", "occult blood (ocb-3)"
         For Each observation In observations
            If InStr(Lower(observation!value), "occult blood") Then
               If Not InStr(Lower(requestname), "faecal occult blood;") Then 
                  requestname &= "Faecal Occult Blood;"
                  If InStr(Lower(observation!value), "positive") Then
                     Message.Title = "ABNORMAL RESULT"
                     Message.Warning("This is a postive Faecal occult blood.\n\nIt is vital that this is actioned") 
                  Endif
               End If 
            End If        
         Next  
      Case "x025"
         For Each observation In observations
            If InStr(Lower(observation!value), "hla b27 ag") Then
               If Not InStr(requestname, "HLA B27;") Then 
                  requestname &= "HLA B27;"
               End If 
            End If        
         Next    
      Case "x029"
         For Each observation In observations
            If InStr(Lower(observation!value), "faeces") Then
               If Not InStr(Lower(requestname), "faeces - ova, cysts parasites (microscopy, direct+/-concentrate);") Then 
                  requestname &= "Faeces - ova, cysts parasites (microscopy, direct+/-concentrate);"
               End If 
            End If        
         Next  
         For Each observation In observations
            If InStr(Lower(observation!value), "occult blood") Then
               If Not InStr(Lower(requestname), "faecal occult blood;") Then 
                  requestname &= "Faecal Occult Blood;"
                  If InStr(Lower(observation!value), "positive") Then
                     Message.Title = "ABNORMAL RESULT"
                     Message.Warning("This is a postive Faecal occult blood.\n\nIt is vital that this is actioned") 
                  Endif
               End If 
            End If        
         Next  
      Case "x031"
         For Each observation In observations
            If InStr(Lower(observation!value), "thyroglobulin") Then
               If Not InStr(Lower(requestname), "thyroglobulin") Then 
                  requestname &= "Thyroglobulin;"
               End If 
            End If  
            If InStr(Lower(observation!value), "anti-thyroglobulin ab") Then
               If Not InStr(Lower(requestname), "anti-thyroglobulin ab") Then 
                  requestname &= "Anti-thyroglobulin Ab;"
               End If 
            End If    
            If InStr(Lower(observation!value), "vitamin d") Then
               If Not InStr(Lower(requestname), "vitamin d;") Then 
                  requestname &= "Vitamin D;"
               End If 
            End If    
         Next
         If InStr(Lower(observation!value), "androstenedione") Then
            If Not InStr(Lower(requestname), "androstenedione") Then 
               requestname &= "Androstenedione;"
            End If 
         End If  
         If InStr(Lower(observation!value), "dheas") Then
            If Not InStr(Lower(requestname), "dheasandrostenedione") Then
               requestname &= "DHEAS;"
            End If 
         End If   
         If InStr(Lower(observation!value), "dpd") Then
            If Not InStr(requestname, "DPD/Cr (morning urine pyridinoline/Cr)") Then
               requestname &= "DPD/Cr (morning urine pyridinoline/Cr);"
            End If 
         End If     
         
      Case "x032"
         For Each observation In observations
            If InStr(Lower(observation!value), "wcc") Or InStr(Lower(observation!value), "neutrophils") Then
               If Not InStr(Lower(requestname), "fbc;") Then 
                  requestname &= "FBC;"
               End If 
            End If    
            If InStr(Lower(observation!value), "haemoglobin") Then
               If Not InStr(Lower(requestname), "fbc;") Or Not InStr(Lower(requestname), "hb") Then 
                  requestname &= "Hb;"
               End If 
            End If    
            If InStr(Lower(observation!value), "malarial parasites") Then
               If Not InStr(requestname, "Malaria ICT for Falciparum and Vixax") Then 
                  requestname &= "Malaria ICT for Falciparum and Vixax;"
               End If 
            End If         
            
         Next  
         For Each observation In observations
            If InStr(Lower(observation!value), "heterophile") Then
               If Not InStr(Lower(requestname), "heterophile antibody;") Then 
                  requestname &= "heterophile antibody;"
               End If 
            End If        
         Next  
      Case "x037"
         For Each observation In observations
            If InStr(Lower(observation!value), "thyroid receptor") Then
               If Not InStr(requestname, "Thryoid receptor antibody") Then 
                  requestname &= "Thryoid receptor antibody;"
               End If 
            End If    
            If InStr(Lower(observation!value), "rast allergen response") Or InStr(Lower(observation!value), "allergy serology") Then
               If Not InStr(requestname, "Rast Allergy Testing") Then 
                  requestname &= "Rast Allergy Testing;"
               End If 
            End If     
         Next  
         
      Case "x051"
         For Each observation In observations
            If InStr(Lower(observation!value), "tsh") Then
               If Not InStr(Lower(requestname), "tsh") Then 
                  requestname &= "TSH;"
               End If 
            End If        
         Next     
      Case "alpha globulin, urine"
         For Each observation In observations
            If InStr(Lower(observation!value), "alpha 1 microglobulin") Then
               If Not InStr(requestname, "Urine Alpha-1 Microglobulin (A1M)") Then  
                  requestname &= "Urine Alpha-1 Microglobulin (A1M);"
               End If
            End If
         Next 
         
      Case "x027"
         For Each observation In observations
            If InStr(Lower(observation!value), "creatinine clearance") Then
               If Not InStr(Lower(requestname), "creatinine clearance") Then
                  requestname &= "24hour Urinary Creatinine Clearance;"
               End If
            End If
            If InStr(Lower(observation!value), "electrolytes, urine") Then
               If Not InStr(Lower(requestname), "creatinine clearance") Then
                  requestname &= "Electrolytes - urine;"
               End If
            End If
            If InStr(Lower(observation!value), "catecholamines, urine") Then
               If Not InStr(Lower(requestname), "catecholamines") Then
                  requestname &= "24hr urine catecholamines;"
               End If
            End If
            
            If InStr(Lower(observation!value), "calculi") Then
               If Not InStr(Lower(requestname), "calculus - renal") Then
                  requestname &= "Calculus - renal;"
               End If
            End If
            If InStr(Lower(observation!value), "b2 microglobulin") Then
               If Not InStr(requestname, "Beta-2 Microglobulin") Then
                  requestname &= "Beta-2 Microglobulin;"
               End If
            End If
            If InStr(Lower(observation!value), "magnesium") Then
               If Not InStr(requestname, "24Hr Urine Magnesium") Then
                  requestname &= "24Hr Urine Magnesium;"
               End If
            End If 
            If InStr(Lower(observation!value), "oxalate") Then
               If Not InStr(requestname, "24Hr Urine Oxalate") Then
                  requestname &= "24Hr Urine Oxalate;"
               End If
            End If 
            If InStr(Lower(observation!value), "citrate") Then
               If Not InStr(requestname, "24Hr Urine Citrate") Then
                  requestname &= "24Hr Urine Citrate;"
               End If
            End If 
            If InStr(Lower(observation!value), "urinary free cortisol") Then
               If Not InStr(Lower(requestname), "cortisol - urinary free;") Then
                  requestname &= "cortisol - urinary free;"
               End If
            End If 
            
         Next
      Case "x034"
         For Each observation In observations
            If InStr(Lower(observation!value), "chromosome analysis") Then
               If Not InStr(Lower(requestname), "chromosome analysis") Then
                  requestname &= "chromosome analysis;"
               End If
            End If
            If InStr(Lower(observation!value), "hiv") Then
               If Not InStr(requestname, "Anti-HIV") Then
                  requestname &= "Anti-HIV antibody;"
               End If
            End If
            If InStr(Lower(observation!value), "papp-a") Then
               If Not InStr(requestname, "Pregnancy Associated Plasma Protein a (PAPPA)") Then
                  requestname &= "Pregnancy Associated Plasma Protein a (PAPPA);"
               End If
            End If
         Next
         
      Case "x035", "coagulation screen", "a.p.t.t (apt-0)"
         For Each observation In observations
            If InStr(Lower(observation!value), "protein s") Then
               If Not InStr(Lower(requestname), "protein s") Then
                  requestname &= "Protein S;"
               End If
            End If
            If InStr(Lower(observation!value), "protein c") Then
               If Not InStr(Lower(requestname), "protein c") Then
                  requestname &= "Protein C;"
               End If
            End If
            If InStr(Lower(observation!value), "lupus anticoagulant") Then
               If Not InStr(requestname, "Lupus Anti-coagulant") Then
                  requestname &= "Lupus Anti-coagulant;"
               End If
            End If
            If InStr(Lower(observation!value), "antithrombin") Then
               If Not InStr(requestname, "Anti-thrombin III;") Then
                  requestname &= "Anti-thrombin III;"     
               End If
            End If
            If InStr(Lower(observation!value), "inr") Then
               If Not InStr(requestname, "INR;") Then
                  requestname &= "INR;"     
               End If
            End If
            If InStr(Lower(observation!value), "prothrombin time") Then
               If Not InStr(requestname, "Prothrombin time;") Then
                  requestname &= "Prothrombin Time;"     
               End If
            End If
            
            If InStr(Lower(observation!value), "fibrinogen") Then
               If Not InStr(requestname, "Fibrinogen;") Then
                  requestname &= "Fibrinogen;"     
               End If
            End If
            If InStr(Lower(observation!value), "aptt") Then
               If Not InStr(requestname, "APTT") Then
                  requestname &= "APTT (Activated Partial Thromboplastin Time);"     
               End If
            End If
            
         Next
         
      Case "x044"
         For Each observation In observations
            If InStr(Lower(observation!value), "arterial blood gases") Then
               If Not InStr(Lower(requestname), "arterial blood gases") Then
                  requestname &= "Arterial Blood Gases;"
               End If
            End If
            If InStr(Lower(observation!value), "aptt") Then
               If Not InStr(requestname, "APTT") Then
                  requestname &= "APTT (Activated Partial Thromboplastin Time);"     
               End If
            End If
            
            If InStr(Lower(observation!value), "haemoglobin") Then
               If Not InStr(Lower(requestname), "hb") Then
                  requestname &= "Hb;"
               End If
            End If
            
         Next
      Case "x045"
         For Each observation In observations
            If InStr(Lower(observation!value), "chlamydia serology") Then
               If Not InStr(requestname, "Chlamydia antibody - IF or EIA") Then
                  requestname &= "Chlamydia antibody - IF or EIA;;"
               End If
            End If  
            If InStr(Lower(observation!value), "chlamydia trachomatis") Then 'mixture here sometimes pcr is included sometimes not
               If Not InStr(requestname, "chlamydia trachomatis pcr") Then
                  requestname &= "Chlamydia Trachomatis PCR;"
               End If
            End If  
            
         Next
      Case "x046", "mtb1"
         For Each observation In observations
            If InStr(Lower(observation!value), "afb") Then
               If InStr(Lower(observation!value), "sputum") Then
                  If Not InStr(Lower(requestname), "sputum for afb") Then
                     requestname &= "Sputum for AFB;"
                  End If
               End If
            End If
            If InStr(Lower(observation!value), "pleural fluid") Then
               If Not InStr(Lower(requestname), "pleural fluid c&s for afb") Then
                  requestname &= "Pleural fluid c&s for AFB;"
               End If
            End If
            
         Next  
      Case "thal"
         For Each observation In observations
            If Not InStr(Lower(requestname), "thalassemia") Then 
               requestname &= "Thalassemia screen;"
            End If
         Next  
      Case "faecal viruses"
         For Each observation In observations
            If InStr(Lower(observation!value), "norovirus") Then
               requestname &= "Norovirus Antigen;"
            Endif
         Next
      Case "hormones (hoc-0)"
         For Each observation In observations
            If Not InStr(Lower(requestname), "testosterone;") Then 
               If InStr(Lower(observation!value), "testosterone") Then
                  requestname &= "Testosterone;"
               End If
            End If
            If Not InStr(Lower(requestname), "dheas;") Then 
               If InStr(Lower(observation!value), "dheas") Then
                  requestname &= "DHEAS;"
               End If
            End If
            
         Next
      Case "referred test (sen-0)"
         For Each observation In observations
            If InStr(Lower(observation!value), "shbg") Then
               requestname &= "Sex hormone binding globulin;"
               Break
            End If
         Next
      Case "clinical chemistry"
         
         requestname = Guess_Request_Names_From_Observation(Observations)
         If requestname = "" Then 
            For Each observation In observations
               If observation!value_type = "NM" Then
                  If Not IsNull(observation!identifier) Then
                     requestname &= Loinc_Get_component(observation!loinc)
                  Endif
                  Break
               End If
            Next
         End If
      Case "blood histamine"
         Requestname &= "B-Histamine"
      Case "spore1", "spore2", "spore3", "spore4", "spore5", "spore6", "spore7", "spore8", "spore9", "spore10"
         requestname &= "spore testing - autoclave;"
      Case "biochemistry"
         'This really sucks, evolving code over time, this module is really bad now
         requestname &= Guess_Request_Names_From_Observation(observations) 
         If requestname = "" Then
            Print
         Endif
         
      Case "biochem"    ' , "biochemistry"
         For Each observation In observations
            If InStr(Lower(observation!value), "calculus analysis") Then
               requestname &= "Calculus - renal;"
               
            End If
         Next
         For Each observation In observations
            If InStr(Lower(observation!identifier), "total protein") Then  
               If Not InStr(requestname, "Protein - Serum") Then
                  requestname &= "Protein - Serum;"
               End If  
            Endif
         Next
         
      Case "x011", "histos"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "histology") Then
               If Not InStr(requestname, "Histopathology") Then
                  requestname = "Histopathology;"
               End If 
            End If
         Next
      Case "x055"
         For Each observation In observations
            If InStr(Lower(observation!value), "rpr") Then
               If Not InStr(Lower(observation!value), "rpr/vdrl-flocculation") Then
                  requestname = "RPR/VDRL - flocculation;"
               Endif
            Endif
         Next 
      Case "serology (axm-0)" 'symbion
         For Each observation In observations
            If InStr(Lower(observation!value), "rubella") Then
               If Not InStr(requestname, "Rubella - EIA IgG/IgM") Then 
                  requestname &= "Rubella - EIA IgG/IgM;"
               Endif
            End If
            If InStr(Lower(observation!value), "cmv") Then
               If Not InStr(requestname, "Cytomegalovirus") Then
                  requestname &= "Cytomegalovirus - EIA IgG IgM;"
               End If
            End If
            If InStr(Lower(observation!value), "toxo") Then
               If Not InStr(requestname, "Toxoplasma") Then
                  requestname &= "Toxoplasma gondii - EIA IgG/IgM;"
               Endif
               
            End If            
         Next
      Case "general serology", "general serology.", "panel serology"  'fuckwits HAPS
         For Each observation In observations
            If InStr(Lower(observation!value), "hepatitis c") And Not InStr(Lower(observation!value), "hep c rna") Then
               If Not InStr(requestname, "Hepatitis C Studies") Then
                  requestname &= "Hepatitis C Studies;"
               End If   
            End If
            
            If InStr(Lower(observation!value), "hep c rna") Then
               requestname &= "Hepatitis C RNA;"
            End If
            
            If InStr(Lower(observation!value), "rubella igg") Then
               If Not InStr(requestname, "Rubella - EIA IgG/IgM") Then 
                  requestname &= "Rubella - EIA IgG/IgM;"
               End If   
            End If
            If InStr(Lower(observation!value), "pertussis pcr") Then
               requestname &= "Bordetella pertussis PCR;"
            End If
            If InStr(Lower(observation!value), "hepb surface ab") Then
               requestname &= "Hepatitis B surface antibody - EIA IgG;"
            End If
            If InStr(Lower(observation!value), "hepb surface ag") Then
               requestname &= "Hepatitis B surface antigen;"
            End If
            If InStr(Lower(observation!value), "syphilis") Then
               requestname &= "Syphilis;"
            End If
            If InStr(Lower(observation!value), "cmv") Then
               If Not InStr(requestname, "Cytomegalovirus - EIA IgG IgM;") Then
                  requestname &= "Cytomegalovirus - EIA IgG IgM;"
               End If
            End If
            If InStr(Lower(observation!value), "streptococcus group a") Then
               If Not InStr(requestname, "Streptolysin O Ab;") Then
                  requestname &= "Streptolysin O Ab;"
               End If
            End If
            If InStr(Lower(observation!value), "parvovirus") Then
               If Not InStr(requestname, "Parvovirus;") Then
                  requestname &= "Parvovirus;"
               End If
            End If
            If InStr(Lower(observation!value), "anti-dnase") Then
               If Not InStr(requestname, "Anti-Dnase B") Then
                  requestname &= "Anti-Dnase B;"
               End If
            End If
            If InStr(Lower(observation!value), "ebv") Then
               If Not InStr(requestname, "Epstein Barr virus EIA IgG IgM;") Then
                  requestname &= "EBV;"
               End If
            End If
            
            If Not IsNull(observation!identifier) Then
               requestname &= Loinc_Get_component(observation!loinc) & ";"
            Endif
         Next      
      Case "viral pcr panel"
         For Each observation In observations
            If InStr(Lower(observation!value), "pertussis pcr") Or InStr(Lower(observation!value), "b.pertussis pcr") Then
               requestname = "Bordetella pertussis PCR;"
            End If
         Next
      Case "urine epg"
         requestname = "EPG - urine"
      Case "electrophoresis"
         For Each observation In observations
            If InStr(Lower(observation!value), "crp") Then
               requestname = "c-Reactive Protein;"
            Endif
            
            If InStr(Lower(observation!value), "urine") Then
               requestname = "EPG - urine;"
            Else
               If requestname = "" Then requestname = "Protein Electrophoresis;"
            End If
         Next
         
      Case "17ohp"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "17-oh progesterone") Then
               If Not InStr(requestname, "17 hydroxyprogesterone") Then
                  requestname &= "17 hydroxyprogesterone"
               Endif
            End If
         Next
      Case "hba1c/gtt"
         For Each observation In observations
            If InStr(Lower(observation!identifier), "hba1c") Then
               If Not InStr(Lower(requestname), "hba1c;") Then
                  requestname &= "hba1c;"
               Endif
            End If
            If InStr(Lower(observation!identifier), "hba1c (ifcc)") Then
               If Not InStr(Lower(requestname), "hba1c(ifcc);") Then
                  requestname &= "Hba1c (IFCC);"
               Endif
            Endif
            If InStr(Lower(observation!identifier), "glucose load") And observation!value = "50" Then
               If Not InStr(requestname, "GTT 50gm Pregnancy") Then
                  requestname &= "GTT 50gm Pregnancy;"
               Endif
            Endif
         Next
         
      Case "respir.microbiology"
         For Each observation In observations
            If InStr(Lower(observation!value), "swab cough") Then
               requestname = "Cough Swab C&S;"
            End If
         Next   
      Case "coag inhibitor assay"
         For Each observation In observations
            If InStr(Lower(observation!value), "lupus anticoagulant") Then
               requestname = "Lupus Anti-coagulant;"
            End If
         Next   
      Case "blood bank"
         For Each Observation In Observations
            If InStr(Lower(Observation!identifier), "blood group") Then
               If Not InStr(requestname, "Blood group")
                  requestname &= "Blood group;"
               End If
            Endif
            If InStr(Lower(Observation!identifier), "antibody screen") Then
               If InStr(requestname, "Blood group") Then
                  requestname = "Blood group and Antibody screen;"
               Else
                  requestname &= "Red blood cell antibody screen;"
               End If   
            End If 
         Next
      Case "cross match (xm-0)"
      Case "tumour markers", "hormone testing", "hepatitis serology (hep-0)", "specific proteins (spp-0)", "anti leucocyte antibody (lla-0)", "hormones" ', "HORMONES (HOC-0)"
         
         For Each observation In observations
            If InStr(Lower(Observation!identifier), "serum hcg") Then
               If Not InStr(requestname, "Quantitative BHCG") Then
                  requestname &= "Quantitative BHCG"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "ca 19.9") Then
               If Not InStr(requestname, "Ca 19-9 (pancreatic tumour marker)") Then
                  requestname &= "Ca 19-9 (pancreatic tumour marker)"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "afp") Then
               If Not InStr(requestname, "Alpha Fetoprotein;") Then
                  requestname &= "Alpha Fetoprotein;"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "testosterone") Then
               If Not InStr(requestname, "Testosterone;") Then
                  requestname &= "Testosterone;"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "oestradiol") Then
               If Not InStr(requestname, "Oestradiol;") Then
                  requestname &= "Oestradiol;"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "shbg") Then 'sex hormone binding globulin
               If Not InStr(requestname, "SHBG;") Then
                  requestname &= "SHBG;"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "fai") Then 'sex hormone binding globulin
               If Not InStr(requestname, "Free Androgen Index;") Then
                  requestname &= "Free Androgen Index;"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "lh") Then 'sex hormone binding globulin
               If Not InStr(requestname, "LH;") Then
                  requestname &= "LH;"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "fsh") Then 'sex hormone binding globulin
               If Not InStr(requestname, "FSH;") Then
                  requestname &= "FSH;"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "cortisol") Then 'sex hormone binding globulin
               If Not InStr(requestname, "Cortisol") Then
                  requestname &= "Cortisol;"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "dheas") Then
               If Not InStr(requestname, "DHEAS") Then
                  requestname &= "DHEAS;"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "anti-hcv") Then
               If Not InStr(requestname, "Hepatitis C Studies") Then
                  requestname &= "Hepatitis C Studies;"
               Endif
            Endif
            If InStr(Lower(Observation!identifier), "hbsag") Then
               If Not InStr(requestname, "Hepatitis B surface antigen") Then
                  requestname &= "Hepatitis B surface antigen;"
               Endif
            Endif
            
         Next
         
         For Each observation In observations
            If Not IsNull(observation!identifier) And requestname = "" Then
               If Not IsNull(observation!loinc) Then 
                  sString = modCodingDBI.Loinc_Get_component(observation!loinc)
                  If Not InStr(Lower(sString), "service comment") Then
                     If Not modRequestsDBI.Request_Item_?exists(sString) Then
                        modRequestsDBI.Request_Save_loinc(sSTring)
                        modDBConnect.CommitTrans()
                     End If
                     If Not InStr(requestname, sString) Then
                        requestname &= sString & ";"
                     End If   
                  End If
               Else
                  requestname &= observation!identifier  
               End If
            Else
               'Try and guess from free text field
               If InStr(Lower(observation!value), "faeces") Then bFaeces = True
               If bFaeces Then 
                  If InStr(Lower(Observation!value), "occult blood") Then
                     requestname = "Faecal Occult Blood;"
                  Endif
               End If
               
            End If
         Next
      Case "pertussis culture"
         For Each Observation In Observations 
            If InStr(Lower(Observation!value), "pertussis") Then
               If Not InStr(requestname, "Bordetella Culture") Then
                  requestname = "Bordetella Culture;"
               End If   
            End If
         Next
      Case "direct antigen tests"   
         For Each Observation In Observations
            If InStr(Lower(Observation!value), "chlamydia trachomatis") Or InStr(Lower(Observation!value), "c.trachomatis") Then
               If Not InStr(requestname, "Chlamydia trachomatis PCR") Then
                  requestname &= "Chlamydia trachomatis PCR;"
               End If   
            End If
            If InStr(Lower(Observation!value), "neisseria gonorrhoeae") Or InStr(Lower(Observation!value), "n.gonorrhoeae") Then
               If Not InStr(requestname, "Neisseria gonorrhoeae PCR") Then
                  requestname &= "Neisseria gonorrhoeae PCR;"
               End If   
            End If
            If InStr(Lower(Observation!value), "influenza") Or InStr(Lower(Observation!value), "rsv") Then
               If Not InStr(requestname, "Viral antigen test - respiratory EIA IF - RSV influenza etc") Then
                  requestname &= "Viral antigen test - respiratory EIA IF - RSV influenza etc;"
               End If   
            End If
         Next
      Case "b12/folate/ferritin"
         For Each Observation In Observations
            If InStr(Lower(Observation!identifier), "b12") Then
               requestname &= "Vitamin B12 And Folate;"
            End If
            If InStr(Lower(Observation!identifier), "ferritin") Then
               If Not InStr(requestname, "Ferritin") Then
                  requestname &= "Ferritin;"
               End If   
            End If
            If InStr(Lower(Observation!identifier), "iron") Then
               requestname &= "Iron studies incl. iron/TIBC"
               If InStr(requestname, "Ferritin;") Then
                  requestname = Replace(requestname, "Ferritin;", "")
               Endif
            End If
         Next
      Case "u301"
         For Each Observation In Observations 
            If InStr(Lower(observation!identifier), "benzodiazepine") Then
               If Not InStr(requestname, "Benzodiazepine") Then
                  requestname &= "Benzodiazepine;"
               Endif
            Endif
         Next
      Case "virus culture"
         requestname &= "Virus Culture;"
      Case "androgens (and-0)"
         For Each Observation In Observations 
            If Not IsNull(observation!identifier) Then
               If Not IsNull(observation!loinc) Then 
                  sString = modCodingDBI.Loinc_Get_component(observation!loinc)  'may return an empty string.
                  If sString <> "" Then 
                     Request_Save_New_Term_From_Loinc_Component(sSTring)
                     requestname &= sString & ";"
                  End If  
               End If
            End If
         Next
         
      Case "therapeutic venesection"
         requestname &= "Venesection for polycythaemia vera;"
      Case "iron studies (fe-0)"
         For Each Observation In Observations 
            If Not InStr(requestname, "Iron studies incl. iron/TIBC") Then
               requestname &= "Iron studies incl. iron/TIBC;"
            End If   
         Next
         Print 
      Case "microbiology culture", "general swab m/c/s (pus-1)", "x028", "x039", "general swab m/c/s (pus-0)"
         For Each Observation In Observations
            If InStr(Lower(Observation!value), "blood culture") Then
               If Not InStr(requestname, "Blood culture - routine")
                  requestname &= "Blood culture - routine;"
               End If
            End If
            If InStr(Lower(Observation!value), "low vaginal") Then
               If Not InStr(requestname, "Low vaginal swab c&s")
                  requestname &= "Low vaginal swab c&s;"
               End If
            End If
            If InStr(Lower(Observation!value), "cannula") Then
               If Not InStr(requestname, "Cannula")
                  requestname &= "Cannula or intravenous line tip C&S;"
               End If
            End If
            If InStr(Lower(Observation!value), "polarisation") And InStr(Lower(Observation!value), "urate") Then
               If Not InStr(requestname, "Joint fluid c&s;Joint fluid crystals")
                  requestname &= "Joint fluid c&s;Joint fluid crystals;"
               End If
            End If
            
            If InStr(Lower(Observation!value), "faeces") Then
               If Not InStr(requestname, "Faeces - bacterial culture")
                  requestname &= "Faeces - bacterial culture;"
               End If
            End If
            If InStr(Lower(Observation!value), "urine") Then
               If Not InStr(requestname, "MSU")
                  requestname &= "MSU;"
               End If
            End If
            If InStr(Lower(Observation!value), "csf") Then
               If Not InStr(requestname, "CSF")
                  requestname &= "CSF;"
               End If
            End If
            
            If InStr(Lower(Observation!value), "wound") Or InStr(Lower(Observation!value), " ear ") Or InStr(Lower(Observation!value), "toe") Or InStr(Lower(Observation!value), "leg") Or InStr(Lower(Observation!value), "breast") Or InStr(Lower(Observation!value), "knee") Or InStr(Lower(Observation!value), "skin") Or InStr(Lower(Observation!value), "wrist") Or InStr(Lower(Observation!value), "finger") Then
               If Not InStr(Lower(Observation!value), "skin flora") Then   'msu's reported as skin flora sometimes.
                  If Not InStr(Lower(requestname), "pus swab c&s;")
                     requestname &= "Pus Swab c&s;"
                  End If
               End If   
            End If
            If InStr(Lower(Observation!value), "eye") Then
               If Not InStr(requestname, "Eye swab c&s;")
                  requestname &= "Eye swab c&s;"
               End If
            End If
            If InStr(Lower(Observation!value), "nose") Then
               If Not InStr(requestname, "Nasal swab c&s;")
                  requestname &= "Nasal swab c&s;"
               End If
            End If
            If InStr(Lower(Observation!value), "blood culture") Then
               If Not InStr(requestname, "Blood culture - routine;")
                  requestname &= "Blood culture - routine;"
               End If
            End If
            
            If InStr(Lower(Observation!value), "abscess") Then
               If Not InStr(requestname, "Abscess swab c&s;")
                  requestname &= "Abscess swab c&s;"
               End If
            End If
            If InStr(Lower(Observation!value), "sputum") Then
               If Not InStr(requestname, "Sputum culture - routine;")
                  requestname &= "Sputum culture - routine;"
               End If
            End If
            If InStr(Lower(Observation!value), "throat") Then
               If Not InStr(requestname, "Throat Swab c&s;")
                  requestname &= "Throat Swab c&s;"
               End If
            End If
            
            If InStr(Lower(Observation!value), "foot") Or InStr(Lower(Observation!value), "arm") Or InStr(Lower(Observation!value), "skin") Or InStr(Lower(Observation!value), "leg") Then
               If Not InStr(Lower(requestname), "pus swab c&s")
                  requestname &= "Pus Swab c&s;"
               End If
            End If
            If InStr(Lower(Observation!value), "fluid") And InStr(Lower(Observation!value), "knee") Then
               If Not InStr(requestname, "Joint fluid c&s;")
                  requestname &= "Joint fluid c&s;"
               End If
            End If
            If InStr(Lower(Observation!value), "swab high vaginal") Or InStr(Lower(Observation!value), "high vaginal") Then
               If Not InStr(requestname, "High Vaginal Swab c&s;")
                  requestname &= "High Vaginal Swab c&s;"
               End If
            End If
            
         Next
      Case "respiratory serology"
         requestname = "Viral antigen test - respiratory EIA IF - RSV influenza etc;"
      Case "parasite screening"
         For Each Observation In Observations
            If InStr(Lower(Observation!value), "faeces") Then
               requestname = "Faeces - ova, cysts parasites (microscopy, direct+/-concentrate);"
            End If
         Next
      Case "nephrology lab urines"
         requestname = "urine - red cell morphology;"
      Case "faeces microbiology (fmc-1)" 
         requestname = "Faeces - ova, cysts parasites (microscopy, direct+/-concentrate)"
      Case "rast"
         requestname = "RAST Allergy Testing"
         For Each Observation In Observations
            If InStr(Lower(Observation!identifier), "latex") Then
               If Not InStr(requestname, "RAST - Latex") Then
                  requestname = "RAST - Latex;"
               Endif
            Endif
         Next
      Case "fbc", "haematology", "_haematology"
         For Each Observation In Observations
            If Not IsNull(observation!identifier) Then
               Select Case Lower(observation!identifier)
                  Case "haemoglobin"
                     requestname = "Hb"
                  Case "esr"
                     requestname &= "ESR;"
                  Case Else
                     
                     requestname &= observation!identifier
               End Select
            End If
         Next
         If requestname <> "ESR;" Then 
            If InStr(requestname, "ESR") Then
               requestname = "FBC;ESR"
            Else
               If requestname <> "Hb" Then
                  requestname = "FBC;"
               End If
            End If
         End If
         
      Case "pth"
         For Each Observation In Observations
            Select Case Lower(observation!identifier)
               Case "intact parathyroid hormone"
                  requestname &= "Parathyroid hormone;" 
               Case "calcium"
                  requestname &= "Calcium"
                  
            End Select
         Next
      Case "e498"
         For Each Observation In Observations
            Select Case Lower(observation!identifier)
                  
               Case "carcinoembryonic ag"
                  requestname &= "Carcinoembryonic antigen;"
               Case "alpha fetoprotein"
                  requestname &= "Alpha Fetoprotein;"
            End Select
         Next 
      Case "iron studies", "irs"
         For Each Observation In Observations
            Select Case Lower(observation!identifier)
               Case "transferrin"
                  
               Case "ferritin"
                  requestname &= "Ferritin" & ";"
               Case "iron", "tibc(calculated)", "saturation"
                  If Not InStr(requestname, "Iron studies incl. iron/TIBC") Then
                     requestname &= "Iron studies incl. iron/TIBC;"
                  End If   
            End Select
         Next
         If InStr(requestname, "Iron studies incl. iron/TIBC") Then
            requestname = Replace(requestname, "Ferritin;", "") 'if it exists
         End If
         
      Case "ctsw1"
         requestname = "Chlamydia trachomatis PCR"
      Case "ngsw1"
         requestname = "Neisseria gonorrhoeae PCR"
      Case "creatinine clearance"
         requestname = "24hour Urinary Creatinine Clearance"
      Case "s/away"
         requestname = "Pending - sent away"
      Case "hiv"
         requestname = "Anti-HIV Antibody"
      Case "bpcr"
         requestname = "Bordetella pertussis PCR"
      Case "ebv"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "epstein") Then
               requestname &= "Epstein Barr virus EIA IgG IgM;"
            End If
            If InStr(Lower(observation!value), "cytomegalo") Then
               requestname &= "Cytomegalovirus - EIA IgG IgM;"
            End If
         Next
         
      Case "syphilis"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "treponemal ab (eia)") Then
               requestname &= "Treponemal Ab (EIA);"
            End If
         Next
      Case "pt"
         requestname = "Prothrombin Time"
      Case "jak2 mutation"
         requestname = "JAK-2 mutation for polycythaemia"
      Case "vitamin d 1-25"
         requestname = "Vitamin D" 
      Case "hep serology"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "hepatitis c") Then
               requestname &= "Hepatitis C Studies;"
            End If   
         Next
      Case "antitrypsin pheno (aap-0)"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "antitrypsin phenotype") Then
               If Not InStr(Lower(requestname), "alpha 1 - antitrypsin phenotype") Then 
                  requestname &= "Alpha 1 - antitrypsin phenotype;"
               End If
            End If
         Next  
         
      Case "rheumatoid factor (rf-0)"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "rheumatoid factor") Then
               If Not InStr(Lower(requestname), "rf") Then 
                  requestname &= "RF;"
               End If
            End If
         Next  
      Case "arbovirus serology (arv-0)"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "ross river") Then
               If Not InStr(requestname, "Ross River - EIA or HI;") Then
                  requestname &= "Ross River - EIA or HI;"
               Endif
            Endif
         Next
      Case "urine trichomonas (utr-0)"
         requestname &= "Trichomonas Vaginalis PCR;"
      Case "autoimmune (ctd-0)"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "anti-dna") Then
               If Not InStr(Lower(requestname), "anti-dna antibody") Then 
                  requestname &= "Anti-DNA antibody;"
               End If
            End If
            If InStr(Lower(observation!identifier), "anti-nuclear antibodies") Or InStr(Lower(observation!identifier), "antinuclear antibodies") Then
               If Not InStr(Lower(requestname), "anti-nuclear antibody;") Then  
                  requestname &= "Anti-nuclear antibody;"
               End If 
            End If   
            If InStr(observation!identifier, "ENA") Then
               If Not InStr(Lower(requestname), "anti-ena;") Then  
                  requestname &= "Anti-ENA;"
               End If 
            End If   
            If InStr(Lower(observation!identifier), "ana") Then  
               If Not InStr(Lower(requestname), "ana;") Then  
                  requestname &= "ANA;"
               Endif
            End If
            
         Next  
      Case "coeliac gene test (hla dq (hlc-0)"
         
         requestname &= "Coeliac Genotyping;"
      Case "metals, blood", "metals blood", "blood metals"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "lead") Then
               requestname &= "Lead blood;"
            End If
            If InStr(Lower(observation!identifier), "p-zinc") Or InStr(Lower(observation!identifier), "zinc") Then
               requestname &= "Zinc;"
            End If
            
            If InStr(Lower(observation!identifier), "arsenic") Then
               requestname &= "Arsenic blood;"
            End If
            
            If InStr(Lower(observation!identifier), "mercury") Then
               requestname &= "Mercury blood;"
            End If
            
            If InStr(Lower(observation!identifier), "cadmium") Then
               requestname &= "Cadmium blood;"
            End If
            
         Next
         
      Case "metals, 24hr urine"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "copper") Then
               requestname &= "24hr Urine copper;"
            End If
         Next
      Case "hepatitis serology", "hepatitis c serology", "x049"
         
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "hepatitis a igg") Or InStr(Lower(observation!value), "hepatitis a igg") Then
               If Not InStr(requestname, "Hepatitis A IgG") Then 
                  requestname &= "Hepatitis A IgG;"
               Endif
            End If
            If InStr(Lower(observation!identifier), "hepatitis a igm") Or InStr(Lower(observation!value), "hepatitis a igm") Then
               requestname &= "Hepatitis A IgM;"
            End If
            If InStr(Lower(observation!identifier), "hepatitis b core ab") Or InStr(Lower(observation!value), "hepatitis b core ab") Then
               requestname &= "Hepatitis B core antibody - EIA IgM;"
            End If
            If InStr(Lower(observation!identifier), "hepatitis c ab") Or InStr(Lower(observation!value), "hepatitis c ab") Then
               requestname &= "Hepatitis C Studies;"
            End If
            
            If InStr(Lower(observation!identifier), "hepatitis b surface ag") Or InStr(Lower(observation!value), "hepatitis b surface ag") Then
               requestname &= "Hepatitis B surface antigen;"
            End If
            If InStr(Lower(observation!identifier), "hepatitis b surface ab") Or InStr(Lower(observation!value), "hepatitis b surface ab") Then 
               requestname &= "Hepatitis B virus surface Ab;"
            End If
         Next
         If requestname = "Hepatitis B surface antigen;Hepatitis B antibody;" Then
            requestname = Replace(requestname, "Hepatitis B surface antigen;Hepatitis B virus surface Ab;", "Hepatitis B Studies")
         End If
         If requestname = "Hepatitis B virus surface Ab;Hepatitis B surface antigen;" Then
            requestname = Replace(requestname, "Hepatitis B virus surface Ab;Hepatitis B surface antigen;", "Hepatitis B Studies")
         End If
         
      Case "hepatitis b serology"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "hepatitis b surface ag") Then
               requestname &= "Hepatitis B surface antigen;"
            End If
            If InStr(Lower(observation!identifier), "hepatitis b surface ab") Then
               requestname &= "Hepatitis B virus surface Ab;"
            End If
            If InStr(Lower(observation!identifier), "hepatitis b core ab") Then
               requestname &= "Hepatitis B Core Ab;"
            End If
         Next
         
         If requestname = "Hepatitis B surface antigen;Hepatitis B virus surface Ab;" Or requestname = "Hepatitis B virus surface Ab;Hepatitis B surface antigen;" Then
            requestname = "Hepatitis B Studies"
         End If
      Case "ngsp"
         For Each Observation In Observations
            
            If InStr(Lower(observation!identifier), "sputum") Then
               If Not InStr(Lower(requestname), "sputum") Then
                  requestname = "Sputum cytology for malignant cells"
               End If
            End If
         Next
         
      Case "sputum1", "sputum2", "sputum3"
         For Each Observation In Observations
            
            If InStr(Lower(observation!value), "cytopathology") Then
               requestname = "Sputum cytology for malignant cells"
            End If
         Next
      Case "gluc2hrpp"
         
         requestname = "Glucose 2 Hr.PP"
      Case "mcs"
         For Each observation In observations
            If InStr(Lower(observation!value), "specimen swab - leg") Then
               requestname = "Pus swab c&s"
               Break
            End If
         Next
      Case "gmc1", "gmc2", "gmc3"
         '   fixme make me more sophisticated eg, check if pus swab, if is, check cached anatomical body bits to match
         For Each Observation In Observations
            Select Case Lower(observation!value)
               Case "penile swab", "pus", "pus swab"
                  requestname = "Pus swab c&s"
               Case "vulval swab"
                  requestname = "Vulval Swab c&s"
               Case "perineal swab"
                  requestname = "Perineal Swab c&s"
               Case "urethral swab"
                  requestname = "Urethral swab c&s;"
               Case "sputum"
                  requestname = "Sputum culture - routine"
               Case "nasal swab"
                  requestname = "Nose swab c&s"
               Case "vaginal swab"
                  requestname = "Genitourinary - eg vaginal discharge, vaginal swab - Gram stain and aerobic culture"
               Case "perianal swab"
                  requestname = "peri-anal swab c&s"
               Case "synovial fluid"
                  requestname = "Joint fluid c&s;Joint fluid crystals"
               Case "pus swab scalp"
                  requestname = "Pus swab c&s"
               Case "genital swab"
                  requestname = "Genitourinary - STD cervical urethral swabs - Gram stain gonococcal culture Trichomonas"
               Case "throat swab"
                  requestname = "Throat swab c&s"
               Case Else  'last ditch attempt - they someone put in stuff like 'pus swab on nose' 'pus swab on neck'..... idiots!!!!!!
                  If InStr(Lower(observation!value), "pus swab") Or InStr(Lower(observation!value), "buttock swab") Or InStr(Lower(observation!value), "tissue bursa") Then
                     requestname = "Pus swab c&s"
                  End If
                  If InStr(Lower(observation!value), "nasal swab") Then
                     requestname = "Nose swab c&s"
                  End If
            End Select
            If InStr(Lower(observation!value), "synovial") Then
               If Not InStr(requestname, "Joint fluid c&s;Joint fluid crystals;") Then
                  requestname = "Joint fluid c&s;Joint fluid crystals;"
                  Break
               End If
            End If
            If InStr(Lower(observation!value), "wound") Then
               requestname = "Pus swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "knee") Then
               requestname = "Pus swab c&s"
               Break
            End If
            If InStr(Lower(observation!value), "abdominal") Then
               requestname = "Pus swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "umbilical") Then
               requestname = "Umbilical swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "leg") Then
               requestname = "Pus swab c&s"
               Break
            End If
            If InStr(Lower(observation!value), "ear") Then
               requestname = "Ear swab c&s;"
               Break
            End If
            
            If InStr(Lower(observation!value), "hand") Then
               requestname = "Pus swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "eye") Then
               requestname = "Eye swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "chest") Then
               requestname = "Pus swab c&s"
               Break
            End If
            If InStr(Lower(observation!value), "hand") Then
               requestname = "Pus swab c&s"
               Break
            End If
            If InStr(Lower(observation!value), "foot") Or InStr(Lower(observation!value), "toe") Then
               requestname = "Pus swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "paronychia") Then
               requestname = "Pus swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "finger") Then
               requestname = "Pus swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "pilonidal") Then
               requestname = "Pus swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "perianal") Then
               requestname = "Perianal swab c&s"
               Break
            End If
            If InStr(Lower(observation!value), "face") Then
               requestname = "Pus swab c&s"
               Break
            End If
            If InStr(Lower(observation!value), "abscess") Then
               requestname = "Abscess swab c&s;"
               Break
            End If
            If InStr(Lower(observation!value), "shin") Then
               requestname = "Pus swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "axilla") Then
               requestname = "Pus swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "skin") Then
               requestname = "Pus swab c&s"
               Break
            End If
            If InStr(Lower(observation!value), "groin") Then
               requestname = "Pus swab c&s"
               Break
            End If
            
            If InStr(Lower(observation!value), "vaginal") Or InStr(Lower(observation!value), "cervical") Then
               requestname = "Genitourinary - eg vaginal discharge, vaginal swab - Gram stain and aerobic culture;"
               Break
            End If
            
         Next
      Case "helab"
         For Each Observation In Observations
            
            If InStr(Lower(observation!identifier), "helicobacter pylori") Then    
               If Not InStr(requestname, "Helicobacter pylori antibodies") Then
                  requestname &= "Helicobacter pylori antibodies;"
               Endif
            Endif
         Next
      Case "whole blood lead / zinc (pbz-0)"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "lead") Then
               If Not InStr(requestname, "Lead Blood") Then
                  requestname &= "Lead Blood;"
               Endif
            Endif
            If InStr(Lower(observation!identifier), "cadmium") Then
               If Not InStr(requestname, "Cadmium Blood") Then
                  requestname &= "Cadmium Blood;"
               Endif
            Endif
            If InStr(Lower(observation!identifier), "mercury") Then
               If Not InStr(requestname, "Mercury BLood") Then
                  requestname &= "Mercury Blood;"
               Endif
            Endif
            
         Next
      Case "coag", "coagulation tests"
         
         For Each Observation In Observations
            If InStr(Lower(observation!value), "aptt") Or InStr(Lower(observation!identifier), "aptt") Then
               If Not InStr(requestname, "APTT (Activated Partial Thromboplastin Time") Then
                  requestname &= "APTT (Activated Partial Thromboplastin Time);"
               Endif
            Endif
            If InStr(Lower(observation!value), "pt") Or InStr(Lower(observation!identifier), "pt") Then
               If Not InStr(Lower(requestname), "prothrombin time") Then
                  requestname &= "Prothrombin Time;"
               Endif
            Endif
            If InStr(Lower(observation!value), "prot c") Or InStr(Lower(observation!value), "protein c") Then
               If Not InStr(requestname, "Protein C") Then
                  requestname &= "Protein C;"
               Endif
            Endif
            If InStr(Lower(observation!value), "prot s") Or InStr(Lower(observation!value), "protein s") Then
               If Not InStr(requestname, "Protein S") Then
                  requestname &= "Protein S;"
               Endif
            Endif
            If InStr(Lower(observation!value), "anti-thrombin") Then
               If Not InStr(requestname, "Anti-Thrombin") Then
                  requestname &= "Anti-Thrombin III;"
               Endif
            Endif
            If InStr(Lower(observation!value), "inr") Then
               If Not InStr(requestname, "INR") Then
                  requestname &= "INR;"
               Endif
            Endif
            
            If observation!loinc = "8251-1" Then 'service comment look in text
               If InStr(Lower(observation!value), "prothrombin gene mutation") Then
                  If Not InStr(requestname, "Prothrombin Gene Analysis;") Then 
                     requestname &= "Prothrombin Gene Analysis;"
                  End If
               End If
            End If
         Next
         If requestname = "" Then requestname = "Coagulation screen"
      Case "blood gp/antibodies"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "blood group") Then
               If Not InStr(requestname, "Blood Group") Then 
                  requestname &= "Blood Group;"
               End If
            End If      
            If InStr(Lower(observation!value), "antibodies") Then
               If Not InStr(requestname, "Red Cell Antibody Screen") Then 
                  requestname &= "Red Cell Antibody Screen;"
               End If
            End If      
         Next
         If InStr(requestname, "Blood Group") And InStr(Requestname, "Red Cell Antibody Screen") Then
            requestname = "Blood Group and Antibody Screen"
         Endif
      Case "arbovirus-zoonosis"  
         For Each Observation In Observations
            If InStr(Lower(observation!value), "rickettsia") Then
               If Not InStr(requestname, "Rickettsia Serology") Then
                  requestname &= "Rickettsia Serology;"
               Endif
            Endif
         Next
      Case "alb/creat ratio"
         requestname = "spot urine albumin/creatinine ratio"
      Case "albumin excr (ur)"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "collection period") Then
               requestname &= "Timed Urine Microalbumin;"
            End If
         Next
         If requestname = "" Then requestname = "Albumin - urine (microalbumin)"
      Case "tof"
         requestname = "Outstanding Tests"
      Case "hm"
         requestname = "24Hr Holter Scan"
         
      Case "x043"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "synovial fluid") Then
               If Not InStr(requestname, "Joint Fluid") Then
                  requestname &= "Joint fluid c&s;Joint fluid crystals;"
               End If 
            End If
         Next
      Case "x033"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "bhcg") Then
               If Not InStr(requestname, "BHCG") Then
                  requestname &= "Quantitative BHCG;"
               End If 
            End If
         Next 
         For Each Observation In Observations
            If InStr(Lower(observation!value), "glucose") Then
               If Not InStr(requestname, "BSL") Then
                  requestname &= "BSL;"
               End If 
            End If
         Next   
      Case "x021"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "bhcg") Then
               If Not InStr(requestname, "BHCG") Then
                  requestname &= "Quantitative BHCG;"
               End If 
            End If
         Next       
      Case "x054"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "bhcg") Then
               If Not InStr(requestname, "BHCG") Then
                  requestname &= "Quantitative BHCG;"
               End If 
            End If
         Next
         
      Case "cytology non gynae (cyt-0)", "urine1", "cytology", "urine2", "urine3"
         For Each observation In observations
            If InStr(Lower(observation!value), " pleural fluid") Then
               If Not InStr(requestname, "Pleural fluid cytology;") Then
                  requestname = "Pleural fluid cytology;"
               End If
            End If
            If InStr(Lower(observation!value), "urine") Then
               If Not InStr(requestname, "Urine cytology;") Then
                  requestname = "Urine cytology;"
               End If
            End If
            If InStr(Lower(observation!value), "fine needle aspiration") Then
               If InStr(Lower(observation!value), "breast") Then
                  requestname = "FNA Breast;"
               End If
            End If
            
         Next
      Case "phenotyping"
         requestname = "Lymphocyte subsets;"
      Case "ige specific allerg."
         
         For Each observation In observations
            If InStr(Lower(observation!value), "penicilloyl") Or InStr(Lower(observation!value), "amoxicilloyl") Then
               requestname = "Penicillin & Amoxycillin IgE;"
               
            End If
            If requestname = "" Then
               If Not IsNull(observation!identifier) Then
                  If Not IsNull(observation!loinc) Then 
                     sString = modCodingDBI.Loinc_Get_component(observation!loinc)  'may return an empty string.
                     If sString <> "" Then 
                        Request_Save_New_Term_From_Loinc_Component(sSTring)
                        requestname &= sString & ";"
                     End If  
                  End If
               End If
            End If   
            
         Next  
      Case "calc"
         requestname = "Calculus - renal"
      Case "urine chemistry", "immunoglobulins (imm-0)"
         
         For Each observation In observations
            If Not IsNull(observation!identifier) Then
               If Not IsNull(observation!loinc) Then 
                  sString = modCodingDBI.Loinc_Get_component(observation!loinc)  'may return an empty string.
                  If sString <> "" Then 
                     Request_Save_New_Term_From_Loinc_Component(sSTring)
                     requestname &= sString & ";"
                  End If  
               End If
            End If
         Next  
      Case "chemistry, ur.24h"
         For Each Observation In Observations
            Select Case Lower(observation!identifier)
               Case "sodium excretion", "potassium excretion", "chloride excretion"
                  If Not InStr(requestname, "24hr urine electrolytes") Then
                     requestname &= "24hr urine electrolytes;"
                  End If
               Case "protein excretion"
                  requestname &= "24 Hour Urinary Protein Excretion;"
               Case "citrate excretion" 
                  requestname &= "24hr urine citrate;"
               Case "calcium excretion"
                  requestname &= "24hr urine calcium;"
               Case "u-creatinine excretion"
                  requestname &= "24hr urine creatinine;"
               Case "oxalate excretion"
                  requestname &= "24hr urine oxalate;"
               Case "u-magnesium excretion"
                  requestname &= "24hr urine magnesium;"
               Case "urate excretion"
                  requestname &= "24hour Urinary Uric Acid Excretion;"
            End Select
         Next
      Case "cardiac markers"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "troponin") Then
               requestname = "Troponin"
            End If
         Next
      Case "thyroid abs virtual", "_thyroid abs virtual", "thyab", "thyroid abs"
         For Each Observation In Observations
            Select Case Lower(observation!identifier)
               Case "thyroid peroxidase ab"
                  requestname &= "Thyroid Peroxidase Ab;"
               Case "thyroglobulin"
                  requestname &= "Thyroglobulin;"
               Case "thyroglobulin ab"
                  requestname &= "Thyroglobulin ab;"
            End Select
         Next
      Case "tp-ctpcr"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "chlamydia") Then
               If Not InStr(requestname, "Chlamydia trachomatis PCR") Then
                  requestname &= "Chlamydia trachomatis PCR;"
               End If  
            End If
         Next
      Case "misc.chemistry"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "ostase") Then
               requestname = "Ostase;"
            End If
           If InStr(Lower(observation!identifier), "ammonia") Then
               requestname = "Ammonia;"
            End If
            If InStr(Lower(observation!value), "sweat") Then
               If Not InStr(requestname, "Sweat conductivity") Then
                  requestname &= "Sweat conductivity;"
               End If  
            End If
            If InStr(Lower(observation!value), "ethanol") Then
               If Not (InStr(requestname, "Ethanol")) Then 
                  requestname &= "Ethanol;"
               Endif
            End If
            If InStr(Lower(observation!value), "magnesium") Then
               requestname &= "magnesium;"
            End If
            If InStr(Lower(observation!value), "crp") Then
               requestname &= "C-Reactive protein;"
            End If
            If InStr(Lower(observation!value), "lipase") Then
               requestname &= "Lipase;"
            End If
            If InStr(Lower(observation!identifier), "ethanol") Then
               If Not (InStr(requestname, "Ethanol")) Then 
                  requestname &= "Ethanol;"
               Endif
            End If  
         Next
      Case "chemistry urine", "chemistry, urine"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "r-u-creatinine") Then
               requestname = "Creatinine - urine"
               
            End If
            If InStr(Lower(observation!identifier), "u-creatinine") Then
               requestname = "Creatinine - urine"
               
            End If
            If InStr(Lower(observation!identifier), "r-u-protein/creat ratio") Then
               requestname = "spot urine albumin/creatinine ratio" 
            End If
         Next
      Case "retics"
         requestname = "Reticulocyte count"
      Case "cpls"
         requestname = "caeruloplasmin"
         
      Case "fun", "fun2", "x036"
         For Each Observation In Observations               
            If InStr(Lower(observation!value), "abscess") Or InStr(Lower(observation!value), "swab") Or InStr(Lower(observation!value), "abcess") Then
               requestname = "Fungal stain & culture - tissues swabs etc;"             'abcess!! mmmmmmmmmm spelling!!!!!!!!!!!!
               Break
            End If
            
            If InStr(Lower(observation!value), "nail") Or InStr(Lower(observation!value), "toenail") Then
               requestname = "Nail c&s for fungi;"
               Break
            End If
            If InStr(Lower(observation!value), "face") Or InStr(Lower(observation!value), "hand") Then
               requestname = "Fungal stain & culture - skin scrapings (dermatophytes);"
               Break
            End If
            
            If InStr(Lower(observation!value), "skin") Or InStr(Lower(observation!value), "leg") Or InStr(Lower(observation!value), "chest") Or InStr(Lower(observation!value), "groin") Or InStr(Lower(observation!value), "arm ") Then
               requestname = "Fungal stain & culture - skin scrapings (dermatophytes);"
               Break
            End If
            
            If InStr(Lower(observation!value), "trunk") Or InStr(Lower(observation!value), "foot") Or InStr(Lower(observation!value), "scalp") Then
               requestname = "Fungal stain & culture - skin scrapings (dermatophytes);"
               Break
            End If
            If InStr(Lower(observation!value), "biopsy") Then
               requestname = "Fungal stain & culture - tissues swabs etc;"
               Break
            End If
         Next
         
      Case "antenatal testing"
         For Each Observation In Observations
            If InStr(Lower(Observation!value), "blood group") Then
               If InStr(Lower(Observation!value), "antibodies") Then
                  requestname &= "pregnancy blood group antibody screen;"
               Else
                  requestname &= "Blood Group;"
               End If
            End If
            If Not IsNull(observation!identifier) Then
               If Not IsNull(observation!loinc) Then 
                  sString = modCodingDBI.Loinc_Get_component(observation!loinc)  'may return an empty string.
                  If sString <> "" Then 
                     Request_Save_New_Term_From_Loinc_Component(sSTring)
                     requestname &= sString & ";"
                  End If  
               End If
            End If
            
         Next
      Case "x042"
         For Each Observation In Observations
            If InStr(Lower(Observation!value), "hsv") Then
               If Not InStr(requestname, "Herpes simplex virus - EIA IgG IgM;") Then
                  requestname &= "Herpes simplex virus - EIA IgG IgM;"
               Endif
            Endif
         Next    
      Case "cmv abs"
         For Each Observation In Observations
            If InStr(Lower(Observation!value), "herpes simplex type 1") Then
               requestname = "Herpes simplex virus - EIA IgG IgM;"
            End If
            If InStr(Lower(Observation!value), "herpes simplex type 2") Then
               requestname = "Herpes simplex virus - EIA IgG IgM;"
            End If
            If requestname = "" Then 
               If InStr(Lower(Observation!value), "pending") Then
                  requestname = "Test Pending;"
               End If
            End If
         Next
      Case "u-alb"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "timed") Then
               requestname = "Albumin/Creatinine ratio Timed overnight collection.;"
               Break
            End If
            If InStr(Lower(observation!value), "alb:cr ratio") Then
               requestname = "spot urine albumin/creatinine ratio"
            End If
         Next
         
      Case "a1at"
         requestname = "Alpha 1 - antitrypsin" 
      Case "papr v"
         requestname = "Vaginal Vault Smear;"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "thinprep") Then
               requestname &= "THINPREP;"
               Break
            End If
         Next
      Case "papr", "papr ns", "pap ns", "pap smear", "pap smear (pan-0)", "pap screen", "pap smear (pap-0)", "x157", "x156"
         requestname = "PAP;"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "thinprep") Then
               requestname &= "THINPREP;"
               Break
            End If
         Next
         
      Case "hapt"
         requestname = "haptoglobins"
      Case "fmcs"
         requestname = "Faeces - ova, cysts parasites (microscopy, direct+/-concentrate);"               
      Case "fob", "fob 2", "fob 3"
         For Each Observation In Observations
            If InStr(Lower(observation!identifier), "immunological") Then
               requestname &= "Haemoglobin - Faecal (Immunological);"
            End If
            If InStr(Lower(observation!identifier), "immunochemical") Or InStr(Lower(observation!identifier), "chemical") Then
               requestname &= "Haemoglobin - Faecal (ImmunoChemical);"
            End If
            If InStr(Lower(observation!value), "positive") Then
               Message.Title = "ABNORMAL RESULT"
               Message.Warning("This is a postive Faecal occult blood.\n\nIt is vital that this is actioned") 
            End If         
         Next
      Case "ecg"
         requestname = "ECG Resting and Report" 
      Case "hb"
         
         For Each Observation In Observations
            
            If Lower(observation!identifier) = "white cell count" Then
               requestname = "FBC;"
               Break
            End If
         Next
         If requestname <> "FBC;" Then requestname = "Hb;"
      Case "venesection"
      Case "blood gas"
         requestname &= "Arterial Blood Gases;"
      Case "cord blood"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "group") Then
               If Not InStr(requestname, "Blood Group") Then
                  requestname &= "Blood Group;"
               Endif
            Endif
            If InStr(Lower(observation!value), "direct antiglobulin") Then
               If Not InStr(requestname, "Direct Antiglobulin Testing") Then
                  requestname &= "Direct Antiglobulin Testing;"
               Endif
            Endif
         Next
      Case "ana/autoantibodies", "autoimmune (ctd-0)"
         For Each Observation In Observations
            If InStr(Lower(observation!value), "thyroglobulin ab eia") Then 
               If Not InStr(requestname, "Thyroglobulin Ab") Then
                  requestname &= "Thyroglobulin Ab;"
               End If   
            End If 
            If InStr(Lower(observation!value), "anca") Then 
               If Not InStr(requestname, "ANCA (Anti-neutrophil cytoplasmic antibody") Then
                  requestname &= "ANCA (Anti-neutrophil cytoplasmic antibody);"
               End If   
            End If 
            If InStr(Lower(observation!value), "gbm") Then 
               If Not InStr(requestname, "Anti-GBM (glomerular basement membrane) antibody") Then 
                  requestname &= "Anti-GBM (glomerular basement membrane) antibody;"
               End If   
            End If   
            If InStr(Lower(observation!value), "deamid. gliadin iga") Then 
               If Not InStr(requestname, "Gliadin (Deamidated) IgA Antibody") Then 
                  requestname &= "Gliadin (Deamidated) IgA Antibody;"
               End If  
            End If   
            If InStr(Lower(observation!identifier), "transglutaminase") Then 'go figure
               If Not InStr(requestname, "Transglutaminase antibody") Then 
                  requestname &= "Transglutaminase antibody;"
               End If   
            End If   
            
         Next
   End Select
   If InStr(Lower(SelectedDocument!tag), "obstetric multiple pregnancy") Then
      requestname = "Pregnancy U/S Morphology Scan;"
   End If   
   Return requestname
   
End

Public Function Guess_Radiology_From_Tag(tag As String) As Collection 
   
   Return Guess_Radiology(Lower(tag), Lower(tag))
   
End

Public Function Guess_Request_Names_From_Parsing_Report(observations As Collection) As Collection  ', laterality As Integer
   
   Dim observation As Collection 
   Dim Modality As String 'u/s xray mri doppler
   Dim Lateralisation As String 
   Dim requestname As String 
   
   Dim guess As New Collection 
   
   For Each Observation In Observations
      guess = Guess_Radiology(observation!identifier, observation!value)
   Next
   Return guess
   
End

Public Function Guess_Radiology(identifier As String, value As String) As Collection
   
   Dim bfoundModality As Boolean
   Dim Modality As String 'u/s xray mri doppler
   Dim Lateralisation As String 
   Dim requestname As String 
   Dim guess As New Collection 
   
   Select Case identifier
      Case "barium enema"
         guess!name = identifier
         Return guess
   End Select
   
   If InStr(Upper(identifier), "CT ") Then 
      Modality = "CT"  'words can end in ct/CT
      bfoundModality = True   
   Else
      If InStr(value, "CT ") And bfoundModality = False Then 
         Modality = "CT"
         bfoundModality = True
      End If
      
      If (InStr(Lower(value), "x-ray") Or InStr(Lower(value), "xray")) And bfoundModality = False Then 
         Modality = "XRay"
         bfoundModality = True
      End If
      
      If (InStr(Lower(value), "ultrasound") Or InStr(Upper(value), "US")) And bfoundModality = False Then 
         Modality = "Ultrasound"
         bfoundModality = True
      End If
      If InStr(Lower(value), "mri") And bfoundModality = False Then  ' Or InStr(Lower(value), "mr") And bfoundModality = False Then 
         Modality = "MRI"
         bfoundModality = True   
      End If
   End If   
   If InStr(Lower(value), "ankle brachial indices") Then
      guess!name = "arterial lower limb pressures" 
      Return guess
   Endif
   If InStr(Lower(value), "left") Then
      Lateralisation = "left"
      guess!laterality = const.LateralityLeft
   End If
   If InStr(Lower(value), "right") Then
      Lateralisation = "right"
      guess!laterality = const.LateralityRight
   End If
   
   If InStr(Lower(value), "ultrasound renal tract") Then
      guess!name = "Renal Tract Ultrasound;"
   End If
   
   If Modality = "" Then Modality = "Xray" 'commonest stab in the dark
   If InStr(Lower(value), "brain") Then
      Select Case Modality
         Case "CT"
            If InStr(Lower(identifier), "no contrast") Or InStr(Lower(identifier), "non contrast") Or InStr(Lower(identifier), "plain") Then
               guess!name = "CT Brain Non Contrast;"
            Else
               guess!name = "CT Brain Contrast;"
            End If
         Case "MRI"
            guess!name = "MRI Brain;"
      End Select
   End If
   If InStr(Lower(value), "chest") And Modality <> "CT" Then
      requestname = "CXR AP/Lateral;"
      guess!name = requestname
      Return guess
   End If
   If InStr(Lower(value), "chest") And Modality = "CT" Then
      requestname = "CT Chest"
      If InStr(Lower(value), "with contrast") Then
         requestname &= " (Contrast)"
      Endif
      guess!name = requestname
      Return guess
   Endif
   If InStr(Lower(value), "ct sinus") Or InStr(Lower(value), "sinus ct") Then
      guess!name = "Facial Sinus CT;"
      guess!laterality = const.LateralityNone
      Return guess
   End If
   If InStr(Lower(value), "knee") Then
      requestname = Modality & " " & "Knee"
      guess!name = requestname
      Return guess
   End If
   If InStr(Lower(value), "achilles") Then
      requestname = Modality & " " & "Achilles"
      guess!name = requestname
      Return guess
   End If
   
   If InStr(Lower(value), "elbow") Then
      requestname = Modality & " " & "Elbow"
      guess!name = requestname
      Return guess
   End If
   If InStr(Lower(value), "wrist") Then
      requestname = Modality & " " & "Wrist"
      guess!name = requestname
      Return guess
   End If
   If InStr(Lower(value), "ankle") Then
      requestname = Modality & " " & "Ankle"
      guess!name = requestname
      Return guess
   End If
   
   If InStr(Lower(value), "foot") Then
      requestname = Modality & " " & "Foot"
      guess!name = requestname
      Return guess
   End If
   If InStr(Lower(value), "hand") Then
      requestname = Modality & " " & "Hand"
      guess!name = requestname
      Return guess
   End If
   If InStr(Lower(value), "finger") Then
      requestname = Modality & " " & "Finger"
      guess!name = requestname
      Return guess
   End If
   If InStr(Lower(value), "thumb") Then
      requestname = Modality & " " & "Thumb"
      guess!name = requestname
      Return guess
   End If
   If InStr(Lower(value), "heel") Then
      requestname = Modality & " " & "Heel"
      guess!name = requestname
      Return guess
   End If
   If InStr(Lower(value), "abdomen and pelvis") Then
      If Modality = "CT" Then guess!name = "CT Abdomen and Pelvis pre/post contrast;"
      Return guess
   End If
   
   If InStr(Lower(value), "ultrasound pelvis") Then
      guess!name = "Ultrasound Pelvis;"
      Return guess
   End If
   
   If InStr(Lower(value), "breast") And Not (InStr(Lower(value), "breastscreen nsw")) Then
      If Modality = "Ultrasound" Then 
         requestname = "Ultrasound Of breast"
         guess!name = requestname
         Return guess
      End If
   End If
   If InStr(Lower(value), "nuchal translucency") Then
      guess!name = "Nuchal fold for Down's;"
      Return guess
   End If
   If InStr(Lower(value), "ct renal tract") Then
      guess!name = "Renal Tract CT;"
      Return guess
   End If
   If InStr(Lower(value), "specialist consultation") Then
      guess!name = "Specialist Consultation;"
      Return guess
   End If
   If InStr(Lower(value), "obstetric ultrasound") Then
      If InStr(Lower(identifier), "under 12 weeks") Then
         guess!name = "Early Pregnancy U/S Scan;"
         Return guess
      End If
   End If
   If InStr(Lower(value), "thoracic spine") Then
      guess!name = Modality & " " & "Thoracic Spine;"
      Return guess
   End If
   
   If InStr(Lower(value), "shoulder") Then
      requestname = Modality & " Shoulder" 
      guess!name = requestname
      Return guess
   End If
   Return guess
   
End

Public Function Guess_Request_Names_From_Observation(observations As Collection) As String 
   
   Dim requestnames As String 
   Dim requestname As String
   Dim observation As Collection
   
   requestnames = ""
   For Each Observation In Observations
      requestname = ""
      
      Select Case Lower(Trim(observation!identifier)) 'yes, the fuckers also put blanks in front!!!!!1
         Case "troponin i"   'yes, Haps uses an 'i' istead of 1
            requestname = "troponin 1"
         Case "prothrombin ratio"
            requestname = "INR"
         Case "protein"
            requestname &= "Protein - Serum"
         Case "albumin"
            requestname &= "Albumin"
         Case "ige"
            requestname = "IgE"
         Case "alk phos"
            requestname = "Alkaline Phosphatase"
         Case "insulin"
            requestname = "insulin"
         Case "carbamazepine"
            requestname = "Carbamazepine"
         Case "cryptococcal antigen"
            requestname = "Cryptococcal antigen - latex EIA serum/CSF"
         Case "igf-1"
            requestname = "Insulin like growth factor 1, IGF-1"
         Case "igfbp-3"
            requestname = "Insulin-like growth factor binding protein 3"
         Case "b. pertussis iga (eia)"
            requestname = "B. pertussis IgA (EIA)"
         Case "collagen/epinephrine"
            requestname = "Platelet Function - collagen/epinephrine"
         Case "phenytoin total"
            requestname = "phenytoin"
         Case "amylase"
            requestname = "amylase"
         Case "alpha fetoprotein"
            requestname = "Alpha fetoprotein"
         Case "ldh"
            requestname = "LDH"
         Case "erythropoetin"
         Case "serum copper"
            requestname = "Serum Copper"
         Case "magnesium"
            requestname = "Magnesium"
         Case "prolactin (total)"
            requestname = "Prolactin"
         Case "shbg"
            requestname = "Sex hormone binding globulin"
         Case "free androgen index"
            requestname = "Free Androgen Index"
         Case "fsh"
            requestname = "FSH" 
         Case "oestradiol"
            requestname = "Oestradiol"
         Case "progesterone"
            requestname = "Progesterone"
         Case "cea"
            requestname = "carcinoembryonic antigen"
         Case "lh", "serum lh :" 'yes, just for HAPS whose hl7 is screwed
            requestname = "LH"
         Case "testosterone"
            requestname = "Testosterone"
         Case "histopathology"
            requestname = "Histopathology"
         Case "hepatitis b surface ab"
            requestname = "Hepatitis B surface antibody - EIAIgG"
         Case "vitamin b12"
            requestname = "Vitamin B12"
         Case "red cell folate"
            requestname = "Red cell folate"
         Case "egfr", "est. gfr", "gfr est."
            requestname = "eGFR"
         Case "sodium", "bicarbonate", "creatinine"
            requestname = "UEC"
         Case "potassium"
            requestname = "Potassium (not on U&E profile)"
         Case "crp"
            requestname = "C-Reactive protein"
         Case "serum cortisol"
            requestname = "Cortisol"
         Case "lipase"
            requestname = "lipase"
         Case "ast", "alt", "bilirubin"
            requestname = "LFTs"
         Case "cholesterol"
            requestname = "Cholesterol"
         Case "triglycerides", "triglyceride"
            requestname = "Triglycerides"
         Case "hdl cholesterol", "hdl-cholesterol"
            requestname = "HDL Cholesterol"
         Case "ldl cholesterol", "ldl-cholesterol" 
            requestname = "LDL Cholesterol"
         Case "uric acid", "urate"
            requestname = "Urate"
         Case "glucose", "glucose random", "glucose fasting", "fasting glucose"
            requestname = "BSL"  'DOG
         Case "calcium"
            requestname = "Calcium"
         Case "ck" 
            requestname = "CPK"
         Case "tsh"
            requestname = "TSH"
         Case "t4"
            requestname = "T4"
         Case "free t4", "free-t4"
            requestname = "fT4"
         Case "vitamin d"
            requestname = "Vitamin D"
         Case "t3", "free t3", "free-t3"
            requestname = "T3"
         Case "digoxin"
            requestname = "Digoxin"
         Case "r-u-protein/creat ratio"
            requestname = "spot urine albumin/creatinine ratio"
      End Select
      
      If requestname <> "" Then 
         If Not InStr(requestnames, requestname) Then
            requestnames &= requestname & ";"
         End If
      End If
      
   Next
   If InStr(requestnames, "Cholesterol") And InStr(requestnames, "Triglycerides") And InStr(requestnames, "HDL Cholesterol") And InStr(requestnames, "LDL Cholesterol") Then
      requestnames = "HDL Cholesterol;"
   End If
   If InStr(requestnames, "UEC") Then
      If InStr(requestnames, "not on U&E profile") Then
         requestnames = Replace(requestnames, "Potassium (not on U&E profile);", "")
      End If
   End If
   
   If requestnames <> "" Then Return Left(requestnames, Len(requestnames) - 1)
   Return requestnames
   
End

Public Function Loinc_Get_component(loinc As String) As String
   
   Dim Sstring As String 
   
   sSTring = modCodingDBI.Loinc_Get_component(loinc)
   If Not modRequestsDBI.Request_Item_?exists(sString) Then
      modRequestsDBI.Request_Save_loinc(sString)
      modDBConnect.CommitTrans()
   End If
   Return sString
   
End

Public Sub Request_Save_New_Term_From_Loinc_Component(sString As String)
   '--------------------------------------
   'Save a new request from its loinc name
   '--------------------------------------
   
   If Not InStr(Lower(sString), "service comment") Then
      If Not modRequestsDBI.Request_Item_?exists(sString) Then
         modRequestsDBI.Request_Save_loinc(sSTring)
         modDBConnect.CommitTrans()
      End If
   End If
   
End
