' Gambas module file

' Copyright (C) 2008-2015 Dr. Richard Terry

' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.

' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.

' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.

Public Sub Import(cons As CConsult)
  '-----------------------------------------------------
  'FIXME Temporary, current used only when importin data
  'fixme to be part of the usual saving of social history
  '------------------------------------------------------
  Dim sql As String
  Dim $Result As Result
  
   sql = "INSERT into clin_history.data_social_history (fk_consult,history, responsible_person) "
          "VALUES ("
   sql &= cons.pk_consult & ",$$" & cons.patient.social_history.history & "$$,"
   sql &= "$$" & cons.patient.social_history.responsible_person & "$$)"
   $Result = modDbConnect.exec_query(sql)

  
End

Public Function SocialHistory_Get(pk_patient As Integer) As Collection 
   '------------------------------------------------------------
   'Gets the patients social history, ever only null or 1 record
   '------------------------------------------------------------
   Dim sql As String    
   sql = "SELECT * FROM clin_history.vwSocialHistory "
   sql &= "WHERE fk_patient =" & pk_patient 
   Return modDBConnect.exec_query_collection(sql)
End

Public Sub Save(currentconsult As CConsult, pk_socialhistory As Integer, history As Collection) As Integer
   '-------------------------------------------------
   'Save or update the current social history
   'creates an audit trail for new or changed records
   '-------------------------------------------------
   Dim audit As New Collection 
   Dim bDatachanged As Boolean
   
   audit!notes = Create_Audit_Summary(history)
   
   If pk_socialhistory < 0 Then 
      '----------------------------------------------------------------------------------
      'If gets to here, there should be some text in either history or responsible person
      '----------------------------------------------------------------------------------
       history!fk_consult = currentconsult.GetPK()
       pk_socialhistory = modDBConnect.insert("clin_history.social_history", history) 
       audit!action = "insert"
       bDatachanged = True 
    Else
      '----------------------------------------------------------------------------
      'save any changes to existing social history, returns false if nothing saved
      'create audit trail if changes. If history!history <> "" Then
      '----------------------------------------------------------------------------
      If modDBConnect.update("clin_history.social_history", currentconsult!social_history[pk_socialhistory], history, "pk_socialhistory") Then ' save to backend and update the collection in RAM too
        '-----------------------------------------------------------
        'Not a new social history, edit the record 
        'what was changed, for auditing purposes this will be hidden
        '-----------------------------------------------------------
         audit!action = "edit"
         bDatachanged = True
      End If
        
   End If
   If bDatachanged Then modAudit.MakeAudit(currentconsult, audit!action, "clin_history.social_history", pk_socialhistory, const.cSection_SocialHistory, audit!notes)
   Return pk_socialhistory
  
End

Public Function Create_Audit_Summary(history As Collection) As String 
   '----------------------------
   'First tidy up the audit data
   '----------------------------
   Dim notes As String
   
    If history!history <> "" Then
     notes = history!history & "<BR>"
   End If  
   If history!responsible_person <> "" Then
     notes &= history!responsible_person
   End If
   '----------------------------------------------------------
   'at this point could have a <"BR>" on the end for no reason
   '----------------------------------------------------------
   If Right(notes, 4) = "<BR>" Then
     notes = Replace(notes, "<BR>", "")
   End If
   Return notes
End

